import React from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
export const colors = { background: '#F4F6FA', surface: '#FFFFFF', ink: '#14253D', muted: '#61718A', line: '#DEE5EF', brand: '#245BE8', danger: '#B42318' };
export function Screen({ title, subtitle, children, refreshing = false, onRefresh }: { title: string; subtitle: string; children: React.ReactNode; refreshing?: boolean; onRefresh?: () => void }) {
  return <SafeAreaView style={ui.screen} edges={['top']}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={ui.content} refreshControl={onRefresh ? <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.brand} /> : undefined}><Text style={ui.eyebrow}>BGOS / WORKSPACE</Text><Text accessibilityRole="header" style={ui.title}>{title}</Text><Text style={ui.subtitle}>{subtitle}</Text><View style={ui.stack}>{children}</View></ScrollView></SafeAreaView>;
}
export function Card({ children }: { children: React.ReactNode }) { return <View style={ui.card}>{children}</View>; }
export function Action({ label, onPress, disabled, secondary = false }: { label: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ disabled: !!disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [ui.button, secondary && ui.secondary, { opacity: disabled ? 0.45 : pressed ? 0.75 : 1 }]}><Text style={[ui.buttonText, secondary && { color: colors.brand }]}>{label}</Text></Pressable>;
}
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View style={{ gap: 7 }}><Text style={ui.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} {...props} style={[ui.input, props.multiline && { minHeight: 100, textAlignVertical: 'top' }, props.style]} /></View>; }
export function Empty({ title, detail }: { title: string; detail: string }) { return <Card><Text style={ui.heading}>{title}</Text><Text style={ui.body}>{detail}</Text></Card>; }
export function Loading() { return <ActivityIndicator accessibilityLabel="Loading" color={colors.brand} style={{ padding: 30 }} />; }
export function ErrorNotice({ message, retry }: { message: string | null; retry?: () => void }) { return message ? <View accessibilityRole="alert" style={ui.error}><Text style={{ color: colors.danger, lineHeight: 21 }}>{message}</Text>{retry && <Action label="Try again" secondary onPress={retry} />}</View> : null; }
export const ui = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 40 }, eyebrow: { fontSize: 10, fontWeight: '700', letterSpacing: 1.8, color: colors.muted, marginTop: 10 }, title: { fontSize: 30, fontWeight: '700', color: colors.ink, marginTop: 12, letterSpacing: -0.8 }, subtitle: { fontSize: 14, lineHeight: 21, color: colors.muted, marginTop: 6, marginBottom: 25 }, stack: { gap: 14 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 20, gap: 12 }, heading: { fontSize: 17, fontWeight: '700', color: colors.ink }, body: { fontSize: 14, lineHeight: 22, color: colors.muted }, metric: { fontSize: 32, fontWeight: '700', color: colors.ink, letterSpacing: -1 }, label: { fontSize: 12, fontWeight: '600', color: colors.ink }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 10, padding: 13, minHeight: 48, backgroundColor: colors.surface, color: colors.ink, fontSize: 15 }, button: { minHeight: 46, borderRadius: 10, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 12 }, buttonText: { fontSize: 14, fontWeight: '600', color: '#FFF' }, secondary: { backgroundColor: '#EEF3FF' }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' }, error: { padding: 16, backgroundColor: '#FFF1F0', borderRadius: 12, gap: 12 } });
