import React, { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialIcons } from '@expo/vector-icons';
export const colors = { background: '#F7F6FE', surface: '#FFFFFF', ink: '#151333', muted: '#76738E', line: '#EBE8F5', brand: '#643BFA', soft: '#EEE9FF', success: '#168557', danger: '#BA3547' };
export function Brand({ large = false }: { large?: boolean }) {
  return <View style={[ui.row, { gap: 5 }]}><Image source={require('../../assets/brand-mark.png')} style={{ width: large ? 70 : 30, height: large ? 70 : 30 }} accessibilityIgnoresInvertColors /><Text style={{ fontSize: large ? 36 : 21, fontWeight: '800', color: colors.ink, letterSpacing: -1 }}>BGOS</Text></View>;
}
export function Screen({ title, subtitle, children, refreshing = false, onRefresh }: { title: string; subtitle?: string; children: React.ReactNode; refreshing?: boolean; onRefresh?: () => void | Promise<unknown> }) {
  const [pulling, setPulling] = useState(false);
  return <SafeAreaView style={ui.screen} edges={['top', 'left', 'right']}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={ui.content} refreshControl={onRefresh ? <RefreshControl refreshing={refreshing || pulling} onRefresh={async () => { setPulling(true); try { await onRefresh(); } finally { setPulling(false); } }} tintColor={colors.brand} /> : undefined}><View style={ui.topbar}><Brand /><View style={ui.brandDot} /></View><Text accessibilityRole="header" style={ui.title}>{title}</Text>{subtitle ? <Text style={ui.subtitle}>{subtitle}</Text> : <View style={{ height: 18 }} />}<View style={ui.stack}>{children}</View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
export function Card({ children }: { children: React.ReactNode }) { return <View style={ui.card}>{children}</View>; }
export function Action({ label, onPress, disabled, secondary = false }: { label: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ disabled: !!disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [ui.button, secondary && ui.secondary, { opacity: disabled ? 0.45 : pressed ? 0.75 : 1 }]}><Text style={[ui.buttonText, secondary && { color: colors.brand }]}>{label}</Text></Pressable>;
}
export function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={[ui.chip, selected && { backgroundColor: colors.soft }]}><Text style={{ color: selected ? colors.brand : colors.muted, fontSize: 12, fontWeight: '600' }}>{label}</Text></Pressable>; }
export function Avatar({ name }: { name: string }) { return <View style={ui.avatar}><Text style={{ color: colors.brand, fontWeight: '700' }}>{name.trim().split(/\s+/).slice(0, 2).map(s => s[0]).join('').toUpperCase() || '?'}</Text></View>; }
export function Badge({ label, success = false }: { label: string; success?: boolean }) { return <View style={{ backgroundColor: success ? '#E6F9EF' : colors.soft, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 7 }}><Text style={{ color: success ? colors.success : colors.brand, fontSize: 11, fontWeight: '600' }}>{label}</Text></View>; }
export function MenuRow({ title, detail, icon = 'chevron-right', onPress }: { title: string; detail?: string; icon?: React.ComponentProps<typeof MaterialIcons>['name']; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [ui.menuRow, { opacity: pressed ? .6 : 1 }]}><View style={ui.iconTile}><MaterialIcons name={icon} size={22} color={colors.brand} /></View><View style={{ flex: 1 }}><Text style={ui.heading}>{title}</Text>{detail && <Text style={ui.caption}>{detail}</Text>}</View><MaterialIcons name="chevron-right" size={20} color={colors.muted} /></Pressable>; }
export function Field({ label, ...props }: TextInputProps & { label: string }) { return <View style={{ gap: 7 }}><Text style={ui.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} {...props} style={[ui.input, props.multiline && { minHeight: 100, textAlignVertical: 'top' }, props.style]} /></View>; }
export function Empty({ title, detail }: { title: string; detail: string }) { return <Card><View style={ui.iconTile}><MaterialIcons name="inbox" size={25} color={colors.brand} /></View><Text style={ui.heading}>{title}</Text><Text style={ui.body}>{detail}</Text></Card>; }
export function Loading() { return <ActivityIndicator accessibilityLabel="Loading" color={colors.brand} style={{ padding: 30 }} />; }
export function ErrorNotice({ message, retry }: { message: string | null; retry?: () => void }) { return message ? <View accessibilityRole="alert" style={ui.error}><Text style={{ color: colors.danger, lineHeight: 21 }}>{message}</Text>{retry && <Action label="Try again" secondary onPress={retry} />}</View> : null; }
export const ui = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 36, maxWidth: 760, width: '100%', alignSelf: 'center' }, topbar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }, brandDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.brand }, eyebrow: { fontSize: 11, fontWeight: '700', letterSpacing: 1.4, color: colors.muted }, title: { fontSize: 25, fontWeight: '700', color: colors.ink, letterSpacing: -.6 }, subtitle: { fontSize: 13, lineHeight: 20, color: colors.muted, marginTop: 6, marginBottom: 22 }, stack: { gap: 14 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 16, padding: 18, gap: 12 }, heading: { fontSize: 15, fontWeight: '700', color: colors.ink }, body: { fontSize: 14, lineHeight: 22, color: colors.muted }, caption: { fontSize: 12, lineHeight: 18, color: colors.muted, marginTop: 3 }, metric: { fontSize: 29, fontWeight: '700', color: colors.ink, letterSpacing: -.8 }, label: { fontSize: 12, fontWeight: '600', color: colors.ink }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: 10, padding: 13, minHeight: 48, backgroundColor: colors.surface, color: colors.ink, fontSize: 15 }, button: { minHeight: 48, borderRadius: 11, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 12 }, buttonText: { fontSize: 14, fontWeight: '600', color: '#FFF' }, secondary: { backgroundColor: colors.soft }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, flexWrap: 'wrap' }, error: { padding: 16, backgroundColor: '#FFF1F0', borderRadius: 12, gap: 12 }, chip: { minHeight: 44, paddingHorizontal: 12, justifyContent: 'center', borderRadius: 10, backgroundColor: '#F0EFF6' }, avatar: { width: 43, height: 43, borderRadius: 22, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center' }, menuRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: colors.line }, iconTile: { width: 43, height: 43, backgroundColor: colors.soft, alignItems: 'center', justifyContent: 'center', borderRadius: 12 } });
