export interface CurrencyItem {
  country: string;
  symbol: string;
  code: string;
}

export const WORLD_CURRENCIES: CurrencyItem[] = [
  { country: "India", symbol: "₹", code: "INR" },
  { country: "United States", symbol: "$", code: "USD" },
  { country: "United Kingdom", symbol: "£", code: "GBP" },
  { country: "European Union", symbol: "€", code: "EUR" },
  { country: "United Arab Emirates", symbol: "د.إ", code: "AED" },
  { country: "Afghanistan", symbol: "؋", code: "AFN" },
  { country: "Albania", symbol: "Lek", code: "ALL" },
  { country: "Algeria", symbol: "د.ج", code: "DZD" },
  { country: "American Samoa", symbol: "$", code: "USD" },
  { country: "Andorra", symbol: "€", code: "EUR" },
  { country: "Angola", symbol: "Kz", code: "AOA" },
  { country: "Anguilla", symbol: "$", code: "XCD" },
  { country: "Antigua and Barbuda", symbol: "$", code: "XCD" },
  { country: "Argentina", symbol: "$", code: "ARS" },
  { country: "Armenia", symbol: "֏", code: "AMD" },
  { country: "Aruba", symbol: "ƒ", code: "AWG" },
  { country: "Australia", symbol: "$", code: "AUD" },
  { country: "Austria", symbol: "€", code: "EUR" },
  { country: "Azerbaijan", symbol: "₼", code: "AZN" },
  { country: "Bahamas", symbol: "$", code: "BSD" },
  { country: "Bahrain", symbol: ".د.ب", code: "BHD" },
  { country: "Bangladesh", symbol: "৳", code: "BDT" },
  { country: "Barbados", symbol: "$", code: "BBD" },
  { country: "Belgium", symbol: "€", code: "EUR" },
  { country: "Belize", symbol: "$", code: "BZD" },
  { country: "Bermuda", symbol: "$", code: "BMD" },
  { country: "Bhutan", symbol: "Nu.", code: "BTN" },
  { country: "Bolivia", symbol: "Bs.", code: "BOB" },
  { country: "Brazil", symbol: "R$", code: "BRL" },
  { country: "Canada", symbol: "$", code: "CAD" },
  { country: "Chile", symbol: "$", code: "CLP" },
  { country: "China", symbol: "¥", code: "CNY" },
  { country: "Colombia", symbol: "$", code: "COP" },
  { country: "Denmark", symbol: "kr", code: "DKK" },
  { country: "Egypt", symbol: "E£", code: "EGP" },
  { country: "France", symbol: "€", code: "EUR" },
  { country: "Germany", symbol: "€", code: "EUR" },
  { country: "Hong Kong", symbol: "HK$", code: "HKD" },
  { country: "Indonesia", symbol: "Rp", code: "IDR" },
  { country: "Ireland", symbol: "€", code: "EUR" },
  { country: "Israel", symbol: "₪", code: "ILS" },
  { country: "Italy", symbol: "€", code: "EUR" },
  { country: "Japan", symbol: "¥", code: "JPY" },
  { country: "Kenya", symbol: "KSh", code: "KES" },
  { country: "Kuwait", symbol: "KD", code: "KWD" },
  { country: "Malaysia", symbol: "RM", code: "MYR" },
  { country: "Mexico", symbol: "$", code: "MXN" },
  { country: "Nepal", symbol: "Rs", code: "NPR" },
  { country: "Netherlands", symbol: "€", code: "EUR" },
  { country: "New Zealand", symbol: "$", code: "NZD" },
  { country: "Nigeria", symbol: "₦", code: "NGN" },
  { country: "Norway", symbol: "kr", code: "NOK" },
  { country: "Oman", symbol: "OMR", code: "OMR" },
  { country: "Pakistan", symbol: "Rs", code: "PKR" },
  { country: "Philippines", symbol: "₱", code: "PHP" },
  { country: "Poland", symbol: "zł", code: "PLN" },
  { country: "Qatar", symbol: "QR", code: "QAR" },
  { country: "Russia", symbol: "₽", code: "RUB" },
  { country: "Saudi Arabia", symbol: "SR", code: "SAR" },
  { country: "Singapore", symbol: "$", code: "SGD" },
  { country: "South Africa", symbol: "R", code: "ZAR" },
  { country: "South Korea", symbol: "₩", code: "KRW" },
  { country: "Spain", symbol: "€", code: "EUR" },
  { country: "Sri Lanka", symbol: "Rs", code: "LKR" },
  { country: "Sweden", symbol: "kr", code: "SEK" },
  { country: "Switzerland", symbol: "CHF", code: "CHF" },
  { country: "Thailand", symbol: "฿", code: "THB" },
  { country: "Turkey", symbol: "₺", code: "TRY" },
  { country: "Vietnam", symbol: "₫", code: "VND" },
];
