/**
 * Prebuilt rich industry templates for instant store setup
 * Kirana, Salon, Restaurant, Fashion/Boutique, Bakery
 */

export interface TemplateProduct {
  id: string;
  name: string;
  price: number;
  category: string;
  description: string;
  unit?: string;
  stock?: number;
  durationMins?: number;
  isVeg?: boolean;
  imageUrl?: string;
  isActive: boolean;
}

export interface IndustryTemplate {
  key: string;
  name: string;
  tagline: string;
  icon: string;
  accentColor: string;
  bannerUrl: string;
  categories: string[];
  products: TemplateProduct[];
}

export const INDUSTRY_TEMPLATES: Record<string, IndustryTemplate> = {
  kirana: {
    key: 'kirana',
    name: 'Kirana & Grocery Mart',
    tagline: 'Daily essentials, fresh groceries, staples & personal care',
    icon: 'local-grocery-store',
    accentColor: '#059669',
    bannerUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    categories: ['Atta & Flour', 'Rice & Dals', 'Edible Oils & Ghee', 'Snacks & Biscuits', 'Spices & Masala', 'Dairy & Milk', 'Home & Personal Care'],
    products: [
      {
        id: 'kirana-1',
        name: 'Aashirvaad Shudh Chakki Atta (5kg)',
        price: 245,
        category: 'Atta & Flour',
        unit: '5 kg',
        stock: 40,
        description: '100% whole wheat chakki atta with natural dietary fibers.',
        isActive: true,
      },
      {
        id: 'kirana-2',
        name: 'India Gate Basmati Rice Feast Rozzana (1kg)',
        price: 110,
        category: 'Rice & Dals',
        unit: '1 kg',
        stock: 35,
        description: 'Aromatic long-grain basmati rice ideal for everyday meals.',
        isActive: true,
      },
      {
        id: 'kirana-3',
        name: 'Tata Sampann Unpolished Toor Dal (1kg)',
        price: 175,
        category: 'Rice & Dals',
        unit: '1 kg',
        stock: 50,
        description: 'Nutritious unpolished toor dal rich in protein.',
        isActive: true,
      },
      {
        id: 'kirana-4',
        name: 'Fortune Sunlite Refined Sunflower Oil (1L Pouch)',
        price: 140,
        category: 'Edible Oils & Ghee',
        unit: '1 L',
        stock: 60,
        description: 'Light and healthy refined sunflower oil enriched with vitamins.',
        isActive: true,
      },
      {
        id: 'kirana-5',
        name: 'Amul Pure Cow Ghee (500ml)',
        price: 310,
        category: 'Edible Oils & Ghee',
        unit: '500 ml',
        stock: 25,
        description: 'Pure, aromatic cow ghee for traditional cooking and sweets.',
        isActive: true,
      },
      {
        id: 'kirana-6',
        name: 'Amul Taaza Homogenised Toned Milk (1L)',
        price: 74,
        category: 'Dairy & Milk',
        unit: '1 L',
        stock: 80,
        description: 'Fresh toned milk with long shelf life, perfect for tea and coffee.',
        isActive: true,
      },
      {
        id: 'kirana-7',
        name: 'Maggi 2-Minute Masala Noodles (Pack of 4)',
        price: 56,
        category: 'Snacks & Biscuits',
        unit: '280 g',
        stock: 100,
        description: 'Classic favorite noodle snack with authentic masala tastemaker.',
        isActive: true,
      },
      {
        id: 'kirana-8',
        name: 'Parle-G Gold Biscuits (1kg Family Pack)',
        price: 130,
        category: 'Snacks & Biscuits',
        unit: '1 kg',
        stock: 45,
        description: 'Crispy, tasty glucose biscuits loved by generations.',
        isActive: true,
      },
      {
        id: 'kirana-9',
        name: 'Tata Salt Vacuum Evaporated (1kg)',
        price: 28,
        category: 'Spices & Masala',
        unit: '1 kg',
        stock: 150,
        description: 'Iodized salt essential for proper physical and mental growth.',
        isActive: true,
      },
      {
        id: 'kirana-10',
        name: 'MDH Deggi Mirch Powder (100g)',
        price: 88,
        category: 'Spices & Masala',
        unit: '100 g',
        stock: 40,
        description: 'Unique blend of mild red peppers for vibrant color and flavor.',
        isActive: true,
      },
      {
        id: 'kirana-11',
        name: 'Surf Excel Quick Wash Detergent Powder (1kg)',
        price: 145,
        category: 'Home & Personal Care',
        unit: '1 kg',
        stock: 30,
        description: 'Fast stain-removing formula that dissolves easily in water.',
        isActive: true,
      },
      {
        id: 'kirana-12',
        name: 'Dettol Original Bathing Soap (Pack of 3)',
        price: 125,
        category: 'Home & Personal Care',
        unit: '3 x 75g',
        stock: 50,
        description: 'Antibacterial germ protection soap for the whole family.',
        isActive: true,
      },
    ],
  },

  salon: {
    key: 'salon',
    name: 'Salon & Spa Studio',
    tagline: 'Professional hair, beard, skincare & beauty treatments',
    icon: 'content-cut',
    accentColor: '#8b5cf6',
    bannerUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    categories: ['Hair Care & Styling', 'Beard & Shave', 'Facial & Cleanup', 'Hair Treatments', 'Hands & Feet'],
    products: [
      {
        id: 'salon-1',
        name: 'Classic Men Haircut & Hairwash',
        price: 250,
        category: 'Hair Care & Styling',
        durationMins: 30,
        description: 'Consultation, precision scissor/clipper haircut, relaxing hairwash and blowout.',
        isActive: true,
      },
      {
        id: 'salon-2',
        name: 'Women Layered Haircut & Blowdry',
        price: 650,
        category: 'Hair Care & Styling',
        durationMins: 45,
        description: 'Customized layered cut, split ends trim, shampoo, conditioning and styling.',
        isActive: true,
      },
      {
        id: 'salon-3',
        name: 'Signature Beard Sculpting & Royal Shave',
        price: 180,
        category: 'Beard & Shave',
        durationMins: 25,
        description: 'Hot towel steam, razor lining, beard oil massage and aftershave splash.',
        isActive: true,
      },
      {
        id: 'salon-4',
        name: 'O3+ Instant Glow Whitening Facial',
        price: 1450,
        category: 'Facial & Cleanup',
        durationMins: 60,
        description: 'Deep pore cleansing, fruit exfoliation, brightening serum and rubber mask.',
        isActive: true,
      },
      {
        id: 'salon-5',
        name: 'Anti-Pollution Charcoal Cleanup',
        price: 750,
        category: 'Facial & Cleanup',
        durationMins: 35,
        description: 'Activated charcoal treatment removing blackheads and excess oil.',
        isActive: true,
      },
      {
        id: 'salon-6',
        name: 'L’Oréal Keratin Hair Spa & Mask',
        price: 1200,
        category: 'Hair Treatments',
        durationMins: 50,
        description: 'Intense nourishing cream bath, 15-minute head massage and steam.',
        isActive: true,
      },
      {
        id: 'salon-7',
        name: 'Anti-Dandruff Scalp Treatment',
        price: 950,
        category: 'Hair Treatments',
        durationMins: 40,
        description: 'Targeted soothing serum treatment to clarify scalp and remove flakes.',
        isActive: true,
      },
      {
        id: 'salon-8',
        name: 'Deluxe Pedicure with Foot Scrub & Massage',
        price: 650,
        category: 'Hands & Feet',
        durationMins: 45,
        description: 'Warm sea-salt soak, cuticles cleanup, exfoliating scrub and relaxing foot massage.',
        isActive: true,
      },
    ],
  },

  restaurant: {
    key: 'restaurant',
    name: 'Cafe & Restaurant',
    tagline: 'Delicious starters, authentic mains, beverages & combos',
    icon: 'restaurant',
    accentColor: '#ea580c',
    bannerUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    categories: ['Starters & Snacks', 'Main Course', 'Rice & Biryani', 'Breads', 'Beverages & Shakes', 'Combos'],
    products: [
      {
        id: 'rest-1',
        name: 'Crispy Veg Spring Rolls (6 Pcs)',
        price: 160,
        category: 'Starters & Snacks',
        isVeg: true,
        description: 'Golden fried crispy rolls stuffed with shredded vegetables and sweet chili sauce.',
        isActive: true,
      },
      {
        id: 'rest-2',
        name: 'Paneer Tikka Tandoori (8 Pcs)',
        price: 240,
        category: 'Starters & Snacks',
        isVeg: true,
        description: 'Fresh cottage cheese cubes marinated in spiced yogurt and grilled in clay tandoor.',
        isActive: true,
      },
      {
        id: 'rest-3',
        name: 'Chicken Momos Steamed (8 Pcs)',
        price: 190,
        category: 'Starters & Snacks',
        isVeg: false,
        description: 'Juicy minced chicken wrapped in thin dough, served with fiery momo chutney.',
        isActive: true,
      },
      {
        id: 'rest-4',
        name: 'Paneer Butter Masala',
        price: 280,
        category: 'Main Course',
        isVeg: true,
        description: 'Soft cottage cheese simmered in a velvety tomato, butter, and cashew gravy.',
        isActive: true,
      },
      {
        id: 'rest-5',
        name: 'Dal Makhani Special',
        price: 220,
        category: 'Main Course',
        isVeg: true,
        description: 'Slow-cooked black lentils simmered overnight with butter and fresh cream.',
        isActive: true,
      },
      {
        id: 'rest-6',
        name: 'Dum Hyderabadi Veg Biryani',
        price: 250,
        category: 'Rice & Biryani',
        isVeg: true,
        description: 'Layers of basmati rice and marinated vegetables cooked under sealed dum, served with raita.',
        isActive: true,
      },
      {
        id: 'rest-7',
        name: 'Butter Naan',
        price: 45,
        category: 'Breads',
        isVeg: true,
        description: 'Clay-oven baked fluffy bread glazed with pure butter.',
        isActive: true,
      },
      {
        id: 'rest-8',
        name: 'Thick Cold Coffee with Ice Cream',
        price: 120,
        category: 'Beverages & Shakes',
        isVeg: true,
        description: 'Blended espresso with chilled creamy milk and a scoop of vanilla ice cream.',
        isActive: true,
      },
      {
        id: 'rest-9',
        name: 'Executive Thali Combo',
        price: 299,
        category: 'Combos',
        isVeg: true,
        description: 'Paneer dish, Dal Makhani, 2 Butter Rotis, Jeera Rice, Gulab Jamun, and Salad.',
        isActive: true,
      },
    ],
  },

  boutique: {
    key: 'boutique',
    name: 'Fashion & Boutique',
    tagline: 'Trending ethnic wear, western outfits & everyday fashion',
    icon: 'checkroom',
    accentColor: '#db2777',
    bannerUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    categories: ['Ethnic Wear', 'Western Tops & Tees', 'Bottom Wear', 'Dresses', 'Accessories'],
    products: [
      {
        id: 'boutique-1',
        name: 'Embroidered Cotton Anarkali Kurti',
        price: 1299,
        category: 'Ethnic Wear',
        unit: 'Sizes: S, M, L, XL',
        stock: 25,
        description: 'Pure breathable cotton kurti with exquisite threadwork and matching dupatta.',
        isActive: true,
      },
      {
        id: 'boutique-2',
        name: 'Chanderi Silk Printed Saree',
        price: 1850,
        category: 'Ethnic Wear',
        unit: 'With Blouse Piece',
        stock: 15,
        description: 'Lightweight Chanderi silk saree with floral print and golden zari border.',
        isActive: true,
      },
      {
        id: 'boutique-3',
        name: 'Oversized Cotton Graphic T-Shirt',
        price: 599,
        category: 'Western Tops & Tees',
        unit: 'Sizes: M, L, XL',
        stock: 40,
        description: '240 GSM pre-shrunk heavy cotton street-style drop shoulder tee.',
        isActive: true,
      },
      {
        id: 'boutique-4',
        name: 'High-Waist Stretchable Denim Jeans',
        price: 1199,
        category: 'Bottom Wear',
        unit: 'Sizes: 28, 30, 32, 34',
        stock: 30,
        description: 'Flattering slim fit high-rise denim with 4-way comfort stretch.',
        isActive: true,
      },
      {
        id: 'boutique-5',
        name: 'Floral Chiffon Midi Summer Dress',
        price: 1450,
        category: 'Dresses',
        unit: 'Sizes: S, M, L',
        stock: 20,
        description: 'Flowy chiffon midi dress with adjustable waist tie and sweetheart neckline.',
        isActive: true,
      },
      {
        id: 'boutique-6',
        name: 'Handcrafted Vegan Leather Tote Bag',
        price: 899,
        category: 'Accessories',
        unit: 'Free Size',
        stock: 25,
        description: 'Spacious everyday tote bag with laptop sleeve and zippered compartments.',
        isActive: true,
      },
    ],
  },

  bakery: {
    key: 'bakery',
    name: 'Bakery & Cake Shop',
    tagline: 'Artisan cakes, pastries, breads & handmade cookies',
    icon: 'cake',
    accentColor: '#d97706',
    bannerUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    categories: ['Custom Cakes', 'Pastries & Desserts', 'Artisan Breads', 'Cookies & Savories'],
    products: [
      {
        id: 'bakery-1',
        name: 'Dutch Chocolate Truffle Cake (0.5kg)',
        price: 499,
        category: 'Custom Cakes',
        unit: '0.5 kg (Eggless)',
        stock: 15,
        description: 'Rich dark chocolate sponge layered with decadent Belgian ganache.',
        isActive: true,
      },
      {
        id: 'bakery-2',
        name: 'Red Velvet Cream Cheese Cake (1kg)',
        price: 950,
        category: 'Custom Cakes',
        unit: '1 kg (Eggless)',
        stock: 10,
        description: 'Classic crimson sponge frosted with smooth Philadelphia cream cheese.',
        isActive: true,
      },
      {
        id: 'bakery-3',
        name: 'Blueberry Glaze Cheesecake Slice',
        price: 160,
        category: 'Pastries & Desserts',
        unit: '1 Slice',
        stock: 25,
        description: 'New York style baked cheesecake topped with wild blueberry compote.',
        isActive: true,
      },
      {
        id: 'bakery-4',
        name: 'Warm Belgian Chocolate Lava Cake',
        price: 110,
        category: 'Pastries & Desserts',
        unit: '1 Pc',
        stock: 30,
        description: 'Individual molten cake with gooey, hot chocolate center.',
        isActive: true,
      },
      {
        id: 'bakery-5',
        name: 'Freshly Baked Garlic Herb Sourdough',
        price: 140,
        category: 'Artisan Breads',
        unit: '400 g Loaf',
        stock: 20,
        description: 'Naturally fermented 36-hour sourdough loaf with roasted garlic and rosemary.',
        isActive: true,
      },
      {
        id: 'bakery-6',
        name: 'Choco-Chip Butter Cookies Tin (300g)',
        price: 220,
        category: 'Cookies & Savories',
        unit: '300 g',
        stock: 35,
        description: 'Crispy, melt-in-mouth golden butter cookies loaded with chocolate chips.',
        isActive: true,
      },
    ],
  },
};
