import type { NodeTypeDefinition } from '@/types/workflow';

// ═══════════════════════════════════════════════════════════════════════════════
// NODE CATEGORIES — Sidebar configuration (merged enterprise + general workflow)
// ═══════════════════════════════════════════════════════════════════════════════

export const NODE_CATEGORIES = [
  { id: 'template', label: 'Templates', icon: 'Sparkles', color: 'yellow' },
  { id: 'trigger', label: 'Triggers', icon: 'PlayCircle', color: 'blue' },
  { id: 'condition', label: 'Conditions', icon: 'GitBranch', color: 'orange' },
  { id: 'action', label: 'Actions', icon: 'Zap', color: 'green' },
  { id: 'flowControl', label: 'Flow Control', icon: 'Workflow', color: 'purple' },
  { id: 'logic', label: 'Logic', icon: 'GitBranch', color: 'orange' },
  { id: 'code', label: 'Code', icon: 'Code', color: 'yellow' },
  { id: 'data', label: 'Data', icon: 'Database', color: 'blue' },
  { id: 'communication', label: 'Communication', icon: 'MessageSquare', color: 'pink' },
  { id: 'cloud', label: 'Cloud & Storage', icon: 'Cloud', color: 'amber' },
  { id: 'ai', label: 'AI', icon: 'Bot', color: 'pink' },
  { id: 'utility', label: 'Utilities', icon: 'Settings', color: 'gray' },
] as const;

// Backward-compatible alias for node-sidebar
export const nodeCategories = NODE_CATEGORIES;

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY COLOR MAP — Consistent color mapping for each category
// ═══════════════════════════════════════════════════════════════════════════════

const CATEGORY_COLORS: Record<string, string> = {
  template: 'bg-yellow-500',
  trigger: 'bg-blue-500',
  condition: 'bg-orange-500',
  action: 'bg-emerald-500',
  flowControl: 'bg-purple-500',
  logic: 'bg-orange-500',
  code: 'bg-yellow-500',
  data: 'bg-blue-500',
  communication: 'bg-pink-500',
  cloud: 'bg-amber-500',
  ai: 'bg-pink-500',
  utility: 'bg-gray-500',
};

// ═══════════════════════════════════════════════════════════════════════════════
// TRIGGER NODES — Enterprise events + General workflow triggers
// ═══════════════════════════════════════════════════════════════════════════════

export const triggerNodes: NodeTypeDefinition[] = [
  // ─── General Workflow Triggers ────────────────────────────────────────────
  {
    type: 'manualTrigger',
    displayName: 'Manual Trigger',
    category: 'trigger',
    description: 'Start workflow manually by clicking Execute',
    icon: 'MousePointerClick',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [],
  },
  {
    type: 'webhookTrigger',
    displayName: 'Webhook',
    category: 'trigger',
    description: 'Receive HTTP requests to trigger workflow',
    icon: 'Globe',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'httpMethod', displayName: 'HTTP Method', type: 'select', default: 'POST', options: [{ name: 'GET', value: 'GET' }, { name: 'POST', value: 'POST' }, { name: 'PUT', value: 'PUT' }, { name: 'PATCH', value: 'PATCH' }, { name: 'DELETE', value: 'DELETE' }] },
      { name: 'path', displayName: 'Path', type: 'string', placeholder: 'Auto-generated UUID' },
      { name: 'authentication', displayName: 'Authentication', type: 'select', default: 'none', options: [{ name: 'None', value: 'none' }, { name: 'Basic Auth', value: 'basic' }, { name: 'Header Auth', value: 'header' }, { name: 'JWT', value: 'jwt' }] },
      { name: 'respond', displayName: 'Respond', type: 'select', default: 'immediately', options: [{ name: 'Immediately', value: 'immediately' }, { name: 'When Last Node Finishes', value: 'lastNode' }, { name: 'Using Webhook Response Node', value: 'webhookResponse' }] },
      { name: 'responseCode', displayName: 'Response Code', type: 'number', default: 200 },
      { name: 'responseBody', displayName: 'Response Body', type: 'string', default: '{"success": true}' },
      { name: 'rawBody', displayName: 'Raw Body', type: 'boolean', default: false },
      { name: 'binaryData', displayName: 'Binary Data', type: 'boolean', default: false },
    ],
  },
  {
    type: 'scheduleTrigger',
    displayName: 'Schedule Trigger',
    category: 'trigger',
    description: 'Run workflow on a schedule using cron expressions',
    icon: 'Clock',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'interval', options: [{ name: 'Every X minutes', value: 'interval' }, { name: 'Cron Expression', value: 'cron' }] },
      { name: 'interval', displayName: 'Interval (minutes)', type: 'number', default: 5 },
      { name: 'cronExpression', displayName: 'Cron Expression', type: 'string', placeholder: '0 * * * *' },
      { name: 'timezone', displayName: 'Timezone', type: 'string', default: 'UTC' },
    ],
  },
  {
    type: 'emailTrigger',
    displayName: 'Email Trigger',
    category: 'trigger',
    description: 'Trigger workflow when receiving emails via IMAP',
    icon: 'Mail',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'host', displayName: 'IMAP Host', type: 'string', required: true },
      { name: 'port', displayName: 'Port', type: 'number', default: 993 },
      { name: 'username', displayName: 'Username', type: 'string', required: true },
      { name: 'password', displayName: 'Password', type: 'string', required: true },
      { name: 'folder', displayName: 'Folder', type: 'string', default: 'INBOX' },
    ],
    credentialTypes: ['httpBasic'],
  },
  {
    type: 'rssTrigger',
    displayName: 'RSS Feed Trigger',
    category: 'trigger',
    description: 'Poll RSS/Atom feeds for new items',
    icon: 'Rss',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'feedUrl', displayName: 'Feed URL', type: 'string', required: true, placeholder: 'https://example.com/feed.xml' },
      { name: 'pollInterval', displayName: 'Poll Interval (minutes)', type: 'number', default: 5 },
    ],
  },
  {
    type: 'httpRequestTrigger',
    displayName: 'HTTP Request Trigger',
    category: 'trigger',
    description: 'Trigger workflow when an HTTP request is received (forms, webhooks, API calls)',
    icon: 'Webhook',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'httpMethod', displayName: 'HTTP Method', type: 'select', default: 'POST', options: [{ name: 'GET', value: 'GET' }, { name: 'POST', value: 'POST' }, { name: 'PUT', value: 'PUT' }, { name: 'PATCH', value: 'PATCH' }, { name: 'DELETE', value: 'DELETE' }] },
      { name: 'path', displayName: 'Path', type: 'string', placeholder: 'Auto-generated UUID' },
      { name: 'sourceUrl', displayName: 'Source URL', type: 'string', placeholder: 'https://example.com/wp-admin/admin-ajax.php' },
      { name: 'contentType', displayName: 'Expected Content-Type', type: 'select', default: 'any', options: [{ name: 'Any', value: 'any' }, { name: 'JSON', value: 'application/json' }, { name: 'Form Data', value: 'multipart/form-data' }, { name: 'URL Encoded', value: 'application/x-www-form-urlencoded' }] },
      { name: 'authentication', displayName: 'Authentication', type: 'select', default: 'none', options: [{ name: 'None', value: 'none' }, { name: 'Basic Auth', value: 'basic' }, { name: 'Header Auth', value: 'header' }] },
      { name: 'respond', displayName: 'Respond', type: 'select', default: 'immediately', options: [{ name: 'Immediately', value: 'immediately' }, { name: 'When Last Node Finishes', value: 'lastNode' }] },
      { name: 'responseCode', displayName: 'Response Code', type: 'number', default: 200 },
      { name: 'responseBody', displayName: 'Response Body', type: 'string', default: '{"success": true}' },
    ],
  },

  // ─── CRM Events ──────────────────────────────────────────────────────────
  {
    type: 'leadCreated',
    displayName: 'Lead Created',
    category: 'trigger',
    description: 'When a new lead is created in the CRM',
    icon: 'UserPlus',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.created',
    properties: [],
  },
  {
    type: 'leadUpdated',
    displayName: 'Lead Updated',
    category: 'trigger',
    description: 'When a lead record is updated',
    icon: 'Edit3',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.updated',
    properties: [],
  },
  {
    type: 'leadAssigned',
    displayName: 'Lead Assigned',
    category: 'trigger',
    description: 'When a lead is assigned to a sales rep',
    icon: 'UserCheck',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.assigned',
    properties: [],
  },
  {
    type: 'leadConverted',
    displayName: 'Lead Converted',
    category: 'trigger',
    description: 'When a lead is converted to a customer',
    icon: 'CheckCircle',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.converted',
    properties: [],
  },
  {
    type: 'leadStatusChanged',
    displayName: 'Lead Status Changed',
    category: 'trigger',
    description: 'When a lead moves through the pipeline stages',
    icon: 'ArrowRightLeft',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.status_changed',
    properties: [],
  },
  {
    type: 'leadWon',
    displayName: 'Lead Won',
    category: 'trigger',
    description: 'When a lead is won — celebrate and start onboarding',
    icon: 'Trophy',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.won',
    properties: [],
  },
  {
    type: 'leadLost',
    displayName: 'Lead Lost',
    category: 'trigger',
    description: 'When a lead is lost — trigger recovery campaign',
    icon: 'Siren',
    color: 'bg-blue-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'lead.lost',
    properties: [],
  },

  // ─── Customer Events ─────────────────────────────────────────────────────
  {
    type: 'customerCreated',
    displayName: 'Customer Created',
    category: 'trigger',
    description: 'When a new customer is added to the system',
    icon: 'Users',
    color: 'bg-emerald-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'customer.created',
    properties: [],
  },
  {
    type: 'customerUpdated',
    displayName: 'Customer Updated',
    category: 'trigger',
    description: 'When customer details are updated',
    icon: 'UserCog',
    color: 'bg-emerald-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'customer.updated',
    properties: [],
  },
  {
    type: 'customerTagged',
    displayName: 'Customer Tagged',
    category: 'trigger',
    description: 'When a customer is tagged — add to marketing segment',
    icon: 'Hash',
    color: 'bg-emerald-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'customer.tagged',
    properties: [],
  },
  {
    type: 'customerJourneyChanged',
    displayName: 'Journey Stage Changed',
    category: 'trigger',
    description: 'When a customer moves to a new journey stage',
    icon: 'Route',
    color: 'bg-emerald-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'customer.journey_stage_changed',
    properties: [],
  },

  // ─── Booking Events ──────────────────────────────────────────────────────
  {
    type: 'bookingCreated',
    displayName: 'Booking Created',
    category: 'trigger',
    description: 'When a new booking is created',
    icon: 'CalendarPlus',
    color: 'bg-purple-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'booking.created',
    properties: [],
  },
  {
    type: 'bookingConfirmed',
    displayName: 'Booking Confirmed',
    category: 'trigger',
    description: 'When a booking is confirmed',
    icon: 'CalendarCheck',
    color: 'bg-purple-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'booking.confirmed',
    properties: [],
  },
  {
    type: 'bookingCancelled',
    displayName: 'Booking Cancelled',
    category: 'trigger',
    description: 'When a booking is cancelled',
    icon: 'CalendarX',
    color: 'bg-purple-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'booking.cancelled',
    properties: [],
  },
  {
    type: 'bookingCompleted',
    displayName: 'Booking Completed',
    category: 'trigger',
    description: 'When a booking is completed',
    icon: 'CircleCheck',
    color: 'bg-purple-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'booking.completed',
    properties: [],
  },
  {
    type: 'bookingRescheduled',
    displayName: 'Booking Rescheduled',
    category: 'trigger',
    description: 'When a booking is rescheduled',
    icon: 'CalendarClock',
    color: 'bg-purple-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'booking.rescheduled',
    properties: [],
  },

  // ─── Job Events ──────────────────────────────────────────────────────────
  {
    type: 'jobCreated',
    displayName: 'Job Created',
    category: 'trigger',
    description: 'When a new job is created',
    icon: 'Briefcase',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'job.created',
    properties: [],
  },
  {
    type: 'jobAssigned',
    displayName: 'Job Assigned',
    category: 'trigger',
    description: 'When a job is assigned to an employee',
    icon: 'UserCheck',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'job.assigned',
    properties: [],
  },
  {
    type: 'jobCompleted',
    displayName: 'Job Completed',
    category: 'trigger',
    description: 'When a job is marked as completed',
    icon: 'CircleCheck',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'job.completed',
    properties: [],
  },
  {
    type: 'jobCancelled',
    displayName: 'Job Cancelled',
    category: 'trigger',
    description: 'When a job is cancelled',
    icon: 'XCircle',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'job.cancelled',
    properties: [],
  },
  {
    type: 'jobStarted',
    displayName: 'Job Started',
    category: 'trigger',
    description: 'When a job is started by the employee',
    icon: 'Play',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'job.started',
    properties: [],
  },

  // ─── Invoice / Quote Events ──────────────────────────────────────────────
  {
    type: 'invoiceCreated',
    displayName: 'Invoice Created',
    category: 'trigger',
    description: 'When a new invoice is created',
    icon: 'Receipt',
    color: 'bg-rose-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'invoice.created',
    properties: [],
  },
  {
    type: 'invoicePaid',
    displayName: 'Invoice Paid',
    category: 'trigger',
    description: 'When an invoice is paid by the customer',
    icon: 'Banknote',
    color: 'bg-rose-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'invoice.paid',
    properties: [],
  },
  {
    type: 'invoiceOverdue',
    displayName: 'Invoice Overdue',
    category: 'trigger',
    description: 'When an invoice becomes overdue',
    icon: 'CreditCard',
    color: 'bg-rose-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'invoice.overdue',
    properties: [],
  },
  {
    type: 'quoteSent',
    displayName: 'Quote Sent',
    category: 'trigger',
    description: 'When a quote is sent to a customer',
    icon: 'Send',
    color: 'bg-rose-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'quote.sent',
    properties: [],
  },
  {
    type: 'quoteAccepted',
    displayName: 'Quote Accepted',
    category: 'trigger',
    description: 'When a quote is accepted by a customer',
    icon: 'FileCheck2',
    color: 'bg-rose-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'quote.accepted',
    properties: [],
  },
  {
    type: 'quoteRejected',
    displayName: 'Quote Rejected',
    category: 'trigger',
    description: 'When a quote is rejected by a customer',
    icon: 'FileX2',
    color: 'bg-rose-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'quote.rejected',
    properties: [],
  },

  // ─── WhatsApp Events ─────────────────────────────────────────────────────
  {
    type: 'whatsappMessageReceived',
    displayName: 'WhatsApp Message Received',
    category: 'trigger',
    description: 'When a new WhatsApp message is received',
    icon: 'MessageCircle',
    color: 'bg-green-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'whatsapp.message_received',
    properties: [],
  },
  {
    type: 'whatsappConversationStarted',
    displayName: 'Conversation Started',
    category: 'trigger',
    description: 'When a new WhatsApp conversation begins',
    icon: 'MessageSquarePlus',
    color: 'bg-green-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'whatsapp.conversation_started',
    properties: [],
  },
  {
    type: 'whatsappMessageDelivered',
    displayName: 'Message Delivered',
    category: 'trigger',
    description: 'When a WhatsApp message is delivered',
    icon: 'MailCheck',
    color: 'bg-green-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'whatsapp.message_delivered',
    properties: [],
  },
  {
    type: 'whatsappTemplateDelivered',
    displayName: 'Template Delivered',
    category: 'trigger',
    description: 'When a WhatsApp template message is delivered',
    icon: 'CheckCircle',
    color: 'bg-green-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'whatsapp.template_delivered',
    properties: [],
  },
  {
    type: 'whatsappTemplateFailed',
    displayName: 'Template Failed',
    category: 'trigger',
    description: 'When a WhatsApp template message fails to send',
    icon: 'AlertCircle',
    color: 'bg-green-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'whatsapp.template_failed',
    properties: [],
  },

  // ─── Form Events ─────────────────────────────────────────────────────────
  {
    type: 'formSubmitted',
    displayName: 'Form Submitted',
    category: 'trigger',
    description: 'When a form is submitted on your website',
    icon: 'MousePointerClick',
    color: 'bg-orange-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'form.submitted',
    properties: [],
  },
  {
    type: 'formSurveySubmitted',
    displayName: 'Survey Submitted',
    category: 'trigger',
    description: 'When a survey form is submitted',
    icon: 'ClipboardList',
    color: 'bg-orange-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'form.survey_submitted',
    properties: [],
  },
  {
    type: 'formAbandoned',
    displayName: 'Form Abandoned',
    category: 'trigger',
    description: 'When a form is started but not completed',
    icon: 'Inbox',
    color: 'bg-orange-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'form.abandoned',
    properties: [],
  },
  {
    type: 'websiteContactForm',
    displayName: 'Website Contact Form',
    category: 'trigger',
    description: 'When a contact form is submitted on your website',
    icon: 'Globe',
    color: 'bg-orange-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'website.contact_form',
    properties: [],
  },
  {
    type: 'websiteBookingForm',
    displayName: 'Website Booking Form',
    category: 'trigger',
    description: 'When a booking form is submitted on your website',
    icon: 'CalendarPlus',
    color: 'bg-orange-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'website.booking_form',
    properties: [],
  },
  {
    type: 'websiteQuoteRequest',
    displayName: 'Website Quote Request',
    category: 'trigger',
    description: 'When a quote request is submitted on your website',
    icon: 'Send',
    color: 'bg-orange-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'website.quote_request',
    properties: [],
  },

  // ─── Employee / System Events ────────────────────────────────────────────
  {
    type: 'employeeCreated',
    displayName: 'Employee Created',
    category: 'trigger',
    description: 'When a new employee is added to the system',
    icon: 'UserRoundPlus',
    color: 'bg-teal-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'employee.created',
    properties: [],
  },
  {
    type: 'employeeAvailable',
    displayName: 'Employee Available',
    category: 'trigger',
    description: 'When an employee becomes available',
    icon: 'UserCheck',
    color: 'bg-teal-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'employee.available',
    properties: [],
  },
  {
    type: 'employeeAssigned',
    displayName: 'Employee Assigned',
    category: 'trigger',
    description: 'When an employee is assigned to a job',
    icon: 'UserCheck',
    color: 'bg-teal-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'employee.assigned',
    properties: [],
  },
  {
    type: 'employeeOffline',
    displayName: 'Employee Offline',
    category: 'trigger',
    description: 'When an employee goes offline',
    icon: 'WifiOff',
    color: 'bg-teal-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'employee.offline',
    properties: [],
  },
  {
    type: 'userRegistered',
    displayName: 'User Registered',
    category: 'trigger',
    description: 'When a new user registers on the platform',
    icon: 'ShieldCheck',
    color: 'bg-teal-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'user.registered',
    properties: [],
  },
  {
    type: 'systemError',
    displayName: 'System Error',
    category: 'trigger',
    description: 'When a system error occurs',
    icon: 'AlertOctagon',
    color: 'bg-red-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'system.error',
    properties: [],
  },
  {
    type: 'systemApiCallFailed',
    displayName: 'API Call Failed',
    category: 'trigger',
    description: 'When an API call fails',
    icon: 'Unplug',
    color: 'bg-red-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    event: 'system.api_call_failed',
    properties: [],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CONDITION NODES — Domain-specific business conditions
// ═══════════════════════════════════════════════════════════════════════════════

export const conditionNodes: NodeTypeDefinition[] = [
  {
    type: 'leadSourceCondition',
    displayName: 'Lead Source',
    category: 'condition',
    description: 'Branch based on where the lead came from',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'Match' },
      { id: 'false', name: 'false', type: 'output', displayName: 'No Match' },
    ],
    properties: [
      { name: 'source', displayName: 'Lead Source', type: 'select', default: 'website', options: [
        { name: 'Website', value: 'website' },
        { name: 'Facebook', value: 'facebook' },
        { name: 'Google Ads', value: 'google_ads' },
        { name: 'WhatsApp', value: 'whatsapp' },
        { name: 'Referral', value: 'referral' },
        { name: 'Manual', value: 'manual' },
      ]},
    ],
  },
  {
    type: 'customerTypeCondition',
    displayName: 'Customer Type',
    category: 'condition',
    description: 'Branch based on customer type',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'Match' },
      { id: 'false', name: 'false', type: 'output', displayName: 'No Match' },
    ],
    properties: [
      { name: 'customerType', displayName: 'Customer Type', type: 'select', default: 'residential', options: [
        { name: 'Residential', value: 'residential' },
        { name: 'Commercial', value: 'commercial' },
        { name: 'Enterprise', value: 'enterprise' },
        { name: 'VIP', value: 'vip' },
      ]},
    ],
  },
  {
    type: 'bookingValueCondition',
    displayName: 'Booking Value',
    category: 'condition',
    description: 'Branch based on the booking value amount',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'Above' },
      { id: 'false', name: 'false', type: 'output', displayName: 'Below' },
    ],
    properties: [
      { name: 'operator', displayName: 'Condition', type: 'select', default: 'greater_than', options: [
        { name: 'Greater Than', value: 'greater_than' },
        { name: 'Less Than', value: 'less_than' },
        { name: 'Equals', value: 'equals' },
        { name: 'Between', value: 'between' },
      ]},
      { name: 'value', displayName: 'Amount', type: 'number', default: 500, required: true },
    ],
  },
  {
    type: 'invoiceAmountCondition',
    displayName: 'Invoice Amount',
    category: 'condition',
    description: 'Branch based on the invoice amount',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'Above' },
      { id: 'false', name: 'false', type: 'output', displayName: 'Below' },
    ],
    properties: [
      { name: 'operator', displayName: 'Condition', type: 'select', default: 'greater_than', options: [
        { name: 'Greater Than', value: 'greater_than' },
        { name: 'Less Than', value: 'less_than' },
        { name: 'Equals', value: 'equals' },
      ]},
      { name: 'value', displayName: 'Amount', type: 'number', default: 1000, required: true },
    ],
  },
  {
    type: 'customerTagCondition',
    displayName: 'Customer Has Tag',
    category: 'condition',
    description: 'Branch based on whether the customer has a specific tag',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'Has Tag' },
      { id: 'false', name: 'false', type: 'output', displayName: 'No Tag' },
    ],
    properties: [
      { name: 'tag', displayName: 'Tag Name', type: 'string', required: true, placeholder: 'e.g. vip, repeat-customer' },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ACTION NODES — Enterprise business actions
// ═══════════════════════════════════════════════════════════════════════════════

export const actionNodes: NodeTypeDefinition[] = [
  {
    type: 'assignOwner',
    displayName: 'Assign Owner',
    category: 'action',
    description: 'Assign the record to a team member',
    icon: 'UserPlus',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'assignTo', displayName: 'Assign To', type: 'select', default: 'round_robin', options: [
        { name: 'Round Robin', value: 'round_robin' },
        { name: 'Least Busy', value: 'least_busy' },
        { name: 'Specific User', value: 'specific' },
      ]},
      { name: 'userId', displayName: 'User ID', type: 'string', placeholder: 'Required if "Specific User" selected' },
    ],
  },
  {
    type: 'sendWhatsApp',
    displayName: 'Send WhatsApp',
    category: 'action',
    description: 'Send a WhatsApp message to the customer or team',
    icon: 'MessageCircle',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'recipient', displayName: 'Recipient', type: 'select', default: 'customer', options: [
        { name: 'Customer', value: 'customer' },
        { name: 'Employee', value: 'employee' },
        { name: 'Manager', value: 'manager' },
      ]},
      { name: 'template', displayName: 'Message Template', type: 'text', required: true, placeholder: 'Hi {{name}}, ...' },
    ],
  },
  {
    type: 'sendEmail',
    displayName: 'Send Email',
    category: 'action',
    description: 'Send an email to the customer or team',
    icon: 'Mail',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'recipient', displayName: 'Recipient', type: 'select', default: 'customer', options: [
        { name: 'Customer', value: 'customer' },
        { name: 'Employee', value: 'employee' },
        { name: 'Manager', value: 'manager' },
      ]},
      { name: 'subject', displayName: 'Subject', type: 'string', required: true, placeholder: 'Email subject' },
      { name: 'body', displayName: 'Body', type: 'text', required: true, placeholder: 'Email content...' },
    ],
  },
  {
    type: 'sendSMS',
    displayName: 'Send SMS',
    category: 'action',
    description: 'Send an SMS message',
    icon: 'Smartphone',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'recipient', displayName: 'Recipient', type: 'select', default: 'customer', options: [
        { name: 'Customer', value: 'customer' },
        { name: 'Employee', value: 'employee' },
      ]},
      { name: 'message', displayName: 'Message', type: 'text', required: true, placeholder: 'SMS content...' },
    ],
  },
  {
    type: 'sendNotification',
    displayName: 'Send Notification',
    category: 'action',
    description: 'Send an in-app notification to a user',
    icon: 'Bell',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'title', displayName: 'Title', type: 'string', required: true, placeholder: 'Notification title' },
      { name: 'message', displayName: 'Message', type: 'text', required: true, placeholder: 'Notification message' },
      { name: 'recipient', displayName: 'Recipient', type: 'select', default: 'owner', options: [
        { name: 'Record Owner', value: 'owner' },
        { name: 'Manager', value: 'manager' },
        { name: 'All Team', value: 'team' },
      ]},
    ],
  },
  {
    type: 'createTask',
    displayName: 'Create Task',
    category: 'action',
    description: 'Create a follow-up task for the team',
    icon: 'PlusCircle',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'title', displayName: 'Task Title', type: 'string', required: true, placeholder: 'Follow up with customer' },
      { name: 'assignTo', displayName: 'Assign To', type: 'select', default: 'round_robin', options: [
        { name: 'Round Robin', value: 'round_robin' },
        { name: 'Record Owner', value: 'owner' },
      ]},
      { name: 'dueIn', displayName: 'Due In (hours)', type: 'number', default: 24 },
    ],
  },
  {
    type: 'createBooking',
    displayName: 'Create Booking',
    category: 'action',
    description: 'Create a new booking from the workflow',
    icon: 'CalendarPlus',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'serviceId', displayName: 'Service', type: 'string', required: true, placeholder: 'Service ID' },
      { name: 'date', displayName: 'Date', type: 'string', required: true, placeholder: 'YYYY-MM-DD' },
    ],
  },
  {
    type: 'createJob',
    displayName: 'Create Job',
    category: 'action',
    description: 'Create a new job from the workflow',
    icon: 'Briefcase',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'title', displayName: 'Job Title', type: 'string', required: true, placeholder: 'Job title' },
      { name: 'assignTo', displayName: 'Assign To', type: 'select', default: 'auto', options: [
        { name: 'Auto Dispatch', value: 'auto' },
        { name: 'Round Robin', value: 'round_robin' },
        { name: 'Specific Employee', value: 'specific' },
      ]},
    ],
  },
  {
    type: 'assignEmployee',
    displayName: 'Assign Employee',
    category: 'action',
    description: 'Assign an employee to a job or task',
    icon: 'UserCheck',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'assignTo', displayName: 'Assign To', type: 'select', default: 'nearest', options: [
        { name: 'Nearest Available', value: 'nearest' },
        { name: 'Round Robin', value: 'round_robin' },
        { name: 'Specific Employee', value: 'specific' },
      ]},
      { name: 'employeeId', displayName: 'Employee ID', type: 'string', placeholder: 'Required if "Specific" selected' },
    ],
  },
  {
    type: 'createInvoice',
    displayName: 'Create Invoice',
    category: 'action',
    description: 'Create a new invoice from the workflow',
    icon: 'Receipt',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'amount', displayName: 'Amount', type: 'number', required: true },
      { name: 'description', displayName: 'Description', type: 'string', placeholder: 'Service description' },
      { name: 'dueIn', displayName: 'Due In (days)', type: 'number', default: 30 },
    ],
  },
  {
    type: 'createQuote',
    displayName: 'Create Quote',
    category: 'action',
    description: 'Create a new quote from the workflow',
    icon: 'FileText',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'amount', displayName: 'Amount', type: 'number', required: true },
      { name: 'description', displayName: 'Description', type: 'string', placeholder: 'Quote description' },
    ],
  },
  {
    type: 'addTag',
    displayName: 'Add Tag',
    category: 'action',
    description: 'Add a tag to the customer or record',
    icon: 'Tag',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'tag', displayName: 'Tag', type: 'string', required: true, placeholder: 'e.g. vip, follow-up, retention' },
    ],
  },
  {
    type: 'removeTag',
    displayName: 'Remove Tag',
    category: 'action',
    description: 'Remove a tag from the customer or record',
    icon: 'X',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'tag', displayName: 'Tag', type: 'string', required: true, placeholder: 'Tag to remove' },
    ],
  },
  {
    type: 'movePipeline',
    displayName: 'Move Pipeline Stage',
    category: 'action',
    description: 'Move a lead to a different pipeline stage',
    icon: 'ArrowRightLeft',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'stage', displayName: 'Target Stage', type: 'select', default: 'contacted', options: [
        { name: 'New', value: 'new' },
        { name: 'Contacted', value: 'contacted' },
        { name: 'Qualified', value: 'qualified' },
        { name: 'Proposal', value: 'proposal' },
        { name: 'Negotiation', value: 'negotiation' },
        { name: 'Won', value: 'won' },
        { name: 'Lost', value: 'lost' },
      ]},
    ],
  },
  {
    type: 'updateRecord',
    displayName: 'Update Record',
    category: 'action',
    description: 'Update a field on a CRM record (lead, customer, job)',
    icon: 'Save',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'recordType', displayName: 'Record Type', type: 'select', default: 'lead', options: [
        { name: 'Lead', value: 'lead' },
        { name: 'Customer', value: 'customer' },
        { name: 'Job', value: 'job' },
        { name: 'Booking', value: 'booking' },
      ]},
      { name: 'field', displayName: 'Field', type: 'string', required: true, placeholder: 'e.g. status, source, priority' },
      { name: 'value', displayName: 'Value', type: 'string', required: true, placeholder: 'New value' },
    ],
  },
  {
    type: 'callWebhook',
    displayName: 'Call Webhook',
    category: 'action',
    description: 'Send data to an external webhook URL',
    icon: 'Webhook',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'url', displayName: 'Webhook URL', type: 'string', required: true, placeholder: 'https://hooks.example.com/...' },
      { name: 'method', displayName: 'Method', type: 'select', default: 'POST', options: [
        { name: 'POST', value: 'POST' },
        { name: 'PUT', value: 'PUT' },
        { name: 'PATCH', value: 'PATCH' },
      ]},
      { name: 'headers', displayName: 'Headers (JSON)', type: 'json', default: {} },
    ],
  },
  // HTTP Request (from general workflow nodes)
  {
    type: 'httpRequest',
    displayName: 'HTTP Request',
    category: 'action',
    description: 'Make HTTP requests to any API',
    icon: 'Globe',
    color: 'bg-teal-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'method', displayName: 'Method', type: 'select', default: 'GET', options: [{ name: 'GET', value: 'GET' }, { name: 'POST', value: 'POST' }, { name: 'PUT', value: 'PUT' }, { name: 'PATCH', value: 'PATCH' }, { name: 'DELETE', value: 'DELETE' }, { name: 'HEAD', value: 'HEAD' }] },
      { name: 'url', displayName: 'URL', type: 'expression', required: true, placeholder: 'https://api.example.com/data' },
      { name: 'authentication', displayName: 'Authentication', type: 'select', default: 'none', options: [{ name: 'None', value: 'none' }, { name: 'Basic Auth', value: 'basic' }, { name: 'Bearer Token', value: 'bearer' }, { name: 'API Key', value: 'apiKey' }, { name: 'OAuth2', value: 'oAuth2' }] },
      { name: 'headers', displayName: 'Headers', type: 'json', default: '{}' },
      { name: 'queryParams', displayName: 'Query Parameters', type: 'json', default: '{}' },
      { name: 'body', displayName: 'Body', type: 'json' },
      { name: 'responseType', displayName: 'Response Type', type: 'select', default: 'json', options: [{ name: 'JSON', value: 'json' }, { name: 'Text', value: 'text' }, { name: 'Binary', value: 'binary' }] },
      { name: 'timeout', displayName: 'Timeout (ms)', type: 'number', default: 10000 },
      { name: 'followRedirects', displayName: 'Follow Redirects', type: 'boolean', default: true },
    ],
    credentialTypes: ['httpBasic', 'httpBearer', 'apiKey', 'oAuth2'],
  },
  {
    type: 'graphqlRequest',
    displayName: 'GraphQL',
    category: 'action',
    description: 'Execute GraphQL queries and mutations',
    icon: 'Share2',
    color: 'bg-teal-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'url', displayName: 'Endpoint URL', type: 'expression', required: true },
      { name: 'query', displayName: 'Query', type: 'code', required: true },
      { name: 'variables', displayName: 'Variables', type: 'json', default: '{}' },
      { name: 'headers', displayName: 'Headers', type: 'json', default: '{}' },
    ],
  },
  {
    type: 'webhookResponse',
    displayName: 'Webhook Response',
    category: 'action',
    description: 'Send a response back to a webhook trigger',
    icon: 'Reply',
    color: 'bg-teal-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [],
    properties: [
      { name: 'statusCode', displayName: 'Status Code', type: 'number', default: 200 },
      { name: 'body', displayName: 'Response Body', type: 'expression', default: '{"success": true}' },
      { name: 'headers', displayName: 'Headers', type: 'json', default: '{"Content-Type": "application/json"}' },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FLOW CONTROL NODES
// ═══════════════════════════════════════════════════════════════════════════════

export const flowControlNodes: NodeTypeDefinition[] = [
  {
    type: 'delay',
    displayName: 'Delay',
    category: 'flowControl',
    description: 'Wait for a specified duration before continuing',
    icon: 'Clock',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'delayMinutes', displayName: 'Delay (minutes)', type: 'number', default: 5, required: true },
    ],
  },
  {
    type: 'waitUntil',
    displayName: 'Wait Until',
    category: 'flowControl',
    description: 'Wait until a specific date/time before continuing',
    icon: 'Calendar',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'waitUntil', displayName: 'Wait Until', type: 'string', required: true, placeholder: 'YYYY-MM-DD HH:mm or expression' },
    ],
  },
  {
    type: 'ifElse',
    displayName: 'If / Else',
    category: 'flowControl',
    description: 'Branch workflow based on a condition',
    icon: 'GitBranch',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'True' },
      { id: 'false', name: 'false', type: 'output', displayName: 'False' },
    ],
    properties: [
      { name: 'condition', displayName: 'Condition', type: 'select', default: 'equals', options: [
        { name: 'Equals', value: 'equals' },
        { name: 'Not Equals', value: 'notEquals' },
        { name: 'Greater Than', value: 'greaterThan' },
        { name: 'Less Than', value: 'lessThan' },
        { name: 'Contains', value: 'contains' },
        { name: 'Is Empty', value: 'isEmpty' },
      ]},
      { name: 'value1', displayName: 'Value 1', type: 'expression', required: true },
      { name: 'value2', displayName: 'Value 2', type: 'expression' },
    ],
  },
  {
    type: 'switch',
    displayName: 'Switch',
    category: 'flowControl',
    description: 'Route to different outputs based on value matching',
    icon: 'Route',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'output0', name: 'Output 0', type: 'output' },
      { id: 'output1', name: 'Output 1', type: 'output' },
      { id: 'fallback', name: 'Fallback', type: 'output', displayName: 'Fallback' },
    ],
    properties: [
      { name: 'valueToMatch', displayName: 'Value to Match', type: 'expression', required: true },
      { name: 'rules', displayName: 'Rules', type: 'collection', description: 'Define routing rules' },
    ],
  },
  {
    type: 'loop',
    displayName: 'Loop',
    category: 'flowControl',
    description: 'Loop through items and process each one',
    icon: 'Repeat',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'each', name: 'each', type: 'output', displayName: 'Each Item' },
      { id: 'done', name: 'done', type: 'output', displayName: 'Done' },
    ],
    properties: [
      { name: 'batchSize', displayName: 'Batch Size', type: 'number', default: 1 },
    ],
  },
  {
    type: 'endWorkflow',
    displayName: 'End Workflow',
    category: 'flowControl',
    description: 'Stop the workflow execution',
    icon: 'Square',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [],
    properties: [],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// LOGIC NODES — Data manipulation and flow logic (n8n-style)
// ═══════════════════════════════════════════════════════════════════════════════

export const logicNodes: NodeTypeDefinition[] = [
  {
    type: 'ifNode',
    displayName: 'IF',
    category: 'logic',
    description: 'Branch workflow based on conditions',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'True' },
      { id: 'false', name: 'false', type: 'output', displayName: 'False' },
    ],
    properties: [
      { name: 'condition', displayName: 'Condition', type: 'select', default: 'equals', options: [{ name: 'Equals', value: 'equals' }, { name: 'Not Equals', value: 'notEquals' }, { name: 'Greater Than', value: 'greaterThan' }, { name: 'Less Than', value: 'lessThan' }, { name: 'Contains', value: 'contains' }, { name: 'Starts With', value: 'startsWith' }, { name: 'Ends With', value: 'endsWith' }, { name: 'Is Empty', value: 'isEmpty' }, { name: 'Is Not Empty', value: 'isNotEmpty' }, { name: 'Regex Match', value: 'regex' }] },
      { name: 'value1', displayName: 'Value 1', type: 'expression', required: true },
      { name: 'value2', displayName: 'Value 2', type: 'expression' },
      { name: 'combineOp', displayName: 'Combine Conditions', type: 'select', default: 'and', options: [{ name: 'AND', value: 'and' }, { name: 'OR', value: 'or' }] },
    ],
  },
  {
    type: 'switchNode',
    displayName: 'Switch',
    category: 'logic',
    description: 'Route to different outputs based on value matching',
    icon: 'Route',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'output0', name: 'Output 0', type: 'output' },
      { id: 'output1', name: 'Output 1', type: 'output' },
      { id: 'fallback', name: 'Fallback', type: 'output', displayName: 'Fallback' },
    ],
    properties: [
      { name: 'valueToMatch', displayName: 'Value to Match', type: 'expression', required: true },
      { name: 'rules', displayName: 'Rules', type: 'collection', description: 'Define routing rules' },
    ],
  },
  {
    type: 'mergeNode',
    displayName: 'Merge',
    category: 'logic',
    description: 'Merge data from multiple branches',
    icon: 'Merge',
    color: 'bg-orange-500',
    inputs: [
      { id: 'input1', name: 'Input 1', type: 'input' },
      { id: 'input2', name: 'Input 2', type: 'input' },
    ],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'append', options: [{ name: 'Append', value: 'append' }, { name: 'Merge By Index', value: 'mergeByIndex' }, { name: 'Merge By Key', value: 'mergeByKey' }, { name: 'Combine', value: 'combine' }, { name: 'Keep Key Matches', value: 'keepKeyMatches' }] },
      { name: 'mergeKey', displayName: 'Merge Key', type: 'string', description: 'Field name to merge by (for Merge By Key mode)' },
    ],
  },
  {
    type: 'splitInBatches',
    displayName: 'Split In Batches',
    category: 'logic',
    description: 'Process items in batches of N',
    icon: 'Layers',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'main', name: 'main', type: 'output' },
      { id: 'done', name: 'done', type: 'output', displayName: 'Done' },
    ],
    properties: [
      { name: 'batchSize', displayName: 'Batch Size', type: 'number', default: 10, required: true },
    ],
  },
  {
    type: 'waitNode',
    displayName: 'Wait',
    category: 'logic',
    description: 'Pause execution for a duration or until a specific time',
    icon: 'Timer',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Wait Type', type: 'select', default: 'duration', options: [{ name: 'Duration', value: 'duration' }, { name: 'Until Date/Time', value: 'untilDateTime' }, { name: 'Until Webhook', value: 'untilWebhook' }] },
      { name: 'duration', displayName: 'Duration (seconds)', type: 'number', default: 60 },
      { name: 'resumeAt', displayName: 'Resume At', type: 'string', placeholder: '2024-12-31T00:00:00Z' },
    ],
  },
  {
    type: 'setError',
    displayName: 'Stop & Error',
    category: 'logic',
    description: 'Throw a custom error and halt workflow execution',
    icon: 'AlertTriangle',
    color: 'bg-red-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [],
    properties: [
      { name: 'errorMessage', displayName: 'Error Message', type: 'string', required: true, default: 'Workflow stopped with error' },
      { name: 'errorCode', displayName: 'Error Code', type: 'string' },
    ],
  },
  {
    type: 'setNode',
    displayName: 'Set',
    category: 'logic',
    description: 'Add, edit, or remove fields on items',
    icon: 'FileEdit',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'manual', options: [{ name: 'Manual', value: 'manual' }, { name: 'JSON', value: 'json' }] },
      { name: 'assignments', displayName: 'Assignments', type: 'collection', description: 'Key-value pairs to set' },
      { name: 'jsonValue', displayName: 'JSON', type: 'json', description: 'JSON to merge into item' },
    ],
  },
  {
    type: 'filterNode',
    displayName: 'Filter',
    category: 'logic',
    description: 'Keep only items matching a condition',
    icon: 'Filter',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'condition', displayName: 'Condition', type: 'select', default: 'equals', options: [{ name: 'Equals', value: 'equals' }, { name: 'Not Equals', value: 'notEquals' }, { name: 'Greater Than', value: 'greaterThan' }, { name: 'Less Than', value: 'lessThan' }, { name: 'Contains', value: 'contains' }, { name: 'Is Empty', value: 'isEmpty' }] },
      { name: 'value1', displayName: 'Value 1', type: 'expression', required: true },
      { name: 'value2', displayName: 'Value 2', type: 'expression' },
    ],
  },
  {
    type: 'sortNode',
    displayName: 'Sort',
    category: 'logic',
    description: 'Sort items by a field',
    icon: 'ArrowUpDown',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'sortField', displayName: 'Sort Field', type: 'expression', required: true },
      { name: 'sortOrder', displayName: 'Order', type: 'select', default: 'ascending', options: [{ name: 'Ascending', value: 'ascending' }, { name: 'Descending', value: 'descending' }] },
    ],
  },
  {
    type: 'limitNode',
    displayName: 'Limit',
    category: 'logic',
    description: 'Take only the first N items',
    icon: 'Minimize2',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'maxItems', displayName: 'Max Items', type: 'number', default: 1, required: true },
    ],
  },
  {
    type: 'removeDuplicates',
    displayName: 'Remove Duplicates',
    category: 'logic',
    description: 'Remove duplicate items based on a field',
    icon: 'CopyX',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'compareField', displayName: 'Compare Field', type: 'expression', required: true },
    ],
  },
  {
    type: 'aggregateNode',
    displayName: 'Aggregate',
    category: 'logic',
    description: 'Group items and apply aggregate functions',
    icon: 'Sigma',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'groupBy', displayName: 'Group By Field', type: 'expression' },
      { name: 'aggregateField', displayName: 'Aggregate Field', type: 'expression', required: true },
      { name: 'aggregateFunction', displayName: 'Function', type: 'select', default: 'sum', options: [{ name: 'Sum', value: 'sum' }, { name: 'Average', value: 'avg' }, { name: 'Min', value: 'min' }, { name: 'Max', value: 'max' }, { name: 'Count', value: 'count' }] },
    ],
  },
  {
    type: 'dateTimeNode',
    displayName: 'DateTime',
    category: 'logic',
    description: 'Parse, format, and manipulate dates',
    icon: 'Calendar',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'format', options: [{ name: 'Format', value: 'format' }, { name: 'Parse', value: 'parse' }, { name: 'Add/Subtract', value: 'addSubtract' }, { name: 'Timezone Convert', value: 'timezone' }, { name: 'Difference', value: 'diff' }] },
      { name: 'value', displayName: 'Date Value', type: 'expression', placeholder: '{{ $json.date }}' },
      { name: 'format', displayName: 'Format', type: 'string', default: 'yyyy-MM-dd HH:mm:ss' },
      { name: 'amount', displayName: 'Amount', type: 'number', default: 0 },
      { name: 'unit', displayName: 'Unit', type: 'select', default: 'days', options: [{ name: 'Seconds', value: 'seconds' }, { name: 'Minutes', value: 'minutes' }, { name: 'Hours', value: 'hours' }, { name: 'Days', value: 'days' }, { name: 'Weeks', value: 'weeks' }, { name: 'Months', value: 'months' }, { name: 'Years', value: 'years' }] },
    ],
  },
  {
    type: 'cryptoNode',
    displayName: 'Crypto',
    category: 'logic',
    description: 'Hash, encrypt/decrypt, generate UUID',
    icon: 'Shield',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'hash', options: [{ name: 'Hash (MD5/SHA)', value: 'hash' }, { name: 'Encrypt (AES)', value: 'encrypt' }, { name: 'Decrypt (AES)', value: 'decrypt' }, { name: 'Generate UUID', value: 'uuid' }, { name: 'HMAC', value: 'hmac' }] },
      { name: 'algorithm', displayName: 'Algorithm', type: 'select', default: 'sha256', options: [{ name: 'MD5', value: 'md5' }, { name: 'SHA-256', value: 'sha256' }, { name: 'SHA-512', value: 'sha512' }] },
      { name: 'value', displayName: 'Value', type: 'expression', required: true },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CODE NODES
// ═══════════════════════════════════════════════════════════════════════════════

export const codeNodes: NodeTypeDefinition[] = [
  {
    type: 'javascriptCode',
    displayName: 'JavaScript',
    category: 'code',
    description: 'Run custom JavaScript code',
    icon: 'Code',
    color: 'bg-yellow-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'runOnceForAllItems', options: [{ name: 'Run Once for All Items', value: 'runOnceForAllItems' }, { name: 'Run Once for Each Item', value: 'runOnceForEachItem' }] },
      { name: 'code', displayName: 'Code', type: 'code', default: '// Access items with $input.all() or $input.first()\nconst items = $input.all();\n\nreturn items.map(item => {\n  return { json: { ...item.json, processed: true } };\n});' },
    ],
  },
  {
    type: 'pythonCode',
    displayName: 'Python',
    category: 'code',
    description: 'Run custom Python code',
    icon: 'Terminal',
    color: 'bg-yellow-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'code', displayName: 'Code', type: 'code', default: '# Process items\ndef execute(items):\n    for item in items:\n        item["processed"] = True\n    return items' },
    ],
  },
  {
    type: 'expressionEvaluator',
    displayName: 'Expression',
    category: 'code',
    description: 'Evaluate expressions with template syntax {{ $json.field }}',
    icon: 'Braces',
    color: 'bg-yellow-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'expression', displayName: 'Expression', type: 'expression', required: true, placeholder: '{{ $json.name }} is {{ $json.age }} years old' },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// DATA / DATABASE NODES
// ═══════════════════════════════════════════════════════════════════════════════

export const dataNodes: NodeTypeDefinition[] = [
  {
    type: 'postgresNode',
    displayName: 'PostgreSQL',
    category: 'data',
    description: 'Query, insert, update, or delete data in PostgreSQL',
    icon: 'Database',
    color: 'bg-blue-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'executeQuery', options: [{ name: 'Execute Query', value: 'executeQuery' }, { name: 'Insert', value: 'insert' }, { name: 'Update', value: 'update' }, { name: 'Delete', value: 'delete' }] },
      { name: 'table', displayName: 'Table', type: 'string' },
      { name: 'query', displayName: 'Query', type: 'code' },
      { name: 'queryParams', displayName: 'Query Parameters', type: 'json', default: '{}' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'mysqlNode',
    displayName: 'MySQL',
    category: 'data',
    description: 'Query and modify data in MySQL/MariaDB',
    icon: 'Database',
    color: 'bg-blue-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'executeQuery', options: [{ name: 'Execute Query', value: 'executeQuery' }, { name: 'Insert', value: 'insert' }, { name: 'Update', value: 'update' }, { name: 'Delete', value: 'delete' }] },
      { name: 'table', displayName: 'Table', type: 'string' },
      { name: 'query', displayName: 'Query', type: 'code' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'mongoNode',
    displayName: 'MongoDB',
    category: 'data',
    description: 'Query and modify documents in MongoDB',
    icon: 'Database',
    color: 'bg-green-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'find', options: [{ name: 'Find', value: 'find' }, { name: 'Insert One', value: 'insertOne' }, { name: 'Update One', value: 'updateOne' }, { name: 'Delete One', value: 'deleteOne' }, { name: 'Aggregate', value: 'aggregate' }] },
      { name: 'collection', displayName: 'Collection', type: 'string', required: true },
      { name: 'query', displayName: 'Query', type: 'json', default: '{}' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'redisNode',
    displayName: 'Redis',
    category: 'data',
    description: 'Get, set, delete, or publish data in Redis',
    icon: 'Database',
    color: 'bg-red-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'get', options: [{ name: 'Get', value: 'get' }, { name: 'Set', value: 'set' }, { name: 'Delete', value: 'del' }, { name: 'Publish', value: 'publish' }, { name: 'Incr', value: 'incr' }, { name: 'Push', value: 'push' }] },
      { name: 'key', displayName: 'Key', type: 'expression', required: true },
      { name: 'value', displayName: 'Value', type: 'expression' },
      { name: 'ttl', displayName: 'TTL (seconds)', type: 'number' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'airtableNode',
    displayName: 'Airtable',
    category: 'data',
    description: 'Read and write records in Airtable',
    icon: 'Table',
    color: 'bg-teal-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'read', options: [{ name: 'Read', value: 'read' }, { name: 'Create', value: 'create' }, { name: 'Update', value: 'update' }, { name: 'Delete', value: 'delete' }] },
      { name: 'baseId', displayName: 'Base ID', type: 'string', required: true },
      { name: 'table', displayName: 'Table Name', type: 'string', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'googleSheetsNode',
    displayName: 'Google Sheets',
    category: 'data',
    description: 'Read and write data in Google Sheets',
    icon: 'Sheet',
    color: 'bg-green-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'read', options: [{ name: 'Read Rows', value: 'read' }, { name: 'Append Rows', value: 'append' }, { name: 'Update Rows', value: 'update' }, { name: 'Clear Sheet', value: 'clear' }] },
      { name: 'spreadsheetId', displayName: 'Spreadsheet ID', type: 'string', required: true },
      { name: 'range', displayName: 'Range', type: 'string', default: 'Sheet1!A:Z' },
    ],
    credentialTypes: ['oAuth2'],
  },
  {
    type: 'notionNode',
    displayName: 'Notion',
    category: 'data',
    description: 'Read and write pages and databases in Notion',
    icon: 'BookOpen',
    color: 'bg-neutral-700',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'queryDatabase', options: [{ name: 'Query Database', value: 'queryDatabase' }, { name: 'Get Page', value: 'getPage' }, { name: 'Create Page', value: 'createPage' }, { name: 'Update Page', value: 'updatePage' }] },
      { name: 'databaseId', displayName: 'Database ID', type: 'string' },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'databaseNode',
    displayName: 'Database Query',
    category: 'data',
    description: 'Query, insert, update, or delete data in FlowForge database (jobs, employees, customers, resources)',
    icon: 'Database',
    color: 'bg-emerald-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'query', options: [
        { name: 'Query (Find Many)', value: 'query' },
        { name: 'Find One', value: 'findOne' },
        { name: 'Insert (Create)', value: 'insert' },
        { name: 'Update', value: 'update' },
        { name: 'Delete', value: 'delete' },
        { name: 'Count', value: 'count' },
      ]},
      { name: 'table', displayName: 'Table', type: 'select', default: 'jobs', options: [
        { name: 'Jobs', value: 'jobs' },
        { name: 'Employees', value: 'employees' },
        { name: 'Customers', value: 'customers' },
        { name: 'Resources', value: 'resources' },
      ]},
      { name: 'filters', displayName: 'Filters (JSON)', type: 'json', default: '{}', description: 'Where clause as JSON' },
      { name: 'data', displayName: 'Data (JSON)', type: 'json', default: '{}', description: 'Data for insert/update operations' },
      { name: 'orderBy', displayName: 'Order By', type: 'string', placeholder: 'createdAt desc' },
      { name: 'limit', displayName: 'Limit', type: 'number', default: 100 },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// COMMUNICATION NODES
// ═══════════════════════════════════════════════════════════════════════════════

export const communicationNodes: NodeTypeDefinition[] = [
  {
    type: 'emailSend',
    displayName: 'Send Email (SMTP)',
    category: 'communication',
    description: 'Send emails via SMTP',
    icon: 'Send',
    color: 'bg-pink-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'from', displayName: 'From', type: 'string', required: true },
      { name: 'to', displayName: 'To', type: 'expression', required: true },
      { name: 'cc', displayName: 'CC', type: 'expression' },
      { name: 'bcc', displayName: 'BCC', type: 'expression' },
      { name: 'subject', displayName: 'Subject', type: 'expression', required: true },
      { name: 'body', displayName: 'Body', type: 'expression', required: true },
      { name: 'html', displayName: 'HTML Body', type: 'expression' },
    ],
    credentialTypes: ['httpBasic'],
  },
  {
    type: 'slackNode',
    displayName: 'Slack',
    category: 'communication',
    description: 'Send messages and interact with Slack',
    icon: 'MessageSquare',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendMessage', options: [{ name: 'Send Message', value: 'sendMessage' }, { name: 'Update Message', value: 'updateMessage' }, { name: 'Upload File', value: 'uploadFile' }] },
      { name: 'channel', displayName: 'Channel', type: 'expression', required: true, placeholder: '#general' },
      { name: 'text', displayName: 'Message', type: 'expression', required: true },
      { name: 'blocks', displayName: 'Blocks (JSON)', type: 'json' },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'discordNode',
    displayName: 'Discord',
    category: 'communication',
    description: 'Send messages to Discord channels via webhook',
    icon: 'MessageCircle',
    color: 'bg-indigo-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'webhookUrl', displayName: 'Webhook URL', type: 'expression', required: true },
      { name: 'content', displayName: 'Message', type: 'expression', required: true },
      { name: 'username', displayName: 'Username', type: 'string' },
      { name: 'embeds', displayName: 'Embeds (JSON)', type: 'json' },
    ],
  },
  {
    type: 'telegramNode',
    displayName: 'Telegram',
    category: 'communication',
    description: 'Send messages via Telegram Bot API',
    icon: 'Paperclip',
    color: 'bg-sky-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendMessage', options: [{ name: 'Send Message', value: 'sendMessage' }, { name: 'Send Photo', value: 'sendPhoto' }, { name: 'Send Document', value: 'sendDocument' }] },
      { name: 'chatId', displayName: 'Chat ID', type: 'expression', required: true },
      { name: 'text', displayName: 'Message', type: 'expression', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'twilioNode',
    displayName: 'Twilio',
    category: 'communication',
    description: 'Send SMS and make calls via Twilio',
    icon: 'Phone',
    color: 'bg-red-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendSms', options: [{ name: 'Send SMS', value: 'sendSms' }, { name: 'Make Call', value: 'makeCall' }] },
      { name: 'to', displayName: 'To Number', type: 'expression', required: true },
      { name: 'from', displayName: 'From Number', type: 'string', required: true },
      { name: 'body', displayName: 'Message', type: 'expression', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'gmailNode',
    displayName: 'Gmail',
    category: 'communication',
    description: 'Send and manage emails via Gmail API',
    icon: 'Mail',
    color: 'bg-red-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'send', options: [{ name: 'Send Email', value: 'send' }, { name: 'Get Email', value: 'get' }, { name: 'List Emails', value: 'list' }, { name: 'Reply', value: 'reply' }] },
      { name: 'to', displayName: 'To', type: 'expression', required: true },
      { name: 'subject', displayName: 'Subject', type: 'expression', required: true },
      { name: 'body', displayName: 'Body', type: 'expression', required: true },
    ],
    credentialTypes: ['oAuth2'],
  },
  {
    type: 'whatsappNode',
    displayName: 'WhatsApp Business Cloud',
    category: 'communication',
    description: 'Send WhatsApp messages, interactive buttons, and assignment workflows',
    icon: 'MessageCircle',
    color: 'bg-emerald-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendInteractive', options: [{ name: 'Send Text', value: 'sendText' }, { name: 'Send Template', value: 'sendTemplate' }, { name: 'Send Interactive', value: 'sendInteractive' }] },
      { name: 'phoneNumber', displayName: 'Phone Number', type: 'string', default: '' },
      { name: 'bodyText', displayName: 'Body Text', type: 'text', default: '' },
      { name: 'interactiveType', displayName: 'Interactive Type', type: 'select', default: 'button', options: [{ name: 'Button', value: 'button' }, { name: 'List', value: 'list' }, { name: 'CTA URL', value: 'cta_url' }] },
      { name: 'headerText', displayName: 'Header Text', type: 'string', default: '' },
      { name: 'footerText', displayName: 'Footer Text', type: 'string', default: '' },
      { name: 'templateName', displayName: 'Template Name', type: 'string', default: '' },
      { name: 'templateLanguage', displayName: 'Template Language', type: 'select', default: 'en_US', options: [{ name: 'English (US)', value: 'en_US' }, { name: 'English (UK)', value: 'en_GB' }, { name: 'English', value: 'en' }, { name: 'Hindi', value: 'hi' }, { name: 'Spanish', value: 'es' }, { name: 'Portuguese (BR)', value: 'pt_br' }] },
      { name: 'buttonText', displayName: 'Button Text', type: 'string', default: '' },
    ],
    credentialTypes: ['apiKey'],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CLOUD & STORAGE NODES
// ═══════════════════════════════════════════════════════════════════════════════

export const cloudNodes: NodeTypeDefinition[] = [
  {
    type: 'awsS3Node',
    displayName: 'AWS S3',
    category: 'cloud',
    description: 'Upload, download, and manage files in S3',
    icon: 'Cloud',
    color: 'bg-amber-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'upload', options: [{ name: 'Upload', value: 'upload' }, { name: 'Download', value: 'download' }, { name: 'List', value: 'list' }, { name: 'Delete', value: 'delete' }, { name: 'Get Presigned URL', value: 'presign' }] },
      { name: 'bucket', displayName: 'Bucket', type: 'string', required: true },
      { name: 'key', displayName: 'Key', type: 'expression', required: true },
    ],
    credentialTypes: ['awsIam'],
  },
  {
    type: 'googleDriveNode',
    displayName: 'Google Drive',
    category: 'cloud',
    description: 'Upload, download, and manage files in Google Drive',
    icon: 'HardDrive',
    color: 'bg-green-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'upload', options: [{ name: 'Upload', value: 'upload' }, { name: 'Download', value: 'download' }, { name: 'List', value: 'list' }, { name: 'Share', value: 'share' }] },
      { name: 'folderId', displayName: 'Folder ID', type: 'string' },
    ],
    credentialTypes: ['oAuth2'],
  },
  {
    type: 'githubNode',
    displayName: 'GitHub',
    category: 'cloud',
    description: 'Interact with GitHub repositories, issues, and PRs',
    icon: 'GitBranch',
    color: 'bg-neutral-700',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'createIssue', options: [{ name: 'Create Issue', value: 'createIssue' }, { name: 'List Issues', value: 'listIssues' }, { name: 'Create PR', value: 'createPR' }, { name: 'Get Repo', value: 'getRepo' }] },
      { name: 'owner', displayName: 'Owner', type: 'string', required: true },
      { name: 'repo', displayName: 'Repository', type: 'string', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// AI NODES — Enterprise AI + General AI nodes
// ═══════════════════════════════════════════════════════════════════════════════

export const aiNodes: NodeTypeDefinition[] = [
  // Enterprise AI
  {
    type: 'aiClassify',
    displayName: 'AI Classify',
    category: 'ai',
    description: 'Classify text using AI (e.g. lead intent, sentiment)',
    icon: 'Brain',
    color: 'bg-pink-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'input', displayName: 'Input Text', type: 'expression', required: true },
      { name: 'categories', displayName: 'Categories', type: 'string', required: true, placeholder: 'urgent, normal, low' },
    ],
  },
  {
    type: 'aiReply',
    displayName: 'AI Reply',
    category: 'ai',
    description: 'Generate an AI-powered reply to a message',
    icon: 'Bot',
    color: 'bg-pink-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'context', displayName: 'Context', type: 'text', placeholder: 'Provide context for the reply...' },
      { name: 'tone', displayName: 'Tone', type: 'select', default: 'professional', options: [
        { name: 'Professional', value: 'professional' },
        { name: 'Friendly', value: 'friendly' },
        { name: 'Casual', value: 'casual' },
      ]},
    ],
  },
  {
    type: 'aiSummarize',
    displayName: 'AI Summarize',
    category: 'ai',
    description: 'Summarize long text or conversation history',
    icon: 'FileText',
    color: 'bg-pink-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'input', displayName: 'Text to Summarize', type: 'expression', required: true },
      { name: 'maxLength', displayName: 'Max Length (words)', type: 'number', default: 100 },
    ],
  },
  // General AI
  {
    type: 'openaiNode',
    displayName: 'OpenAI',
    category: 'ai',
    description: 'Use OpenAI for chat completions, embeddings, and image generation',
    icon: 'Brain',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'chatCompletion', options: [{ name: 'Chat Completion', value: 'chatCompletion' }, { name: 'Embeddings', value: 'embeddings' }, { name: 'Image Generation', value: 'imageGeneration' }, { name: 'Audio Transcription', value: 'audioTranscription' }] },
      { name: 'model', displayName: 'Model', type: 'select', default: 'gpt-4o', options: [{ name: 'GPT-4o', value: 'gpt-4o' }, { name: 'GPT-4o Mini', value: 'gpt-4o-mini' }, { name: 'GPT-4 Turbo', value: 'gpt-4-turbo' }, { name: 'GPT-3.5 Turbo', value: 'gpt-3.5-turbo' }] },
      { name: 'prompt', displayName: 'Prompt', type: 'expression', required: true },
      { name: 'systemPrompt', displayName: 'System Prompt', type: 'expression' },
      { name: 'temperature', displayName: 'Temperature', type: 'number', default: 0.7 },
      { name: 'maxTokens', displayName: 'Max Tokens', type: 'number', default: 1000 },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'anthropicNode',
    displayName: 'Anthropic Claude',
    category: 'ai',
    description: 'Use Claude for text generation and analysis',
    icon: 'Sparkles',
    color: 'bg-orange-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'model', displayName: 'Model', type: 'select', default: 'claude-3-5-sonnet-20241022', options: [{ name: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet-20241022' }, { name: 'Claude 3 Opus', value: 'claude-3-opus-20240229' }, { name: 'Claude 3 Haiku', value: 'claude-3-haiku-20240307' }] },
      { name: 'prompt', displayName: 'Prompt', type: 'expression', required: true },
      { name: 'systemPrompt', displayName: 'System Prompt', type: 'expression' },
      { name: 'temperature', displayName: 'Temperature', type: 'number', default: 0.7 },
      { name: 'maxTokens', displayName: 'Max Tokens', type: 'number', default: 1000 },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'huggingFaceNode',
    displayName: 'Hugging Face',
    category: 'ai',
    description: 'Use Hugging Face models for inference',
    icon: 'Smile',
    color: 'bg-yellow-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'model', displayName: 'Model ID', type: 'string', required: true, placeholder: 'meta-llama/Llama-2-7b-chat-hf' },
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'textGeneration', options: [{ name: 'Text Generation', value: 'textGeneration' }, { name: 'Text Classification', value: 'textClassification' }, { name: 'Image Classification', value: 'imageClassification' }] },
      { name: 'input', displayName: 'Input', type: 'expression', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'vectorStoreNode',
    displayName: 'Vector Store',
    category: 'ai',
    description: 'Store and query vector embeddings',
    icon: 'Box',
    color: 'bg-cyan-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'query', options: [{ name: 'Upsert', value: 'upsert' }, { name: 'Query', value: 'query' }, { name: 'Delete', value: 'delete' }] },
      { name: 'provider', displayName: 'Provider', type: 'select', default: 'pinecone', options: [{ name: 'Pinecone', value: 'pinecone' }, { name: 'Qdrant', value: 'qdrant' }, { name: 'Weaviate', value: 'weaviate' }] },
      { name: 'indexName', displayName: 'Index Name', type: 'string', required: true },
      { name: 'vector', displayName: 'Vector', type: 'expression' },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'textSplitterNode',
    displayName: 'Text Splitter',
    category: 'ai',
    description: 'Split text into chunks for processing',
    icon: 'Scissors',
    color: 'bg-cyan-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'method', displayName: 'Method', type: 'select', default: 'character', options: [{ name: 'By Character', value: 'character' }, { name: 'By Token', value: 'token' }, { name: 'By Paragraph', value: 'paragraph' }, { name: 'Recursive', value: 'recursive' }] },
      { name: 'chunkSize', displayName: 'Chunk Size', type: 'number', default: 1000 },
      { name: 'overlap', displayName: 'Overlap', type: 'number', default: 200 },
      { name: 'separator', displayName: 'Separator', type: 'string', default: '\\n\\n' },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// UTILITY NODES
// ═══════════════════════════════════════════════════════════════════════════════

export const utilityNodes: NodeTypeDefinition[] = [
  {
    type: 'readFile',
    displayName: 'Read File',
    category: 'utility',
    description: 'Read a file from disk or URL',
    icon: 'FileText',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'source', displayName: 'Source', type: 'select', default: 'url', options: [{ name: 'URL', value: 'url' }, { name: 'Local File', value: 'local' }] },
      { name: 'url', displayName: 'URL', type: 'expression', placeholder: 'https://example.com/data.csv' },
      { name: 'filePath', displayName: 'File Path', type: 'string' },
    ],
  },
  {
    type: 'writeFile',
    displayName: 'Write File',
    category: 'utility',
    description: 'Write data to a file',
    icon: 'FileOutput',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'filePath', displayName: 'File Path', type: 'string', required: true },
      { name: 'content', displayName: 'Content', type: 'expression', required: true },
    ],
  },
  {
    type: 'pdfGenerator',
    displayName: 'PDF Generator',
    category: 'utility',
    description: 'Generate PDF from HTML content',
    icon: 'FileDown',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'html', displayName: 'HTML Content', type: 'expression', required: true },
      { name: 'fileName', displayName: 'File Name', type: 'string', default: 'output.pdf' },
    ],
  },
  {
    type: 'screenshotNode',
    displayName: 'Screenshot',
    category: 'utility',
    description: 'Capture a screenshot of a webpage',
    icon: 'Camera',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'url', displayName: 'URL', type: 'expression', required: true },
      { name: 'width', displayName: 'Width', type: 'number', default: 1280 },
      { name: 'height', displayName: 'Height', type: 'number', default: 720 },
      { name: 'fullPage', displayName: 'Full Page', type: 'boolean', default: false },
    ],
  },
  {
    type: 'qrCodeNode',
    displayName: 'QR Code',
    category: 'utility',
    description: 'Generate QR codes from text or URLs',
    icon: 'QrCode',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'value', displayName: 'Value', type: 'expression', required: true },
      { name: 'size', displayName: 'Size (px)', type: 'number', default: 256 },
    ],
  },
  {
    type: 'htmlExtract',
    displayName: 'HTML Extract',
    category: 'utility',
    description: 'Extract data from HTML using CSS selectors',
    icon: 'FileSearch',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'html', displayName: 'HTML', type: 'expression', required: true },
      { name: 'selector', displayName: 'CSS Selector', type: 'string', required: true, placeholder: '.article-title' },
      { name: 'attribute', displayName: 'Attribute', type: 'string', default: 'text' },
    ],
  },
  {
    type: 'jsonConvert',
    displayName: 'JSON Convert',
    category: 'utility',
    description: 'Convert between JSON, XML, CSV, and YAML formats',
    icon: 'ArrowLeftRight',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'from', displayName: 'From', type: 'select', default: 'json', options: [{ name: 'JSON', value: 'json' }, { name: 'XML', value: 'xml' }, { name: 'CSV', value: 'csv' }, { name: 'YAML', value: 'yaml' }] },
      { name: 'to', displayName: 'To', type: 'select', default: 'xml', options: [{ name: 'JSON', value: 'json' }, { name: 'XML', value: 'xml' }, { name: 'CSV', value: 'csv' }, { name: 'YAML', value: 'yaml' }] },
      { name: 'value', displayName: 'Value', type: 'expression', required: true },
    ],
  },
  {
    type: 'compressionNode',
    displayName: 'Compression',
    category: 'utility',
    description: 'Compress or decompress files (zip/unzip)',
    icon: 'FolderArchive',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'compress', options: [{ name: 'Compress', value: 'compress' }, { name: 'Decompress', value: 'decompress' }] },
      { name: 'format', displayName: 'Format', type: 'select', default: 'zip', options: [{ name: 'ZIP', value: 'zip' }, { name: 'GZIP', value: 'gzip' }, { name: 'TAR', value: 'tar' }] },
    ],
  },
  {
    type: 'imageResize',
    displayName: 'Image Resize',
    category: 'utility',
    description: 'Resize and compress images',
    icon: 'Image',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'width', displayName: 'Width', type: 'number' },
      { name: 'height', displayName: 'Height', type: 'number' },
      { name: 'quality', displayName: 'Quality (1-100)', type: 'number', default: 80 },
      { name: 'format', displayName: 'Format', type: 'select', default: 'jpeg', options: [{ name: 'JPEG', value: 'jpeg' }, { name: 'PNG', value: 'png' }, { name: 'WebP', value: 'webp' }] },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// WORKFLOW TEMPLATES
// ═══════════════════════════════════════════════════════════════════════════════

export const workflowTemplates = [
  { id: 'autoAssignLead', name: 'Auto Assign New Lead' },
  { id: 'welcomeCustomer', name: 'Welcome New Customer' },
  { id: 'bookingConfirmation', name: 'Booking Confirmation' },
  { id: 'jobCompletionReview', name: 'Job Completion Review Request' },
  { id: 'invoiceReminder', name: 'Invoice Reminder' },
  { id: 'autoDispatch', name: 'Auto Dispatch' },
  { id: 'customerRetention', name: 'Customer Retention Campaign' },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FLAT REGISTRY — All nodes combined (backward compatibility)
// ═══════════════════════════════════════════════════════════════════════════════

export const nodeRegistry: NodeTypeDefinition[] = [
  ...triggerNodes,
  ...conditionNodes,
  ...actionNodes,
  ...flowControlNodes,
  ...logicNodes,
  ...codeNodes,
  ...dataNodes,
  ...communicationNodes,
  ...cloudNodes,
  ...aiNodes,
  ...utilityNodes,
];

// ═══════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

/** Look up a node type definition by its type string */
export function getNodeTypeDefinition(type: string): NodeTypeDefinition | undefined {
  return nodeRegistry.find((n) => n.type === type);
}

/** Get all nodes belonging to a category */
export function getNodesByCategory(categoryId: string): NodeTypeDefinition[] {
  return nodeRegistry.filter((n) => n.category === categoryId);
}

/** Search nodes by display name or description */
export function searchNodes(query: string): NodeTypeDefinition[] {
  const q = query.toLowerCase();
  return nodeRegistry.filter(
    (n) =>
      n.displayName.toLowerCase().includes(q) ||
      n.description.toLowerCase().includes(q) ||
      n.type.toLowerCase().includes(q),
  );
}

/** Get the color for a given category */
export function getCategoryColor(categoryId: string): string {
  return CATEGORY_COLORS[categoryId] || 'bg-gray-500';
}
