import type { NodeTypeDefinition } from '@/types/workflow';

export const nodeCategories: { id: string; label: string; icon: string }[] = [
  { id: 'trigger', label: 'Triggers', icon: 'Zap' },
  { id: 'logic', label: 'Logic', icon: 'GitBranch' },
  { id: 'action', label: 'Actions', icon: 'Play' },
  { id: 'code', label: 'Code', icon: 'Code' },
  { id: 'data', label: 'Data', icon: 'Database' },
  { id: 'communication', label: 'Communication', icon: 'MessageSquare' },
  { id: 'cloud', label: 'Cloud & Storage', icon: 'Cloud' },
  { id: 'ai', label: 'AI & ML', icon: 'Brain' },
  { id: 'utility', label: 'Utility', icon: 'Wrench' },
];

export const nodeRegistry: NodeTypeDefinition[] = [
  // === TRIGGER NODES ===
  {
    type: 'manualTrigger',
    displayName: 'Manual Trigger',
    category: 'trigger',
    description: 'Start workflow manually by clicking Execute',
    icon: 'MousePointerClick',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [],
  },
  {
    type: 'webhookTrigger',
    displayName: 'Webhook',
    category: 'trigger',
    description: 'Receive HTTP requests to trigger workflow',
    icon: 'Globe',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [
      { id: 'main', name: 'main', type: 'output' },
    ],
    properties: [
      { name: 'httpMethod', displayName: 'HTTP Method', type: 'select', default: 'POST', options: [{ name: 'GET', value: 'GET' }, { name: 'POST', value: 'POST' }, { name: 'PUT', value: 'PUT' }, { name: 'PATCH', value: 'PATCH' }, { name: 'DELETE', value: 'DELETE' }] },
      { name: 'path', displayName: 'Path', type: 'string', placeholder: 'Auto-generated UUID' },
      { name: 'authentication', displayName: 'Authentication', type: 'select', default: 'none', options: [{ name: 'None', value: 'none' }, { name: 'Basic Auth', value: 'basic' }, { name: 'Header Auth', value: 'header' }, { name: 'JWT', value: 'jwt' }] },
      { name: 'respond', displayName: 'Respond', type: 'select', default: 'immediately', options: [{ name: 'Immediately', value: 'immediately' }, { name: 'When Last Node Finishes', value: 'lastNode' }, { name: 'Using Webhook Response Node', value: 'webhookResponse' }] },
      { name: 'responseCode', displayName: 'Response Code', type: 'number', default: 200 },
      { name: 'responseBody', displayName: 'Response Body', type: 'string', default: '{"success": true}' },
      { name: 'rawBody', displayName: 'Raw Body', type: 'boolean', default: false },
      { name: 'binaryData', displayName: 'Binary Data', type: 'boolean', default: false },
    ],
  },
  {
    type: 'scheduleTrigger',
    displayName: 'Schedule Trigger',
    category: 'trigger',
    description: 'Run workflow on a schedule using cron expressions',
    icon: 'Clock',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'interval', options: [{ name: 'Every X minutes', value: 'interval' }, { name: 'Cron Expression', value: 'cron' }] },
      { name: 'interval', displayName: 'Interval (minutes)', type: 'number', default: 5 },
      { name: 'cronExpression', displayName: 'Cron Expression', type: 'string', placeholder: '0 * * * *' },
      { name: 'timezone', displayName: 'Timezone', type: 'string', default: 'UTC' },
    ],
  },
  {
    type: 'emailTrigger',
    displayName: 'Email Trigger',
    category: 'trigger',
    description: 'Trigger workflow when receiving emails via IMAP',
    icon: 'Mail',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'host', displayName: 'IMAP Host', type: 'string', required: true },
      { name: 'port', displayName: 'Port', type: 'number', default: 993 },
      { name: 'username', displayName: 'Username', type: 'string', required: true },
      { name: 'password', displayName: 'Password', type: 'string', required: true },
      { name: 'folder', displayName: 'Folder', type: 'string', default: 'INBOX' },
    ],
    credentialTypes: ['httpBasic'],
  },
  {
    type: 'rssTrigger',
    displayName: 'RSS Feed Trigger',
    category: 'trigger',
    description: 'Poll RSS/Atom feeds for new items',
    icon: 'Rss',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'feedUrl', displayName: 'Feed URL', type: 'string', required: true, placeholder: 'https://example.com/feed.xml' },
      { name: 'pollInterval', displayName: 'Poll Interval (minutes)', type: 'number', default: 5 },
    ],
  },
  {
    type: 'httpRequestTrigger',
    displayName: 'HTTP Request Trigger',
    category: 'trigger',
    description: 'Trigger workflow when an HTTP request is received (forms, webhooks, API calls)',
    icon: 'Webhook',
    color: 'bg-amber-500',
    inputs: [],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'httpMethod', displayName: 'HTTP Method', type: 'select', default: 'POST', options: [{ name: 'GET', value: 'GET' }, { name: 'POST', value: 'POST' }, { name: 'PUT', value: 'PUT' }, { name: 'PATCH', value: 'PATCH' }, { name: 'DELETE', value: 'DELETE' }] },
      { name: 'path', displayName: 'Path', type: 'string', placeholder: 'Auto-generated UUID' },
      { name: 'sourceUrl', displayName: 'Source URL', type: 'string', placeholder: 'https://example.com/wp-admin/admin-ajax.php' },
      { name: 'contentType', displayName: 'Expected Content-Type', type: 'select', default: 'any', options: [{ name: 'Any', value: 'any' }, { name: 'JSON', value: 'application/json' }, { name: 'Form Data', value: 'multipart/form-data' }, { name: 'URL Encoded', value: 'application/x-www-form-urlencoded' }] },
      { name: 'authentication', displayName: 'Authentication', type: 'select', default: 'none', options: [{ name: 'None', value: 'none' }, { name: 'Basic Auth', value: 'basic' }, { name: 'Header Auth', value: 'header' }] },
      { name: 'respond', displayName: 'Respond', type: 'select', default: 'immediately', options: [{ name: 'Immediately', value: 'immediately' }, { name: 'When Last Node Finishes', value: 'lastNode' }] },
      { name: 'responseCode', displayName: 'Response Code', type: 'number', default: 200 },
      { name: 'responseBody', displayName: 'Response Body', type: 'string', default: '{"success": true}' },
    ],
  },

  // === LOGIC NODES ===
  {
    type: 'ifNode',
    displayName: 'IF',
    category: 'logic',
    description: 'Branch workflow based on conditions',
    icon: 'GitBranch',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'true', name: 'true', type: 'output', displayName: 'True' },
      { id: 'false', name: 'false', type: 'output', displayName: 'False' },
    ],
    properties: [
      { name: 'condition', displayName: 'Condition', type: 'select', default: 'equals', options: [{ name: 'Equals', value: 'equals' }, { name: 'Not Equals', value: 'notEquals' }, { name: 'Greater Than', value: 'greaterThan' }, { name: 'Less Than', value: 'lessThan' }, { name: 'Contains', value: 'contains' }, { name: 'Starts With', value: 'startsWith' }, { name: 'Ends With', value: 'endsWith' }, { name: 'Is Empty', value: 'isEmpty' }, { name: 'Is Not Empty', value: 'isNotEmpty' }, { name: 'Regex Match', value: 'regex' }] },
      { name: 'value1', displayName: 'Value 1', type: 'expression', required: true },
      { name: 'value2', displayName: 'Value 2', type: 'expression' },
      { name: 'combineOp', displayName: 'Combine Conditions', type: 'select', default: 'and', options: [{ name: 'AND', value: 'and' }, { name: 'OR', value: 'or' }] },
    ],
  },
  {
    type: 'switchNode',
    displayName: 'Switch',
    category: 'logic',
    description: 'Route to different outputs based on value matching',
    icon: 'Route',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'output0', name: 'Output 0', type: 'output' },
      { id: 'output1', name: 'Output 1', type: 'output' },
      { id: 'fallback', name: 'Fallback', type: 'output', displayName: 'Fallback' },
    ],
    properties: [
      { name: 'valueToMatch', displayName: 'Value to Match', type: 'expression', required: true },
      { name: 'rules', displayName: 'Rules', type: 'collection', description: 'Define routing rules' },
    ],
  },
  {
    type: 'mergeNode',
    displayName: 'Merge',
    category: 'logic',
    description: 'Merge data from multiple branches',
    icon: 'Merge',
    color: 'bg-orange-500',
    inputs: [
      { id: 'input1', name: 'Input 1', type: 'input' },
      { id: 'input2', name: 'Input 2', type: 'input' },
    ],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'append', options: [{ name: 'Append', value: 'append' }, { name: 'Merge By Index', value: 'mergeByIndex' }, { name: 'Merge By Key', value: 'mergeByKey' }, { name: 'Combine', value: 'combine' }, { name: 'Keep Key Matches', value: 'keepKeyMatches' }] },
      { name: 'mergeKey', displayName: 'Merge Key', type: 'string', description: 'Field name to merge by (for Merge By Key mode)' },
    ],
  },
  {
    type: 'splitInBatches',
    displayName: 'Split In Batches',
    category: 'logic',
    description: 'Process items in batches of N',
    icon: 'Layers',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [
      { id: 'main', name: 'main', type: 'output' },
      { id: 'done', name: 'done', type: 'output', displayName: 'Done' },
    ],
    properties: [
      { name: 'batchSize', displayName: 'Batch Size', type: 'number', default: 10, required: true },
    ],
  },
  {
    type: 'waitNode',
    displayName: 'Wait',
    category: 'logic',
    description: 'Pause execution for a duration or until a specific time',
    icon: 'Timer',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Wait Type', type: 'select', default: 'duration', options: [{ name: 'Duration', value: 'duration' }, { name: 'Until Date/Time', value: 'untilDateTime' }, { name: 'Until Webhook', value: 'untilWebhook' }] },
      { name: 'duration', displayName: 'Duration (seconds)', type: 'number', default: 60 },
      { name: 'resumeAt', displayName: 'Resume At', type: 'string', placeholder: '2024-12-31T00:00:00Z' },
    ],
  },
  {
    type: 'setError',
    displayName: 'Stop & Error',
    category: 'logic',
    description: 'Throw a custom error and halt workflow execution',
    icon: 'AlertTriangle',
    color: 'bg-red-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [],
    properties: [
      { name: 'errorMessage', displayName: 'Error Message', type: 'string', required: true, default: 'Workflow stopped with error' },
      { name: 'errorCode', displayName: 'Error Code', type: 'string' },
    ],
  },
  {
    type: 'setNode',
    displayName: 'Set',
    category: 'logic',
    description: 'Add, edit, or remove fields on items',
    icon: 'FileEdit',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'manual', options: [{ name: 'Manual', value: 'manual' }, { name: 'JSON', value: 'json' }] },
      { name: 'assignments', displayName: 'Assignments', type: 'collection', description: 'Key-value pairs to set' },
      { name: 'jsonValue', displayName: 'JSON', type: 'json', description: 'JSON to merge into item' },
    ],
  },
  {
    type: 'filterNode',
    displayName: 'Filter',
    category: 'logic',
    description: 'Keep only items matching a condition',
    icon: 'Filter',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'condition', displayName: 'Condition', type: 'select', default: 'equals', options: [{ name: 'Equals', value: 'equals' }, { name: 'Not Equals', value: 'notEquals' }, { name: 'Greater Than', value: 'greaterThan' }, { name: 'Less Than', value: 'lessThan' }, { name: 'Contains', value: 'contains' }, { name: 'Is Empty', value: 'isEmpty' }] },
      { name: 'value1', displayName: 'Value 1', type: 'expression', required: true },
      { name: 'value2', displayName: 'Value 2', type: 'expression' },
    ],
  },
  {
    type: 'sortNode',
    displayName: 'Sort',
    category: 'logic',
    description: 'Sort items by a field',
    icon: 'ArrowUpDown',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'sortField', displayName: 'Sort Field', type: 'expression', required: true },
      { name: 'sortOrder', displayName: 'Order', type: 'select', default: 'ascending', options: [{ name: 'Ascending', value: 'ascending' }, { name: 'Descending', value: 'descending' }] },
    ],
  },
  {
    type: 'limitNode',
    displayName: 'Limit',
    category: 'logic',
    description: 'Take only the first N items',
    icon: 'Minimize2',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'maxItems', displayName: 'Max Items', type: 'number', default: 1, required: true },
    ],
  },
  {
    type: 'removeDuplicates',
    displayName: 'Remove Duplicates',
    category: 'logic',
    description: 'Remove duplicate items based on a field',
    icon: 'CopyX',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'compareField', displayName: 'Compare Field', type: 'expression', required: true },
    ],
  },
  {
    type: 'aggregateNode',
    displayName: 'Aggregate',
    category: 'logic',
    description: 'Group items and apply aggregate functions',
    icon: 'Sigma',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'groupBy', displayName: 'Group By Field', type: 'expression' },
      { name: 'aggregateField', displayName: 'Aggregate Field', type: 'expression', required: true },
      { name: 'aggregateFunction', displayName: 'Function', type: 'select', default: 'sum', options: [{ name: 'Sum', value: 'sum' }, { name: 'Average', value: 'avg' }, { name: 'Min', value: 'min' }, { name: 'Max', value: 'max' }, { name: 'Count', value: 'count' }] },
    ],
  },
  {
    type: 'dateTimeNode',
    displayName: 'DateTime',
    category: 'logic',
    description: 'Parse, format, and manipulate dates',
    icon: 'Calendar',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'format', options: [{ name: 'Format', value: 'format' }, { name: 'Parse', value: 'parse' }, { name: 'Add/Subtract', value: 'addSubtract' }, { name: 'Timezone Convert', value: 'timezone' }, { name: 'Difference', value: 'diff' }] },
      { name: 'value', displayName: 'Date Value', type: 'expression', placeholder: '{{ $json.date }}' },
      { name: 'format', displayName: 'Format', type: 'string', default: 'yyyy-MM-dd HH:mm:ss' },
      { name: 'amount', displayName: 'Amount', type: 'number', default: 0 },
      { name: 'unit', displayName: 'Unit', type: 'select', default: 'days', options: [{ name: 'Seconds', value: 'seconds' }, { name: 'Minutes', value: 'minutes' }, { name: 'Hours', value: 'hours' }, { name: 'Days', value: 'days' }, { name: 'Weeks', value: 'weeks' }, { name: 'Months', value: 'months' }, { name: 'Years', value: 'years' }] },
    ],
  },
  {
    type: 'cryptoNode',
    displayName: 'Crypto',
    category: 'logic',
    description: 'Hash, encrypt/decrypt, generate UUID',
    icon: 'Shield',
    color: 'bg-orange-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'hash', options: [{ name: 'Hash (MD5/SHA)', value: 'hash' }, { name: 'Encrypt (AES)', value: 'encrypt' }, { name: 'Decrypt (AES)', value: 'decrypt' }, { name: 'Generate UUID', value: 'uuid' }, { name: 'HMAC', value: 'hmac' }] },
      { name: 'algorithm', displayName: 'Algorithm', type: 'select', default: 'sha256', options: [{ name: 'MD5', value: 'md5' }, { name: 'SHA-256', value: 'sha256' }, { name: 'SHA-512', value: 'sha512' }] },
      { name: 'value', displayName: 'Value', type: 'expression', required: true },
    ],
  },

  // === CODE NODES ===
  {
    type: 'javascriptCode',
    displayName: 'JavaScript',
    category: 'code',
    description: 'Run custom JavaScript code',
    icon: 'Code',
    color: 'bg-yellow-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'mode', displayName: 'Mode', type: 'select', default: 'runOnceForAllItems', options: [{ name: 'Run Once for All Items', value: 'runOnceForAllItems' }, { name: 'Run Once for Each Item', value: 'runOnceForEachItem' }] },
      { name: 'code', displayName: 'Code', type: 'code', default: '// Access items with $input.all() or $input.first()\nconst items = $input.all();\n\nreturn items.map(item => {\n  return { json: { ...item.json, processed: true } };\n});' },
    ],
  },
  {
    type: 'pythonCode',
    displayName: 'Python',
    category: 'code',
    description: 'Run custom Python code',
    icon: 'Terminal',
    color: 'bg-yellow-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'code', displayName: 'Code', type: 'code', default: '# Process items\ndef execute(items):\n    for item in items:\n        item["processed"] = True\n    return items' },
    ],
  },
  {
    type: 'expressionEvaluator',
    displayName: 'Expression',
    category: 'code',
    description: 'Evaluate expressions with template syntax {{ $json.field }}',
    icon: 'Braces',
    color: 'bg-yellow-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'expression', displayName: 'Expression', type: 'expression', required: true, placeholder: '{{ $json.name }} is {{ $json.age }} years old' },
    ],
  },

  // === HTTP / API NODES ===
  {
    type: 'httpRequest',
    displayName: 'HTTP Request',
    category: 'action',
    description: 'Make HTTP requests to any API',
    icon: 'Globe',
    color: 'bg-teal-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'method', displayName: 'Method', type: 'select', default: 'GET', options: [{ name: 'GET', value: 'GET' }, { name: 'POST', value: 'POST' }, { name: 'PUT', value: 'PUT' }, { name: 'PATCH', value: 'PATCH' }, { name: 'DELETE', value: 'DELETE' }, { name: 'HEAD', value: 'HEAD' }] },
      { name: 'url', displayName: 'URL', type: 'expression', required: true, placeholder: 'https://api.example.com/data' },
      { name: 'authentication', displayName: 'Authentication', type: 'select', default: 'none', options: [{ name: 'None', value: 'none' }, { name: 'Basic Auth', value: 'basic' }, { name: 'Bearer Token', value: 'bearer' }, { name: 'API Key', value: 'apiKey' }, { name: 'OAuth2', value: 'oAuth2' }] },
      { name: 'headers', displayName: 'Headers', type: 'json', default: '{}' },
      { name: 'queryParams', displayName: 'Query Parameters', type: 'json', default: '{}' },
      { name: 'body', displayName: 'Body', type: 'json' },
      { name: 'responseType', displayName: 'Response Type', type: 'select', default: 'json', options: [{ name: 'JSON', value: 'json' }, { name: 'Text', value: 'text' }, { name: 'Binary', value: 'binary' }] },
      { name: 'timeout', displayName: 'Timeout (ms)', type: 'number', default: 10000 },
      { name: 'followRedirects', displayName: 'Follow Redirects', type: 'boolean', default: true },
    ],
    credentialTypes: ['httpBasic', 'httpBearer', 'apiKey', 'oAuth2'],
  },
  {
    type: 'graphqlRequest',
    displayName: 'GraphQL',
    category: 'action',
    description: 'Execute GraphQL queries and mutations',
    icon: 'Share2',
    color: 'bg-teal-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'url', displayName: 'Endpoint URL', type: 'expression', required: true },
      { name: 'query', displayName: 'Query', type: 'code', required: true },
      { name: 'variables', displayName: 'Variables', type: 'json', default: '{}' },
      { name: 'headers', displayName: 'Headers', type: 'json', default: '{}' },
    ],
  },
  {
    type: 'webhookResponse',
    displayName: 'Webhook Response',
    category: 'action',
    description: 'Send a response back to a webhook trigger',
    icon: 'Reply',
    color: 'bg-teal-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [],
    properties: [
      { name: 'statusCode', displayName: 'Status Code', type: 'number', default: 200 },
      { name: 'body', displayName: 'Response Body', type: 'expression', default: '{"success": true}' },
      { name: 'headers', displayName: 'Headers', type: 'json', default: '{"Content-Type": "application/json"}' },
    ],
  },

  // === DATA / DATABASE NODES ===
  {
    type: 'postgresNode',
    displayName: 'PostgreSQL',
    category: 'data',
    description: 'Query, insert, update, or delete data in PostgreSQL',
    icon: 'Database',
    color: 'bg-blue-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'executeQuery', options: [{ name: 'Execute Query', value: 'executeQuery' }, { name: 'Insert', value: 'insert' }, { name: 'Update', value: 'update' }, { name: 'Delete', value: 'delete' }] },
      { name: 'table', displayName: 'Table', type: 'string' },
      { name: 'query', displayName: 'Query', type: 'code' },
      { name: 'queryParams', displayName: 'Query Parameters', type: 'json', default: '{}' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'mysqlNode',
    displayName: 'MySQL',
    category: 'data',
    description: 'Query and modify data in MySQL/MariaDB',
    icon: 'Database',
    color: 'bg-blue-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'executeQuery', options: [{ name: 'Execute Query', value: 'executeQuery' }, { name: 'Insert', value: 'insert' }, { name: 'Update', value: 'update' }, { name: 'Delete', value: 'delete' }] },
      { name: 'table', displayName: 'Table', type: 'string' },
      { name: 'query', displayName: 'Query', type: 'code' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'mongoNode',
    displayName: 'MongoDB',
    category: 'data',
    description: 'Query and modify documents in MongoDB',
    icon: 'Database',
    color: 'bg-green-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'find', options: [{ name: 'Find', value: 'find' }, { name: 'Insert One', value: 'insertOne' }, { name: 'Update One', value: 'updateOne' }, { name: 'Delete One', value: 'deleteOne' }, { name: 'Aggregate', value: 'aggregate' }] },
      { name: 'collection', displayName: 'Collection', type: 'string', required: true },
      { name: 'query', displayName: 'Query', type: 'json', default: '{}' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'redisNode',
    displayName: 'Redis',
    category: 'data',
    description: 'Get, set, delete, or publish data in Redis',
    icon: 'Database',
    color: 'bg-red-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'get', options: [{ name: 'Get', value: 'get' }, { name: 'Set', value: 'set' }, { name: 'Delete', value: 'del' }, { name: 'Publish', value: 'publish' }, { name: 'Incr', value: 'incr' }, { name: 'Push', value: 'push' }] },
      { name: 'key', displayName: 'Key', type: 'expression', required: true },
      { name: 'value', displayName: 'Value', type: 'expression' },
      { name: 'ttl', displayName: 'TTL (seconds)', type: 'number' },
    ],
    credentialTypes: ['dbConnection'],
  },
  {
    type: 'airtableNode',
    displayName: 'Airtable',
    category: 'data',
    description: 'Read and write records in Airtable',
    icon: 'Table',
    color: 'bg-teal-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'read', options: [{ name: 'Read', value: 'read' }, { name: 'Create', value: 'create' }, { name: 'Update', value: 'update' }, { name: 'Delete', value: 'delete' }] },
      { name: 'baseId', displayName: 'Base ID', type: 'string', required: true },
      { name: 'table', displayName: 'Table Name', type: 'string', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'googleSheetsNode',
    displayName: 'Google Sheets',
    category: 'data',
    description: 'Read and write data in Google Sheets',
    icon: 'Sheet',
    color: 'bg-green-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'read', options: [{ name: 'Read Rows', value: 'read' }, { name: 'Append Rows', value: 'append' }, { name: 'Update Rows', value: 'update' }, { name: 'Clear Sheet', value: 'clear' }] },
      { name: 'spreadsheetId', displayName: 'Spreadsheet ID', type: 'string', required: true },
      { name: 'range', displayName: 'Range', type: 'string', default: 'Sheet1!A:Z' },
    ],
    credentialTypes: ['oAuth2'],
  },
  {
    type: 'notionNode',
    displayName: 'Notion',
    category: 'data',
    description: 'Read and write pages and databases in Notion',
    icon: 'BookOpen',
    color: 'bg-neutral-700',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'queryDatabase', options: [{ name: 'Query Database', value: 'queryDatabase' }, { name: 'Get Page', value: 'getPage' }, { name: 'Create Page', value: 'createPage' }, { name: 'Update Page', value: 'updatePage' }] },
      { name: 'databaseId', displayName: 'Database ID', type: 'string' },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'databaseNode',
    displayName: 'Database Query',
    category: 'data',
    description: 'Query, insert, update, or delete data in FlowForge database (jobs, employees, customers, resources)',
    icon: 'Database',
    color: 'bg-emerald-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'query', options: [
        { name: 'Query (Find Many)', value: 'query' },
        { name: 'Find One', value: 'findOne' },
        { name: 'Insert (Create)', value: 'insert' },
        { name: 'Update', value: 'update' },
        { name: 'Delete', value: 'delete' },
        { name: 'Count', value: 'count' },
      ]},
      { name: 'table', displayName: 'Table', type: 'select', default: 'jobs', options: [
        { name: 'Jobs', value: 'jobs' },
        { name: 'Employees', value: 'employees' },
        { name: 'Customers', value: 'customers' },
        { name: 'Resources', value: 'resources' },
      ]},
      { name: 'filters', displayName: 'Filters (JSON)', type: 'json', default: '{}', description: 'Where clause as JSON, e.g. {"status": "available", "role": "driver"}' },
      { name: 'data', displayName: 'Data (JSON)', type: 'json', default: '{}', description: 'Data for insert/update operations' },
      { name: 'orderBy', displayName: 'Order By', type: 'string', placeholder: 'createdAt desc' },
      { name: 'limit', displayName: 'Limit', type: 'number', default: 100 },
    ],
  },

  // === COMMUNICATION NODES ===
  {
    type: 'emailSend',
    displayName: 'Send Email',
    category: 'communication',
    description: 'Send emails via SMTP',
    icon: 'Send',
    color: 'bg-pink-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'from', displayName: 'From', type: 'string', required: true },
      { name: 'to', displayName: 'To', type: 'expression', required: true },
      { name: 'cc', displayName: 'CC', type: 'expression' },
      { name: 'bcc', displayName: 'BCC', type: 'expression' },
      { name: 'subject', displayName: 'Subject', type: 'expression', required: true },
      { name: 'body', displayName: 'Body', type: 'expression', required: true },
      { name: 'html', displayName: 'HTML Body', type: 'expression' },
    ],
    credentialTypes: ['httpBasic'],
  },
  {
    type: 'slackNode',
    displayName: 'Slack',
    category: 'communication',
    description: 'Send messages and interact with Slack',
    icon: 'MessageSquare',
    color: 'bg-purple-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendMessage', options: [{ name: 'Send Message', value: 'sendMessage' }, { name: 'Update Message', value: 'updateMessage' }, { name: 'Upload File', value: 'uploadFile' }] },
      { name: 'channel', displayName: 'Channel', type: 'expression', required: true, placeholder: '#general' },
      { name: 'text', displayName: 'Message', type: 'expression', required: true },
      { name: 'blocks', displayName: 'Blocks (JSON)', type: 'json' },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'discordNode',
    displayName: 'Discord',
    category: 'communication',
    description: 'Send messages to Discord channels via webhook',
    icon: 'MessageCircle',
    color: 'bg-indigo-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'webhookUrl', displayName: 'Webhook URL', type: 'expression', required: true },
      { name: 'content', displayName: 'Message', type: 'expression', required: true },
      { name: 'username', displayName: 'Username', type: 'string' },
      { name: 'embeds', displayName: 'Embeds (JSON)', type: 'json' },
    ],
  },
  {
    type: 'telegramNode',
    displayName: 'Telegram',
    category: 'communication',
    description: 'Send messages via Telegram Bot API',
    icon: 'Paperclip',
    color: 'bg-sky-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendMessage', options: [{ name: 'Send Message', value: 'sendMessage' }, { name: 'Send Photo', value: 'sendPhoto' }, { name: 'Send Document', value: 'sendDocument' }] },
      { name: 'chatId', displayName: 'Chat ID', type: 'expression', required: true },
      { name: 'text', displayName: 'Message', type: 'expression', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'twilioNode',
    displayName: 'Twilio',
    category: 'communication',
    description: 'Send SMS and make calls via Twilio',
    icon: 'Phone',
    color: 'bg-red-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendSms', options: [{ name: 'Send SMS', value: 'sendSms' }, { name: 'Make Call', value: 'makeCall' }] },
      { name: 'to', displayName: 'To Number', type: 'expression', required: true },
      { name: 'from', displayName: 'From Number', type: 'string', required: true },
      { name: 'body', displayName: 'Message', type: 'expression', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'gmailNode',
    displayName: 'Gmail',
    category: 'communication',
    description: 'Send and manage emails via Gmail API',
    icon: 'Mail',
    color: 'bg-red-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'send', options: [{ name: 'Send Email', value: 'send' }, { name: 'Get Email', value: 'get' }, { name: 'List Emails', value: 'list' }, { name: 'Reply', value: 'reply' }] },
      { name: 'to', displayName: 'To', type: 'expression', required: true },
      { name: 'subject', displayName: 'Subject', type: 'expression', required: true },
      { name: 'body', displayName: 'Body', type: 'expression', required: true },
    ],
    credentialTypes: ['oAuth2'],
  },
  {
    type: 'whatsappNode',
    displayName: 'WhatsApp Business Cloud',
    category: 'communication',
    description: 'Send WhatsApp messages, interactive buttons, and assignment workflows',
    icon: 'MessageCircle',
    color: 'bg-emerald-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'sendInteractive', options: [{ name: 'Send Text', value: 'sendText' }, { name: 'Send Template', value: 'sendTemplate' }, { name: 'Send Interactive', value: 'sendInteractive' }] },
      { name: 'phoneNumber', displayName: 'Phone Number', type: 'string', default: '' },
      { name: 'bodyText', displayName: 'Body Text', type: 'text', default: '' },
      { name: 'interactiveType', displayName: 'Interactive Type', type: 'select', default: 'button', options: [{ name: 'Button', value: 'button' }, { name: 'List', value: 'list' }, { name: 'CTA URL', value: 'cta_url' }] },
      { name: 'headerText', displayName: 'Header Text', type: 'string', default: '' },
      { name: 'footerText', displayName: 'Footer Text', type: 'string', default: '' },
      { name: 'templateName', displayName: 'Template Name', type: 'string', default: '' },
      { name: 'templateLanguage', displayName: 'Template Language', type: 'select', default: 'en_US', options: [{ name: 'English (US)', value: 'en_US' }, { name: 'English (UK)', value: 'en_GB' }, { name: 'English', value: 'en' }, { name: 'Hindi', value: 'hi' }, { name: 'Spanish', value: 'es' }, { name: 'Portuguese (BR)', value: 'pt_br' }] },
      { name: 'buttonText', displayName: 'Button Text', type: 'string', default: '' },
    ],
    credentialTypes: ['apiKey'],
  },

  // === CLOUD / STORAGE NODES ===
  {
    type: 'awsS3Node',
    displayName: 'AWS S3',
    category: 'cloud',
    description: 'Upload, download, and manage files in S3',
    icon: 'Cloud',
    color: 'bg-amber-600',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'upload', options: [{ name: 'Upload', value: 'upload' }, { name: 'Download', value: 'download' }, { name: 'List', value: 'list' }, { name: 'Delete', value: 'delete' }, { name: 'Get Presigned URL', value: 'presign' }] },
      { name: 'bucket', displayName: 'Bucket', type: 'string', required: true },
      { name: 'key', displayName: 'Key', type: 'expression', required: true },
    ],
    credentialTypes: ['awsIam'],
  },
  {
    type: 'googleDriveNode',
    displayName: 'Google Drive',
    category: 'cloud',
    description: 'Upload, download, and manage files in Google Drive',
    icon: 'HardDrive',
    color: 'bg-green-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'upload', options: [{ name: 'Upload', value: 'upload' }, { name: 'Download', value: 'download' }, { name: 'List', value: 'list' }, { name: 'Share', value: 'share' }] },
      { name: 'folderId', displayName: 'Folder ID', type: 'string' },
    ],
    credentialTypes: ['oAuth2'],
  },
  {
    type: 'githubNode',
    displayName: 'GitHub',
    category: 'cloud',
    description: 'Interact with GitHub repositories, issues, and PRs',
    icon: 'GitBranch',
    color: 'bg-neutral-700',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'createIssue', options: [{ name: 'Create Issue', value: 'createIssue' }, { name: 'List Issues', value: 'listIssues' }, { name: 'Create PR', value: 'createPR' }, { name: 'Get Repo', value: 'getRepo' }] },
      { name: 'owner', displayName: 'Owner', type: 'string', required: true },
      { name: 'repo', displayName: 'Repository', type: 'string', required: true },
    ],
    credentialTypes: ['apiKey'],
  },

  // === AI / ML NODES ===
  {
    type: 'openaiNode',
    displayName: 'OpenAI',
    category: 'ai',
    description: 'Use OpenAI for chat completions, embeddings, and image generation',
    icon: 'Brain',
    color: 'bg-emerald-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'chatCompletion', options: [{ name: 'Chat Completion', value: 'chatCompletion' }, { name: 'Embeddings', value: 'embeddings' }, { name: 'Image Generation', value: 'imageGeneration' }, { name: 'Audio Transcription', value: 'audioTranscription' }] },
      { name: 'model', displayName: 'Model', type: 'select', default: 'gpt-4o', options: [{ name: 'GPT-4o', value: 'gpt-4o' }, { name: 'GPT-4o Mini', value: 'gpt-4o-mini' }, { name: 'GPT-4 Turbo', value: 'gpt-4-turbo' }, { name: 'GPT-3.5 Turbo', value: 'gpt-3.5-turbo' }] },
      { name: 'prompt', displayName: 'Prompt', type: 'expression', required: true },
      { name: 'systemPrompt', displayName: 'System Prompt', type: 'expression' },
      { name: 'temperature', displayName: 'Temperature', type: 'number', default: 0.7 },
      { name: 'maxTokens', displayName: 'Max Tokens', type: 'number', default: 1000 },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'anthropicNode',
    displayName: 'Anthropic Claude',
    category: 'ai',
    description: 'Use Claude for text generation and analysis',
    icon: 'Sparkles',
    color: 'bg-orange-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'model', displayName: 'Model', type: 'select', default: 'claude-3-5-sonnet-20241022', options: [{ name: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet-20241022' }, { name: 'Claude 3 Opus', value: 'claude-3-opus-20240229' }, { name: 'Claude 3 Haiku', value: 'claude-3-haiku-20240307' }] },
      { name: 'prompt', displayName: 'Prompt', type: 'expression', required: true },
      { name: 'systemPrompt', displayName: 'System Prompt', type: 'expression' },
      { name: 'temperature', displayName: 'Temperature', type: 'number', default: 0.7 },
      { name: 'maxTokens', displayName: 'Max Tokens', type: 'number', default: 1000 },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'huggingFaceNode',
    displayName: 'Hugging Face',
    category: 'ai',
    description: 'Use Hugging Face models for inference',
    icon: 'Smile',
    color: 'bg-yellow-400',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'model', displayName: 'Model ID', type: 'string', required: true, placeholder: 'meta-llama/Llama-2-7b-chat-hf' },
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'textGeneration', options: [{ name: 'Text Generation', value: 'textGeneration' }, { name: 'Text Classification', value: 'textClassification' }, { name: 'Image Classification', value: 'imageClassification' }] },
      { name: 'input', displayName: 'Input', type: 'expression', required: true },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'vectorStoreNode',
    displayName: 'Vector Store',
    category: 'ai',
    description: 'Store and query vector embeddings',
    icon: 'Box',
    color: 'bg-cyan-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'query', options: [{ name: 'Upsert', value: 'upsert' }, { name: 'Query', value: 'query' }, { name: 'Delete', value: 'delete' }] },
      { name: 'provider', displayName: 'Provider', type: 'select', default: 'pinecone', options: [{ name: 'Pinecone', value: 'pinecone' }, { name: 'Qdrant', value: 'qdrant' }, { name: 'Weaviate', value: 'weaviate' }] },
      { name: 'indexName', displayName: 'Index Name', type: 'string', required: true },
      { name: 'vector', displayName: 'Vector', type: 'expression' },
    ],
    credentialTypes: ['apiKey'],
  },
  {
    type: 'textSplitterNode',
    displayName: 'Text Splitter',
    category: 'ai',
    description: 'Split text into chunks for processing',
    icon: 'Scissors',
    color: 'bg-cyan-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'method', displayName: 'Method', type: 'select', default: 'character', options: [{ name: 'By Character', value: 'character' }, { name: 'By Token', value: 'token' }, { name: 'By Paragraph', value: 'paragraph' }, { name: 'Recursive', value: 'recursive' }] },
      { name: 'chunkSize', displayName: 'Chunk Size', type: 'number', default: 1000 },
      { name: 'overlap', displayName: 'Overlap', type: 'number', default: 200 },
      { name: 'separator', displayName: 'Separator', type: 'string', default: '\\n\\n' },
    ],
  },

  // === UTILITY NODES ===
  {
    type: 'readFile',
    displayName: 'Read File',
    category: 'utility',
    description: 'Read a file from disk or URL',
    icon: 'FileText',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'source', displayName: 'Source', type: 'select', default: 'url', options: [{ name: 'URL', value: 'url' }, { name: 'Local File', value: 'local' }] },
      { name: 'url', displayName: 'URL', type: 'expression', placeholder: 'https://example.com/data.csv' },
      { name: 'filePath', displayName: 'File Path', type: 'string' },
    ],
  },
  {
    type: 'writeFile',
    displayName: 'Write File',
    category: 'utility',
    description: 'Write data to a file',
    icon: 'FileOutput',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'filePath', displayName: 'File Path', type: 'string', required: true },
      { name: 'content', displayName: 'Content', type: 'expression', required: true },
    ],
  },
  {
    type: 'pdfGenerator',
    displayName: 'PDF Generator',
    category: 'utility',
    description: 'Generate PDF from HTML content',
    icon: 'FileDown',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'html', displayName: 'HTML Content', type: 'expression', required: true },
      { name: 'fileName', displayName: 'File Name', type: 'string', default: 'output.pdf' },
    ],
  },
  {
    type: 'screenshotNode',
    displayName: 'Screenshot',
    category: 'utility',
    description: 'Capture a screenshot of a webpage',
    icon: 'Camera',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'url', displayName: 'URL', type: 'expression', required: true },
      { name: 'width', displayName: 'Width', type: 'number', default: 1280 },
      { name: 'height', displayName: 'Height', type: 'number', default: 720 },
      { name: 'fullPage', displayName: 'Full Page', type: 'boolean', default: false },
    ],
  },
  {
    type: 'qrCodeNode',
    displayName: 'QR Code',
    category: 'utility',
    description: 'Generate QR codes from text or URLs',
    icon: 'QrCode',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'value', displayName: 'Value', type: 'expression', required: true },
      { name: 'size', displayName: 'Size (px)', type: 'number', default: 256 },
    ],
  },
  {
    type: 'htmlExtract',
    displayName: 'HTML Extract',
    category: 'utility',
    description: 'Extract data from HTML using CSS selectors',
    icon: 'FileSearch',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'html', displayName: 'HTML', type: 'expression', required: true },
      { name: 'selector', displayName: 'CSS Selector', type: 'string', required: true, placeholder: '.article-title' },
      { name: 'attribute', displayName: 'Attribute', type: 'string', default: 'text' },
    ],
  },
  {
    type: 'jsonConvert',
    displayName: 'JSON Convert',
    category: 'utility',
    description: 'Convert between JSON, XML, CSV, and YAML formats',
    icon: 'ArrowLeftRight',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'from', displayName: 'From', type: 'select', default: 'json', options: [{ name: 'JSON', value: 'json' }, { name: 'XML', value: 'xml' }, { name: 'CSV', value: 'csv' }, { name: 'YAML', value: 'yaml' }] },
      { name: 'to', displayName: 'To', type: 'select', default: 'xml', options: [{ name: 'JSON', value: 'json' }, { name: 'XML', value: 'xml' }, { name: 'CSV', value: 'csv' }, { name: 'YAML', value: 'yaml' }] },
      { name: 'value', displayName: 'Value', type: 'expression', required: true },
    ],
  },
  {
    type: 'compressionNode',
    displayName: 'Compression',
    category: 'utility',
    description: 'Compress or decompress files (zip/unzip)',
    icon: 'FolderArchive',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'operation', displayName: 'Operation', type: 'select', default: 'compress', options: [{ name: 'Compress', value: 'compress' }, { name: 'Decompress', value: 'decompress' }] },
      { name: 'format', displayName: 'Format', type: 'select', default: 'zip', options: [{ name: 'ZIP', value: 'zip' }, { name: 'GZIP', value: 'gzip' }, { name: 'TAR', value: 'tar' }] },
    ],
  },
  {
    type: 'imageResize',
    displayName: 'Image Resize',
    category: 'utility',
    description: 'Resize and compress images',
    icon: 'Image',
    color: 'bg-slate-500',
    inputs: [{ id: 'main', name: 'main', type: 'input' }],
    outputs: [{ id: 'main', name: 'main', type: 'output' }],
    properties: [
      { name: 'width', displayName: 'Width', type: 'number' },
      { name: 'height', displayName: 'Height', type: 'number' },
      { name: 'quality', displayName: 'Quality (1-100)', type: 'number', default: 80 },
      { name: 'format', displayName: 'Format', type: 'select', default: 'jpeg', options: [{ name: 'JPEG', value: 'jpeg' }, { name: 'PNG', value: 'png' }, { name: 'WebP', value: 'webp' }] },
    ],
  },
];

export function getNodeTypeDefinition(type: string): NodeTypeDefinition | undefined {
  return nodeRegistry.find(n => n.type === type);
}

export function getNodesByCategory(category: string): NodeTypeDefinition[] {
  return nodeRegistry.filter(n => n.category === category);
}

export function searchNodes(query: string): NodeTypeDefinition[] {
  const q = query.toLowerCase();
  return nodeRegistry.filter(n =>
    n.displayName.toLowerCase().includes(q) ||
    n.description.toLowerCase().includes(q) ||
    n.type.toLowerCase().includes(q)
  );
}
