// ─── Shared Trigger Catalog (51 Pre-built Triggers) ─────────────────────────
// This file is the single source of truth for all pre-built triggers.
// Both triggers-view.tsx and workflows-view.tsx import from here.

import {
  Zap, UserPlus, Clock3, ArrowRightLeft, CheckCircle, Edit3, Users,
  CalendarCheck, CalendarX, CalendarClock, CalendarPlus, AlertCircle,
  CircleCheck, UserCheck, XCircle, Briefcase, AlertTriangle,
  MessageCircle, MessageSquarePlus, MailCheck, Banknote, CreditCard,
  Receipt, FileCheck2, WifiOff, Globe, MousePointerClick, TimerReset,
  Tag, PlusCircle, Bell, Save, Bot, Timer,
  Trophy, Siren, UserCog, Hash, Send, FileX2,
  ClipboardList, UserRoundPlus, ShieldCheck,
  FileInput, Inbox, AlertOctagon, Unplug, Route,
} from 'lucide-react';

export interface PrebuiltTrigger {
  id: string;
  name: string;
  description: string;
  eventSource: string;
  eventLabel: string;
  category: string;
  categoryColor: string;
  icon: React.ElementType;
  defaultActions: { label: string; icon: React.ElementType; type: string; config: Record<string, any> }[];
  triggerType: string;
  triggerConfigJson: string;
  conditionsJson: string;
  popular?: boolean;
}

export const PREBUILT_TRIGGERS: PrebuiltTrigger[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // CRM Events — 8 triggers (Lead-focused)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'lead_created_assign',
    name: 'Lead Created → Assign Owner',
    description: 'Automatically assign new leads to available sales reps using round-robin distribution',
    eventSource: 'lead.created',
    eventLabel: 'Lead Created',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: UserPlus,
    defaultActions: [
      { label: 'Assign Round Robin', icon: UserCheck, type: 'assign_user', config: { assignTo: 'round_robin' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thank you for reaching out! A team member will contact you shortly.' } },
    ],
    triggerType: 'lead.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_assigned_notify',
    name: 'Lead Assigned → Notify Owner',
    description: 'When a lead is assigned to a sales rep, notify them immediately so they can follow up fast',
    eventSource: 'lead.assigned',
    eventLabel: 'Lead Assigned',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: UserCheck,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New lead assigned', message: 'You have been assigned a new lead. Follow up ASAP!' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hi! I\'ll be your point of contact. How can I help you today?' } },
    ],
    triggerType: 'lead.assigned',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_updated_log',
    name: 'Lead Updated → Log Activity',
    description: 'Automatically log a follow-up activity whenever a lead record is updated',
    eventSource: 'lead.updated',
    eventLabel: 'Lead Updated',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Edit3,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Lead updated', message: 'A lead record has been modified' } },
    ],
    triggerType: 'lead.updated',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'lead_status_changed',
    name: 'Lead Status Changed → Notify Team',
    description: 'Keep your team in the loop when a lead moves through the pipeline',
    eventSource: 'lead.status_changed',
    eventLabel: 'Lead Status Changed',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: ArrowRightLeft,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Lead status updated', message: 'A lead has moved to a new stage' } },
      { label: 'Move Pipeline', icon: ArrowRightLeft, type: 'move_pipeline', config: { stage: 'contacted' } },
    ],
    triggerType: 'lead.status_changed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'lead_won_celebrate',
    name: 'Lead Won → Celebrate & Onboard',
    description: 'When a lead is won, celebrate with the team and start the customer onboarding process',
    eventSource: 'lead.won',
    eventLabel: 'Lead Won',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Trophy,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'Onboarding for new customer' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'Lead won! 🎉', message: 'A lead has been won! Start onboarding.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'won' } },
    ],
    triggerType: 'lead.won',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_lost_recover',
    name: 'Lead Lost → Recovery Campaign',
    description: 'When a lead is lost, trigger a recovery campaign to win them back later',
    eventSource: 'lead.lost',
    eventLabel: 'Lead Lost',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Siren,
    defaultActions: [
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'lost-lead-recovery' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Lead lost', message: 'A lead was lost. Consider a recovery follow-up.' } },
    ],
    triggerType: 'lead.lost',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'lead_converted_celebrate',
    name: 'Lead Converted → Celebrate & Create Job',
    description: 'When a lead is converted, notify the team and automatically create a job',
    eventSource: 'lead.converted',
    eventLabel: 'Lead Converted',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: CheckCircle,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'New Job from converted lead' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'Lead converted!', message: 'A lead has been converted to a customer' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'converted' } },
    ],
    triggerType: 'lead.converted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_stuck_notify',
    name: 'Lead Stuck 2 Days → Notify Manager',
    description: 'When a lead hasn\'t been updated in 2 days, alert the manager for quick follow-up',
    eventSource: 'time.1h_after_lead',
    eventLabel: 'Time-Based',
    category: 'CRM Events',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Clock3,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Lead needs attention', message: 'Lead has not been updated in 2 days' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hi! Just checking in — do you still need help?' } },
    ],
    triggerType: 'time.1h_after_lead',
    triggerConfigJson: JSON.stringify({ delayMinutes: 2880 }),
    conditionsJson: '[]',
    popular: true,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Customer Events — 4 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'customer_created_welcome',
    name: 'Customer Created → Send Welcome',
    description: 'Send a warm welcome message via WhatsApp when a new customer is added to the system',
    eventSource: 'customer.created',
    eventLabel: 'Customer Created',
    category: 'Customer Events',
    categoryColor: 'bg-emerald-500/15 text-emerald-600 border-emerald-500/20',
    icon: Users,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Welcome! We\'re excited to have you. Let us know how we can help.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'new-customer' } },
    ],
    triggerType: 'customer.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'customer_updated_sync',
    name: 'Customer Updated → Sync & Notify',
    description: 'When customer details are updated, sync the changes across systems and notify the account manager',
    eventSource: 'customer.updated',
    eventLabel: 'Customer Updated',
    category: 'Customer Events',
    categoryColor: 'bg-emerald-500/15 text-emerald-600 border-emerald-500/20',
    icon: UserCog,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Customer updated', message: 'Customer details have been updated' } },
    ],
    triggerType: 'customer.updated',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'customer_tagged_segment',
    name: 'Customer Tagged → Add to Segment',
    description: 'When a customer is tagged, automatically add them to the relevant marketing segment',
    eventSource: 'customer.tagged',
    eventLabel: 'Customer Tagged',
    category: 'Customer Events',
    categoryColor: 'bg-emerald-500/15 text-emerald-600 border-emerald-500/20',
    icon: Hash,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Customer tagged', message: 'A customer has been tagged and may need segment assignment' } },
    ],
    triggerType: 'customer.tagged',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'customer_journey_notify',
    name: 'Customer Journey Stage Changed → Notify Account Manager',
    description: 'When a customer moves to a new journey stage, notify the account manager to adjust their approach',
    eventSource: 'customer.journey_stage_changed',
    eventLabel: 'Journey Stage Changed',
    category: 'Customer Events',
    categoryColor: 'bg-emerald-500/15 text-emerald-600 border-emerald-500/20',
    icon: Route,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Customer journey updated', message: 'A customer has moved to a new journey stage' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'journey-stage-changed' } },
    ],
    triggerType: 'customer.journey_stage_changed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Booking Events — 6 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'booking_created_confirm',
    name: 'Booking Created → Send Confirmation',
    description: 'Automatically send a booking confirmation to the customer when a new booking is created',
    eventSource: 'booking.created',
    eventLabel: 'Booking Created',
    category: 'Booking Events',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarPlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your booking has been received! We\'ll confirm it shortly.' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New booking', message: 'A new booking has been created' } },
    ],
    triggerType: 'booking.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_confirmed_job',
    name: 'Booking Confirmed → Create Job',
    description: 'Automatically create a job when a booking is confirmed, ready for dispatch',
    eventSource: 'booking.confirmed',
    eventLabel: 'Booking Confirmed',
    category: 'Booking Events',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarCheck,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'Job from booking confirmation' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your booking is confirmed! We\'ll send you updates.' } },
    ],
    triggerType: 'booking.confirmed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'booking_cancelled_alert',
    name: 'Booking Cancelled → Alert Manager',
    description: 'Get notified when a customer cancels so you can follow up and save the relationship',
    eventSource: 'booking.cancelled',
    eventLabel: 'Booking Cancelled',
    category: 'Booking Events',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarX,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Booking cancelled', message: 'A customer has cancelled their booking' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We\'re sorry to see you go. Is there anything we can do?' } },
    ],
    triggerType: 'booking.cancelled',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_completed_followup',
    name: 'Booking Completed → Request Review',
    description: 'When a booking is completed, send a follow-up message requesting a review',
    eventSource: 'booking.completed',
    eventLabel: 'Booking Completed',
    category: 'Booking Events',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CircleCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for visiting! We\'d love your feedback. Would you like to leave a review?' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'completed-booking' } },
    ],
    triggerType: 'booking.completed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_rescheduled_notify',
    name: 'Booking Rescheduled → Update Team',
    description: 'Keep your field team updated when customers reschedule their bookings',
    eventSource: 'booking.rescheduled',
    eventLabel: 'Booking Rescheduled',
    category: 'Booking Events',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarClock,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Booking rescheduled', message: 'A customer has rescheduled their booking' } },
    ],
    triggerType: 'booking.rescheduled',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_noshow_alert',
    name: 'Booking No-Show → Alert & Reschedule',
    description: 'When a customer doesn\'t show up for their booking, alert the team and offer to reschedule',
    eventSource: 'booking.cancelled',
    eventLabel: 'Booking No-Show',
    category: 'Booking Events',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: AlertCircle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Customer no-show', message: 'A customer did not show up for their booking' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We missed you today! Would you like to reschedule?' } },
    ],
    triggerType: 'booking.cancelled',
    triggerConfigJson: JSON.stringify({ reason: 'no_show' }),
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Job Events — 6 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'job_created_auto_assign',
    name: 'Job Created → Auto Assign',
    description: 'When a new job is created, automatically assign it to the nearest available employee',
    eventSource: 'job.created',
    eventLabel: 'Job Created',
    category: 'Job Events',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: Briefcase,
    defaultActions: [
      { label: 'Assign User', icon: UserPlus, type: 'assign_user', config: { assignTo: 'round_robin' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New job created', message: 'Auto-assignment in progress' } },
    ],
    triggerType: 'job.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'job_assigned_notify',
    name: 'Job Assigned → Notify Employee',
    description: 'Send a WhatsApp notification to the employee when they are assigned a new job',
    eventSource: 'job.assigned',
    eventLabel: 'Job Assigned',
    category: 'Job Events',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: UserCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'employee', template: 'You have a new job assigned. Check your schedule.' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New job assigned', message: 'Check your schedule for new assignment' } },
    ],
    triggerType: 'job.assigned',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'job_completed_review',
    name: 'Job Completed → Request Review',
    description: 'After completing a job, send a WhatsApp message requesting a Google review and tag for retention',
    eventSource: 'job.completed',
    eventLabel: 'Job Completed',
    category: 'Job Events',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: CircleCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for choosing us! Would you like to leave a review? https://g.page/review' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'retention-campaign' } },
    ],
    triggerType: 'job.completed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'job_cancelled_alert',
    name: 'Job Cancelled → Alert & Reschedule',
    description: 'Notify the manager and customer when a job is cancelled, offer rescheduling',
    eventSource: 'job.cancelled',
    eventLabel: 'Job Cancelled',
    category: 'Job Events',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: XCircle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Job cancelled', message: 'A job has been cancelled' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your job was cancelled. Would you like to reschedule?' } },
    ],
    triggerType: 'job.cancelled',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'job_overdue_alert',
    name: 'Job Overdue → Alert Manager',
    description: 'When a job passes its scheduled time without completion, alert the manager to take action',
    eventSource: 'job.started',
    eventLabel: 'Job Overdue',
    category: 'Job Events',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: AlertTriangle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Job overdue', message: 'A job has passed its scheduled time without completion' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We\'re running a bit behind schedule. We\'ll update you shortly!' } },
    ],
    triggerType: 'job.started',
    triggerConfigJson: JSON.stringify({ delayMinutes: 120 }),
    conditionsJson: '[]',
  },
  {
    id: 'time_3d_after_job',
    name: '3 Days After Job → Retention Campaign',
    description: '3 days after a job is completed, add the customer to a retention campaign',
    eventSource: 'time.3d_after_job',
    eventLabel: 'Time-Based',
    category: 'Job Events',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: TimerReset,
    defaultActions: [
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'retention-campaign' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hope everything is going well! Here\'s a special offer for you.' } },
    ],
    triggerType: 'time.3d_after_job',
    triggerConfigJson: JSON.stringify({ delayMinutes: 4320 }),
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Invoice Events — 8 triggers (Renamed from Finance)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'invoice_created_send',
    name: 'Invoice Created → Send to Customer',
    description: 'Automatically send the invoice to the customer via WhatsApp as soon as it is created',
    eventSource: 'invoice.created',
    eventLabel: 'Invoice Created',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Receipt,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your invoice is ready! Please review and complete payment at your convenience.' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Invoice sent', message: 'Invoice has been sent to the customer' } },
    ],
    triggerType: 'invoice.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'invoice_paid_thanks',
    name: 'Invoice Paid → Send Thank You',
    description: 'When a customer pays, send a thank you message and add to retention campaign',
    eventSource: 'invoice.paid',
    eventLabel: 'Invoice Paid',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Banknote,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Payment received! Thank you for your business.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'paid-customer' } },
    ],
    triggerType: 'invoice.paid',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'invoice_overdue_reminder',
    name: 'Invoice Overdue → Send Reminder',
    description: 'When an invoice is overdue, automatically send a payment reminder via WhatsApp',
    eventSource: 'invoice.overdue',
    eventLabel: 'Invoice Overdue',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: CreditCard,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your invoice is overdue. Please complete payment at your earliest convenience.' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Invoice overdue', message: 'An invoice is overdue — reminder sent' } },
    ],
    triggerType: 'invoice.overdue',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'quote_sent_followup',
    name: 'Quote Sent → Follow Up',
    description: 'When a quote is sent to a customer, schedule a follow-up reminder',
    eventSource: 'quote.sent',
    eventLabel: 'Quote Sent',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Send,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your quote has been sent! Let us know if you have any questions.' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'Quote sent', message: 'A quote has been sent to the customer' } },
    ],
    triggerType: 'quote.sent',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'quote_accepted_create',
    name: 'Quote Accepted → Create Job & Invoice',
    description: 'When a quote is accepted, automatically create a job and send the invoice to the customer',
    eventSource: 'quote.accepted',
    eventLabel: 'Quote Accepted',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: FileCheck2,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'Job from accepted quote' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Great choice! We\'re preparing your job and invoice.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'quote-accepted' } },
    ],
    triggerType: 'quote.accepted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'quote_rejected_recover',
    name: 'Quote Rejected → Recovery Follow-up',
    description: 'When a quote is rejected, follow up to understand why and try to recover the deal',
    eventSource: 'quote.rejected',
    eventLabel: 'Quote Rejected',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: FileX2,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We\'re sorry the quote didn\'t work out. Can we offer a different option?' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'quote-rejected' } },
    ],
    triggerType: 'quote.rejected',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'quote_3d_followup',
    name: 'Quote Not Accepted 3 Days → Follow Up',
    description: 'If a quote hasn\'t been accepted in 3 days, automatically follow up via WhatsApp',
    eventSource: 'time.1d_after_quote',
    eventLabel: 'Time-Based',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Clock3,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hi! Just following up on the quote we sent. Any questions?' } },
    ],
    triggerType: 'time.1d_after_quote',
    triggerConfigJson: JSON.stringify({ delayMinutes: 4320 }),
    conditionsJson: JSON.stringify([{ field: 'status', operator: 'not_equals', value: 'accepted' }]),
  },
  {
    id: 'time_7d_after_invoice',
    name: '7 Days After Invoice → Second Reminder',
    description: '7 days after an invoice becomes overdue, send a second reminder with urgency',
    eventSource: 'time.7d_after_invoice',
    eventLabel: 'Time-Based',
    category: 'Invoice Events',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Timer,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'This is a reminder that your payment is overdue. Please pay at your earliest convenience to avoid late fees.' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Second overdue reminder sent', message: '7-day overdue reminder sent to customer' } },
    ],
    triggerType: 'time.7d_after_invoice',
    triggerConfigJson: JSON.stringify({ delayMinutes: 10080 }),
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WhatsApp Events — 5 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'whatsapp_msg_lead',
    name: 'WhatsApp Message → Create Lead',
    description: 'When a new WhatsApp message comes in, automatically create a lead so nothing slips through',
    eventSource: 'whatsapp.message_received',
    eventLabel: 'WhatsApp Message',
    category: 'WhatsApp Events',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: MessageCircle,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Follow up with WhatsApp contact', assignTo: 'round_robin' } },
      { label: 'Auto Reply', icon: Bot, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for reaching out! We\'ll get back to you shortly.' } },
    ],
    triggerType: 'whatsapp.message_received',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'whatsapp_conversation_started',
    name: 'Conversation Started → Auto Welcome',
    description: 'Send an automatic welcome message when a new WhatsApp conversation begins',
    eventSource: 'whatsapp.conversation_started',
    eventLabel: 'Conversation Started',
    category: 'WhatsApp Events',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: MessageSquarePlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Welcome! How can we help you today?' } },
    ],
    triggerType: 'whatsapp.conversation_started',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'whatsapp_message_delivered',
    name: 'Message Delivered → Log & Update',
    description: 'When a WhatsApp message is delivered to the customer, update the record and log delivery',
    eventSource: 'whatsapp.message_delivered',
    eventLabel: 'Message Delivered',
    category: 'WhatsApp Events',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: CheckCircle,
    defaultActions: [
      { label: 'Update Record', icon: Save, type: 'update_record', config: { recordType: 'lead', field: 'whatsappStatus', value: 'delivered' } },
    ],
    triggerType: 'whatsapp.message_delivered',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'whatsapp_template_delivered',
    name: 'Template Delivered → Log Status',
    description: 'When a WhatsApp template message is delivered, log the delivery status for tracking',
    eventSource: 'whatsapp.template_delivered',
    eventLabel: 'Template Delivered',
    category: 'WhatsApp Events',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: MailCheck,
    defaultActions: [
      { label: 'Update Record', icon: Save, type: 'update_record', config: { recordType: 'lead', field: 'whatsappStatus', value: 'delivered' } },
    ],
    triggerType: 'whatsapp.template_delivered',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'whatsapp_template_failed',
    name: 'Template Failed → Retry & Alert',
    description: 'When a WhatsApp template fails to send, alert the team and attempt a retry',
    eventSource: 'whatsapp.template_failed',
    eventLabel: 'Template Failed',
    category: 'WhatsApp Events',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: AlertCircle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'WhatsApp template failed', message: 'A template message failed to send' } },
    ],
    triggerType: 'whatsapp.template_failed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Form Events — 7 triggers (EXPANDED)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'form_submitted_notify',
    name: 'Form Submitted → Notify & Create Lead',
    description: 'When a form is submitted on your website, create a lead and notify the sales team',
    eventSource: 'form.submitted',
    eventLabel: 'Form Submitted',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: MousePointerClick,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Follow up with form submission', assignTo: 'round_robin' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New form submission', message: 'A new form has been submitted on the website' } },
    ],
    triggerType: 'form.submitted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'survey_submitted_analyze',
    name: 'Survey Submitted → Analyze & Tag',
    description: 'When a survey is submitted, analyze the responses and tag the customer accordingly',
    eventSource: 'form.survey_submitted',
    eventLabel: 'Survey Submitted',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: ClipboardList,
    defaultActions: [
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'survey-respondent' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Survey submitted', message: 'A customer has submitted a survey response' } },
    ],
    triggerType: 'form.survey_submitted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'form_response_received',
    name: 'Form Response Received → Create Lead & Assign',
    description: 'When a form response is received, automatically create a lead and assign it to the sales team',
    eventSource: 'form.response_received',
    eventLabel: 'Form Response Received',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: FileInput,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Follow up with form response', assignTo: 'round_robin' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New form response', message: 'A new form response has been received' } },
    ],
    triggerType: 'form.response_received',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'form_abandoned_remind',
    name: 'Form Abandoned → Send Reminder',
    description: 'When a form is started but not completed, send a reminder to encourage completion',
    eventSource: 'form.abandoned',
    eventLabel: 'Form Abandoned',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: Inbox,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'It looks like you didn\'t finish filling out the form. Need any help?' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'form-abandoned' } },
    ],
    triggerType: 'form.abandoned',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'website_contact_form',
    name: 'Website Contact Form → Create Lead & Notify',
    description: 'When a contact form is submitted on your website, create a lead and alert the sales team',
    eventSource: 'website.contact_form',
    eventLabel: 'Contact Form',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: Globe,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Follow up with contact form', assignTo: 'round_robin' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New contact form', message: 'A new contact form has been submitted on the website' } },
    ],
    triggerType: 'website.contact_form',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'website_booking_form',
    name: 'Website Booking Form → Create Booking',
    description: 'When a booking form is submitted on your website, automatically create a booking',
    eventSource: 'website.booking_form',
    eventLabel: 'Booking Form',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: CalendarPlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for booking! We\'ll confirm your appointment shortly.' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New booking from website', message: 'A booking form has been submitted on the website' } },
    ],
    triggerType: 'website.booking_form',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'website_quote_request',
    name: 'Website Quote Request → Create Quote & Notify',
    description: 'When a quote request is submitted on your website, create a quote and notify the sales team',
    eventSource: 'website.quote_request',
    eventLabel: 'Quote Request',
    category: 'Form Events',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: Send,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Prepare quote for website request', assignTo: 'round_robin' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for your quote request! We\'ll get back to you with a quote soon.' } },
    ],
    triggerType: 'website.quote_request',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // System Events — 7 triggers (EXPANDED)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'user_registered_welcome',
    name: 'User Registered → Welcome & Setup',
    description: 'When a new user registers on the platform, send a welcome message and guide them through setup',
    eventSource: 'user.registered',
    eventLabel: 'User Registered',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: ShieldCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Welcome to our platform! Let us help you get started.' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New user registered', message: 'A new user has signed up on the platform' } },
    ],
    triggerType: 'user.registered',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'employee_created_onboard',
    name: 'Employee Created → Send Onboarding',
    description: 'When a new employee is added to the system, send them onboarding information and welcome message',
    eventSource: 'employee.created',
    eventLabel: 'Employee Created',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: UserRoundPlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'employee', template: 'Welcome to the team! Here\'s everything you need to get started.' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New employee added', message: 'A new employee has been added to the system' } },
    ],
    triggerType: 'employee.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'employee_available_dispatch',
    name: 'Employee Available → Auto Dispatch',
    description: 'When an employee becomes available, automatically assign pending jobs nearby',
    eventSource: 'employee.available',
    eventLabel: 'Employee Available',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: CircleCheck,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Employee available', message: 'An employee is now available for dispatch' } },
    ],
    triggerType: 'employee.available',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'employee_assigned_details',
    name: 'Employee Assigned → Send Job Details',
    description: 'When an employee is assigned to a job, send them full job details via WhatsApp',
    eventSource: 'employee.assigned',
    eventLabel: 'Employee Assigned',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: UserCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'employee', template: 'You\'ve been assigned a new job. Check your dashboard for full details.' } },
    ],
    triggerType: 'employee.assigned',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'employee_offline_alert',
    name: 'Employee Offline → Alert Manager',
    description: 'When an employee goes offline during working hours, notify the manager immediately',
    eventSource: 'employee.offline',
    eventLabel: 'Employee Offline',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: WifiOff,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Employee offline', message: 'An employee has gone offline during working hours' } },
    ],
    triggerType: 'employee.offline',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'system_error_alert',
    name: 'System Error → Alert Dev Team',
    description: 'When a system error occurs, immediately alert the development team for quick resolution',
    eventSource: 'system.error',
    eventLabel: 'System Error',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: AlertOctagon,
    defaultActions: [
      { label: 'Notify Dev Team', icon: Bell, type: 'send_notification', config: { title: 'System error detected', message: 'A system error has occurred and needs immediate attention' } },
    ],
    triggerType: 'system.error',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'system_api_call_failed',
    name: 'API Call Failed → Retry & Alert',
    description: 'When an API call fails, automatically retry and alert the team if it continues to fail',
    eventSource: 'system.api_call_failed',
    eventLabel: 'API Call Failed',
    category: 'System Events',
    categoryColor: 'bg-teal-500/15 text-teal-600 border-teal-500/20',
    icon: Unplug,
    defaultActions: [
      { label: 'Notify Dev Team', icon: Bell, type: 'send_notification', config: { title: 'API call failed', message: 'An API call has failed and may need manual intervention' } },
    ],
    triggerType: 'system.api_call_failed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
];

export const TRIGGER_CATEGORIES = [
  { id: 'all', label: 'All Triggers', color: 'text-emerald-500', icon: Zap },
  { id: 'CRM Events', label: 'CRM Events', color: 'text-blue-500', icon: UserPlus },
  { id: 'Customer Events', label: 'Customer Events', color: 'text-emerald-500', icon: Users },
  { id: 'Booking Events', label: 'Booking Events', color: 'text-purple-500', icon: CalendarCheck },
  { id: 'Job Events', label: 'Job Events', color: 'text-amber-500', icon: Briefcase },
  { id: 'Invoice Events', label: 'Invoice Events', color: 'text-rose-500', icon: CreditCard },
  { id: 'WhatsApp Events', label: 'WhatsApp Events', color: 'text-green-500', icon: MessageCircle },
  { id: 'Form Events', label: 'Form Events', color: 'text-orange-500', icon: MousePointerClick },
  { id: 'System Events', label: 'System Events', color: 'text-teal-500', icon: ShieldCheck },
];

// Action types available for workflow builder
export const ACTION_TYPES = [
  { value: 'send_whatsapp', label: 'Send WhatsApp', icon: MessageCircle, color: 'bg-green-500/15 text-green-600 border-green-500/20' },
  { value: 'send_notification', label: 'Send Notification', icon: Bell, color: 'bg-blue-500/15 text-blue-600 border-blue-500/20' },
  { value: 'send_email', label: 'Send Email', icon: MailCheck, color: 'bg-pink-500/15 text-pink-600 border-pink-500/20' },
  { value: 'send_sms', label: 'Send SMS', icon: MessageCircle, color: 'bg-sky-500/15 text-sky-600 border-sky-500/20' },
  { value: 'create_task', label: 'Create Task', icon: PlusCircle, color: 'bg-violet-500/15 text-violet-600 border-violet-500/20' },
  { value: 'create_job', label: 'Create Job', icon: Briefcase, color: 'bg-amber-500/15 text-amber-600 border-amber-500/20' },
  { value: 'assign_user', label: 'Assign User', icon: UserPlus, color: 'bg-cyan-500/15 text-cyan-600 border-cyan-500/20' },
  { value: 'add_tag', label: 'Add Tag', icon: Tag, color: 'bg-slate-500/15 text-slate-600 border-slate-500/20' },
  { value: 'remove_tag', label: 'Remove Tag', icon: XCircle, color: 'bg-gray-500/15 text-gray-600 border-gray-500/20' },
  { value: 'update_record', label: 'Update Record', icon: Save, color: 'bg-indigo-500/15 text-indigo-600 border-indigo-500/20' },
  { value: 'move_pipeline', label: 'Move Pipeline', icon: ArrowRightLeft, color: 'bg-teal-500/15 text-teal-600 border-teal-500/20' },
  { value: 'create_broadcast', label: 'Create Broadcast', icon: Send, color: 'bg-emerald-500/15 text-emerald-600 border-emerald-500/20' },
  { value: 'condition', label: 'If/Else Condition', icon: ArrowRightLeft, color: 'bg-orange-500/15 text-orange-600 border-orange-500/20' },
  { value: 'delay', label: 'Delay / Wait', icon: Clock3, color: 'bg-gray-500/15 text-gray-600 border-gray-500/20' },
];

import { Mail } from 'lucide-react';

export const TRIGGER_EVENTS = [
  // CRM Events
  { value: 'lead.created', label: 'Lead Created', category: 'CRM Events' },
  { value: 'lead.assigned', label: 'Lead Assigned', category: 'CRM Events' },
  { value: 'lead.updated', label: 'Lead Updated', category: 'CRM Events' },
  { value: 'lead.status_changed', label: 'Lead Status Changed', category: 'CRM Events' },
  { value: 'lead.won', label: 'Lead Won', category: 'CRM Events' },
  { value: 'lead.lost', label: 'Lead Lost', category: 'CRM Events' },
  { value: 'lead.converted', label: 'Lead Converted', category: 'CRM Events' },
  { value: 'time.1h_after_lead', label: 'Lead Stuck 2 Days', category: 'CRM Events' },
  // Customer Events
  { value: 'customer.created', label: 'Customer Created', category: 'Customer Events' },
  { value: 'customer.updated', label: 'Customer Updated', category: 'Customer Events' },
  { value: 'customer.tagged', label: 'Customer Tagged', category: 'Customer Events' },
  { value: 'customer.journey_stage_changed', label: 'Journey Stage Changed', category: 'Customer Events' },
  // Booking Events
  { value: 'booking.created', label: 'Booking Created', category: 'Booking Events' },
  { value: 'booking.confirmed', label: 'Booking Confirmed', category: 'Booking Events' },
  { value: 'booking.cancelled', label: 'Booking Cancelled', category: 'Booking Events' },
  { value: 'booking.completed', label: 'Booking Completed', category: 'Booking Events' },
  { value: 'booking.rescheduled', label: 'Booking Rescheduled', category: 'Booking Events' },
  // Job Events
  { value: 'job.created', label: 'Job Created', category: 'Job Events' },
  { value: 'job.assigned', label: 'Job Assigned', category: 'Job Events' },
  { value: 'job.started', label: 'Job Started', category: 'Job Events' },
  { value: 'job.completed', label: 'Job Completed', category: 'Job Events' },
  { value: 'job.cancelled', label: 'Job Cancelled', category: 'Job Events' },
  { value: 'time.3d_after_job', label: '3 Days After Job', category: 'Job Events' },
  // Invoice Events
  { value: 'invoice.created', label: 'Invoice Created', category: 'Invoice Events' },
  { value: 'invoice.paid', label: 'Invoice Paid', category: 'Invoice Events' },
  { value: 'invoice.overdue', label: 'Invoice Overdue', category: 'Invoice Events' },
  { value: 'quote.sent', label: 'Quote Sent', category: 'Invoice Events' },
  { value: 'quote.accepted', label: 'Quote Accepted', category: 'Invoice Events' },
  { value: 'quote.rejected', label: 'Quote Rejected', category: 'Invoice Events' },
  { value: 'time.1d_after_quote', label: 'Quote Not Accepted 3 Days', category: 'Invoice Events' },
  { value: 'time.7d_after_invoice', label: '7 Days After Invoice', category: 'Invoice Events' },
  // WhatsApp Events
  { value: 'whatsapp.message_received', label: 'Message Received', category: 'WhatsApp Events' },
  { value: 'whatsapp.message_delivered', label: 'Message Delivered', category: 'WhatsApp Events' },
  { value: 'whatsapp.conversation_started', label: 'Conversation Started', category: 'WhatsApp Events' },
  { value: 'whatsapp.template_delivered', label: 'Template Delivered', category: 'WhatsApp Events' },
  { value: 'whatsapp.template_failed', label: 'Template Failed', category: 'WhatsApp Events' },
  // Form Events
  { value: 'form.submitted', label: 'Form Submitted', category: 'Form Events' },
  { value: 'form.survey_submitted', label: 'Survey Submitted', category: 'Form Events' },
  { value: 'form.response_received', label: 'Form Response Received', category: 'Form Events' },
  { value: 'form.abandoned', label: 'Form Abandoned', category: 'Form Events' },
  { value: 'website.contact_form', label: 'Contact Form', category: 'Form Events' },
  { value: 'website.booking_form', label: 'Booking Form', category: 'Form Events' },
  { value: 'website.quote_request', label: 'Quote Request', category: 'Form Events' },
  // System Events
  { value: 'user.registered', label: 'User Registered', category: 'System Events' },
  { value: 'employee.created', label: 'Employee Created', category: 'System Events' },
  { value: 'employee.assigned', label: 'Employee Assigned', category: 'System Events' },
  { value: 'employee.available', label: 'Employee Available', category: 'System Events' },
  { value: 'employee.offline', label: 'Employee Offline', category: 'System Events' },
  { value: 'system.error', label: 'System Error', category: 'System Events' },
  { value: 'system.api_call_failed', label: 'API Call Failed', category: 'System Events' },
];
