// ─── Shared Trigger Catalog (33 Pre-built Triggers) ─────────────────────────
// This file is the single source of truth for all pre-built triggers.
// Both triggers-view.tsx and workflows-view.tsx import from here.

import {
  UserPlus, Clock3, ArrowRightLeft, CheckCircle, Edit3, Users,
  CalendarCheck, CalendarX, CalendarClock, CalendarPlus, AlertCircle,
  CircleCheck, UserCheck, XCircle, Briefcase, AlertTriangle,
  MessageCircle, MessageSquarePlus, MailCheck, Banknote, CreditCard,
  Receipt, FileCheck2, WifiOff, Globe, MousePointerClick, TimerReset,
  Tag, PlusCircle, Bell, Save, Bot, Timer,
} from 'lucide-react';

export interface PrebuiltTrigger {
  id: string;
  name: string;
  description: string;
  eventSource: string;
  eventLabel: string;
  category: string;
  categoryColor: string;
  icon: React.ElementType;
  defaultActions: { label: string; icon: React.ElementType; type: string; config: Record<string, any> }[];
  triggerType: string;
  triggerConfigJson: string;
  conditionsJson: string;
  popular?: boolean;
}

export const PREBUILT_TRIGGERS: PrebuiltTrigger[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // CRM — 6 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'lead_created_assign',
    name: 'Lead Created → Assign Owner',
    description: 'Automatically assign new leads to available sales reps using round-robin distribution',
    eventSource: 'lead.created',
    eventLabel: 'Lead Created',
    category: 'CRM',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: UserPlus,
    defaultActions: [
      { label: 'Assign Round Robin', icon: UserCheck, type: 'assign_user', config: { assignTo: 'round_robin' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thank you for reaching out! A team member will contact you shortly.' } },
    ],
    triggerType: 'lead.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_stuck_notify',
    name: 'Lead Stuck 2 Days → Notify Manager',
    description: 'When a lead hasn\'t been updated in 2 days, alert the manager for quick follow-up',
    eventSource: 'time.1h_after_lead',
    eventLabel: 'Time-Based',
    category: 'CRM',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Clock3,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Lead needs attention', message: 'Lead has not been updated in 2 days' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hi! Just checking in — do you still need help?' } },
    ],
    triggerType: 'time.1h_after_lead',
    triggerConfigJson: JSON.stringify({ delayMinutes: 2880 }),
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_status_changed',
    name: 'Lead Status Changed → Notify Team',
    description: 'Keep your team in the loop when a lead moves through the pipeline',
    eventSource: 'lead.status_changed',
    eventLabel: 'Lead Status Changed',
    category: 'CRM',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: ArrowRightLeft,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Lead status updated', message: 'A lead has moved to a new stage' } },
      { label: 'Move Pipeline', icon: ArrowRightLeft, type: 'move_pipeline', config: { stage: 'contacted' } },
    ],
    triggerType: 'lead.status_changed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'lead_converted_celebrate',
    name: 'Lead Converted → Celebrate & Create Job',
    description: 'When a lead is won, notify the team and automatically create a job',
    eventSource: 'lead.converted',
    eventLabel: 'Lead Converted',
    category: 'CRM',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: CheckCircle,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'New Job from converted lead' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'Lead converted!', message: 'A lead has been converted to a customer' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'converted' } },
    ],
    triggerType: 'lead.converted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'lead_updated_log',
    name: 'Lead Updated → Log Activity',
    description: 'Automatically log a follow-up activity whenever a lead record is updated',
    eventSource: 'lead.updated',
    eventLabel: 'Lead Updated',
    category: 'CRM',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Edit3,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Lead updated', message: 'A lead record has been modified' } },
    ],
    triggerType: 'lead.updated',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'customer_created_welcome',
    name: 'Customer Created → Send Welcome',
    description: 'Send a warm welcome message via WhatsApp when a new customer is added to the system',
    eventSource: 'customer.created',
    eventLabel: 'Customer Created',
    category: 'CRM',
    categoryColor: 'bg-blue-500/15 text-blue-600 border-blue-500/20',
    icon: Users,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Welcome! We\'re excited to have you. Let us know how we can help.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'new-customer' } },
    ],
    triggerType: 'customer.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Booking — 5 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'booking_confirmed_job',
    name: 'Booking Confirmed → Create Job',
    description: 'Automatically create a job when a booking is confirmed, ready for dispatch',
    eventSource: 'booking.confirmed',
    eventLabel: 'Booking Confirmed',
    category: 'Booking',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarCheck,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'Job from booking confirmation' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your booking is confirmed! We\'ll send you updates.' } },
    ],
    triggerType: 'booking.confirmed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'booking_cancelled_alert',
    name: 'Booking Cancelled → Alert Manager',
    description: 'Get notified when a customer cancels so you can follow up and save the relationship',
    eventSource: 'booking.cancelled',
    eventLabel: 'Booking Cancelled',
    category: 'Booking',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarX,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Booking cancelled', message: 'A customer has cancelled their booking' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We\'re sorry to see you go. Is there anything we can do?' } },
    ],
    triggerType: 'booking.cancelled',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_rescheduled_notify',
    name: 'Booking Rescheduled → Update Team',
    description: 'Keep your field team updated when customers reschedule their bookings',
    eventSource: 'booking.rescheduled',
    eventLabel: 'Booking Rescheduled',
    category: 'Booking',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarClock,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Booking rescheduled', message: 'A customer has rescheduled their booking' } },
    ],
    triggerType: 'booking.rescheduled',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_created_confirm',
    name: 'Booking Created → Send Confirmation',
    description: 'Automatically send a booking confirmation to the customer when a new booking is created',
    eventSource: 'booking.created',
    eventLabel: 'Booking Created',
    category: 'Booking',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: CalendarPlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your booking has been received! We\'ll confirm it shortly.' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New booking', message: 'A new booking has been created' } },
    ],
    triggerType: 'booking.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'booking_noshow_alert',
    name: 'Booking No-Show → Alert & Reschedule',
    description: 'When a customer doesn\'t show up for their booking, alert the team and offer to reschedule',
    eventSource: 'booking.cancelled',
    eventLabel: 'Booking No-Show',
    category: 'Booking',
    categoryColor: 'bg-purple-500/15 text-purple-600 border-purple-500/20',
    icon: AlertCircle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Customer no-show', message: 'A customer did not show up for their booking' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We missed you today! Would you like to reschedule?' } },
    ],
    triggerType: 'booking.cancelled',
    triggerConfigJson: JSON.stringify({ reason: 'no_show' }),
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Job — 5 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'job_completed_review',
    name: 'Job Completed → Request Review',
    description: 'After completing a job, send a WhatsApp message requesting a Google review and tag for retention',
    eventSource: 'job.completed',
    eventLabel: 'Job Completed',
    category: 'Job',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: CircleCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for choosing us! Would you like to leave a review? https://g.page/review' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'retention-campaign' } },
    ],
    triggerType: 'job.completed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'job_assigned_notify',
    name: 'Job Assigned → Notify Employee',
    description: 'Send a WhatsApp notification to the employee when they are assigned a new job',
    eventSource: 'job.assigned',
    eventLabel: 'Job Assigned',
    category: 'Job',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: UserCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'employee', template: 'You have a new job assigned. Check your schedule.' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New job assigned', message: 'Check your schedule for new assignment' } },
    ],
    triggerType: 'job.assigned',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'job_cancelled_alert',
    name: 'Job Cancelled → Alert & Reschedule',
    description: 'Notify the manager and customer when a job is cancelled, offer rescheduling',
    eventSource: 'job.cancelled',
    eventLabel: 'Job Cancelled',
    category: 'Job',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: XCircle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Job cancelled', message: 'A job has been cancelled' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your job was cancelled. Would you like to reschedule?' } },
    ],
    triggerType: 'job.cancelled',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'job_created_auto_assign',
    name: 'Job Created → Auto Assign',
    description: 'When a new job is created, automatically assign it to the nearest available employee',
    eventSource: 'job.created',
    eventLabel: 'Job Created',
    category: 'Job',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: Briefcase,
    defaultActions: [
      { label: 'Assign User', icon: UserPlus, type: 'assign_user', config: { assignTo: 'round_robin' } },
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'New job created', message: 'Auto-assignment in progress' } },
    ],
    triggerType: 'job.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'job_overdue_alert',
    name: 'Job Overdue → Alert Manager',
    description: 'When a job passes its scheduled time without completion, alert the manager to take action',
    eventSource: 'job.started',
    eventLabel: 'Job Overdue',
    category: 'Job',
    categoryColor: 'bg-amber-500/15 text-amber-600 border-amber-500/20',
    icon: AlertTriangle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Job overdue', message: 'A job has passed its scheduled time without completion' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'We\'re running a bit behind schedule. We\'ll update you shortly!' } },
    ],
    triggerType: 'job.started',
    triggerConfigJson: JSON.stringify({ delayMinutes: 120 }),
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WhatsApp — 4 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'whatsapp_msg_lead',
    name: 'WhatsApp Message → Create Lead',
    description: 'When a new WhatsApp message comes in, automatically create a lead so nothing slips through',
    eventSource: 'whatsapp.message_received',
    eventLabel: 'WhatsApp Message',
    category: 'WhatsApp',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: MessageCircle,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Follow up with WhatsApp contact', assignTo: 'round_robin' } },
      { label: 'Auto Reply', icon: Bot, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for reaching out! We\'ll get back to you shortly.' } },
    ],
    triggerType: 'whatsapp.message_received',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'whatsapp_conversation_started',
    name: 'Conversation Started → Auto Welcome',
    description: 'Send an automatic welcome message when a new WhatsApp conversation begins',
    eventSource: 'whatsapp.conversation_started',
    eventLabel: 'Conversation Started',
    category: 'WhatsApp',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: MessageSquarePlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Welcome! How can we help you today?' } },
    ],
    triggerType: 'whatsapp.conversation_started',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'whatsapp_template_delivered',
    name: 'Template Delivered → Log Status',
    description: 'When a WhatsApp template message is delivered, log the delivery status for tracking',
    eventSource: 'whatsapp.template_delivered',
    eventLabel: 'Template Delivered',
    category: 'WhatsApp',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: MailCheck,
    defaultActions: [
      { label: 'Update Record', icon: Save, type: 'update_record', config: { recordType: 'lead', field: 'whatsappStatus', value: 'delivered' } },
    ],
    triggerType: 'whatsapp.template_delivered',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'whatsapp_template_failed',
    name: 'Template Failed → Retry & Alert',
    description: 'When a WhatsApp template fails to send, alert the team and attempt a retry',
    eventSource: 'whatsapp.template_failed',
    eventLabel: 'Template Failed',
    category: 'WhatsApp',
    categoryColor: 'bg-green-500/15 text-green-600 border-green-500/20',
    icon: AlertCircle,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'WhatsApp template failed', message: 'A template message failed to send' } },
    ],
    triggerType: 'whatsapp.template_failed',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Finance — 5 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'invoice_overdue_reminder',
    name: 'Payment Failed → Send Reminder',
    description: 'When an invoice is overdue, automatically send a payment reminder via WhatsApp',
    eventSource: 'invoice.overdue',
    eventLabel: 'Invoice Overdue',
    category: 'Finance',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: CreditCard,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your invoice is overdue. Please complete payment at your earliest convenience.' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Invoice overdue', message: 'An invoice is overdue — reminder sent' } },
    ],
    triggerType: 'invoice.overdue',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'invoice_paid_thanks',
    name: 'Invoice Paid → Send Thank You',
    description: 'When a customer pays, send a thank you message and add to retention campaign',
    eventSource: 'invoice.paid',
    eventLabel: 'Invoice Paid',
    category: 'Finance',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Banknote,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Payment received! Thank you for your business.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'paid-customer' } },
    ],
    triggerType: 'invoice.paid',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'quote_sent_followup',
    name: 'Quote Sent → 3-Day Follow Up',
    description: 'If a quote hasn\'t been accepted in 3 days, automatically follow up via WhatsApp',
    eventSource: 'time.1d_after_quote',
    eventLabel: 'Time-Based',
    category: 'Finance',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Clock3,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hi! Just following up on the quote we sent. Any questions?' } },
    ],
    triggerType: 'time.1d_after_quote',
    triggerConfigJson: JSON.stringify({ delayMinutes: 4320 }),
    conditionsJson: JSON.stringify([{ field: 'status', operator: 'not_equals', value: 'accepted' }]),
  },
  {
    id: 'quote_accepted_create',
    name: 'Quote Accepted → Create Job & Invoice',
    description: 'When a quote is accepted, automatically create a job and send the invoice to the customer',
    eventSource: 'quote.accepted',
    eventLabel: 'Quote Accepted',
    category: 'Finance',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: FileCheck2,
    defaultActions: [
      { label: 'Create Job', icon: Briefcase, type: 'create_job', config: { title: 'Job from accepted quote' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Great choice! We\'re preparing your job and invoice.' } },
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'quote-accepted' } },
    ],
    triggerType: 'quote.accepted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'invoice_created_send',
    name: 'Invoice Created → Send to Customer',
    description: 'Automatically send the invoice to the customer via WhatsApp as soon as it is created',
    eventSource: 'invoice.created',
    eventLabel: 'Invoice Created',
    category: 'Finance',
    categoryColor: 'bg-rose-500/15 text-rose-600 border-rose-500/20',
    icon: Receipt,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your invoice is ready! Please review and complete payment at your convenience.' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Invoice sent', message: 'Invoice has been sent to the customer' } },
    ],
    triggerType: 'invoice.created',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Employee — 3 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'employee_available_dispatch',
    name: 'Employee Available → Auto Dispatch',
    description: 'When an employee becomes available, automatically assign pending jobs nearby',
    eventSource: 'employee.available',
    eventLabel: 'Employee Available',
    category: 'Employee',
    categoryColor: 'bg-cyan-500/15 text-cyan-600 border-cyan-500/20',
    icon: CircleCheck,
    defaultActions: [
      { label: 'Send Notification', icon: Bell, type: 'send_notification', config: { title: 'Employee available', message: 'An employee is now available for dispatch' } },
    ],
    triggerType: 'employee.available',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'employee_assigned_details',
    name: 'Employee Assigned → Send Job Details',
    description: 'When an employee is assigned to a job, send them full job details via WhatsApp',
    eventSource: 'employee.assigned',
    eventLabel: 'Employee Assigned',
    category: 'Employee',
    categoryColor: 'bg-cyan-500/15 text-cyan-600 border-cyan-500/20',
    icon: UserCheck,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'employee', template: 'You\'ve been assigned a new job. Check your dashboard for full details.' } },
    ],
    triggerType: 'employee.assigned',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'employee_offline_alert',
    name: 'Employee Offline → Alert Manager',
    description: 'When an employee goes offline during working hours, notify the manager immediately',
    eventSource: 'employee.offline',
    eventLabel: 'Employee Offline',
    category: 'Employee',
    categoryColor: 'bg-cyan-500/15 text-cyan-600 border-cyan-500/20',
    icon: WifiOff,
    defaultActions: [
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Employee offline', message: 'An employee has gone offline during working hours' } },
    ],
    triggerType: 'employee.offline',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Website — 3 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'form_submitted_notify',
    name: 'Form Submitted → Notify & Create Lead',
    description: 'When a form is submitted on your website, create a lead and notify the sales team',
    eventSource: 'form.submitted',
    eventLabel: 'Form Submitted',
    category: 'Website',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: MousePointerClick,
    defaultActions: [
      { label: 'Create Task', icon: PlusCircle, type: 'create_task', config: { title: 'Follow up with form submission', assignTo: 'round_robin' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New form submission', message: 'A new form has been submitted on the website' } },
    ],
    triggerType: 'form.submitted',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },
  {
    id: 'website_contact_lead',
    name: 'Contact Form → Create Lead',
    description: 'Automatically create a lead when someone submits the contact form on your website',
    eventSource: 'website.contact_form',
    eventLabel: 'Contact Form',
    category: 'Website',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: Globe,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Thanks for contacting us! We\'ll be in touch soon.' } },
      { label: 'Assign Owner', icon: UserPlus, type: 'assign_user', config: { assignTo: 'round_robin' } },
    ],
    triggerType: 'website.contact_form',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
    popular: true,
  },
  {
    id: 'website_booking_form',
    name: 'Booking Form → Create Booking',
    description: 'When a booking form is submitted from your website, create a booking and notify the team',
    eventSource: 'website.booking_form',
    eventLabel: 'Booking Form',
    category: 'Website',
    categoryColor: 'bg-orange-500/15 text-orange-600 border-orange-500/20',
    icon: CalendarPlus,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Your booking request has been received! We\'ll confirm shortly.' } },
      { label: 'Notify Team', icon: Bell, type: 'send_notification', config: { title: 'New booking request', message: 'A booking form was submitted from the website' } },
    ],
    triggerType: 'website.booking_form',
    triggerConfigJson: '{}',
    conditionsJson: '[]',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Time-Based — 2 triggers
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'time_3d_after_job',
    name: '3 Days After Job → Retention Campaign',
    description: '3 days after a job is completed, add the customer to a retention campaign',
    eventSource: 'time.3d_after_job',
    eventLabel: 'Time-Based',
    category: 'Time-Based',
    categoryColor: 'bg-slate-500/15 text-slate-600 border-slate-500/20',
    icon: TimerReset,
    defaultActions: [
      { label: 'Add Tag', icon: Tag, type: 'add_tag', config: { tag: 'retention-campaign' } },
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'Hope everything is going well! Here\'s a special offer for you.' } },
    ],
    triggerType: 'time.3d_after_job',
    triggerConfigJson: JSON.stringify({ delayMinutes: 4320 }),
    conditionsJson: '[]',
  },
  {
    id: 'time_7d_after_invoice',
    name: '7 Days After Invoice → Second Reminder',
    description: '7 days after an invoice becomes overdue, send a second reminder with urgency',
    eventSource: 'time.7d_after_invoice',
    eventLabel: 'Time-Based',
    category: 'Time-Based',
    categoryColor: 'bg-slate-500/15 text-slate-600 border-slate-500/20',
    icon: Timer,
    defaultActions: [
      { label: 'Send WhatsApp', icon: MessageCircle, type: 'send_whatsapp', config: { recipient: 'customer', template: 'This is a reminder that your payment is overdue. Please pay at your earliest convenience to avoid late fees.' } },
      { label: 'Notify Manager', icon: Bell, type: 'send_notification', config: { title: 'Second overdue reminder sent', message: '7-day overdue reminder sent to customer' } },
    ],
    triggerType: 'time.7d_after_invoice',
    triggerConfigJson: JSON.stringify({ delayMinutes: 10080 }),
    conditionsJson: '[]',
  },
];

export const TRIGGER_CATEGORIES = [
  { id: 'all', label: 'All Triggers', color: 'text-emerald-500' },
  { id: 'CRM', label: 'CRM', color: 'text-blue-500' },
  { id: 'Booking', label: 'Booking', color: 'text-purple-500' },
  { id: 'Job', label: 'Job', color: 'text-amber-500' },
  { id: 'Employee', label: 'Employee', color: 'text-cyan-500' },
  { id: 'WhatsApp', label: 'WhatsApp', color: 'text-green-500' },
  { id: 'Finance', label: 'Finance', color: 'text-rose-500' },
  { id: 'Website', label: 'Website', color: 'text-orange-500' },
  { id: 'Time-Based', label: 'Time-Based', color: 'text-slate-500' },
];

// Action types available for workflow builder
export const ACTION_TYPES = [
  { value: 'send_whatsapp', label: 'Send WhatsApp', icon: MessageCircle, color: 'bg-green-500/15 text-green-600 border-green-500/20' },
  { value: 'send_notification', label: 'Send Notification', icon: Bell, color: 'bg-blue-500/15 text-blue-600 border-blue-500/20' },
  { value: 'send_email', label: 'Send Email', icon: MailCheck, color: 'bg-pink-500/15 text-pink-600 border-pink-500/20' },
  { value: 'create_task', label: 'Create Task', icon: PlusCircle, color: 'bg-violet-500/15 text-violet-600 border-violet-500/20' },
  { value: 'create_job', label: 'Create Job', icon: Briefcase, color: 'bg-amber-500/15 text-amber-600 border-amber-500/20' },
  { value: 'assign_user', label: 'Assign User', icon: UserPlus, color: 'bg-cyan-500/15 text-cyan-600 border-cyan-500/20' },
  { value: 'add_tag', label: 'Add Tag', icon: Tag, color: 'bg-slate-500/15 text-slate-600 border-slate-500/20' },
  { value: 'update_record', label: 'Update Record', icon: Save, color: 'bg-indigo-500/15 text-indigo-600 border-indigo-500/20' },
  { value: 'move_pipeline', label: 'Move Pipeline', icon: ArrowRightLeft, color: 'bg-teal-500/15 text-teal-600 border-teal-500/20' },
  { value: 'condition', label: 'If/Else Condition', icon: ArrowRightLeft, color: 'bg-orange-500/15 text-orange-600 border-orange-500/20' },
  { value: 'delay', label: 'Delay / Wait', icon: Clock3, color: 'bg-gray-500/15 text-gray-600 border-gray-500/20' },
];

import { Mail } from 'lucide-react';

export const TRIGGER_EVENTS = [
  { value: 'lead.created', label: 'Lead Created', category: 'CRM' },
  { value: 'lead.updated', label: 'Lead Updated', category: 'CRM' },
  { value: 'lead.status_changed', label: 'Lead Status Changed', category: 'CRM' },
  { value: 'lead.converted', label: 'Lead Converted', category: 'CRM' },
  { value: 'customer.created', label: 'Customer Created', category: 'CRM' },
  { value: 'booking.created', label: 'Booking Created', category: 'Booking' },
  { value: 'booking.confirmed', label: 'Booking Confirmed', category: 'Booking' },
  { value: 'booking.cancelled', label: 'Booking Cancelled', category: 'Booking' },
  { value: 'booking.rescheduled', label: 'Booking Rescheduled', category: 'Booking' },
  { value: 'job.created', label: 'Job Created', category: 'Job' },
  { value: 'job.assigned', label: 'Job Assigned', category: 'Job' },
  { value: 'job.started', label: 'Job Started', category: 'Job' },
  { value: 'job.completed', label: 'Job Completed', category: 'Job' },
  { value: 'job.cancelled', label: 'Job Cancelled', category: 'Job' },
  { value: 'employee.assigned', label: 'Employee Assigned', category: 'Employee' },
  { value: 'employee.available', label: 'Employee Available', category: 'Employee' },
  { value: 'employee.offline', label: 'Employee Offline', category: 'Employee' },
  { value: 'whatsapp.message_received', label: 'WhatsApp Message', category: 'WhatsApp' },
  { value: 'whatsapp.conversation_started', label: 'Conversation Started', category: 'WhatsApp' },
  { value: 'form.submitted', label: 'Form Submitted', category: 'Website' },
  { value: 'website.contact_form', label: 'Contact Form', category: 'Website' },
  { value: 'website.booking_form', label: 'Booking Form', category: 'Website' },
  { value: 'invoice.created', label: 'Invoice Created', category: 'Finance' },
  { value: 'invoice.paid', label: 'Invoice Paid', category: 'Finance' },
  { value: 'invoice.overdue', label: 'Invoice Overdue', category: 'Finance' },
  { value: 'quote.accepted', label: 'Quote Accepted', category: 'Finance' },
  { value: 'time.1h_after_lead', label: '1H After Lead', category: 'Time-Based' },
  { value: 'time.3d_after_job', label: '3D After Job', category: 'Time-Based' },
  { value: 'time.7d_after_invoice', label: '7D After Invoice', category: 'Time-Based' },
];
