'use client';

import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import {
  Globe,
  Camera,
  FileText,
  Sparkles,
  Loader2,
  CheckCircle2,
  Upload,
  ArrowRight,
} from 'lucide-react';
import { toast } from 'sonner';
import { FormSchema } from '@/lib/forms/form-schema-types';

interface FormImporterDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onImportSuccess: (schema: FormSchema, formName?: string) => void;
}

export function FormImporterDialog({
  open,
  onOpenChange,
  onImportSuccess,
}: FormImporterDialogProps) {
  const [activeTab, setActiveTab] = useState<'url' | 'photo' | 'text'>('url');
  const [urlInput, setUrlInput] = useState('');
  const [textInput, setTextInput] = useState('');
  const [fileBase64, setFileBase64] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      setFileBase64(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleImport = async () => {
    setLoading(true);
    try {
      let payload: any = { mode: activeTab };

      if (activeTab === 'url') {
        if (!urlInput.trim()) {
          toast.error('Please enter a website or form URL');
          setLoading(false);
          return;
        }
        payload.url = urlInput.trim();
      } else if (activeTab === 'photo') {
        if (!fileBase64) {
          toast.error('Please select an image or PDF of the form');
          setLoading(false);
          return;
        }
        payload.imageUrl = fileBase64;
        payload.content = fileName || 'Uploaded Document';
      } else {
        if (!textInput.trim()) {
          toast.error('Please enter form questions or text description');
          setLoading(false);
          return;
        }
        payload.content = textInput.trim();
      }

      const res = await fetch('/api/forms/ai/ocr-import', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      const data = await res.json();
      if (res.ok && data.schema) {
        toast.success('Form successfully imported & generated by AI!');
        onImportSuccess(data.schema, data.schema.steps?.[0]?.title || 'Imported Form');
        onOpenChange(false);
      } else {
        toast.error(data.error || 'Failed to import form');
      }
    } catch {
      toast.error('Network error during form import');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[540px] p-0 overflow-hidden rounded-2xl">
        {/* Header */}
        <div className="p-5 bg-gradient-to-r from-emerald-600 to-teal-700 text-white">
          <div className="flex items-center gap-2 text-emerald-100 text-[11px] font-bold uppercase tracking-wider">
            <Sparkles className="size-3.5" /> AI Universal Form Importer
          </div>
          <DialogTitle className="text-lg font-black text-white mt-1">
            Import Any Form in Seconds
          </DialogTitle>
          <DialogDescription className="text-xs text-emerald-100/90 mt-0.5">
            Convert existing web forms, paper PDFs, or raw questions into interactive digital forms.
          </DialogDescription>
        </div>

        <div className="p-5 space-y-4">
          <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as any)}>
            <TabsList className="grid grid-cols-3 bg-muted/60 p-1 rounded-xl">
              <TabsTrigger value="url" className="text-xs gap-1.5 rounded-lg">
                <Globe className="size-3.5 text-emerald-600" /> From URL
              </TabsTrigger>
              <TabsTrigger value="photo" className="text-xs gap-1.5 rounded-lg">
                <Camera className="size-3.5 text-emerald-600" /> Paper / PDF
              </TabsTrigger>
              <TabsTrigger value="text" className="text-xs gap-1.5 rounded-lg">
                <FileText className="size-3.5 text-emerald-600" /> Paste Text
              </TabsTrigger>
            </TabsList>

            {/* TAB 1: URL */}
            <TabsContent value="url" className="space-y-3 pt-3">
              <div className="space-y-1.5">
                <Label className="text-xs font-semibold">Webpage or Form URL</Label>
                <Input
                  value={urlInput}
                  onChange={(e) => setUrlInput(e.target.value)}
                  placeholder="https://example.com/contact-us or Google/Typeform URL"
                  className="text-xs"
                  disabled={loading}
                />
                <p className="text-[11px] text-muted-foreground">
                  AI will scrape all form fields, input types, and branding from the live website.
                </p>
              </div>
            </TabsContent>

            {/* TAB 2: Paper / PDF OCR */}
            <TabsContent value="photo" className="space-y-3 pt-3">
              <div className="space-y-1.5">
                <Label className="text-xs font-semibold">Upload Photo of Paper Form or PDF</Label>
                <div className="border-2 border-dashed border-border/80 hover:border-emerald-500 rounded-xl p-5 text-center cursor-pointer bg-muted/20 relative">
                  <input
                    type="file"
                    accept="image/*,application/pdf"
                    onChange={handleFileUpload}
                    className="absolute inset-0 opacity-0 cursor-pointer"
                    disabled={loading}
                  />
                  <div className="flex flex-col items-center justify-center gap-1.5">
                    <div className="size-9 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-600 flex items-center justify-center">
                      <Upload className="size-4" />
                    </div>
                    <p className="text-xs font-semibold text-foreground">
                      {fileName ? fileName : 'Choose photo or PDF scan'}
                    </p>
                    <p className="text-[10px] text-muted-foreground">
                      Vision OCR extracts all checkboxes, question tables, and signatures.
                    </p>
                  </div>
                </div>
              </div>
            </TabsContent>

            {/* TAB 3: Raw Text */}
            <TabsContent value="text" className="space-y-3 pt-3">
              <div className="space-y-1.5">
                <Label className="text-xs font-semibold">Paste Form Questions / Job Sheet Notes</Label>
                <Textarea
                  value={textInput}
                  onChange={(e) => setTextInput(e.target.value)}
                  placeholder="1. Customer Name & Contact&#10;2. Vehicle Model & Year&#10;3. Description of Damage with photos&#10;4. Required Inspection Checklists..."
                  rows={4}
                  className="text-xs resize-none"
                  disabled={loading}
                />
              </div>
            </TabsContent>
          </Tabs>

          {/* Action Button */}
          <div className="flex justify-end gap-2 pt-2 border-t border-border/60">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onOpenChange(false)}
              disabled={loading}
              className="text-xs"
            >
              Cancel
            </Button>
            <Button
              type="button"
              size="sm"
              onClick={handleImport}
              disabled={loading}
              className="text-xs bg-emerald-600 hover:bg-emerald-700 text-white gap-1.5 shadow-sm"
            >
              {loading ? (
                <>
                  <Loader2 className="size-3.5 animate-spin" /> Analyzing with AI...
                </>
              ) : (
                <>
                  <Sparkles className="size-3.5" /> Convert into Form
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
