import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getAuthUser } from '@/lib/auth';
import { requirePlanFeature } from '@/lib/plan-gate';

// ─── GET /api/recurring-jobs/[id]/jobs ──────────────────────────────────────
//
// Returns ALL jobs generated by a recurring schedule, paginated.
//
// The GET /api/recurring-jobs/[id] endpoint only returns the last 10 generated
// jobs (for the header + a quick preview). This dedicated endpoint backs the
// "Generated Jobs" tab on the detail page, which needs the full history with
// status filtering + pagination.
//
// Query params:
//   page     — 1-indexed page number (default 1)
//   limit    — page size, capped at 100 (default 20)
//   status   — optional status filter. Accepts either:
//                • a single exact status string ('pending', 'completed', …)
//                • the special value 'upcoming' → expands to
//                  status IN (pending, assigned, accepted, in_progress),
//                  matching the Generated Jobs tab's filter dropdown.
//
// Response shape:
//   {
//     jobs: Array<{ id, jobNumber, title, status, scheduledAt, completedAt,
//                   cancelledAt, createdAt, customerId, customerName,
//                   assigneeId, assigneeName, recurringScheduleId,
//                   assignee: { id, name } | null }>,
//     total: number,         // total matching rows (for pagination UI)
//     page: number,
//     totalPages: number,
//   }
//
// Auth: must be the schedule's owning tenant. Plan-gated to `recurring_jobs`.
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await getAuthUser();
    if (!user || !user.tenantId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const gate = await requirePlanFeature('recurring_jobs');
    if (!gate.ok) {
      return NextResponse.json({ error: gate.reason }, { status: gate.status });
    }

    const { id } = await params;

    // Verify schedule exists + belongs to this tenant.
    const schedule = await db.recurringJobSchedule.findUnique({
      where: { id },
      select: { id: true, tenantId: true, title: true },
    });
    if (!schedule) {
      return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
    }
    if (schedule.tenantId !== user.tenantId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    // Parse + clamp pagination params.
    const { searchParams } = new URL(request.url);
    const page = Math.max(1, parseInt(searchParams.get('page') || '1', 10) || 1);
    const limitRaw = parseInt(searchParams.get('limit') || '20', 10) || 20;
    const limit = Math.min(Math.max(1, limitRaw), 100);
    const skip = (page - 1) * limit;

    // Optional status filter. Two forms are accepted:
    //   1. The literal token 'upcoming' → expands to status IN
    //      (pending, assigned, accepted, in_progress) — matches the
    //      Generated Jobs tab's "Upcoming" filter option.
    //   2. Any other string → treated as an exact status match.
    const status = searchParams.get('status')?.trim() || null;
    const statusFilter: Record<string, unknown> | null = status
      ? status === 'upcoming'
        ? { status: { in: ['pending', 'assigned', 'accepted', 'in_progress'] } }
        : { status }
      : null;

    // The Job model lives under `workspaceId` (NOT `tenantId` directly — see
    // prisma/schema.prisma). To stay tenant-scoped, we restrict to workspaces
    // owned by this tenant. We also pin recurringScheduleId = id, which is the
    // primary scoping for this endpoint — the workspace filter is a belt-and-
    // braces guard against any job whose recurringScheduleId was somehow set
    // from another tenant (it shouldn't happen since schedules are tenant-
    // scoped, but defense in depth).
    const tenantWorkspaces = await db.workspace.findMany({
      where: { tenantId: user.tenantId },
      select: { id: true },
    });
    const workspaceIds = tenantWorkspaces.map((w) => w.id);

    const where: Record<string, unknown> = {
      recurringScheduleId: id,
      ...(statusFilter ?? {}),
      ...(workspaceIds.length > 0 ? { workspaceId: { in: workspaceIds } } : {}),
    };

    // Parallel: page of jobs + total count for the pagination envelope.
    const [jobs, total] = await Promise.all([
      db.job.findMany({
        where,
        orderBy: { scheduledAt: 'desc' },
        skip,
        take: limit,
        select: {
          id: true,
          jobNumber: true,
          title: true,
          status: true,
          scheduledAt: true,
          completedAt: true,
          cancelledAt: true,
          createdAt: true,
          customerId: true,
          customerName: true,
          assigneeId: true,
          assigneeName: true,
          recurringScheduleId: true,
          // Include the assignee relation for the cases where assigneeName
          // wasn't denormalized at creation time (older rows).
          assignee: { select: { id: true, name: true } },
        },
      }),
      db.job.count({ where }),
    ]);

    return NextResponse.json({
      jobs,
      total,
      page,
      totalPages: Math.max(1, Math.ceil(total / limit)),
    });
  } catch (error) {
    console.error('Get recurring-jobs/[id]/jobs error:', error);
    return NextResponse.json({ error: 'Failed to fetch generated jobs' }, { status: 500 });
  }
}
