-- ───────────────────────────────────────────────────────────────────────────
-- TEST — 5 records (Houston, TX plumbers)
-- Generated: 2026-08-06T05:58:12.964Z
-- Records: 5
-- Source: Google Places API (Text Search) + website scraping
-- Idempotent: ON CONFLICT ("googlePlaceId") DO NOTHING
-- Run in Supabase SQL Editor (paste entire file, click Run)
-- ───────────────────────────────────────────────────────────────────────────

BEGIN;
INSERT INTO "Tenant" ("id", "name", "slug", "industry", "phone", "email", "website", "address", "country", "currency", "city", "state", "postalCode", "latitude", "longitude", "serviceRadiusKm", "plan", "marketplaceOptIn", "publicProfileEnabled", "listingTier", "claimed", "rating", "reviewCount", "tagline", "description", "seoTitle", "seoDescription", "businessCategoriesJson", "settingsJson", "employeesCount", "googlePlaceId", "createdAt", "updatedAt")
  VALUES ('cmsh3u4v5gjwkwii3p9vy', 'Cooper Plumbing | Houston Plumber', 'cooper-plumbing-houston-plumber-7c73d1', 'plumbing', '+1 832-441-9683', NULL, 'https://www.cooperplumbinghouston.com/?utm_source=google&utm_medium=organic&utm_campaign=gmb-listing', '10825 Barely Ln, Houston, TX 77070', 'US', 'USD', 'Houston', 'TX', '77070', 29.9410686, -95.5828155, 25, 'business', true, true, 'free', false, 4.9, 557, 'Cooper Plumbing | Houston Plumber — plumbing in Houston', '<p>From toilet repairs to whole house re-pipes, our plumbing service experts in Houston can help diagnose and provide you with the best options to fix your plumbing issues.</p>
<p>If you have a high water bill, mysterious water stains, or standing water, it could be a sign of a leak. Our technicians are fully certified to diagnose and perform an effective leak detection .</p>
<p>Whether you are in need of a horizontal repipe or whole house repipe, our team of Houston Repipe Specialists provide turn-key repiping services in the most efficient way.</p>
<p>When you need a professional sewer line replacement or repair? Our licensed plumbers assure you the drain reroute or repair will be done by a professional dig crew and certified licensed plumber drain specialist. Our experienced drain crew will provide a turn-key quality job with the best quality and materials from start to finish.</p>
<p>Hear from one of our REAL customers! Pam has used Cooper Plumbing for years for all of her plumbing needs. Hear her personalized account and what to expect when using Cooper Plumbing.</p>', 'Cooper Plumbing | Houston Plumber — plumbing in Houston | Fieseros', 'Book Cooper Plumbing | Houston Plumber for plumbing services in Houston. Professional, reliable, and trusted by local customers. Rated 4.9★ (557 reviews).', '["plumbing"]', '{"emailSource":"none","emailVerified":false,"descriptionSource":"website_scrape","seededAt":"2026-08-06T05:58:05.345Z","seedSource":"google-places"}', 6, 'ChIJA_eUDQLRQIYR8yJYKP1k_nw', '2026-08-06T05:58:12.964Z', '2026-08-06T05:58:12.964Z')
  ON CONFLICT ("googlePlaceId") DO NOTHING;

INSERT INTO "Tenant" ("id", "name", "slug", "industry", "phone", "email", "website", "address", "country", "currency", "city", "state", "postalCode", "latitude", "longitude", "serviceRadiusKm", "plan", "marketplaceOptIn", "publicProfileEnabled", "listingTier", "claimed", "rating", "reviewCount", "tagline", "description", "seoTitle", "seoDescription", "businessCategoriesJson", "settingsJson", "employeesCount", "googlePlaceId", "createdAt", "updatedAt")
  VALUES ('cmsh3u7kr7iyb6a6oyn9y', 'Texas Quality Plumbing', 'texas-quality-plumbing-314c45', 'plumbing', '+1 713-385-0349', NULL, 'https://www.texasqualityplumbing.com/?utm_source=google&utm_medium=organic&utm_campaign=local+listings', '10814 Woodedge Dr, Houston, TX 77070', 'US', 'USD', 'Houston', 'TX', '77070', 29.9448859, -95.58199479999999, 25, 'business', true, true, 'free', false, 4.8, 4288, 'Texas Quality Plumbing — plumbing in Houston', '<p>At Texas Quality Plumbing, our number one priority is our customers. We are constantly working toward our goal of being the best home and family resource for all your plumbing and drain cleaning needs. We respect our client''s time and needs because we know you have busy schedules, places to go, and things to do and we understand that this means you don''t have time for repairs that have to be done over again or time to wait for technicians who can''t show up on time. That’s why we do our best to provide you with efficient and quick services. And one of the ways we accomplish this is to do everything we can to troubleshoot and evaluate your current problems quickly and get the job done as accurately and efficiently as possible.</p>', 'Texas Quality Plumbing — plumbing in Houston | Fieseros', 'Book Texas Quality Plumbing for plumbing services in Houston. Professional, reliable, and trusted by local customers. Rated 4.8★ (4288 reviews).', '["plumbing"]', '{"emailSource":"none","emailVerified":false,"descriptionSource":"website_scrape","seededAt":"2026-08-06T05:58:08.859Z","seedSource":"google-places"}', 6, 'ChIJRYJR0Y7PQIYR_47naUFx8Mo', '2026-08-06T05:58:12.965Z', '2026-08-06T05:58:12.965Z')
  ON CONFLICT ("googlePlaceId") DO NOTHING;

INSERT INTO "Tenant" ("id", "name", "slug", "industry", "phone", "email", "website", "address", "country", "currency", "city", "state", "postalCode", "latitude", "longitude", "serviceRadiusKm", "plan", "marketplaceOptIn", "publicProfileEnabled", "listingTier", "claimed", "rating", "reviewCount", "tagline", "description", "seoTitle", "seoDescription", "businessCategoriesJson", "settingsJson", "employeesCount", "googlePlaceId", "createdAt", "updatedAt")
  VALUES ('cmsh3u8h2hmntasswyxgz', 'Village Plumbing, Air & Electric', 'village-plumbing-air-electric-7d2d3e', 'plumbing', '+1 281-344-2270', 'service@villageplumbing.com', 'https://villageplumbing.com/?utm_source=google&utm_medium=gmb&utm_campaign=Google%20Business%20Profile', '10644 W Little York Rd #200, Houston, TX 77041', 'US', 'USD', 'Houston', 'TX', '77041', 29.8677916, -95.5618629, 25, 'business', true, true, 'free', false, 4.8, 10581, 'Village Plumbing, Air & Electric — plumbing in Houston', '<p>Houston homes face challenges that most parts of the country never experience. Long cooling seasons, intense humidity, sudden storms, and shifting clay soil all place demands on plumbing, electrical, and HVAC systems. That is why homeowners need a company with deep local experience and the ability to respond quickly when problems arise.</p>
<p>Since 1946, Village Plumbing, Air & Electric has supported homeowners across the region with dependable solutions tailored to Houston’s unique conditions. From older homes built before modern electrical standards to newer developments with advanced HVAC zoning and high electrical loads, our team understands the wide range of systems found throughout the city.</p>
<p>Houston’s lack of zoning creates neighborhoods where old homes sit beside modern construction, meaning no two service calls are alike. As a full-service HVAC company in Houston, TX, that locals trust, we handle everything from AC replacement and indoor air improvements to plumbing upgrades and electrical repairs with the same professional approach.</p>
<p>Village Plumbing, Air & Electric has been part of the Houston community for more than 80 years. Very few companies in the…</p>', 'Village Plumbing, Air & Electric — plumbing in Houston | Fieseros', 'Book Village Plumbing, Air & Electric for plumbing services in Houston. Professional, reliable, and trusted by local customers. Rated 4.8★ (10581 reviews).', '["plumbing","electrical","construction"]', '{"emailSource":"website_scrape","emailVerified":false,"descriptionSource":"website_scrape","seededAt":"2026-08-06T05:58:10.022Z","seedSource":"google-places"}', 15, 'ChIJIc-2aF_AQIYRJab07qEMW4A', '2026-08-06T05:58:12.965Z', '2026-08-06T05:58:12.965Z')
  ON CONFLICT ("googlePlaceId") DO NOTHING;

INSERT INTO "Tenant" ("id", "name", "slug", "industry", "phone", "email", "website", "address", "country", "currency", "city", "state", "postalCode", "latitude", "longitude", "serviceRadiusKm", "plan", "marketplaceOptIn", "publicProfileEnabled", "listingTier", "claimed", "rating", "reviewCount", "tagline", "description", "seoTitle", "seoDescription", "businessCategoriesJson", "settingsJson", "employeesCount", "googlePlaceId", "createdAt", "updatedAt")
  VALUES ('cmsh3u8nziaqos0tjwsr9', 'Nick''s Plumbing & Air Conditioning', 'nicks-plumbing-air-conditioning-44a6ef', 'plumbing', '+1 713-868-9907', 'service@nicksplumbing.com', 'https://www.nicksplumbing.com/', '3780 Yale St, Houston, TX 77018', 'US', 'USD', 'Houston', 'TX', '77018', 29.8200218, -95.39895489999999, 25, 'business', true, true, 'free', false, 4.7, 4313, 'Nick''s Plumbing & Air Conditioning — plumbing in Houston', '<p>With over 45 years of experience, we provide fast, reliable, and professional plumbing services you can count on.</p>
<p>Comprehensive services to keep your home or business running smoothly. From emergency repairs to preventive maintenance, we’ve got you covered.</p>
<p>From leaky faucets to full repipes, our certified plumbers provide reliable solutions for your home. We handle everything from routine maintenance to emergency repairs with precision and care.</p>
<p>Keep your business flowing with our commercial plumbing services. We minimize downtime with efficient solutions for restaurants, offices, and industrial facilities.</p>
<p>Since 1979, Nick’s Plumbing has been Houston’s most dependable name for quality plumbing and HVAC services. Our locally owned business takes pride in treating every customer like a neighbor, because that’s exactly what you are.</p>
<p>Contact us today for fast, reliable service from Houston’s most trusted plumbing experts.</p>', 'Nick''s Plumbing & Air Conditioning — plumbing in Houston | Fieseros', 'Book Nick''s Plumbing & Air Conditioning for plumbing services in Houston. Professional, reliable, and trusted by local customers. Rated 4.7★ (4313 reviews)', '["plumbing","construction"]', '{"emailSource":"website_scrape","emailVerified":false,"descriptionSource":"website_scrape","seededAt":"2026-08-06T05:58:10.271Z","seedSource":"google-places"}', 13, 'ChIJc48_TGrHQIYRiWl40K2R6Xo', '2026-08-06T05:58:12.965Z', '2026-08-06T05:58:12.965Z')
  ON CONFLICT ("googlePlaceId") DO NOTHING;

INSERT INTO "Tenant" ("id", "name", "slug", "industry", "phone", "email", "website", "address", "country", "currency", "city", "state", "postalCode", "latitude", "longitude", "serviceRadiusKm", "plan", "marketplaceOptIn", "publicProfileEnabled", "listingTier", "claimed", "rating", "reviewCount", "tagline", "description", "seoTitle", "seoDescription", "businessCategoriesJson", "settingsJson", "employeesCount", "googlePlaceId", "createdAt", "updatedAt")
  VALUES ('cmsh3uaqryi0j4bzx0tjc', 'Roto-Rooter Plumbing & Water Cleanup', 'roto-rooter-plumbing-water-cleanup-e9a3a2', 'plumbing', '+1 713-470-0080', NULL, 'https://www.rotorooter.com/houston/?utm_source=Google&utm_medium=organic&utm_campaign=gmb&utm_content=website', '3403 North Sam Houston Pkwy W, Houston, TX 77086', 'US', 'USD', 'Houston', 'TX', '77086', 29.936673000000003, -95.4737262, 25, 'business', true, true, 'free', false, 4.7, 3671, 'Roto-Rooter Plumbing & Water Cleanup — plumbing in Houston', '<p>Roto-Rooter is a fully licensed and insured plumber in Houston, TX, providing 24/7 plumbing services, drain cleaning, and water damage cleanup. More people depend on Roto-Rooter than any other plumbing company in North America.</p>
<p>Roto-Rooter of Houston is on the job when you need us. Contact us at 713-472-5554, or use our online scheduling form .</p>
<p>Houston plumbing faces unique challenges due to the local climate and infrastructure. Heavy rainfall and hurricane storm surges can lead to sewer backups and flooding. Local “gumbo” clay soil expands and contracts with moisture changes, resulting in misaligned, cracked, or collapsed underground pipes. Older buildings may still use galvanized or cast iron pipes, which corrode, rust, and leak over time. Roto-Rooter’s skilled Houston plumbing technicians tailor their services to meet and resolve local plumbing issues.</p>
<p>You can’t afford to wait when you need an emergency plumber in Houston. Roto-Rooter’s dedicated plumbers are on call 24/7 with same-day service to solve your plumbing and water-related emergencies.</p>
<p>Debris that builds up over time in drains can cause clogs, reducing water flow and blocking the drain.…</p>', 'Roto-Rooter Plumbing & Water Cleanup — plumbing in Houston | Fieseros', 'Book Roto-Rooter Plumbing & Water Cleanup for plumbing services in Houston. Professional, reliable, and trusted by local customers. Rated 4.7★ (3671 review', '["plumbing","construction"]', '{"emailSource":"none","emailVerified":false,"descriptionSource":"website_scrape","seededAt":"2026-08-06T05:58:12.963Z","seedSource":"google-places"}', 15, 'ChIJR4Z2chlcP4YR1Qdrqp3DgjM', '2026-08-06T05:58:12.965Z', '2026-08-06T05:58:12.965Z')
  ON CONFLICT ("googlePlaceId") DO NOTHING;

COMMIT;
