import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getAuthUser } from '@/lib/auth';

// GET /api/recurring-jobs/[id]/activity
//
// Returns the last 50 ActivityLog entries that pertain to this schedule:
//   1. Direct schedule events (entityType='recurringJobSchedule', entityId=schedule.id)
//      — create / update / pause / resume / stop / delete
//   2. Events for any Job generated by this schedule (entityType='job',
//      entityId IN generatedJobIds) — e.g. "manually triggered", "completed",
//      "assigned", "invoice generated".
//
// We do NOT pull invoices' ActivityLog rows here — the Billing tab already
// surfaces invoices directly from the Invoice table, and most invoice events
// (paid/sent) are not relevant to schedule diagnostics.
//
// Auth: same gate as the rest of /api/recurring-jobs/[id]/* — must be the
// schedule's owning tenant.
//
// Response shape:
//   { activities: Array<ActivityLogRow> }
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await getAuthUser();
    if (!user || !user.tenantId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const { id } = await params;

    // Verify schedule exists + belongs to this tenant.
    const schedule = await db.recurringJobSchedule.findUnique({
      where: { id },
      select: { id: true, tenantId: true, title: true },
    });
    if (!schedule) {
      return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
    }
    if (schedule.tenantId !== user.tenantId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    // Pull generated job IDs so we can include their activity rows too.
    // Cap to the last 200 generated jobs — more than enough to cover the 50
    // most-recent activity entries that reference them.
    const generatedJobs = await db.job.findMany({
      where: { recurringScheduleId: id },
      orderBy: { createdAt: 'desc' },
      take: 200,
      select: { id: true },
    });
    const generatedJobIds = generatedJobs.map((j) => j.id);

    // Combined OR clause: schedule events OR events for any generated job.
    // We don't filter by severity — show everything for the audit timeline.
    const orClause = [
      { entityType: 'recurringJobSchedule', entityId: id },
      ...(generatedJobIds.length
        ? [{ entityType: 'job', entityId: { in: generatedJobIds } }]
        : []),
    ];

    const activities = await db.activityLog.findMany({
      where: {
        tenantId: user.tenantId,
        OR: orClause,
      },
      orderBy: { createdAt: 'desc' },
      take: 50,
    });

    return NextResponse.json({ activities });
  } catch (error) {
    console.error('Get recurring job activity error:', error);
    return NextResponse.json({ error: 'Failed to fetch activity log' }, { status: 500 });
  }
}
