/**
 * Canonical Form Templates — Master Suite 200+ (2026 Pro Edition)
 *
 * Completes the 200+ canonical template catalog with 42 curated canonical templates
 * across specialized industries, featuring 2026 UI/UX design tokens and split-hero media.
 */

import type { FormTemplate } from '../types';
import { registerTemplate } from '../registry';

interface MasterSuiteConfig {
  id: string;
  name: string;
  shortDescription: string;
  description: string;
  industry: string;
  category: string;
  color: string;
  photo: string;
  badge?: string;
  fields: any[];
  keywords: string[];
}

const MASTER_SUITE_DATA: MasterSuiteConfig[] = [
  // ─── 1. Real Estate, Mortgages & Property ──────────────────────────────────
  {
    id: 'hard-money-bridge-loan-application',
    name: 'Hard Money Fix & Flip Bridge Loan Application',
    shortDescription: 'Real estate investor financing, rehab draw schedules, and 72-hour fast closes.',
    description: 'Investor loan application capturing purchase price, estimated ARV, rehab budget, and exit strategy.',
    industry: 'finance',
    category: 'application',
    color: '#047857',
    photo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80',
    badge: '🏦 72-Hour Express Closing • Up to 90% Purchase / 100% Rehab',
    fields: [
      { id: 'investor_name', type: 'short_answer', label: 'Borrower / Entity Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'property_address', type: 'address', label: 'Subject Property Address', required: true, width: 'full' },
      { id: 'purchase_price', type: 'short_answer', label: 'Contract Purchase Price ($)', required: true, width: 'half' },
      { id: 'rehab_budget', type: 'short_answer', label: 'Estimated Rehab Budget ($)', required: true, width: 'half' },
      { id: 'after_repair_value', type: 'short_answer', label: 'Projected After Repair Value (ARV)', required: true, width: 'half' },
      { id: 'experience_count', type: 'dropdown', label: 'Completed Flips in Past 36 Months', required: true, width: 'half',
        options: [{ label: 'First Deal (0 Flips)', value: 'first_deal' }, { label: '1 to 3 Flips', value: '1_3' }, { label: '4 to 10 Flips', value: '4_10' }, { label: '10+ Flips (Tier-1 Pro)', value: '10_plus' }] },
    ],
    keywords: ['hard money loan application', 'fix and flip bridge loan', 'real estate investor financing'],
  },
  {
    id: 'mortgage-cash-out-refinance-quote',
    name: 'Mortgage Cash-Out Refinance & Rate Reduction Quote',
    shortDescription: 'Home equity cash-out, debt consolidation, and 15/30-year fixed rate comparisons.',
    description: 'Mortgage intake evaluating estimated home market value, current mortgage balance, credit score, and cash-out target.',
    industry: 'finance',
    category: 'quote',
    color: '#0f766e',
    photo: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80',
    badge: '🏡 Direct Wholesale Mortgage Rates • Zero Origination Option',
    fields: [
      { id: 'borrower_name', type: 'short_answer', label: 'Borrower Full Legal Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'property_address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'home_value', type: 'short_answer', label: 'Estimated Home Value ($)', required: true, width: 'half' },
      { id: 'mortgage_balance', type: 'short_answer', label: 'Current 1st Mortgage Balance ($)', required: true, width: 'half' },
      { id: 'cash_out_amount', type: 'short_answer', label: 'Desired Cash-Out Amount ($)', width: 'half' },
      { id: 'credit_bracket', type: 'dropdown', label: 'Estimated Credit Score', required: true, width: 'half',
        options: [{ label: '740+ Excellent', value: '740_plus' }, { label: '680 – 739 Good', value: '680_739' }, { label: '620 – 679 Fair', value: '620_679' }] },
    ],
    keywords: ['cash out refinance quote', 'mortgage refinance rate estimate', 'home equity loan application'],
  },
  {
    id: 'luxury-home-valuation-seller-consult',
    name: 'Luxury Home Comparative Market Analysis (CMA) & Seller Intake',
    shortDescription: 'Custom estate pricing analysis, architectural staging strategy, and confidential marketing.',
    description: 'Luxury seller intake documenting square footage, custom upgrades, panoramic views, and target listing timing.',
    industry: 'real_estate',
    category: 'inquiry',
    color: '#1e293b',
    photo: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    badge: '🏆 Top 1% Luxury Real Estate Advisors • Global Reach',
    fields: [
      { id: 'owner_name', type: 'short_answer', label: 'Homeowner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'selling_timeline', type: 'dropdown', label: 'Target Selling Timeline', required: true, width: 'half',
        options: [{ label: 'Ready to list in 30 – 60 days', value: '30_60d' }, { label: 'Planning within 3 – 6 months', value: '3_6m' }, { label: 'Just curious about market value', value: 'curious' }] },
      { id: 'property_highlights', type: 'long_answer', label: 'Key Upgrades, Architectural Details & Custom Features', width: 'full' },
    ],
    keywords: ['luxury home cma', 'home seller valuation intake', 'real estate listing consultation'],
  },

  // ─── 2. Specialty Trades & Exterior Solutions ──────────────────────────────
  {
    id: 'french-drain-yard-drainage-quote',
    name: 'French Drain & Yard Water Drainage Solutions Quote',
    shortDescription: 'Catch basins, channel drains, sump discharges, and erosion mitigation.',
    description: 'Drainage estimate intake identifying lawn pooling, downspout pooling, standing water, and slope grades.',
    industry: 'landscaping',
    category: 'quote',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1557429287-b2e26467fc2b?auto=format&fit=crop&w=1200&q=80',
    badge: '🌊 Gravity-Fed & Sump Yard Drainage Specialists',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Client Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'drainage_issue', type: 'dropdown', label: 'Primary Drainage Problem', required: true, width: 'half',
        options: [{ label: 'Standing Water in Yard / Soggy Lawn after Rain', value: 'soggy_yard' }, { label: 'Water Pooling near Foundation / Siding', value: 'foundation_pooling' }, { label: 'Gutter Downspout Runoff Flooding Patio / Walkway', value: 'downspouts' }, { label: 'Driveway / Garage Threshold Flooding', value: 'driveway_flooding' }] },
      { id: 'timeline', type: 'dropdown', label: 'Target Project Timeline', width: 'half',
        options: [{ label: 'Urgent / Next Heavy Rain', value: 'urgent' }, { label: 'Within 2 to 4 weeks', value: 'soon' }, { label: 'Flexible / Next month', value: 'flexible' }] },
    ],
    keywords: ['french drain quote', 'yard drainage contractor', 'downspout burial estimate'],
  },
  {
    id: 'sprinkler-irrigation-smart-controller-repair',
    name: 'Lawn Sprinkler Irrigation Repair & Smart Rachio Setup',
    shortDescription: 'Zone valve repairs, broken head replacements, backflow testing, and smart weather controllers.',
    description: 'Irrigation service intake detailing zone count, low pressure heads, leaking valves, and winterization blowouts.',
    industry: 'landscaping',
    category: 'request',
    color: '#16a34a',
    photo: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=1200&q=80',
    badge: '💧 EPA WaterSense Certified Irrigation Audits',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Customer Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'irrigation_service', type: 'dropdown', label: 'Service Needed', required: true, width: 'half',
        options: [{ label: 'Repair Leaks / Broken Sprinkler Heads', value: 'repair' }, { label: 'Full System Tune-Up & Coverage Audit', value: 'tuneup' }, { label: 'Smart WiFi Controller Upgrade (Rachio/Hunter)', value: 'smart_controller' }, { label: 'Spring Startup or Fall Winterization Blowout', value: 'seasonal' }] },
      { id: 'zone_count', type: 'dropdown', label: 'Number of Irrigation Zones', width: 'half',
        options: [{ label: '1 to 4 Zones', value: '1_4' }, { label: '5 to 8 Zones', value: '5_8' }, { label: '9 to 16 Zones', value: '9_16' }, { label: '16+ Commercial Zones', value: '16_plus' }] },
    ],
    keywords: ['sprinkler repair quote', 'lawn irrigation service', 'smart sprinkler controller install'],
  },
  {
    id: 'holiday-christmas-lighting-installation',
    name: 'Professional Holiday & Christmas Light Installation',
    shortDescription: 'Custom-cut C9 LED roofline lights, wreath accents, tree wrapping, and post-holiday removal.',
    description: 'Seasonal holiday light intake calculating roofline perimeter, tree wrapping quantities, and storage packages.',
    industry: 'home_services',
    category: 'quote',
    color: '#dc2626',
    photo: 'https://images.unsplash.com/photo-1543589077-47d81606c1bf?auto=format&fit=crop&w=1200&q=80',
    badge: '🎄 All-Inclusive Commercial LED Christmas Lighting',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Homeowner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'lighting_package', type: 'dropdown', label: 'Lighting Package Desired', required: true, width: 'full',
        options: [{ label: 'Classic Roofline C9 Warm White LEDs (Fascia & Gables)', value: 'roofline_c9' }, { label: 'Roofline + Lighted 36" Wreaths & Garland', value: 'roof_wreath' }, { label: 'Full Estate (Roofline, Palm/Oak Tree Trunk Wraps, Landscape Shrubs)', value: 'full_estate' }] },
      { id: 'stories', type: 'dropdown', label: 'Home Stories', width: 'full',
        options: [{ label: '1 Story Home', value: '1_story' }, { label: '2 Story Home', value: '2_story' }, { label: '3 Story / Steep Pitched Peaks', value: '3_story' }] },
    ],
    keywords: ['christmas light installation quote', 'holiday lighting contractor', 'roofline holiday lights cost'],
  },

  // ─── 3. Auto Hail & Specialized Auto Services ──────────────────────────────
  {
    id: 'paintless-dent-repair-auto-hail-intake',
    name: 'Auto Hail Damage & Paintless Dent Repair (PDR) Intake',
    shortDescription: 'Zero-deductible insurance claims, factory paint preservation, and rental car coordination.',
    description: 'Hail repair intake logging auto insurance carrier, VIN number, vehicle location, and claim deductible.',
    industry: 'automotive',
    category: 'quote',
    color: '#0f172a',
    photo: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80',
    badge: '🚗 Master PDR Technicians • $0 Out-of-Pocket with Full Coverage',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Vehicle Owner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'vehicle_info', type: 'short_answer', label: 'Year, Make, Model & VIN', required: true, width: 'half' },
      { id: 'insurance_carrier', type: 'dropdown', label: 'Auto Insurance Company', required: true, width: 'half',
        options: [{ label: 'State Farm', value: 'state_farm' }, { label: 'GEICO', value: 'geico' }, { label: 'Progressive', value: 'progressive' }, { label: 'Allstate / USAA / Liberty Mutual', value: 'other_major' }] },
      { id: 'claim_filed', type: 'dropdown', label: 'Has a claim been filed yet?', required: true, width: 'full',
        options: [{ label: 'No, need help filing and deductible assistance', value: 'need_help' }, { label: 'Yes, insurance adjuster has written initial estimate', value: 'have_estimate' }] },
    ],
    keywords: ['auto hail damage repair', 'paintless dent repair quote', 'pdr insurance deductible'],
  },
  {
    id: 'windshield-auto-glass-camera-calibration',
    name: 'Windshield Replacement & ADAS Camera Calibration',
    shortDescription: 'OEM glass replacements, mobile rock chip repair, and forward camera ADAS recalibration.',
    description: 'Auto glass intake capturing vehicle VIN, rain sensors, heads-up display (HUD), and lane departure camera.',
    industry: 'automotive',
    category: 'quote',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=1200&q=80',
    badge: '🛡️ OEM Certified Glass & Dynamic ADAS Recalibration',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Vehicle Owner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'vehicle_specs', type: 'short_answer', label: 'Year, Make & Model', required: true, width: 'half' },
      { id: 'service_needed', type: 'dropdown', label: 'Glass Service', required: true, width: 'half',
        options: [{ label: 'Windshield Full Replacement + ADAS Recalibration', value: 'windshield_adas' }, { label: 'Rock Chip / Small Crack Mobile Repair', value: 'chip_repair' }, { label: 'Side Window / Rear Glass Replacement', value: 'side_rear' }] },
      { id: 'glass_features', type: 'dropdown', label: 'Special Glass Features', width: 'full',
        options: [{ label: 'Heads-Up Display (HUD) & Rain Sensors', value: 'hud_rain' }, { label: 'Lane Keep Assist Forward Facing Camera', value: 'lane_assist' }, { label: 'Standard Glass (No special cameras)', value: 'standard' }] },
    ],
    keywords: ['windshield replacement quote', 'adas camera calibration', 'mobile auto glass repair'],
  },

  // ─── 4. Health, Clinical & Functional Medicine ─────────────────────────────
  {
    id: 'cosmetic-teeth-whitening-smile-makeover',
    name: 'Laser Teeth Whitening & Veneers Smile Consultation',
    shortDescription: 'In-office Zoom! laser whitening, porcelain veneers, and digital cosmetic smile design.',
    description: 'Cosmetic dental intake evaluating shade goals, dental sensitivity, composite vs porcelain veneers, and timing.',
    industry: 'dental',
    category: 'booking',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80',
    badge: '✨ Up to 8 Shades Whiter in 60 Minutes • Zero Sensitivity',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Patient Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Mobile Number', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email Address', required: true, width: 'half' },
      { id: 'cosmetic_interest', type: 'dropdown', label: 'Service of Interest', required: true, width: 'half',
        options: [{ label: 'In-Office 1-Hour Laser Teeth Whitening ($299 Special)', value: 'laser_whitening' }, { label: 'Custom Porcelain Veneers Consultation (Smile Makeover)', value: 'veneers' }, { label: 'Composite Bonding for Chipped / Gapped Teeth', value: 'bonding' }, { label: 'Custom Take-Home Professional Bleaching Trays', value: 'take_home' }] },
      { id: 'teeth_sensitivity', type: 'dropdown', label: 'Do you have sensitive teeth to hot or cold?', required: true, width: 'full',
        options: [{ label: 'No sensitivity', value: 'none' }, { label: 'Mild sensitivity occasionally', value: 'mild' }, { label: 'Very sensitive teeth (Requires desensitizing protocol)', value: 'high' }] },
    ],
    keywords: ['teeth whitening booking', 'porcelain veneers consultation', 'cosmetic dentist smile makeover'],
  },
  {
    id: 'concierge-medicine-executive-health-membership',
    name: 'Concierge Primary Care & Executive Health Membership',
    shortDescription: '24/7 direct physician cell access, same-day unhurried visits, and comprehensive longevity biomarkers.',
    description: 'Executive healthcare intake detailing preventive goals, advanced cardiovascular screenings (Cleerly CT, DEXA), and family memberships.',
    industry: 'healthcare',
    category: 'application',
    color: '#1e3a8a',
    photo: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80',
    badge: '🩺 24/7 Private Physician Cell Phone Access • Zero Wait Times',
    fields: [
      { id: 'applicant_name', type: 'short_answer', label: 'Applicant Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Direct Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email', required: true, width: 'half' },
      { id: 'membership_type', type: 'dropdown', label: 'Membership Tier', required: true, width: 'half',
        options: [{ label: 'Individual Executive Membership', value: 'individual' }, { label: 'Couple / Family Plan', value: 'family' }, { label: 'Corporate C-Suite Executive Health Retainer', value: 'corporate' }] },
      { id: 'health_focus', type: 'long_answer', label: 'Primary Health Optimization Goals (Longevity, Heart Health, Hormones, Weight)', width: 'full' },
    ],
    keywords: ['concierge doctor membership', 'executive primary care intake', 'private physician consultation'],
  },

  // ─── 5. Additional 30 Curated Templates ─────────────────────────────────────
  {
    id: 'microbrewery-private-event-taproom-booking',
    name: 'Craft Microbrewery Taproom & Beer Garden Private Event',
    shortDescription: 'Exclusive taproom buyouts, craft beer flights, and private patio party booking.',
    description: 'Brewery event intake specifying draft packages, outside catering, audio setup, and guest headcount.',
    industry: 'hospitality',
    category: 'booking',
    color: '#b45309',
    photo: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=80',
    badge: '🍺 Award-Winning Craft Brewery & Private Taproom',
    fields: [
      { id: 'organizer_name', type: 'short_answer', label: 'Host Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'event_date', type: 'date', label: 'Event Date', required: true, width: 'half' },
      { id: 'party_size', type: 'dropdown', label: 'Guest Count', required: true, width: 'half',
        options: [{ label: '25 – 50 guests (Private Barrel Room)', value: '25_50' }, { label: '50 – 100 guests (Outdoor Beer Garden)', value: '50_100' }, { label: '100 – 250 guests (Full Taproom Buyout)', value: 'full_buyout' }] },
      { id: 'beverage_package', type: 'dropdown', label: 'Draft Beer & Beverage Tier', width: 'full',
        options: [{ label: 'Open Craft Beer & Cider Tap Bar (4 Hours)', value: 'open_tap' }, { label: 'Beer + Wine & Premium Seltzers', value: 'beer_wine' }, { label: 'Drink Ticket Package (2 per guest)', value: 'drink_tickets' }] },
    ],
    keywords: ['brewery private event booking', 'taproom rental quote', 'beer garden party form'],
  },
  {
    id: 'bed-and-breakfast-romantic-weekend-booking',
    name: 'Luxury Bed & Breakfast Boutique Inn Reservation',
    shortDescription: 'Fireplace suites, farm-fresh 3-course breakfast, and private hot tub getaway booking.',
    description: 'Boutique lodging intake capturing check-in dates, romantic packages (champagne/roses), and dietary preferences.',
    industry: 'hospitality',
    category: 'booking',
    color: '#831843',
    photo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    badge: '🌿 5-Star Boutique Country Inn & Gourmet Breakfast',
    fields: [
      { id: 'guest_name', type: 'short_answer', label: 'Primary Guest Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'checkin_date', type: 'date', label: 'Check-In Date', required: true, width: 'half' },
      { id: 'nights', type: 'dropdown', label: 'Number of Nights', required: true, width: 'half',
        options: [{ label: '2 Nights (Weekend Retreat)', value: '2' }, { label: '3 Nights (Long Weekend)', value: '3' }, { label: '4+ Nights (Extended Stay)', value: '4_plus' }] },
      { id: 'suite_type', type: 'dropdown', label: 'Suite Selection', required: true, width: 'full',
        options: [{ label: 'King Master Fireplace Suite + Jacuzzi Tub', value: 'king_fireplace' }, { label: 'Private Garden Cottage with Outdoor Cedar Hot Tub', value: 'garden_cottage' }, { label: 'Vintage Deluxe Balcony Room with Mountain View', value: 'deluxe_balcony' }] },
    ],
    keywords: ['bed and breakfast booking', 'boutique inn reservation', 'romantic weekend getaway quote'],
  },
  {
    id: 'custom-wedding-cake-tasting-consultation',
    name: 'Artisan Custom Wedding Cake Tasting & Design Consult',
    shortDescription: 'Sugar flower artistry, modern fondant tiers, flavor flight tastings, and delivery setup.',
    description: 'Bakery intake capturing guest servings count, flavor combinations (passionfruit, salted caramel), and venue delivery logistics.',
    industry: 'restaurant',
    category: 'booking',
    color: '#db2777',
    photo: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=1200&q=80',
    badge: '🍰 Master Sugar Cake Artists • Featured in Vogue & Brides',
    fields: [
      { id: 'couple_names', type: 'short_answer', label: 'Couple Names', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'wedding_date', type: 'date', label: 'Wedding Date', required: true, width: 'half' },
      { id: 'guest_servings', type: 'dropdown', label: 'Cake Servings Needed', required: true, width: 'half',
        options: [{ label: '50 – 80 Servings (2 Tiers)', value: '2_tier' }, { label: '100 – 150 Servings (3 Tiers)', value: '3_tier' }, { label: '175 – 250 Servings (4 Tiers)', value: '4_tier' }, { label: '250+ Grand Multi-Tier + Sheet Cake', value: 'grand_tier' }] },
      { id: 'venue_address', type: 'address', label: 'Reception Venue Address (for Refrigerated Delivery)', required: true, width: 'full' },
    ],
    keywords: ['wedding cake tasting booking', 'custom bakery consultation', 'wedding cake quote'],
  },
  {
    id: 'private-jet-empty-leg-charter-quote',
    name: 'On-Demand Private Jet Charter & Empty Leg Flights',
    shortDescription: 'Heavy jets, super-midsize cabins, turbo-props, and bespoke private aviation routing.',
    description: 'Private aviation flight request detailing departure airport (FBO), passenger count, pets onboard, and catering.',
    industry: 'transportation',
    category: 'quote',
    color: '#0f172a',
    photo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
    badge: '✈️ ARG/US Platinum Rated Luxury Private Fleet',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Passenger / Principal Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'origin_dest', type: 'short_answer', label: 'Departure Airport & Destination Airport', required: true, width: 'full' },
      { id: 'depart_date', type: 'date', label: 'Departure Date', required: true, width: 'half' },
      { id: 'pax_count', type: 'dropdown', label: 'Passenger Count', required: true, width: 'half',
        options: [{ label: '1 – 4 Passengers (Light Jet / Citation)', value: '1_4' }, { label: '5 – 8 Passengers (Midsize / Hawker)', value: '5_8' }, { label: '9 – 14 Passengers (Heavy Jet / Challenger / Gulfstream)', value: '9_14' }] },
    ],
    keywords: ['private jet charter quote', 'empty leg flight booking', 'luxury aircraft rental'],
  },
  {
    id: 'rv-campervan-rental-reservation',
    name: 'Luxury RV & Mercedes Sprinter Campervan Rental',
    shortDescription: 'Class-A motorhomes, adventure campervans, unlimited generator hours, and national park setup.',
    description: 'RV rental booking intake detailing departure dates, travel itinerary, pet-friendly requirements, and towing needs.',
    industry: 'transportation',
    category: 'booking',
    color: '#047857',
    photo: 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?auto=format&fit=crop&w=1200&q=80',
    badge: '🚐 Fully Equipped 4x4 Sprinter Campervans & Luxury RVs',
    fields: [
      { id: 'renter_name', type: 'short_answer', label: 'Primary Driver Legal Name (25+)', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'pickup_date', type: 'date', label: 'Departure Pickup Date', required: true, width: 'half' },
      { id: 'vehicle_class', type: 'dropdown', label: 'RV Class Preference', required: true, width: 'half',
        options: [{ label: 'Mercedes Sprinter 4x4 Campervan (Sleeps 2-4)', value: 'sprinter_van' }, { label: 'Class C 28ft Motorhome with Slide-Outs (Sleeps 6)', value: 'class_c' }, { label: 'Class A 36ft Luxury Coach (Sleeps 8)', value: 'class_a' }] },
      { id: 'trip_destinations', type: 'long_answer', label: 'Planned Destinations & Total Estimated Miles', width: 'full' },
    ],
    keywords: ['rv rental booking', 'campervan hire reservation', 'motorhome quote'],
  },
  {
    id: 'boat-winterization-shrink-wrap-service',
    name: 'Marine Boat Winterization & Heavy Shrink-Wrap Service',
    shortDescription: 'Inboard/outboard engine fogging, antifreeze flush, acid wash hull cleaning, and ventilated shrink-wrap.',
    description: 'Marine service intake capturing boat length, engine make (Mercury, Yamaha, Volvo Penta), and dry dock storage.',
    industry: 'automotive',
    category: 'request',
    color: '#0369a1',
    photo: 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=1200&q=80',
    badge: '⚓ Certified Marine Master Mechanics • Freeze Damage Guarantee',
    fields: [
      { id: 'owner_name', type: 'short_answer', label: 'Boat Owner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'boat_specs', type: 'short_answer', label: 'Boat Year, Make, Model & Length (Ft)', required: true, width: 'half' },
      { id: 'engine_type', type: 'dropdown', label: 'Engine Configuration', required: true, width: 'half',
        options: [{ label: 'Single Outboard Engine (Yamaha/Mercury)', value: 'single_outboard' }, { label: 'Twin Outboard Engines', value: 'twin_outboard' }, { label: 'Inboard / Sterndrive (Mercruiser/Volvo)', value: 'inboard_io' }] },
      { id: 'services_requested', type: 'dropdown', label: 'Winterization Scope', required: true, width: 'full',
        options: [{ label: 'Complete Winterization (Engine, Water Systems) + Heavy Shrink Wrap', value: 'full_winter_wrap' }, { label: 'Engine Winterization Only', value: 'engine_only' }, { label: 'Shrink Wrap Only (With Moisture Damp Bags & Vents)', value: 'wrap_only' }] },
    ],
    keywords: ['boat winterization quote', 'marine shrink wrap service', 'outboard motor winterize estimate'],
  },
  {
    id: 'drywall-hang-tape-texture-quote',
    name: 'Drywall Installation, Level 5 Smooth Finish & Texture Quote',
    shortDescription: 'Sheetrock hanging, dustless taped joints, orange peel/knockdown textures, and skim coating.',
    description: 'Drywall contractor intake determining square footage, ceiling height (10ft+), moisture-resistant greenboard, and soundproofing.',
    industry: 'construction',
    category: 'quote',
    color: '#64748b',
    photo: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
    badge: '🔨 Level 5 Mirror Smooth Drywall Finishes • Dust-Free Sanding',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Homeowner / General Contractor Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Jobsite Address', required: true, width: 'full' },
      { id: 'drywall_scope', type: 'dropdown', label: 'Project Scope', required: true, width: 'half',
        options: [{ label: 'Whole Basement / Addition Drywall (Hang, Tape, Finish)', value: 'whole_space' }, { label: 'Drywall Patching & Water Damage Ceiling Repair', value: 'patch_repair' }, { label: 'Popcorn Ceiling Removal & Smooth Level 5 Skim Coat', value: 'popcorn_removal' }] },
      { id: 'finish_texture', type: 'dropdown', label: 'Desired Texture Style', required: true, width: 'half',
        options: [{ label: 'Level 5 Ultra-Smooth Flat', value: 'level_5_smooth' }, { label: 'Orange Peel Texture', value: 'orange_peel' }, { label: 'Knockdown Texture', value: 'knockdown' }] },
    ],
    keywords: ['drywall installation quote', 'sheetrock finishing estimate', 'popcorn ceiling removal cost'],
  },
  {
    id: 'chimney-sweep-flue-inspection-service',
    name: 'Chimney Sweep, Level 2 Video Camera Inspection & Masonry Repair',
    shortDescription: 'Creosote removal, certified CSIA video scan, chimney crown sealing, and damper replacement.',
    description: 'Chimney intake recording fireplace type (wood-burning, gas, wood stove), creosote buildup, and draft issues.',
    industry: 'home_services',
    category: 'inspection',
    color: '#854d0e',
    photo: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80',
    badge: '🔥 CSIA Certified Chimney Sweeps & NFPA 211 Camera Inspections',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Homeowner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Home Address', required: true, width: 'full' },
      { id: 'fireplace_type', type: 'dropdown', label: 'Fireplace / Appliance System', required: true, width: 'half',
        options: [{ label: 'Open Wood-Burning Masonry Fireplace', value: 'masonry_wood' }, { label: 'Prefabricated Zero-Clearance Metal Fireplace', value: 'prefab_metal' }, { label: 'Wood Burning Stove / Pellet Insert', value: 'wood_stove' }, { label: 'Direct Vent Gas Fireplace', value: 'gas_fireplace' }] },
      { id: 'primary_issue', type: 'dropdown', label: 'Reason for Inspection', required: true, width: 'half',
        options: [{ label: 'Annual Sweep & Safety Inspection', value: 'annual_clean' }, { label: 'Smoke Backing Up into House / Poor Draft', value: 'smoke_draft' }, { label: 'Water Leaking around Chimney / Damaged Crown', value: 'water_leak' }, { label: 'Real Estate Transfer Level 2 Camera Inspection', value: 'real_estate_level2' }] },
    ],
    keywords: ['chimney sweep quote', 'chimney inspection cost', 'fireplace creosote cleaning'],
  },
  {
    id: 'appliance-repair-refrigerator-oven-dispatch',
    name: 'Major Appliance Repair & Same-Day Diagnostic Dispatch',
    shortDescription: 'Sub-Zero refrigerators, Bosch dishwashers, Viking ovens, and Samsung washer/dryers.',
    description: 'Appliance technician dispatch form collecting brand, model number, fault error codes, and symptoms.',
    industry: 'home_services',
    category: 'request',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80',
    badge: '⚡ Same-Day Factory-Certified Appliance Technicians',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Customer Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Mobile Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Service Address', required: true, width: 'full' },
      { id: 'appliance_type', type: 'dropdown', label: 'Broken Appliance', required: true, width: 'half',
        options: [{ label: 'Refrigerator / Freezer Not Cooling', value: 'refrigerator' }, { label: 'Washing Machine Not Draining / Spinning', value: 'washer' }, { label: 'Dryer Not Heating', value: 'dryer' }, { label: 'Oven / Stove / Range Not Heating', value: 'oven' }, { label: 'Dishwasher Leaking / Not Washing', value: 'dishwasher' }] },
      { id: 'brand_name', type: 'short_answer', label: 'Appliance Brand (e.g. Sub-Zero, Samsung, Whirlpool, LG)', required: true, width: 'half' },
    ],
    keywords: ['appliance repair service', 'refrigerator repair near me', 'washing machine technician dispatch'],
  },
  {
    id: 'commercial-window-tinting-uv-quote',
    name: 'Commercial Architectural Window Tinting & Solar Film Quote',
    shortDescription: '3M solar rejection film, security anti-shatter film, and decorative frosted privacy glass.',
    description: 'Commercial tinting intake calculating window pane square footage, glare reduction, HVAC load reduction, and privacy frosting.',
    industry: 'construction',
    category: 'quote',
    color: '#334155',
    photo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    badge: '🏢 3M™ Certified Commercial Window Film Dealer',
    fields: [
      { id: 'company_name', type: 'short_answer', label: 'Company / Property Name', required: true, width: 'half' },
      { id: 'contact_name', type: 'short_answer', label: 'Contact Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Building Address', required: true, width: 'half' },
      { id: 'film_objective', type: 'dropdown', label: 'Primary Film Objective', required: true, width: 'full',
        options: [{ label: 'Solar Heat & Glare Rejection (Lowers energy bills up to 30%)', value: 'solar_heat' }, { label: 'Decorative Frosted & Gradient Privacy Film for Conference Rooms', value: 'privacy_frost' }, { label: 'Safety & Security Anti-Shatter Forced Entry Film (8mil+)', value: 'security_film' }] },
    ],
    keywords: ['commercial window tinting quote', '3m solar window film estimate', 'frosted glass office film'],
  },
  {
    id: 'tile-grout-deep-cleaning-color-seal',
    name: 'Tile & Grout Deep Steam Extraction & Color Sealing',
    shortDescription: 'High-pressure 1000-PSI enclosed extraction, grout color restoration, and clear silicone sealing.',
    description: 'Intake for porcelain, ceramic, and travertine floors estimating square footage, grout discoloration, and shower stall restoration.',
    industry: 'cleaning',
    category: 'quote',
    color: '#0d9488',
    photo: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    badge: '✨ Restores Grout to Like-New Condition • 10-Year Stain Barrier',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Homeowner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Address', required: true, width: 'full' },
      { id: 'tile_area', type: 'dropdown', label: 'Tile Surface Area', required: true, width: 'half',
        options: [{ label: 'Kitchen & Dining Floors (200 – 400 sq ft)', value: 'kitchen_dining' }, { label: 'Whole First Floor (500 – 1,200 sq ft)', value: 'whole_floor' }, { label: 'Walk-In Shower & Bathroom Stalls', value: 'showers' }, { label: 'Natural Stone Travertine / Marble Polishing', value: 'natural_stone' }] },
      { id: 'grout_sealing', type: 'dropdown', label: 'Grout Sealing Preference', width: 'half',
        options: [{ label: 'Color Seal (Changes/restores grout color & locks out stains)', value: 'color_seal' }, { label: 'Clear Penetrating Seal', value: 'clear_seal' }] },
    ],
    keywords: ['tile and grout cleaning quote', 'grout color seal estimate', 'travertine floor cleaning'],
  },
  {
    id: 'commercial-janitorial-recurring-bid',
    name: 'Commercial Janitorial & Daily Office Cleaning RFP',
    shortDescription: 'Nightly office cleaning, commercial floor buffing, sanitized restrooms, and trash disposal.',
    description: 'Janitorial proposal intake recording square footage, cleanings per week (3x vs 5x), day porter needs, and supply replenishment.',
    industry: 'cleaning',
    category: 'quote',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    badge: '🧹 Bonded & Insured Commercial Cleaning Teams • 100% Green Certified',
    fields: [
      { id: 'company_name', type: 'short_answer', label: 'Facility / Company Name', required: true, width: 'half' },
      { id: 'contact_name', type: 'short_answer', label: 'Facility Manager Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'facility_address', type: 'address', label: 'Facility Address', required: true, width: 'half' },
      { id: 'facility_sqft', type: 'dropdown', label: 'Facility Square Footage', required: true, width: 'half',
        options: [{ label: '2,500 – 6,000 sq ft', value: 'small_office' }, { label: '6,000 – 15,000 sq ft', value: 'med_office' }, { label: '15,000 – 40,000 sq ft', value: 'large_office' }, { label: '40,000+ sq ft Commercial Campus', value: 'campus' }] },
      { id: 'frequency', type: 'dropdown', label: 'Cleaning Frequency', required: true, width: 'half',
        options: [{ label: '5 Nights / Week (Mon – Fri)', value: '5x_week' }, { label: '3 Nights / Week (Mon / Wed / Fri)', value: '3x_week' }, { label: '7 Days / Week (Including Weekends)', value: '7x_week' }] },
    ],
    keywords: ['commercial janitorial bid', 'office cleaning quote', 'nightly janitorial contract RFP'],
  },
  {
    id: 'estate-probate-letters-testamentary-consult',
    name: 'Probate Law & Estate Administration Consultation',
    shortDescription: 'Letters testamentary, asset distribution, creditor notice handling, and probate court hearings.',
    description: 'Probate intake evaluating if a valid will exists, approximate estate gross asset value, real property count, and executor status.',
    industry: 'legal',
    category: 'intake',
    color: '#1e293b',
    photo: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
    badge: '⚖️ Compassionate Probate & Estate Administration Attorneys',
    fields: [
      { id: 'executor_name', type: 'short_answer', label: 'Executor / Personal Representative Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'decedent_name', type: 'short_answer', label: 'Deceased Loved One Legal Name', required: true, width: 'half' },
      { id: 'date_of_passing', type: 'date', label: 'Date of Passing', required: true, width: 'half' },
      { id: 'will_status', type: 'dropdown', label: 'Did the deceased leave a Last Will & Testament?', required: true, width: 'full',
        options: [{ label: 'Yes, original signed Will is available', value: 'valid_will' }, { label: 'No Will (Intestate Estate)', value: 'intestate' }, { label: 'A Living Trust exists (Trust administration needed)', value: 'trust_admin' }] },
    ],
    keywords: ['probate lawyer consultation', 'letters testamentary intake form', 'estate administration attorney'],
  },
  {
    id: 'irs-tax-debt-offer-in-compromise-intake',
    name: 'IRS Fresh Start & Tax Debt Relief Assessment',
    shortDescription: 'Offer in compromise (OIC), wage garnishment stops, penalty abatements, and unfiled back taxes.',
    description: 'Tax resolution intake determining total back tax amount owed, IRS levy threats, annual household income, and asset equity.',
    industry: 'accounting',
    category: 'assessment',
    color: '#14532d',
    photo: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=1200&q=80',
    badge: '🛡️ Enrolled Agents & Tax Attorneys Representing You Against the IRS',
    fields: [
      { id: 'taxpayer_name', type: 'short_answer', label: 'Taxpayer Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Confidential Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email Address', required: true, width: 'half' },
      { id: 'debt_amount', type: 'dropdown', label: 'Estimated Total Back Tax Debt', required: true, width: 'half',
        options: [{ label: '$10,000 – $25,000', value: '10k_25k' }, { label: '$25,000 – $75,000', value: '25k_75k' }, { label: '$75,000 – $200,000', value: '75k_200k' }, { label: '$200,000+ High-Debt Resolution', value: '200k_plus' }] },
      { id: 'urgent_action', type: 'dropdown', label: 'Is the IRS actively levying or garnishing wages?', required: true, width: 'full',
        options: [{ label: 'Yes, active wage garnishment / bank levy', value: 'active_levy' }, { label: 'Received final notice of intent to levy (Urgent)', value: 'final_notice' }, { label: 'Just need to resolve back taxes before escalation', value: 'general_relief' }] },
    ],
    keywords: ['irs tax relief intake', 'offer in compromise assessment', 'back tax attorney help'],
  },
  {
    id: 'high-ticket-marketing-retainer-proposal',
    name: 'Full-Funnel Growth Marketing & Paid Media Retainer Scoping',
    shortDescription: 'Google Ads PPC, Meta/TikTok performance scaling, landing page CRO, and ROAS optimization.',
    description: 'Growth marketing intake capturing monthly ad spend budget, current blended CAC, attribution tracking, and revenue growth goals.',
    industry: 'marketing',
    category: 'quote',
    color: '#ec4899',
    photo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    badge: '📈 Scaled Over $150M in Profitable Ad Spend • Top 1% Growth Agency',
    fields: [
      { id: 'company_name', type: 'short_answer', label: 'Brand / Company Name', required: true, width: 'half' },
      { id: 'contact_name', type: 'short_answer', label: 'Founder / Marketing Lead Name', required: true, width: 'half' },
      { id: 'work_email', type: 'email', label: 'Work Email', required: true, width: 'half' },
      { id: 'monthly_ad_spend', type: 'dropdown', label: 'Current Monthly Ad Spend', required: true, width: 'half',
        options: [{ label: '$10,000 – $30,000 / mo', value: '10k_30k' }, { label: '$30,000 – $100,000 / mo', value: '30k_100k' }, { label: '$100,000 – $500,000+ / mo', value: '100k_500k' }] },
      { id: 'growth_channels', type: 'dropdown', label: 'Primary Focus Channel', required: true, width: 'full',
        options: [{ label: 'Paid Search (Google Ads / Performance Max / YouTube)', value: 'google_ads' }, { label: 'Paid Social (Meta Ads + TikTok Scaling)', value: 'meta_tiktok' }, { label: 'Full Omnichannel Engine (Paid Media + CRO + Email/SMS Lifecycle)', value: 'omnichannel' }] },
    ],
    keywords: ['growth marketing agency quote', 'paid media retainer proposal', 'google ads performance agency intake'],
  },
  {
    id: 'ux-design-accessibility-wcag-audit',
    name: 'UI/UX Design & WCAG 2.2 Accessibility Compliance Audit',
    shortDescription: 'Screen reader usability, color contrast remediation, ADA lawsuit defense, and Figma design polish.',
    description: 'Digital accessibility intake analyzing website URL, automated audit reports, VPAT compliance needs, and checkout flows.',
    industry: 'technology',
    category: 'assessment',
    color: '#3b82f6',
    photo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1200&q=80',
    badge: '♿ Certified IAAP Accessibility Specialists • WCAG 2.2 AA Conformance',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Contact Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'website_url', type: 'short_answer', label: 'Website / App URL to Audit', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Work Email', required: true, width: 'half' },
      { id: 'audit_scope', type: 'dropdown', label: 'Audit Scope Needed', required: true, width: 'full',
        options: [{ label: 'Comprehensive WCAG 2.2 AA Audit + VPAT Statement', value: 'wcag_vpat' }, { label: 'Urgent ADA Demand Letter Remediation', value: 'ada_demand' }, { label: 'Full UX Design Heuristic & Conversion Redesign', value: 'ux_heuristic' }] },
    ],
    keywords: ['wcag accessibility audit quote', 'ada website compliance form', 'ux design audit proposal'],
  },
  {
    id: 'private-chef-dinner-party-booking',
    name: 'Private Chef Multi-Course Dinner Party & Tasting Experience',
    shortDescription: 'In-home custom tasting menus, wine pairings, table setting, and full kitchen cleanup.',
    description: 'Private culinary intake detailing guest count, dietary intolerances, culinary theme (French, Omakase, Modern Italian), and date.',
    industry: 'restaurant',
    category: 'booking',
    color: '#ca8a04',
    photo: 'https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1200&q=80',
    badge: '👨‍🍳 Michelin-Experienced Private Chefs • Full Kitchen Cleanup Included',
    fields: [
      { id: 'host_name', type: 'short_answer', label: 'Host Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'dinner_date', type: 'date', label: 'Dinner Party Date', required: true, width: 'half' },
      { id: 'guest_count', type: 'dropdown', label: 'Number of Guests', required: true, width: 'half',
        options: [{ label: 'Intimate Couple (2 Guests)', value: '2' }, { label: '4 – 8 Guests (Dinner Party)', value: '4_8' }, { label: '9 – 16 Guests (Celebration Banquet)', value: '9_16' }] },
      { id: 'cuisine_theme', type: 'dropdown', label: 'Cuisine Style', required: true, width: 'full',
        options: [{ label: 'Modern European / French Fine Dining (5 Courses)', value: 'french' }, { label: 'Omakase Sushi & Japanese Wagyu Experience', value: 'omakase' }, { label: 'Tuscan Farm-to-Table & Handmade Pasta', value: 'tuscan' }, { label: 'Custom Fusion Menu based on Seasonal Ingredients', value: 'custom_fusion' }] },
    ],
    keywords: ['private chef booking', 'in home private dining quote', 'private chef dinner party cost'],
  },
  {
    id: 'wedding-rehearsal-dinner-venue-booking',
    name: 'Wedding Rehearsal Dinner & Welcome Party Venue Booking',
    shortDescription: 'Private terrace rooms, cocktail hour passed hors d’oeuvres, speeches AV, and customized menus.',
    description: 'Rehearsal dinner booking intake capturing wedding weekend schedule, party size, open bar packages, and slideshow projection.',
    industry: 'events',
    category: 'booking',
    color: '#be185d',
    photo: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    badge: '🥂 Intimate Private Dining Suites & Waterfront Terraces',
    fields: [
      { id: 'planner_name', type: 'short_answer', label: 'Host / Planner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'rehearsal_date', type: 'date', label: 'Rehearsal Dinner Date', required: true, width: 'half' },
      { id: 'guest_count', type: 'dropdown', label: 'Guest Headcount', required: true, width: 'half',
        options: [{ label: '20 – 35 Guests (Close Family & Bridal Party)', value: '20_35' }, { label: '35 – 60 Guests (Rehearsal + Out-of-Town Welcome)', value: '35_60' }, { label: '60 – 120 Guests (Full Welcome Reception)', value: '60_120' }] },
      { id: 'audio_visual_needs', type: 'dropdown', label: 'AV Needs for Speeches & Slideshows', width: 'full',
        options: [{ label: 'Wireless Mic + HD Projector & Sound System', value: 'full_av' }, { label: 'Microphone Only for Toasts', value: 'mic_only' }, { label: 'Background Music Only', value: 'music_only' }] },
    ],
    keywords: ['wedding rehearsal dinner booking', 'welcome party venue quote', 'private dining rehearsal dinner'],
  },

  // ─── 6. Final 15 Curated Power Templates ───────────────────────────────────
  {
    id: 'personal-concierge-lifestyle-assistant-onboarding',
    name: 'Executive Personal Concierge & Lifestyle Management Intake',
    shortDescription: 'Bespoke travel curation, VIP reservations, private chef booking, and luxury property oversight.',
    description: 'Lifestyle onboarding questionnaire cataloging dietary preferences, frequent flier numbers, preferred hotel chains, and family calendar.',
    industry: 'hospitality',
    category: 'intake',
    color: '#334155',
    photo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    badge: '💎 24/7 Dedicated Luxury Lifestyle Concierge',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Principal Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Confidential Mobile Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email', required: true, width: 'half' },
      { id: 'service_tier', type: 'dropdown', label: 'Concierge Retainer Tier', required: true, width: 'half',
        options: [{ label: 'Executive Tier (20 Hours / Month)', value: 'executive_20' }, { label: 'Family Estate Tier (40 Hours / Month)', value: 'family_40' }, { label: 'Unlimited 24/7 On-Demand White Glove', value: 'unlimited_247' }] },
      { id: 'priority_tasks', type: 'long_answer', label: 'Top Immediate Lifestyle Support Priorities', width: 'full' },
    ],
    keywords: ['personal concierge intake', 'lifestyle management consultation', 'luxury executive assistant booking'],
  },
  {
    id: 'pilates-reformer-studio-membership-pass',
    name: 'Reformer Pilates Studio Membership & VIP Intro Class',
    shortDescription: 'Allegro 2 Reformers, small-group athletic conditioning, Tower sessions, and posture alignment.',
    description: 'Pilates intake assessing prior reformer experience, spinal disc injuries, fitness goals, and preferred class times.',
    industry: 'fitness',
    category: 'registration',
    color: '#0d9488',
    photo: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',
    badge: '🧘 Certified Balanced Body® Reformer Instructors',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Student Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email Address', required: true, width: 'half' },
      { id: 'reformer_exp', type: 'dropdown', label: 'Reformer Experience Level', required: true, width: 'half',
        options: [{ label: 'Complete Beginner (Never used a reformer)', value: 'beginner' }, { label: 'Intermediate (10+ classes completed)', value: 'intermediate' }, { label: 'Advanced Practitioner', value: 'advanced' }] },
      { id: 'membership_pass', type: 'dropdown', label: 'Pass Option', required: true, width: 'full',
        options: [{ label: 'First Timer Intro 2-Class Pass ($49 Special)', value: 'intro_pass' }, { label: 'Unlimited Monthly Reformer Membership', value: 'unlimited_monthly' }, { label: '10-Class Flexible Studio Pack', value: '10_pack' }] },
    ],
    keywords: ['pilates reformer class booking', 'pilates studio membership form', 'intro reformer pass registration'],
  },
  {
    id: 'cryotherapy-infrared-sauna-recovery-pass',
    name: 'Whole-Body Cryotherapy & Infrared Sauna Recovery Session',
    shortDescription: '-200°F cryo chamber, full-spectrum infrared sauna, compression boots, and contrast therapy.',
    description: 'Athletic recovery intake assessing cold therapy contraindications (Raynaud’s, high BP), detox goals, and session packages.',
    industry: 'wellness',
    category: 'booking',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80',
    badge: '❄️ Sub-Zero Cryo & Clearlight Sanctuary Infrared Saunas',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Client Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email Address', required: true, width: 'half' },
      { id: 'modalities', type: 'dropdown', label: 'Recovery Experience', required: true, width: 'half',
        options: [{ label: 'Fire & Ice Combo (Whole Body Cryo + 45min Infrared Sauna)', value: 'fire_ice' }, { label: 'Whole Body Cryotherapy Session (-220°F for 3 mins)', value: 'cryo_only' }, { label: 'Full Spectrum Infrared Sauna + Chromotherapy (45 mins)', value: 'sauna_only' }, { label: 'Normatec 3 Dynamic Air Compression Leg Flush', value: 'normatec' }] },
      { id: 'contraindications', type: 'dropdown', label: 'Do you have uncontrolled high blood pressure or Raynaud’s?', required: true, width: 'full',
        options: [{ label: 'No contraindications', value: 'none' }, { label: 'Yes (Will consult technician prior to entry)', value: 'yes' }] },
    ],
    keywords: ['cryotherapy session booking', 'infrared sauna appointment', 'athletic recovery spa pass'],
  },
  {
    id: 'corporate-headshot-photography-session-booking',
    name: 'Executive Studio Headshots & LinkedIn Personal Brand Session',
    shortDescription: 'Tethered capture, professional studio lighting, wardrobe styling advice, and same-day retouched files.',
    description: 'Headshot booking intake capturing individual vs team count, backdrop preferences (editorial gray, white, natural office), and retouch turnaround.',
    industry: 'agency',
    category: 'booking',
    color: '#0f172a',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
    badge: '📸 Magazine Cover Lighting & Expert Posing Direction',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Professional / Team Lead Name', required: true, width: 'half' },
      { id: 'company_name', type: 'short_answer', label: 'Company / Brand Name', width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'session_tier', type: 'dropdown', label: 'Headshot Session Package', required: true, width: 'half',
        options: [{ label: 'Individual Executive (30 mins / 2 Looks / 3 Retouched Images)', value: 'individual_30m' }, { label: 'Founder Personal Brand Suite (90 mins / 5 Looks / 12 Images)', value: 'founder_suite' }, { label: 'Company Team On-Site Headshot Day (10 – 50 employees)', value: 'team_day' }] },
      { id: 'backdrop_vibe', type: 'dropdown', label: 'Preferred Backdrop & Style', width: 'full',
        options: [{ label: 'Modern Studio Neutral (Charcoal / Cream / Pure White)', value: 'studio_neutral' }, { label: 'Environmental Lifestyle (Modern Architectural Office)', value: 'environmental' }, { label: 'Dramatic High-Contrast Editorial', value: 'editorial' }] },
    ],
    keywords: ['corporate headshot booking', 'executive portrait photographer', 'linkedin headshot session quote'],
  },
  {
    id: 'tankless-water-heater-conversion-quote',
    name: 'Rinnai® & Navien Tankless Water Heater Conversion Quote',
    shortDescription: 'Endless hot water, gas line sizing, space-saving wall mounts, and energy tax credit guidance.',
    description: 'Plumbing estimate intake evaluating current tank gallon size (40 vs 50 gal), gas vs electric, bathroom count, and simultaneous showers.',
    industry: 'plumbing',
    category: 'quote',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
    badge: '🔥 Endless Hot Water & Up to $1,200 Federal Tax Credit Eligible',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Homeowner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'bathroom_count', type: 'dropdown', label: 'Number of Bathrooms in Home', required: true, width: 'half',
        options: [{ label: '1 to 2 Bathrooms', value: '1_2_bath' }, { label: '2.5 to 3.5 Bathrooms', value: '3_bath' }, { label: '4+ Bathrooms (High Demand / Multiple Showers)', value: '4_plus_bath' }] },
      { id: 'current_heater_fuel', type: 'dropdown', label: 'Current Water Heater Fuel', required: true, width: 'half',
        options: [{ label: 'Natural Gas Tank', value: 'nat_gas' }, { label: 'Electric Tank Water Heater', value: 'electric' }, { label: 'Propane (LP)', value: 'propane' }] },
    ],
    keywords: ['tankless water heater quote', 'navien tankless install estimate', 'endless hot water conversion'],
  },
  {
    id: 'landscape-lighting-low-voltage-led-quote',
    name: 'Architectural LED Landscape Lighting & Tree Uplighting Quote',
    shortDescription: 'Brass fixtures, path lights, architectural facade grazing, smart smartphone zoning, and lifetime warranty.',
    description: 'Outdoor lighting intake evaluating home facade width, mature tree count, patio entertainment areas, and color temperature.',
    industry: 'landscaping',
    category: 'quote',
    color: '#eab308',
    photo: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    badge: '✨ Solid Cast Brass Fixtures • Lifetime Manufacturer Warranty',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Homeowner Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Property Address', required: true, width: 'full' },
      { id: 'lighting_scope', type: 'dropdown', label: 'Target Lighting Areas', required: true, width: 'full',
        options: [{ label: 'Front Curb Appeal (Home facade uplighting + Walkway path lights)', value: 'front_curb' }, { label: 'Backyard Resort (Patio bistro lighting + Pool area + Tree uplighting)', value: 'backyard_resort' }, { label: 'Whole Estate Comprehensive Architectural & Security Lighting Package', value: 'full_estate' }] },
      { id: 'fixture_count_est', type: 'dropdown', label: 'Estimated Fixture Count', width: 'full',
        options: [{ label: 'Starter Package (8 – 12 Solid Brass Fixtures + Transformer)', value: '8_12' }, { label: 'Medium Estate (15 – 25 Fixtures + Smart WiFi Control)', value: '15_25' }, { label: 'Large Estate (30+ Multi-Zone Fixtures)', value: '30_plus' }] },
    ],
    keywords: ['landscape lighting quote', 'outdoor low voltage led estimate', 'tree uplighting installation cost'],
  },
  {
    id: 'dog-daycare-temperament-test-booking',
    name: 'Doggy Daycare & Boarding Temperament Evaluation Booking',
    shortDescription: 'Supervised pack play, live webcams, luxury boarding suites, and behavioral assessment.',
    description: 'Pet daycare intake verifying bordetella/rabies vaccination dates, spay/neuter status, and playgroup energy matching.',
    industry: 'veterinary',
    category: 'booking',
    color: '#059669',
    photo: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1200&q=80',
    badge: '🐕 Fear-Free Certified Staff • Climate Controlled Indoor Turf Playparks',
    fields: [
      { id: 'owner_name', type: 'short_answer', label: 'Pet Parent Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Mobile Number', required: true, width: 'half' },
      { id: 'dog_name_breed', type: 'short_answer', label: 'Dog Name, Breed & Age', required: true, width: 'half' },
      { id: 'spayed_neutered', type: 'dropdown', label: 'Spayed / Neutered?', required: true, width: 'half',
        options: [{ label: 'Yes (Required for 7+ months)', value: 'yes' }, { label: 'No (Under 7 months puppy)', value: 'puppy_no' }] },
      { id: 'vaccines_current', type: 'dropdown', label: 'Are Rabies, DHPP, and Bordetella Vaccines Current?', required: true, width: 'full',
        options: [{ label: 'Yes, fully vaccinated and ready to upload vet records', value: 'yes_current' }, { label: 'Need to schedule booster with our vet first', value: 'need_booster' }] },
    ],
    keywords: ['dog daycare booking', 'dog boarding intake form', 'pet evaluation booking'],
  },
  {
    id: 'custom-car-audio-sound-system-quote',
    name: 'Custom Car Audio, Subwoofer & DSP Sound Tuning Quote',
    shortDescription: 'JL Audio, Focal, sound dampening dynamat, Apple CarPlay head units, and stealth subwoofer boxes.',
    description: 'Mobile audio intake documenting vehicle model, factory amplifier bypass, bass expectations, and audiophile DSP tuning.',
    industry: 'automotive',
    category: 'quote',
    color: '#7c3aed',
    photo: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=80',
    badge: '🔊 MECP Master Certified Mobile Audio Installers',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Client Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'vehicle_info', type: 'short_answer', label: 'Vehicle Year, Make & Model', required: true, width: 'half' },
      { id: 'audio_upgrade', type: 'dropdown', label: 'Audio Upgrade Desired', required: true, width: 'half',
        options: [{ label: 'Deep Bass Subwoofer Package (Custom Box + Monoblock Amp)', value: 'sub_package' }, { label: 'Full Audiophile Overhaul (Component Speakers + DSP + 5-Channel Amp)', value: 'full_overhaul' }, { label: 'Wireless Apple CarPlay / Android Auto Touchscreen Upgrade', value: 'carplay_screen' }] },
      { id: 'sound_dampening', type: 'dropdown', label: 'Include Sound Dampening (Kill road noise & door rattles)?', width: 'full',
        options: [{ label: 'Yes, full 4-door Dynamat soundproofing', value: 'yes_dynamat' }, { label: 'Audio equipment only', value: 'audio_only' }] },
    ],
    keywords: ['car audio installation quote', 'subwoofer install near me', 'custom sound system car'],
  },
  {
    id: 'music-recording-mixing-mastering-quote',
    name: 'Professional Recording Studio, Mixing & Dolby Atmos Mastering',
    shortDescription: 'Neumann U87 microphones, SSL 4000 console, vocal tuning, and Apple Spatial Audio mastering.',
    description: 'Music production intake recording track count, instrumentation, reference artists, and stem delivery formats.',
    industry: 'agency',
    category: 'quote',
    color: '#be185d',
    photo: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=80',
    badge: '🎚️ Multi-Platinum Audio Engineers & Dolby Atmos 7.1.4 Certified',
    fields: [
      { id: 'artist_name', type: 'short_answer', label: 'Artist / Band Name', required: true, width: 'half' },
      { id: 'contact_phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'service_needed', type: 'dropdown', label: 'Audio Service', required: true, width: 'half',
        options: [{ label: 'Single Track Full Mix & Master (Analog Outboard + Digital)', value: 'mix_master_single' }, { label: 'EP / Album Package (4 – 10 Songs)', value: 'album_package' }, { label: 'Dolby Atmos Spatial Audio Mix for Apple Music/Tidal', value: 'dolby_atmos' }, { label: 'Studio Tracking Time (Includes Sound Engineer)', value: 'tracking_hours' }] },
      { id: 'genre', type: 'short_answer', label: 'Musical Genre & Reference Artist', required: true, width: 'half' },
      { id: 'target_deadline', type: 'date', label: 'Target Release Date', width: 'full' },
    ],
    keywords: ['mixing and mastering quote', 'music recording studio hire', 'dolby atmos audio engineer'],
  },
  {
    id: 'metal-building-steel-barndominium-quote',
    name: 'Engineered Steel Building & Barndominium Construction Quote',
    shortDescription: 'Clear-span commercial steel shops, agricultural barns, and custom luxury barndominiums.',
    description: 'Pre-engineered metal building intake calculating width x length x eave height, snow load certifications, and living quarters.',
    industry: 'construction',
    category: 'quote',
    color: '#0f172a',
    photo: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1200&q=80',
    badge: '🏗️ Commercial-Grade 100% US Red Iron Steel Buildings',
    fields: [
      { id: 'client_name', type: 'short_answer', label: 'Client Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'jobsite_address', type: 'address', label: 'Build Site Address', required: true, width: 'full' },
      { id: 'building_use', type: 'dropdown', label: 'Building Use Type', required: true, width: 'half',
        options: [{ label: 'Custom Luxury Barndominium (Living Quarters + Shop)', value: 'barndominium' }, { label: 'Commercial Warehouse / Workshop (30x50 / 40x60)', value: 'commercial_shop' }, { label: 'Agricultural Equipment Barn / Riding Arena', value: 'agricultural' }, { label: 'Auto Storage / Hobby Garage', value: 'hobby_garage' }] },
      { id: 'building_dimensions', type: 'dropdown', label: 'Estimated Building Size', required: true, width: 'half',
        options: [{ label: '30 ft x 40 ft (1,200 sq ft)', value: '30x40' }, { label: '40 ft x 60 ft (2,400 sq ft)', value: '40x60' }, { label: '50 ft x 100 ft (5,000 sq ft)', value: '50x100' }, { label: 'Custom Large Dimension (6,000+ sq ft)', value: 'custom_large' }] },
    ],
    keywords: ['steel building quote', 'barndominium builder estimate', 'metal workshop construction cost'],
  },
];

export function registerMasterSuite200Templates(): void {
  for (const item of MASTER_SUITE_DATA) {
    const template: FormTemplate = {
      id: item.id,
      name: item.name,
      shortDescription: item.shortDescription,
      description: item.description,
      schema: {
        version: 1,
        steps: [{ id: 'step-1', title: 'Intake Details' }],
        fields: item.fields,
        rules: [],
        theme: {
          primaryColor: item.color,
          backgroundColor: '#ffffff',
          textColor: '#0f172a',
          borderRadius: '1rem',
          inputBorderRadius: '0.75rem',
          inputHeight: 'large',
          cardBackground: 'rgba(255, 255, 255, 0.98)',
          showTopBorder: true,
          layout: 'split_media',
          mediaPanel: {
            enabled: true,
            position: 'left',
            splitRatio: '40-60',
            mediaType: 'image',
            mediaUrl: item.photo,
            badgeText: item.badge || '⭐ Premier Verified Specialist • 2026 Pro',
            headline: item.name,
            subtitle: item.shortDescription,
            benefitsList: [
              'Zero hidden fees with upfront transparent pricing',
              'Direct online consultation scheduling with instant confirmation',
              'Strict 256-bit encryption & complete client privacy',
            ],
            mobileBehavior: 'stack_top',
          },
        },
        settings: {
          submitButtonText: 'Submit & Get Instant Quote ⚡',
          successTitle: 'Submission Confirmed!',
          successMessage: 'Our lead specialist is reviewing your request and will reach out promptly.',
          actions: {
            sendEmailNotification: { enabled: true, toEmails: [] },
            createCrmLead: { enabled: true, source: `master_suite_${item.id}` },
          },
        },
      },
      categories: [item.category as any, 'quote', 'booking', 'intake', 'application'],
      industries: [item.industry as any, 'professional_services', 'home_services'],
      useCases: ['lead_capture', 'quote_request', 'appointment_booking'],
      audiences: ['residential', 'commercial', 'b2b'],
      tags: [item.industry, 'curated', 'canonical', '2026-ui'],
      fieldTypes: item.fields.map((f) => f.type),
      source: 'curated',
      status: 'published',
      isFeatured: true,
      isPublic: true,
      rating: 4.98,
      ratingCount: 110,
      usageCount: 1750,
      estimatedMinutes: 2,
      seo: {
        seoTitle: `${item.name} | Verified Online Intake & Quote`,
        seoDescription: `${item.shortDescription} 2026 responsive split-hero form.`,
        seoKeywords: item.keywords,
        faq: [
          {
            question: `How fast will I hear back from your team?`,
            answer: 'All submissions are acknowledged within 15 minutes during standard business hours.',
          },
        ],
      },
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-09-19T00:00:00Z',
    };

    registerTemplate(template);
  }
}

// Auto-register
registerMasterSuite200Templates();
