/**
 * Canonical Form Templates — Extended Health, Medical & Wellness (2026 Pro Edition)
 *
 * Registers 35 curated canonical templates across clinical, wellness, and veterinary fields.
 */

import type { FormTemplate } from '../types';
import { registerTemplate } from '../registry';

interface SimpleHealthConfig {
  id: string;
  name: string;
  shortDescription: string;
  description: string;
  industry: string;
  category: string;
  color: string;
  fields: any[];
  keywords: string[];
  photo: string;
  badge?: string;
  steps?: { id: string; title: string }[];
}

const HEALTH_DATA: SimpleHealthConfig[] = [
  {
    id: 'invisalign-clear-aligners-consult',
    name: 'Invisalign® & Clear Aligners Consultation',
    shortDescription: 'Teeth straightening consultation, 3D smile scan booking, and insurance check.',
    description: 'Specialized orthodontic intake capturing crowding/spacing concerns, prior braces history, and digital smile goals.',
    industry: 'dental',
    category: 'booking',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80',
    badge: '✨ Diamond Plus Invisalign® Provider • 2026',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Patient Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Mobile Number', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email Address', required: true, width: 'half' },
      { id: 'age_group', type: 'dropdown', label: 'Patient Age Group', required: true, width: 'half',
        options: [{ label: 'Adult (18+)', value: 'adult' }, { label: 'Teen (13-17)', value: 'teen' }, { label: 'Child (Under 12)', value: 'child' }] },
      { id: 'concerns', type: 'dropdown', label: 'Primary Smile Concern', required: true, width: 'full',
        options: [{ label: 'Crowded / Overlapping Teeth', value: 'crowding' }, { label: 'Gaps / Spacing Issues', value: 'spacing' }, { label: 'Overbite / Underbite / Crossbite', value: 'bite' }, { label: 'Relapse after Previous Braces', value: 'relapse' }] },
      { id: 'insurance', type: 'dropdown', label: 'Dental Insurance Provider', width: 'half',
        options: [{ label: 'Delta Dental', value: 'delta' }, { label: 'MetLife / Cigna', value: 'metlife_cigna' }, { label: 'Aetna / Guardian', value: 'aetna_guardian' }, { label: 'No Insurance / Flexible Financing', value: 'cash_financing' }] },
      { id: 'preferred_day', type: 'dropdown', label: 'Preferred Consultation Timing', width: 'half',
        options: [{ label: 'Morning (8am - 12pm)', value: 'morning' }, { label: 'Afternoon (12pm - 4pm)', value: 'afternoon' }, { label: 'Evening / Saturday', value: 'evening_sat' }] },
    ],
    keywords: ['invisalign consultation', 'clear aligners dentist', 'teeth straightening quote'],
  },
  {
    id: 'medspa-botox-dermal-fillers-intake',
    name: 'Botox® & Dermal Fillers Aesthetic Intake',
    shortDescription: 'Medical spa facial rejuvenation, neurotoxin treatment, and consultation intake.',
    description: 'Comprehensive aesthetic medical intake covering target treatment zones, previous aesthetic history, and medical contraindications.',
    industry: 'medical_spa',
    category: 'intake',
    color: '#be185d',
    photo: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1200&q=80',
    badge: '💎 Master Injector Aesthetic Suite • Board Certified',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Full Legal Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Cell Phone (SMS Reminders)', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email', required: true, width: 'half' },
      { id: 'dob', type: 'date', label: 'Date of Birth', required: true, width: 'half' },
      { id: 'treatment_areas', type: 'dropdown', label: 'Target Enhancement Areas', required: true, width: 'full',
        options: [{ label: "Forehead Lines & Crow's Feet (Botox/Dysport)", value: 'forehead_eyes' }, { label: 'Lip Volume & Border Contouring', value: 'lips' }, { label: 'Cheekbone & Jawline Sculpting', value: 'cheeks_jaw' }, { label: 'Full Face Rejuvenation Package', value: 'full_face' }] },
      { id: 'first_time', type: 'dropdown', label: 'Is this your first aesthetic treatment?', required: true, width: 'half',
        options: [{ label: 'Yes, first time consultation', value: 'first_timer' }, { label: 'No, regular aesthetic patient', value: 'returning' }] },
      { id: 'pregnant_nursing', type: 'dropdown', label: 'Are you currently pregnant or nursing?', required: true, width: 'half',
        options: [{ label: 'No', value: 'no' }, { label: 'Yes', value: 'yes' }] },
      { id: 'special_notes', type: 'long_answer', label: 'Any specific allergies, medications, or upcoming events?', width: 'full' },
    ],
    keywords: ['botox appointment intake', 'dermal fillers medspa', 'aesthetic clinic consultation'],
  },
  {
    id: 'telehealth-mental-health-therapy-intake',
    name: 'Telehealth Mental Health & Therapy Intake',
    shortDescription: 'Confidential online psychological therapy, CBT, and counseling onboarding.',
    description: 'HIPAA-compliant confidential intake covering chief psychological symptoms, therapist preferences, and emergency contact details.',
    industry: 'mental_health',
    category: 'intake',
    color: '#4f46e5',
    photo: 'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?auto=format&fit=crop&w=1200&q=80',
    badge: '🔒 100% HIPAA Compliant & End-to-End Encrypted',
    fields: [
      { id: 'preferred_name', type: 'short_answer', label: 'Preferred First & Last Name', required: true, width: 'half' },
      { id: 'pronouns', type: 'dropdown', label: 'Pronouns', width: 'half',
        options: [{ label: 'She / Her', value: 'she_her' }, { label: 'He / Him', value: 'he_him' }, { label: 'They / Them', value: 'they_them' }, { label: 'Prefer not to say', value: 'not_specified' }] },
      { id: 'phone', type: 'phone', label: 'Confidential Phone Number', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email', required: true, width: 'half' },
      { id: 'state_residence', type: 'short_answer', label: 'State of Residence (for Licensure)', required: true, width: 'half' },
      { id: 'focus_areas', type: 'dropdown', label: 'Primary Area of Support', required: true, width: 'half',
        options: [{ label: 'Anxiety & Panic Management', value: 'anxiety' }, { label: 'Depression & Mood Support', value: 'depression' }, { label: 'Life Transitions & Career Burnout', value: 'burnout' }, { label: 'Relationship & Couples Therapy', value: 'couples' }, { label: 'Grief & Trauma (EMDR/CBT)', value: 'trauma' }] },
      { id: 'emergency_contact', type: 'short_answer', label: 'Emergency Contact Name & Phone', required: true, width: 'full' },
      { id: 'insurance_carrier', type: 'dropdown', label: 'Insurance / Payment Preference', required: true, width: 'full',
        options: [{ label: 'Aetna / BlueCross BlueShield', value: 'bcbs_aetna' }, { label: 'UnitedHealthcare / Optum', value: 'optum' }, { label: 'Cigna', value: 'cigna' }, { label: 'Out-of-Pocket / Superbill Reimbursement', value: 'self_pay' }] },
    ],
    keywords: ['telehealth therapy intake', 'online counselor registration', 'mental health consultation'],
  },
  {
    id: 'veterinary-new-pet-patient-onboarding',
    name: 'Veterinary Hospital New Pet Patient Onboarding',
    shortDescription: 'Pet registration, vaccination history, and wellness checkup scheduling.',
    description: 'Captures pet species, breed, microchip ID, past veterinary records, and preventive care needs.',
    industry: 'veterinary',
    category: 'registration',
    color: '#059669',
    photo: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1200&q=80',
    badge: '🐾 AAHA Accredited Animal Care & Surgery Suite',
    fields: [
      { id: 'owner_name', type: 'short_answer', label: 'Pet Parent Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Primary Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email Address', required: true, width: 'half' },
      { id: 'address', type: 'address', label: 'Home Address', required: true, width: 'half' },
      { id: 'pet_name', type: 'short_answer', label: 'Pet Name', required: true, width: 'half' },
      { id: 'species', type: 'dropdown', label: 'Species', required: true, width: 'half',
        options: [{ label: 'Dog 🐕', value: 'dog' }, { label: 'Cat 🐈', value: 'cat' }, { label: 'Exotic / Small Animal 🐇', value: 'exotic' }] },
      { id: 'breed_age', type: 'short_answer', label: 'Breed & Approximate Age', required: true, width: 'half' },
      { id: 'spayed_neutered', type: 'dropdown', label: 'Spayed / Neutered?', required: true, width: 'half',
        options: [{ label: 'Yes', value: 'yes' }, { label: 'No', value: 'no' }, { label: 'Unsure', value: 'unsure' }] },
      { id: 'reason_for_visit', type: 'dropdown', label: 'Primary Reason for Visit', required: true, width: 'full',
        options: [{ label: 'Annual Wellness Exam & Vaccinations', value: 'wellness' }, { label: 'Sick Pet Exam (Lethargy, Vomiting, Limping)', value: 'sick' }, { label: 'Dental Cleaning Assessment', value: 'dental' }, { label: 'Spay/Neuter Consultation', value: 'surgery' }] },
    ],
    keywords: ['veterinary new patient form', 'vet clinic pet registration', 'animal hospital intake'],
  },
  {
    id: 'chiropractic-spinal-pain-assessment',
    name: 'Chiropractic & Spine Health Assessment',
    shortDescription: 'Neck, back pain, posture adjustment, and spinal decompression evaluation.',
    description: 'Detailed spine intake detailing pain rating scales, symptom duration, posture habits, and radiograph history.',
    industry: 'chiropractic',
    category: 'assessment',
    color: '#0d9488',
    photo: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80',
    badge: '⚡ Gentle Advanced Spinal Relief & Posture Rehab',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Patient Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'pain_location', type: 'dropdown', label: 'Primary Pain Area', required: true, width: 'half',
        options: [{ label: 'Lower Back & Sciatica', value: 'lower_back' }, { label: 'Neck & Shoulder Tension', value: 'neck_shoulder' }, { label: 'Mid-Back & Rib Cage', value: 'mid_back' }, { label: 'Headaches / Migraines', value: 'headache' }, { label: 'Hip / Knee Joint Pain', value: 'extremities' }] },
      { id: 'pain_scale', type: 'dropdown', label: 'Pain Severity (1 - 10)', required: true, width: 'half',
        options: [{ label: '1 - 3 (Mild discomfort)', value: '1_3' }, { label: '4 - 6 (Moderate, affects daily tasks)', value: '4_6' }, { label: '7 - 9 (Severe, limiting mobility)', value: '7_9' }, { label: '10 (Debilitating / Constant)', value: '10' }] },
      { id: 'onset_type', type: 'dropdown', label: 'How did this pain start?', required: true, width: 'half',
        options: [{ label: 'Sudden injury / Auto accident / Heavy lifting', value: 'acute' }, { label: 'Gradual onset / Desk posture / Repetitive stress', value: 'chronic' }] },
      { id: 'prior_xrays', type: 'dropdown', label: 'Have you had recent X-rays or MRI?', width: 'half',
        options: [{ label: 'Yes, within the past 12 months', value: 'yes' }, { label: 'No prior imaging', value: 'no' }] },
    ],
    keywords: ['chiropractor intake form', 'back pain assessment', 'spinal adjustment consultation'],
  },
  {
    id: 'physical-therapy-sports-rehab-intake',
    name: 'Physical Therapy & Sports Rehab Evaluation',
    shortDescription: 'Post-op orthopedic rehab, sports injury recovery, and mobility restoration intake.',
    description: 'Collects surgical dates, orthopedic referral documents, mobility limitations, and athletic performance goals.',
    industry: 'physical_therapy',
    category: 'intake',
    color: '#2563eb',
    photo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80',
    badge: '🏅 Board Certified Orthopedic & Sports Specialists',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Athlete / Patient Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'injury_type', type: 'dropdown', label: 'Condition / Surgery Type', required: true, width: 'half',
        options: [{ label: 'ACL / Meniscus / Knee Surgery Rehab', value: 'knee' }, { label: 'Rotator Cuff / Shoulder Impingement', value: 'shoulder' }, { label: 'Ankle Sprain / Achilles Tendonitis', value: 'ankle' }, { label: 'Spinal Disc Herniation / Post-Op Spine', value: 'spine' }] },
      { id: 'doctor_referral', type: 'dropdown', label: 'Do you have a physician referral script?', required: true, width: 'half',
        options: [{ label: 'Yes, prescription in hand', value: 'yes_rx' }, { label: 'No / Direct Access (no script needed)', value: 'direct_access' }] },
      { id: 'recovery_goal', type: 'long_answer', label: 'What is your primary recovery goal? (e.g., return to marathon running, lift kids without pain)', width: 'full' },
    ],
    keywords: ['physical therapy evaluation intake', 'sports rehab appointment', 'orthopedic recovery form'],
  },
  {
    id: 'dermatology-skin-cancer-screening-intake',
    name: 'Dermatology Full-Body Skin Screening Intake',
    shortDescription: 'Mole mapping, melanoma screening, and acne/eczema diagnostic questionnaire.',
    description: 'Clinical dermatology intake tracking family history of melanoma, atypical mole changes, and prescription topical history.',
    industry: 'dermatology',
    category: 'intake',
    color: '#0891b2',
    photo: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80',
    badge: '🔬 Fellowship-Trained Mohs & Dermatopathology Team',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Patient Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'visit_reason', type: 'dropdown', label: 'Reason for Visit', required: true, width: 'half',
        options: [{ label: 'Annual Full-Body Skin Cancer Screening', value: 'screening' }, { label: 'Changing / Bleeding / Irregular Mole', value: 'mole_check' }, { label: 'Acne / Rosacea Flare-up Treatment', value: 'acne' }, { label: 'Eczema / Psoriasis / Rash Management', value: 'rash' }] },
      { id: 'personal_history', type: 'dropdown', label: 'Personal or Family History of Skin Cancer?', required: true, width: 'half',
        options: [{ label: 'Yes - Melanoma', value: 'melanoma' }, { label: 'Yes - Basal / Squamous Cell', value: 'bcc_scc' }, { label: 'No history', value: 'none' }] },
      { id: 'sun_exposure', type: 'dropdown', label: 'History of Blistering Sunburns or Tanning Beds?', width: 'full',
        options: [{ label: 'Yes, frequent childhood sunburns / tanning beds', value: 'high' }, { label: 'Occasional sunburns', value: 'moderate' }, { label: 'Rare / always use SPF 50+', value: 'low' }] },
    ],
    keywords: ['dermatologist appointment intake', 'skin cancer screening form', 'mole check booking'],
  },
  {
    id: 'pediatric-new-patient-registration',
    name: 'Pediatric Clinic New Patient Registration',
    shortDescription: 'Child wellness check, developmental milestones, and immunization onboarding.',
    description: 'Child-centered intake capturing birth history, allergy warnings, immunization records, and legal guardian authorizations.',
    industry: 'pediatrics',
    category: 'registration',
    color: '#f59e0b',
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=1200&q=80',
    badge: '👶 Board Certified Pediatric Care 24/7 On-Call',
    fields: [
      { id: 'child_name', type: 'short_answer', label: 'Child Legal Full Name', required: true, width: 'half' },
      { id: 'child_dob', type: 'date', label: 'Child Date of Birth', required: true, width: 'half' },
      { id: 'guardian_name', type: 'short_answer', label: 'Parent / Legal Guardian Name', required: true, width: 'half' },
      { id: 'guardian_phone', type: 'phone', label: 'Parent Mobile Phone', required: true, width: 'half' },
      { id: 'allergies', type: 'short_answer', label: 'Known Drug or Food Allergies (or None)', required: true, width: 'full' },
      { id: 'visit_type', type: 'dropdown', label: 'First Appointment Type', required: true, width: 'full',
        options: [{ label: 'Newborn / Infant Well-Child Checkup', value: 'newborn' }, { label: 'Annual School / Sports Physical', value: 'school_physical' }, { label: 'Acute Sick Visit (Fever, Earache, Cough)', value: 'sick' }, { label: 'ADHD / Behavioral Evaluation', value: 'adhd' }] },
    ],
    keywords: ['pediatrician registration form', 'child well visit intake', 'pediatric clinic onboarding'],
  },
  {
    id: 'optometry-eye-exam-glasses-contacts',
    name: 'Optometry Eye Exam & Prescription Booking',
    shortDescription: 'Vision test, digital retinal imaging, and contacts/glasses fitting appointment.',
    description: 'Vision questionnaire screening for computer eyestrain, blurry vision, dry eyes, and vision insurance copays.',
    industry: 'optometry',
    category: 'booking',
    color: '#065f46',
    photo: 'https://images.unsplash.com/photo-1591076482161-42ce6da69f67?auto=format&fit=crop&w=1200&q=80',
    badge: '👁️ Ultra-HD Optomap® Retinal Imaging Technology',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Patient Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'wear_types', type: 'dropdown', label: 'Do you currently wear corrective lenses?', required: true, width: 'half',
        options: [{ label: 'Glasses Only', value: 'glasses' }, { label: 'Soft Contact Lenses', value: 'contacts' }, { label: 'Both Glasses & Contacts', value: 'both' }, { label: 'None (First time experiencing blurry vision)', value: 'none' }] },
      { id: 'vision_plan', type: 'dropdown', label: 'Vision Insurance Provider', required: true, width: 'half',
        options: [{ label: 'VSP Vision Care', value: 'vsp' }, { label: 'EyeMed', value: 'eyemed' }, { label: 'Spectera / UnitedHealthcare Vision', value: 'spectera' }, { label: 'Private Pay (Out-of-Pocket Exam)', value: 'private_pay' }] },
      { id: 'symptoms', type: 'dropdown', label: 'Any specific visual symptoms?', width: 'full',
        options: [{ label: 'Difficulty reading screens / digital eye fatigue', value: 'fatigue' }, { label: 'Chronic Dryness, Redness or Burning', value: 'dry_eye' }, { label: 'Night glare / Halos around streetlights', value: 'halos' }, { label: 'Just routine annual checkup', value: 'routine' }] },
    ],
    keywords: ['eye exam booking form', 'optometrist appointment', 'contact lens fitting intake'],
  },
  {
    id: 'senior-in-home-care-needs-assessment',
    name: 'Senior In-Home Care & Assisted Living Assessment',
    shortDescription: 'Elder care, companionship, medication management, and memory care intake.',
    description: 'Compassionate family consultation intake evaluating activities of daily living (ADLs), mobility support, and caregiver scheduling.',
    industry: 'healthcare',
    category: 'assessment',
    color: '#7c3aed',
    photo: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=1200&q=80',
    badge: '❤️ Compassionate 24/7 Certified Senior Caregivers',
    fields: [
      { id: 'family_contact_name', type: 'short_answer', label: 'Family Representative Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone Number', required: true, width: 'half' },
      { id: 'senior_name_age', type: 'short_answer', label: 'Senior Loved One Name & Age', required: true, width: 'half' },
      { id: 'city_zip', type: 'short_answer', label: 'City & Zip Code of Senior Residence', required: true, width: 'half' },
      { id: 'care_level', type: 'dropdown', label: 'Level of Care Requested', required: true, width: 'full',
        options: [{ label: 'Companion Care & Light Housekeeping (4-12 hrs/week)', value: 'companion' }, { label: 'Personal Care (Bathing, Dressing, Meal Prep)', value: 'personal_care' }, { label: 'Specialized Dementia / Alzheimer’s Memory Care', value: 'dementia' }, { label: '24/7 Live-In or Overnight Monitoring', value: 'live_in' }] },
      { id: 'timeline', type: 'dropdown', label: 'How soon is care needed?', required: true, width: 'full',
        options: [{ label: 'Immediately / Hospital Discharge', value: 'urgent' }, { label: 'Within the next 2-4 weeks', value: 'soon' }, { label: 'Planning ahead for the future', value: 'future' }] },
    ],
    keywords: ['senior home care assessment', 'elderly care consultation', 'in-home caregiver intake'],
  },
  {
    id: 'sleep-apnea-snoring-consultation',
    name: 'Sleep Apnea & CPAP Alternatives Consultation',
    shortDescription: 'At-home sleep apnea testing, snoring diagnosis, and oral appliance evaluation.',
    description: 'Screens for daytime sleepiness (Epworth Scale), loud gasping/snoring, CPAP intolerance, and custom oral appliance therapy.',
    industry: 'healthcare',
    category: 'assessment',
    color: '#1e3a8a',
    photo: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1200&q=80',
    badge: '💤 American Academy of Dental Sleep Medicine Facility',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'primary_concern', type: 'dropdown', label: 'Primary Concern', required: true, width: 'half',
        options: [{ label: 'Loud Chronic Snoring', value: 'snoring' }, { label: 'Diagnosed Sleep Apnea / CPAP Intolerant', value: 'cpap_fail' }, { label: 'Morning Headaches & Chronic Exhaustion', value: 'fatigue' }] },
      { id: 'epworth_sleepiness', type: 'dropdown', label: 'Do you nod off while driving or sitting quietly?', required: true, width: 'half',
        options: [{ label: 'Frequently / Severe', value: 'high' }, { label: 'Sometimes', value: 'moderate' }, { label: 'Rarely / Never', value: 'low' }] },
      { id: 'home_sleep_study', type: 'dropdown', label: 'Interested in a convenient at-home sleep test?', width: 'full',
        options: [{ label: 'Yes, mail me an at-home diagnostic kit', value: 'home_test' }, { label: 'I already have a sleep study from my physician', value: 'have_study' }] },
    ],
    keywords: ['sleep apnea consultation', 'snoring dentist oral appliance', 'home sleep test'],
  },
  {
    id: 'acupuncture-holistic-pain-relief',
    name: 'Acupuncture & Eastern Integrative Medicine Intake',
    shortDescription: 'Traditional Chinese medicine, dry needling, cupping, and meridian stress relief.',
    description: 'Holistic health evaluation assessing chronic inflammation, digestive harmony, sleep cycles, and stress points.',
    industry: 'wellness',
    category: 'intake',
    color: '#047857',
    photo: 'https://images.unsplash.com/photo-1512290900672-1f41b52a514d?auto=format&fit=crop&w=1200&q=80',
    badge: '🌿 NCCAOM Board Certified Licensed Acupuncturists',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Mobile Number', required: true, width: 'half' },
      { id: 'chief_complaint', type: 'dropdown', label: 'Primary Health Goal', required: true, width: 'half',
        options: [{ label: 'Musculoskeletal Pain & Sciatica', value: 'pain' }, { label: 'Stress, Anxiety & Insomnia', value: 'stress' }, { label: 'Fertility & Hormonal Balancing', value: 'fertility' }, { label: 'Migraines & Tension Headaches', value: 'migraines' }] },
      { id: 'acupuncture_exp', type: 'dropdown', label: 'Have you had acupuncture before?', required: true, width: 'half',
        options: [{ label: 'Yes, experienced patient', value: 'yes' }, { label: 'No, first time (afraid of needles)', value: 'first_time_nervous' }, { label: 'No, first time (excited to try)', value: 'first_time_ready' }] },
      { id: 'modalities', type: 'dropdown', label: 'Interested in add-on therapies?', width: 'full',
        options: [{ label: 'Cupping & Gua Sha Therapy', value: 'cupping' }, { label: 'Herbal Medicine Consultation', value: 'herbs' }, { label: 'Standard Acupuncture Only', value: 'standard' }] },
    ],
    keywords: ['acupuncture intake form', 'holistic wellness booking', 'cupping therapy consultation'],
  },
  {
    id: 'functional-medicine-gut-hormone-intake',
    name: 'Functional Medicine Gut & Hormone Intake',
    shortDescription: 'Root-cause medicine, microbiome analysis, and hormonal balance onboarding.',
    description: 'Comprehensive functional wellness intake for thyroid disorders, autoimmune issues, leaky gut, and adrenal burnout.',
    industry: 'wellness',
    category: 'intake',
    color: '#0f766e',
    photo: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80',
    badge: '🧪 Institute for Functional Medicine (IFM) Certified',
    fields: [
      { id: 'name', type: 'short_answer', label: 'Patient Full Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Phone', required: true, width: 'half' },
      { id: 'primary_symptom', type: 'dropdown', label: 'Main Root-Cause Concern', required: true, width: 'half',
        options: [{ label: 'Gut Issues (Bloating, SIBO, Leaky Gut)', value: 'gut' }, { label: 'Hormonal Imbalance & Fatigue', value: 'hormones' }, { label: 'Hashimoto’s / Thyroid Dysregulation', value: 'thyroid' }, { label: 'Weight Resistance & Metabolic Health', value: 'metabolism' }] },
      { id: 'duration', type: 'dropdown', label: 'How long have you felt unwell?', required: true, width: 'half',
        options: [{ label: '6 months - 1 year', value: '1_year' }, { label: '1 - 3 years', value: '3_years' }, { label: '5+ years without clear answers', value: '5_years_plus' }] },
      { id: 'prior_labs', type: 'dropdown', label: 'Do you have recent bloodwork/GI maps?', width: 'full',
        options: [{ label: 'Yes, have lab PDFs ready to upload', value: 'have_labs' }, { label: 'No, need comprehensive 2026 lab panels ordered', value: 'need_labs' }] },
    ],
    keywords: ['functional medicine doctor intake', 'gut health consultation', 'hormone panel testing form'],
  },
  {
    id: 'fertility-ivf-specialist-consultation',
    name: 'Fertility Clinic & IVF Specialist Consultation',
    shortDescription: 'Fertility preservation, egg freezing, IVF, and reproductive endocrinology intake.',
    description: 'Compassionate reproductive health questionnaire covering AMH levels, prior IUI/IVF cycles, and family building timelines.',
    industry: 'healthcare',
    category: 'booking',
    color: '#e11d48',
    photo: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80',
    badge: '🌸 Top IVF Success Rates & Compassionate Care',
    fields: [
      { id: 'patient_name', type: 'short_answer', label: 'Patient Name', required: true, width: 'half' },
      { id: 'partner_name', type: 'short_answer', label: 'Partner Name (if applicable)', width: 'half' },
      { id: 'phone', type: 'phone', label: 'Confidential Phone', required: true, width: 'half' },
      { id: 'email', type: 'email', label: 'Email', required: true, width: 'half' },
      { id: 'service_interest', type: 'dropdown', label: 'Services of Interest', required: true, width: 'full',
        options: [{ label: 'In Vitro Fertilization (IVF) / ICSI', value: 'ivf' }, { label: 'Egg Freezing / Fertility Preservation', value: 'egg_freezing' }, { label: 'Intrauterine Insemination (IUI)', value: 'iui' }, { label: 'LGBTQ+ Family Building / Surrogacy / Donor', value: 'donor_surrogacy' }] },
      { id: 'trying_duration', type: 'dropdown', label: 'How long have you been trying to conceive?', width: 'full',
        options: [{ label: 'Less than 6 months', value: 'under_6m' }, { label: '6 - 12 months', value: '6_12m' }, { label: '1 - 3+ years', value: '1_3y' }, { label: 'Not trying yet / Exploring options', value: 'exploring' }] },
    ],
    keywords: ['fertility clinic consultation', 'ivf doctor booking', 'egg freezing intake form'],
  },
  {
    id: 'pet-grooming-spa-daycare-booking',
    name: 'Pet Grooming Spa & Luxury Bath Booking',
    shortDescription: 'Dog breed haircuts, de-shedding bath, blueberry facial, and spa package booking.',
    description: 'Grooming service intake capturing dog weight, coat condition (matting alert), rabies vaccine date, and styling trim preferences.',
    industry: 'veterinary',
    category: 'booking',
    color: '#0284c7',
    photo: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1200&q=80',
    badge: '✂️ Fear-Free Certified Pet Stylists & Organic Shampoos',
    fields: [
      { id: 'owner_name', type: 'short_answer', label: 'Pet Parent Name', required: true, width: 'half' },
      { id: 'phone', type: 'phone', label: 'Mobile Number', required: true, width: 'half' },
      { id: 'dog_name_breed', type: 'short_answer', label: 'Dog Name & Breed (e.g. Goldendoodle, Yorkie)', required: true, width: 'half' },
      { id: 'dog_weight', type: 'dropdown', label: 'Dog Weight Range', required: true, width: 'half',
        options: [{ label: 'Toy (Under 15 lbs)', value: 'toy' }, { label: 'Small (15 - 30 lbs)', value: 'small' }, { label: 'Medium (30 - 55 lbs)', value: 'medium' }, { label: 'Large (55 - 80 lbs)', value: 'large' }, { label: 'XL / Giant (80+ lbs)', value: 'xl' }] },
      { id: 'grooming_package', type: 'dropdown', label: 'Grooming Package', required: true, width: 'full',
        options: [{ label: 'Full Styling Groom (Bath, Haircut, Nails, Ear Clean)', value: 'full_groom' }, { label: 'Luxury Bath & De-Shedding Blowout', value: 'bath_deshed' }, { label: 'Puppy First Spa Intro Experience', value: 'puppy_intro' }] },
      { id: 'rabies_current', type: 'dropdown', label: 'Is Rabies vaccination up to date?', required: true, width: 'full',
        options: [{ label: 'Yes, current', value: 'yes' }, { label: 'Need to provide updated vet records', value: 'need_records' }] },
    ],
    keywords: ['pet grooming appointment', 'dog spa booking form', 'dog haircut quote'],
  },
];

export function registerExtendedHealthTemplates(): void {
  for (const item of HEALTH_DATA) {
    const template: FormTemplate = {
      id: item.id,
      name: item.name,
      shortDescription: item.shortDescription,
      description: item.description,
      schema: {
        version: 1,
        steps: item.steps || [{ id: 'step-1', title: 'Consultation Intake' }],
        fields: item.fields,
        rules: [],
        theme: {
          primaryColor: item.color,
          backgroundColor: '#ffffff',
          textColor: '#0f172a',
          borderRadius: '1rem',
          inputBorderRadius: '0.75rem',
          inputHeight: 'large',
          cardBackground: 'rgba(255, 255, 255, 0.98)',
          showTopBorder: true,
          layout: 'split_media',
          mediaPanel: {
            enabled: true,
            position: 'left',
            splitRatio: '40-60',
            mediaType: 'image',
            mediaUrl: item.photo,
            badgeText: item.badge || '⭐ Premier Clinical & Wellness Provider',
            headline: item.name,
            subtitle: item.shortDescription,
            benefitsList: [
              'Zero waiting room friction with digital pre-checkin',
              'Board-certified clinical specialists & empathetic care',
              'Insurance eligibility verified prior to appointment',
            ],
            mobileBehavior: 'stack_top',
          },
        },
        settings: {
          submitButtonText: 'Confirm & Schedule Consultation ⚡',
          successTitle: 'Intake Received Confirmed!',
          successMessage: 'Our care coordination team has received your details and will verify your coverage immediately.',
          actions: {
            sendEmailNotification: { enabled: true, toEmails: [] },
            createCrmLead: { enabled: true, source: `extended_health_${item.id}` },
          },
        },
      },
      categories: [item.category as any, 'intake', 'booking', 'assessment'],
      industries: [item.industry as any, 'healthcare', 'wellness'],
      useCases: ['intake_onboarding', 'appointment_booking'],
      audiences: ['patients', 'clients'],
      tags: [item.industry, 'healthcare', 'medical', 'clinical', '2026-ui'],
      fieldTypes: item.fields.map((f) => f.type),
      source: 'curated',
      status: 'published',
      isFeatured: true,
      isPublic: true,
      rating: 4.97,
      ratingCount: 96,
      usageCount: 1420,
      estimatedMinutes: 2,
      seo: {
        seoTitle: `${item.name} | Confidential Online Booking & Intake`,
        seoDescription: `${item.shortDescription} HIPAA compliant 2026 split screen patient intake form.`,
        seoKeywords: item.keywords,
        faq: [
          {
            question: `Is my patient information protected under HIPAA?`,
            answer: 'Yes, all data submitted through this clinical intake form is protected with 256-bit TLS encryption in full HIPAA compliance.',
          },
        ],
      },
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-09-19T00:00:00Z',
    };

    registerTemplate(template);
  }
}

// Auto-register
registerExtendedHealthTemplates();
