/**
 * Canonical Inspection, Audit & Checklist Form Templates (Jotform Parity)
 */

import { registerTemplates } from '../registry';
import type { FormTemplate } from '../types';

export const INSPECTION_CHECKLIST_TEMPLATES: FormTemplate[] = [
  {
    id: 'automotive-vehicle-multi-point-inspection',
    name: 'Automotive Multi-Point Vehicle Inspection Form',
    shortDescription: 'Comprehensive automotive multi-point checklist with brakes, tires, fluids, battery, and technician sign-off.',
    description: 'Ensure vehicle roadworthiness and generate transparent repair recommendations for auto shops and dealership service centers.',
    schema: {
      id: 'automotive-vehicle-multi-point-inspection',
      title: 'Vehicle Multi-Point Safety Inspection',
      description: 'Certified technician inspection checklist.',
      fields: [
        { id: 'inspector_name', type: 'text', label: 'Technician / Inspector Name', required: true },
        { id: 'inspection_date', type: 'date', label: 'Date of Inspection', required: true },
        { id: 'customer_name', type: 'text', label: 'Customer Name', required: true },
        { id: 'vehicle_info', type: 'text', label: 'Vehicle Year, Make, Model & VIN', required: true },
        { id: 'current_odometer', type: 'number', label: 'Odometer Mileage', required: true },
        {
          id: 'brake_condition',
          type: 'radio',
          label: 'Front & Rear Brake Pads / Rotors',
          options: [
            { label: '🟢 Good (≥ 6mm remaining)', value: 'good' },
            { label: '🟡 May Require Future Attention (4–5mm)', value: 'fair' },
            { label: '🔴 Requires Immediate Replacement (≤ 3mm)', value: 'critical' },
          ],
          required: true,
        },
        {
          id: 'tire_tread_depth',
          type: 'radio',
          label: 'Tire Tread & Pressure Condition',
          options: [
            { label: '🟢 Good (≥ 5/32" tread, even wear)', value: 'good' },
            { label: '🟡 Fair (3/32"–4/32", rotation recommended)', value: 'fair' },
            { label: '🔴 Poor / Danger (≤ 2/32" or uneven cord wear)', value: 'critical' },
          ],
          required: true,
        },
        {
          id: 'fluid_levels',
          type: 'checkbox',
          label: 'Fluids Requiring Top-off / Flush',
          options: [
            { label: 'Engine Oil & Filter', value: 'oil' },
            { label: 'Brake Fluid', value: 'brake' },
            { label: 'Engine Coolant / Antifreeze', value: 'coolant' },
            { label: 'Transmission Fluid', value: 'trans' },
            { label: 'Windshield Washer Fluid', value: 'washer' },
          ],
        },
        {
          id: 'battery_test_result',
          type: 'radio',
          label: '12V Battery Health Test (CCA / Voltage)',
          options: [
            { label: 'Pass — 100% Cranking Health', value: 'pass' },
            { label: 'Marginal — Recharge / Retest', value: 'marginal' },
            { label: 'Fail — Replace Battery', value: 'fail' },
          ],
          required: true,
        },
        { id: 'technician_notes', type: 'textarea', label: 'Recommended Repairs & Observations' },
        { id: 'tech_signature', type: 'text', label: 'Certified Technician Signature', required: true },
      ],
      theme: { primaryColor: '#dc2626', borderRadius: '0.75rem' },
    },
    categories: ['inspection', 'checklist'],
    industries: ['automotive'],
    useCases: ['inspection'],
    audiences: ['b2b', 'b2c'],
    tags: ['vehicle-inspection', 'auto-repair', 'mechanic-checklist', 'safety-audit'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 1320,
    viewCount: 6400,
    cloneCount: 710,
    ratingAverage: 4.9,
    ratingCount: 54,
    seo: {
      seoTitle: 'Free Vehicle Multi-Point Inspection Form Template | Fieseros',
      seoDescription: 'Download this free automotive multi-point vehicle inspection form template for auto shops, technicians, and car dealerships.',
      seoKeywords: ['vehicle inspection form', 'multi-point inspection template', 'auto repair checklist', 'mechanic inspection sheet'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
  {
    id: 'hvac-seasonal-tune-up-checklist',
    name: 'HVAC Seasonal Tune-Up & Maintenance Checklist',
    shortDescription: 'Seasonal HVAC maintenance log covering refrigerant subcool/superheat, capacitor microfarads, delta-T split, and filter replacement.',
    description: 'Standardize residential and commercial heating and cooling tune-ups with digital technician checklists and customer report generation.',
    schema: {
      id: 'hvac-seasonal-tune-up-checklist',
      title: 'HVAC Seasonal Precision Tune-Up Checklist',
      description: 'System efficiency and safety diagnostic checklist.',
      fields: [
        { id: 'tech_name', type: 'text', label: 'Lead Technician Name', required: true },
        { id: 'service_date', type: 'date', label: 'Service Date', required: true },
        { id: 'customer_info', type: 'text', label: 'Customer Name & Service Address', required: true },
        { id: 'unit_serial', type: 'text', label: 'AC / Furnace Model & Serial Number', required: true },
        {
          id: 'filter_status',
          type: 'radio',
          label: 'Air Filter Condition',
          options: [
            { label: 'Clean / Recently Replaced', value: 'clean' },
            { label: 'Replaced with New 16x25x1 MERV 11 Filter', value: 'replaced' },
            { label: 'Dirty — Customer Declined Replacement', value: 'declined' },
          ],
          required: true,
        },
        { id: 'temp_split_delta_t', type: 'text', label: 'Supply vs Return Delta-T (°F)', placeholder: 'e.g. 18°F to 22°F', required: true },
        { id: 'capacitor_test', type: 'text', label: 'Dual Run Capacitor Test (MFD / % tolerance)', placeholder: 'e.g. 44.8 / 4.9 MFD (Pass)', required: true },
        { id: 'motor_amps', type: 'text', label: 'Compressor & Fan Motor Running Amps vs Rated RLA', placeholder: 'e.g. 11.2 Amps (Rated 14.5A)' },
        {
          id: 'safety_controls',
          type: 'checkbox',
          label: 'Safety Controls & Drains Verified',
          options: [
            { label: 'Condensate Drain Line Flushed & Float Switch Tested', value: 'drain' },
            { label: 'Contactor Points Inspected (No Pitting/Burn)', value: 'contactor' },
            { label: 'High Pressure Safety Cutout Switch Verified', value: 'high_pressure' },
            { label: 'Carbon Monoxide / Gas Leak Test Completed (0 PPM)', value: 'co_test' },
          ],
          required: true,
        },
        { id: 'summary_recommendations', type: 'textarea', label: 'Technician Summary & Recommended Improvements' },
      ],
      theme: { primaryColor: '#d97706', borderRadius: '0.75rem' },
    },
    categories: ['inspection', 'checklist'],
    industries: ['hvac'],
    useCases: ['inspection'],
    audiences: ['b2b', 'b2c'],
    tags: ['hvac-checklist', 'ac-tuneup', 'furnace-inspection', 'maintenance-sheet'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 2100,
    viewCount: 10200,
    cloneCount: 1400,
    ratingAverage: 5.0,
    ratingCount: 128,
    seo: {
      seoTitle: 'Free HVAC Seasonal Tune-Up Checklist Template | Fieseros',
      seoDescription: 'Professional HVAC tune-up and preventive maintenance checklist for heating and air conditioning contractors.',
      seoKeywords: ['hvac maintenance checklist', 'ac tune up form', 'furnace inspection sheet', 'hvac service report'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
];

registerTemplates(INSPECTION_CHECKLIST_TEMPLATES);
