/**
 * Canonical Order, Payment & E-Commerce Form Templates (Jotform Parity)
 */

import { registerTemplates } from '../registry';
import type { FormTemplate } from '../types';

export const ORDER_PAYMENT_TEMPLATES: FormTemplate[] = [
  {
    id: 'product-purchase-order-form',
    name: 'Product Purchase Order Form',
    shortDescription: 'Clean purchase order form with itemized SKU selection, quantity picker, billing address, and payment options.',
    description: 'Allow customers and wholesale buyers to place itemized product orders with automated tax and total calculation.',
    schema: {
      id: 'product-purchase-order-form',
      title: 'Product Purchase Order',
      description: 'Select your items and quantities below.',
      fields: [
        { id: 'buyer_name', type: 'text', label: 'Company / Buyer Name', required: true },
        { id: 'buyer_email', type: 'email', label: 'Billing Email', required: true },
        { id: 'buyer_phone', type: 'tel', label: 'Contact Phone', required: true },
        { id: 'shipping_address', type: 'text', label: 'Shipping Address (Street, City, State, ZIP)', required: true },
        {
          id: 'product_selection',
          type: 'select',
          label: 'Primary Item / Catalog SKU',
          options: [
            { label: 'Standard Package (SKU-100) - $150', value: 'sku_100' },
            { label: 'Professional Kit (SKU-200) - $350', value: 'sku_200' },
            { label: 'Enterprise Bundle (SKU-500) - $800', value: 'sku_500' },
          ],
          required: true,
        },
        { id: 'quantity', type: 'number', label: 'Quantity Ordered', placeholder: '1', required: true },
        {
          id: 'shipping_method',
          type: 'radio',
          label: 'Preferred Shipping Speed',
          options: [
            { label: 'Standard Ground (3–5 days) - Free', value: 'ground' },
            { label: 'Express Air (1–2 days) - $25.00', value: 'express' },
            { label: 'Overnight Priority - $50.00', value: 'overnight' },
          ],
          required: true,
        },
        { id: 'special_instructions', type: 'textarea', label: 'Delivery / Packaging Instructions' },
      ],
      theme: { primaryColor: '#2563eb', borderRadius: '0.75rem' },
    },
    categories: ['order', 'payment'],
    industries: ['general'],
    useCases: ['order', 'payment'],
    audiences: ['b2b', 'b2c'],
    tags: ['order', 'purchase-order', 'products', 'ecommerce', 'checkout'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 1420,
    viewCount: 6800,
    cloneCount: 780,
    ratingAverage: 4.9,
    ratingCount: 88,
    seo: {
      seoTitle: 'Free Product Purchase Order Form Template | Fieseros',
      seoDescription: 'Download or customize this free Product Purchase Order Form. Collect orders, calculate totals, and process payments.',
      seoKeywords: ['purchase order form', 'product order template', 'online checkout form', 'order form builder'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
  {
    id: 'custom-cake-bakery-order-form',
    name: 'Custom Cake & Bakery Order Form',
    shortDescription: 'Specialty bakery order form for custom cakes, flavor choices, dietary restrictions, and pickup scheduling.',
    description: 'Capture custom cake and catering orders with detailed flavor tiers, frosting choices, custom lettering, and event delivery dates.',
    schema: {
      id: 'custom-cake-bakery-order-form',
      title: 'Custom Cake & Bakery Order',
      description: 'Design your custom cake and reserve your date.',
      fields: [
        { id: 'customer_name', type: 'text', label: 'Customer Full Name', required: true },
        { id: 'customer_phone', type: 'tel', label: 'Phone Number', required: true },
        { id: 'customer_email', type: 'email', label: 'Email Address', required: true },
        { id: 'event_date', type: 'date', label: 'Event / Pickup Date', required: true },
        {
          id: 'cake_size',
          type: 'select',
          label: 'Cake Size & Servings',
          options: [
            { label: '6" Round (Serves 8–10) - $45', value: '6_inch' },
            { label: '8" Round (Serves 15–20) - $65', value: '8_inch' },
            { label: '10" Round (Serves 25–30) - $95', value: '10_inch' },
            { label: '2-Tier Celebration Cake (Serves 40–50) - $180', value: '2_tier' },
            { label: '3-Tier Wedding Cake (Serves 75–100) - $350', value: '3_tier' },
          ],
          required: true,
        },
        {
          id: 'flavor',
          type: 'select',
          label: 'Cake Flavor',
          options: [
            { label: 'Vanilla Bean', value: 'vanilla' },
            { label: 'Rich Dark Chocolate', value: 'chocolate' },
            { label: 'Red Velvet with Cream Cheese', value: 'red_velvet' },
            { label: 'Lemon Berry', value: 'lemon_berry' },
            { label: 'Salted Caramel Crunch', value: 'salted_caramel' },
          ],
          required: true,
        },
        { id: 'custom_inscription', type: 'text', label: 'Custom Inscription / Lettering', placeholder: 'e.g. Happy 30th Birthday Sarah!' },
        {
          id: 'dietary_allergies',
          type: 'checkbox',
          label: 'Dietary Considerations',
          options: [
            { label: 'Gluten-Free', value: 'gf' },
            { label: 'Nut Allergy Safe', value: 'nut_free' },
            { label: 'Dairy-Free / Vegan', value: 'vegan' },
          ],
        },
      ],
      theme: { primaryColor: '#ec4899', borderRadius: '0.75rem' },
    },
    categories: ['order', 'booking'],
    industries: ['general'],
    useCases: ['order'],
    audiences: ['b2c'],
    tags: ['bakery', 'cake-order', 'food-order', 'catering', 'event-cake'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 930,
    viewCount: 4200,
    cloneCount: 410,
    ratingAverage: 4.8,
    ratingCount: 42,
    seo: {
      seoTitle: 'Free Custom Cake & Bakery Order Form Template | Fieseros',
      seoDescription: 'Order form template for bakeries, custom cakes, and event catering with flavor and date selectors.',
      seoKeywords: ['bakery order form', 'cake order form template', 'custom cake order form', 'pastry order'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
  {
    id: 'nonprofit-charity-donation-form',
    name: 'Nonprofit Charity Donation Form',
    shortDescription: 'Secure online donation form for charities, foundations, and causes with recurring pledge support.',
    description: 'Accept one-time and recurring monthly donations with tax receipt acknowledgment and donor dedication options.',
    schema: {
      id: 'nonprofit-charity-donation-form',
      title: 'Make a Difference — Donate Today',
      description: 'Your generous contribution directly funds our community programs.',
      fields: [
        { id: 'donor_name', type: 'text', label: 'Donor Name / Organization', required: true },
        { id: 'donor_email', type: 'email', label: 'Email for Tax Receipt', required: true },
        { id: 'donor_phone', type: 'tel', label: 'Phone Number' },
        {
          id: 'donation_frequency',
          type: 'radio',
          label: 'Donation Frequency',
          options: [
            { label: 'One-Time Contribution', value: 'one_time' },
            { label: 'Monthly Recurring Champion', value: 'monthly' },
            { label: 'Annual Patron', value: 'annual' },
          ],
          required: true,
        },
        {
          id: 'donation_amount',
          type: 'radio',
          label: 'Select Gift Amount',
          options: [
            { label: '$25 — Provides meals for 5 families', value: '25' },
            { label: '$50 — Supplies school kits for 10 kids', value: '50' },
            { label: '$100 — Emergency medical support', value: '100' },
            { label: '$250 — Community scholarship sponsor', value: '250' },
            { label: '$500+ — Major impact partner', value: '500' },
          ],
          required: true,
        },
        { id: 'custom_amount', type: 'number', label: 'Or Enter Custom Amount ($)' },
        { id: 'dedication_note', type: 'textarea', label: 'In Honor / Memory Of (Optional dedication note)' },
        {
          id: 'anonymous_toggle',
          type: 'checkbox',
          label: 'I wish to keep this donation anonymous in public donor lists.',
        },
      ],
      theme: { primaryColor: '#10b981', borderRadius: '0.75rem' },
    },
    categories: ['payment', 'donation'],
    industries: ['general'],
    useCases: ['payment'],
    audiences: ['b2c', 'b2b'],
    tags: ['donation', 'charity', 'nonprofit', 'fundraising', 'pledge-form'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 1850,
    viewCount: 9200,
    cloneCount: 1100,
    ratingAverage: 5.0,
    ratingCount: 115,
    seo: {
      seoTitle: 'Free Nonprofit Charity Donation Form Template | Fieseros',
      seoDescription: 'Collect secure donations and recurring monthly gifts with this customizable nonprofit donation form.',
      seoKeywords: ['donation form template', 'charity donation form', 'nonprofit pledge form', 'online donation form'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
];

registerTemplates(ORDER_PAYMENT_TEMPLATES);
