/**
 * Canonical Registration & Application Form Templates (Jotform Parity)
 */

import { registerTemplates } from '../registry';
import type { FormTemplate } from '../types';

export const REGISTRATION_APPLICATION_TEMPLATES: FormTemplate[] = [
  {
    id: 'general-job-application-form',
    name: 'General Employment Job Application Form',
    shortDescription: 'Standard job application form with contact info, work experience, education history, and resume upload.',
    description: 'Simplify candidate screening and hiring with a structured application form including background questions, start date availability, and resume attachment.',
    schema: {
      id: 'general-job-application-form',
      title: 'Employment Job Application',
      description: 'Please complete all sections to apply for open positions.',
      fields: [
        { id: 'candidate_name', type: 'text', label: 'Full Legal Name', required: true },
        { id: 'candidate_email', type: 'email', label: 'Email Address', required: true },
        { id: 'candidate_phone', type: 'tel', label: 'Phone Number', required: true },
        { id: 'candidate_address', type: 'text', label: 'Current Address (City, State, Zip)', required: true },
        {
          id: 'position_applied',
          type: 'select',
          label: 'Position Applying For',
          options: [
            { label: 'Customer Success Specialist', value: 'cs' },
            { label: 'Field Service Technician', value: 'tech' },
            { label: 'Operations & Dispatch Manager', value: 'ops' },
            { label: 'Sales & Account Executive', value: 'sales' },
            { label: 'General Application / Other', value: 'other' },
          ],
          required: true,
        },
        {
          id: 'employment_type_desired',
          type: 'radio',
          label: 'Employment Type Desired',
          options: [
            { label: 'Full-Time (40 hrs/wk)', value: 'full_time' },
            { label: 'Part-Time', value: 'part_time' },
            { label: 'Contract / Project Basis', value: 'contract' },
          ],
          required: true,
        },
        { id: 'years_experience', type: 'number', label: 'Years of Relevant Experience', placeholder: 'e.g. 4', required: true },
        { id: 'earliest_start_date', type: 'date', label: 'Earliest Available Start Date', required: true },
        { id: 'desired_salary', type: 'text', label: 'Desired Annual Salary / Hourly Rate' },
        { id: 'linkedin_portfolio', type: 'text', label: 'LinkedIn Profile or Portfolio URL' },
        { id: 'why_hire_me', type: 'textarea', label: 'Brief Summary of Key Skills & Qualifications' },
      ],
      theme: { primaryColor: '#0f766e', borderRadius: '0.75rem' },
    },
    categories: ['application', 'employment'],
    industries: ['general'],
    useCases: ['application', 'onboarding'],
    audiences: ['b2c', 'b2b'],
    tags: ['job-application', 'employment', 'careers', 'hiring', 'recruiting'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 2200,
    viewCount: 11400,
    cloneCount: 1350,
    ratingAverage: 4.9,
    ratingCount: 140,
    seo: {
      seoTitle: 'Free Job Application Form Template | Fieseros',
      seoDescription: 'Download and customize this free employment job application form template for your hiring and recruitment process.',
      seoKeywords: ['job application form', 'employment application template', 'hiring form', 'career application'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
  {
    id: 'residential-tenant-rental-application',
    name: 'Residential Tenant Rental Application Form',
    shortDescription: 'Comprehensive tenant screening form covering rental history, proof of income, references, and credit check authorization.',
    description: 'Protect landlords and property managers with thorough applicant screening including income verification, previous landlord contacts, and background consent.',
    schema: {
      id: 'residential-tenant-rental-application',
      title: 'Tenant Rental Application',
      description: 'Apply for residential apartment or home lease.',
      fields: [
        { id: 'applicant_name', type: 'text', label: 'Applicant Full Legal Name', required: true },
        { id: 'applicant_dob', type: 'date', label: 'Date of Birth', required: true },
        { id: 'applicant_phone', type: 'tel', label: 'Mobile Phone Number', required: true },
        { id: 'applicant_email', type: 'email', label: 'Email Address', required: true },
        { id: 'property_applied', type: 'text', label: 'Rental Property Address & Unit #', required: true },
        { id: 'desired_move_in', type: 'date', label: 'Desired Move-in Date', required: true },
        { id: 'current_employer', type: 'text', label: 'Current Employer / Company Name', required: true },
        { id: 'monthly_gross_income', type: 'number', label: 'Monthly Gross Income ($)', required: true },
        { id: 'previous_landlord_contact', type: 'text', label: 'Previous Landlord Name & Phone Number' },
        {
          id: 'has_pets',
          type: 'radio',
          label: 'Do you have any pets?',
          options: [
            { label: 'No Pets', value: 'no' },
            { label: 'Yes — Dog (specify breed/weight)', value: 'dog' },
            { label: 'Yes — Cat', value: 'cat' },
            { label: 'Other', value: 'other' },
          ],
          required: true,
        },
        {
          id: 'background_consent',
          type: 'checkbox',
          label: 'I authorize the landlord/property manager to conduct background, employment, and credit checks.',
          required: true,
        },
      ],
      theme: { primaryColor: '#4338ca', borderRadius: '0.75rem' },
    },
    categories: ['application', 'real_estate'],
    industries: ['real_estate'],
    useCases: ['application', 'intake'],
    audiences: ['b2c', 'b2b'],
    tags: ['tenant-application', 'rental-application', 'property-management', 'apartment-lease'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 1650,
    viewCount: 8100,
    cloneCount: 920,
    ratingAverage: 4.8,
    ratingCount: 76,
    seo: {
      seoTitle: 'Free Tenant Rental Application Form Template | Fieseros',
      seoDescription: 'Standard residential tenant rental application form with income verification and background check consent.',
      seoKeywords: ['rental application form', 'tenant application template', 'apartment lease form', 'property management form'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
  {
    id: 'conference-event-registration-form',
    name: 'Conference & Event Registration Form',
    shortDescription: 'Multi-ticket event registration form with attendee info, workshop breakout selections, and dietary requirements.',
    description: 'Streamline attendee check-ins for corporate conferences, summits, networking mixers, and webinars.',
    schema: {
      id: 'conference-event-registration-form',
      title: 'Annual Industry Summit Registration',
      description: 'Reserve your pass and select your breakout sessions.',
      fields: [
        { id: 'attendee_name', type: 'text', label: 'Attendee Full Name', required: true },
        { id: 'attendee_title', type: 'text', label: 'Job Title / Role', required: true },
        { id: 'company_org', type: 'text', label: 'Company / Organization Name', required: true },
        { id: 'attendee_email', type: 'email', label: 'Work Email Address', required: true },
        { id: 'attendee_phone', type: 'tel', label: 'Mobile Phone for SMS Updates' },
        {
          id: 'ticket_tier',
          type: 'select',
          label: 'Ticket Tier Pass',
          options: [
            { label: 'General Access Pass (Keynotes & Expo) - Free', value: 'general' },
            { label: 'All-Access VIP Pass (Workshops + Networking Dinner) - $299', value: 'vip' },
            { label: 'Virtual Livestream Access Only - $49', value: 'virtual' },
          ],
          required: true,
        },
        {
          id: 'breakout_track',
          type: 'radio',
          label: 'Afternoon Breakout Track Choice',
          options: [
            { label: 'Track A: AI Automation & Future of Field Services', value: 'track_a' },
            { label: 'Track B: Customer Acquisition & Digital Growth', value: 'track_b' },
            { label: 'Track C: Operational Scaling & Tech Retention', value: 'track_c' },
          ],
        },
        {
          id: 'dietary_needs',
          type: 'checkbox',
          label: 'Dietary Preferences for Catered Lunch',
          options: [
            { label: 'Vegetarian', value: 'vegetarian' },
            { label: 'Vegan', value: 'vegan' },
            { label: 'Gluten-Free', value: 'gf' },
            { label: 'Kosher / Halal', value: 'kosher_halal' },
          ],
        },
      ],
      theme: { primaryColor: '#7c3aed', borderRadius: '0.75rem' },
    },
    categories: ['registration', 'event'],
    industries: ['general'],
    useCases: ['event', 'registration'],
    audiences: ['b2b'],
    tags: ['event-registration', 'conference', 'summit', 'rsvp', 'tickets'],
    source: 'curated',
    status: 'published',
    isPublic: true,
    isFeatured: true,
    usageCount: 1980,
    viewCount: 10500,
    cloneCount: 1250,
    ratingAverage: 4.9,
    ratingCount: 104,
    seo: {
      seoTitle: 'Free Event Registration Form Template | Fieseros',
      seoDescription: 'Create custom conference and event registration forms with ticket tiers, breakout tracks, and attendee details.',
      seoKeywords: ['event registration form', 'conference signup template', 'workshop rsvp form', 'attendee registration'],
    },
    authorId: 'fieseros-team',
    publishedAt: new Date().toISOString(),
  },
];

registerTemplates(REGISTRATION_APPLICATION_TEMPLATES);
