import React, { useState } from 'react';
import { Modal, Text } from 'react-native';
import { Screen, Card, Field, Action, Empty, ErrorNotice, Loading, ui } from '../../src/components/ui';
import { useResource } from '../../src/hooks/use-resource';
import { apiRequest } from '../../src/lib/api';
type Booking = { id: string; title: string; customerName?: string; scheduledAt?: string; status: string };
export default function AppointmentsScreen() {
  const resource = useResource<{ bookings: Booking[] }>('/api/bookings?limit=100&sortBy=scheduledAt&sortOrder=asc');
  const [selected,setSelected] = useState<Booking | null>(null); const [date,setDate] = useState(''); const [time,setTime] = useState(''); const [error,setError] = useState<string | null>(null); const [busy,setBusy] = useState(false);
  async function save(booking: Booking, body: object) { setBusy(true); setError(null); try { await apiRequest(`/api/bookings/${booking.id}`, { method: 'PUT', body }); setSelected(null); await resource.refresh(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  function reschedule() { const parsed = new Date(`${date}T${time}:00`); if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !/^\d{2}:\d{2}$/.test(time) || !Number.isFinite(parsed.getTime()) || parsed.getTime() < Date.now()) { setError('Enter a valid future date and time.'); return; } if (selected) save(selected, { scheduledAt: parsed.toISOString() }); }
  return <Screen title="Appointments" subtitle="Accept requests and keep your schedule up to date." onRefresh={resource.refresh}><ErrorNotice message={error || resource.error} retry={resource.refresh} />{resource.loading ? <Loading /> : !resource.data?.bookings.length ? <Empty title="No appointments yet" detail="New bookings will appear here when customers reserve a time." /> : resource.data.bookings.map(b => <Card key={b.id}><Text style={ui.heading}>{b.title}</Text><Text style={ui.body}>{b.customerName || 'Customer'} · {b.status}</Text><Text style={ui.body}>{b.scheduledAt ? new Date(b.scheduledAt).toLocaleString() : 'Time not set'}</Text>{!['cancelled','completed'].includes(b.status) && <><Action label="Accept appointment" disabled={busy || b.status === 'confirmed'} onPress={() => save(b, { status: 'confirmed' })} /><Action label="Reschedule" secondary disabled={busy} onPress={() => { setSelected(b); setDate(''); setTime(''); }} /></>}</Card>)}<Modal visible={!!selected} onRequestClose={() => setSelected(null)} animationType="slide"><Screen title="Reschedule" subtitle="Times use your device's local timezone."><ErrorNotice message={error} /><Field label="Date (YYYY-MM-DD)" value={date} onChangeText={setDate} placeholder="2026-10-15" /><Field label="Time (HH:MM, 24-hour)" value={time} onChangeText={setTime} placeholder="14:30" /><Action label={busy ? 'Saving…' : 'Save appointment'} disabled={busy} onPress={reschedule} /><Action secondary label="Cancel" disabled={busy} onPress={() => setSelected(null)} /></Screen></Modal></Screen>;
}
