import React, { useState } from 'react';
import { Modal, ScrollView, Text, View } from 'react-native';
import { Screen, Card, Field, Action, Empty, ErrorNotice, Loading, ui, Chip, Badge } from '../../src/components/ui';
import { useResource } from '../../src/hooks/use-resource';
import { apiRequest } from '../../src/lib/api';
import { localDay, futureLocalTime } from '../../src/lib/dates';
type Booking = { id: string; title: string; customerName?: string; scheduledAt?: string; status: string };
export default function AppointmentsScreen() {
  const [day, setDay] = useState(localDay(new Date()));
  const [week, setWeek] = useState(0);
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() + week * 7 + i); return d; });
  const resource = useResource<{ bookings: Booking[] }>('/api/bookings?limit=100&sortBy=scheduledAt&sortOrder=asc');
  const [selected,setSelected] = useState<Booking | null>(null); const [date,setDate] = useState(''); const [time,setTime] = useState(''); const [error,setError] = useState<string | null>(null); const [busy,setBusy] = useState(false);
  async function save(booking: Booking, body: object) { setBusy(true); setError(null); try { await apiRequest(`/api/bookings/${booking.id}`, { method: 'PUT', body }); setSelected(null); await resource.refresh(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  function reschedule() { const parsed = futureLocalTime(date, time); if (!parsed) { setError('Enter a valid future date and time.'); return; } if (selected) save(selected, { scheduledAt: parsed }); }
  const filtered = resource.data?.bookings.filter(b => day === 'all' || (b.scheduledAt && localDay(new Date(b.scheduledAt)) === day)) || [];
  return <Screen title="Appointments" subtitle="Accept requests and keep your schedule up to date." onRefresh={resource.refresh}><View style={[ui.row, { justifyContent: 'space-between' }]}><Action secondary label="Previous week" onPress={() => setWeek(week - 1)} /><Action secondary label="Next week" onPress={() => setWeek(week + 1)} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={ui.row}><Chip label="All" selected={day === 'all'} onPress={() => setDay('all')} />{days.map(d => <Chip key={localDay(d)} label={d.toLocaleDateString([], { weekday: 'short', day: 'numeric', month: 'short' })} selected={day === localDay(d)} onPress={() => setDay(localDay(d))} />)}</View></ScrollView><Text style={ui.caption}>{day === 'all' ? 'All loaded bookings' : `Agenda · ${day}`}</Text><ErrorNotice message={error || resource.error} retry={resource.refresh} />{resource.loading ? <Loading /> : !filtered.length ? !resource.error && <Empty title="No appointments yet" detail="New bookings will appear here when customers reserve a time." /> : filtered.map(b => <Card key={b.id}><Text style={ui.heading}>{b.title}</Text><View style={[ui.row, { justifyContent: 'space-between' }]}><Text style={ui.body}>{b.customerName || 'Customer'}</Text><Badge label={b.status} success={b.status === 'confirmed'} /></View><Text style={ui.body}>{b.scheduledAt ? new Date(b.scheduledAt).toLocaleString() : 'Time not set'}</Text>{!['cancelled','completed'].includes(b.status) && <><Action label="Accept appointment" disabled={busy || b.status === 'confirmed'} onPress={() => save(b, { status: 'confirmed' })} /><Action label="Reschedule" secondary disabled={busy} onPress={() => { setSelected(b); setDate(''); setTime(''); }} /></>}</Card>)}<Modal visible={!!selected} onRequestClose={() => setSelected(null)} animationType="slide"><Screen title="Reschedule" subtitle="Times use your device's local timezone."><ErrorNotice message={error} /><Field label="Date (YYYY-MM-DD)" value={date} onChangeText={setDate} placeholder="2026-10-15" /><Field label="Time (HH:MM, 24-hour)" value={time} onChangeText={setTime} placeholder="14:30" /><Action label={busy ? 'Saving…' : 'Save appointment'} disabled={busy} onPress={reschedule} /><Action secondary label="Cancel" disabled={busy} onPress={() => setSelected(null)} /></Screen></Modal></Screen>;
}
