import React, { useState } from 'react';
import { Linking, Modal, Pressable, Text, View } from 'react-native';
import { Screen, Card, Action, Avatar, Badge, Field, Empty, ErrorNotice, Loading, ui } from '../../src/components/ui';
import { useResource } from '../../src/hooks/use-resource';
import { WEB_URL } from '../../src/lib/constants';
type Call = { id: string; customerPhone?: string; fromNumber?: string; toNumber?: string; callType?: string; status: string; createdAt: string; durationSec?: number; summary?: string; transcript?: { role: string; content: string }[] };
export default function PhoneScreen() {
  const resource = useResource<{ calls: Call[]; stats: { total: number; totalDurationSec: number; todayCount: number } | null }>('/api/vapi/calls?limit=50');
  const [selected, setSelected] = useState<string | null>(null); const [search, setSearch] = useState(''); const [error, setError] = useState<string | null>(null);
  const items = resource.data?.calls.filter(c => `${c.customerPhone || ''} ${c.fromNumber || ''} ${c.toNumber || ''}`.includes(search)) || [];
  return <Screen title="Business phone" subtitle="Your AI receptionist's call history." onRefresh={resource.refresh}><ErrorNotice message={error || resource.error} retry={resource.refresh} />{resource.data?.stats && <Card><View style={[ui.row, { justifyContent: 'space-between' }]}>{[['Calls today', resource.data.stats.todayCount], ['Total calls', resource.data.stats.total], ['Total minutes', Math.round(resource.data.stats.totalDurationSec / 60)]].map(([label, value]) => <View key={label}><Text style={ui.metric}>{value}</Text><Text style={ui.caption}>{label}</Text></View>)}</View></Card>}<Field label="Search recent calls" value={search} onChangeText={setSearch} keyboardType="phone-pad" placeholder="Phone number" />{resource.loading ? <Loading /> : items.length ? <Card>{items.map(c => <Pressable key={c.id} accessibilityRole="button" onPress={() => setSelected(c.id)} style={ui.menuRow}><Avatar name={c.callType === 'outbound' ? 'Out' : 'In'} /><View style={{ flex: 1 }}><Text style={ui.heading}>{c.customerPhone || c.fromNumber || 'Unknown caller'}</Text><Text style={ui.caption}>{new Date(c.createdAt).toLocaleString()}</Text></View><Badge label={c.status} /></Pressable>)}</Card> : !resource.error && <Empty title="No calls to show" detail="Calls handled by your connected receptionist will appear here." />}<Text style={ui.caption}>Showing the latest 50 calls. Calling back uses your device's phone app; native in-app calling is not enabled.</Text><Action secondary label="Receptionist settings · Web" onPress={() => Linking.openURL(`${WEB_URL}/app?view=aiReceptionist`).catch(() => setError('Could not open the browser.'))} /><Modal visible={!!selected} animationType="slide" onRequestClose={() => setSelected(null)}>{selected && <CallDetail id={selected} close={() => setSelected(null)} />}</Modal></Screen>;
}
function CallDetail({ id, close }: { id: string; close: () => void }) {
  const resource = useResource<{ call: Call }>(`/api/vapi/calls?id=${encodeURIComponent(id)}`); const [error, setError] = useState<string | null>(null); const call = resource.data?.call;
  const number = call?.customerPhone || call?.fromNumber;
  return <Screen title="Call details" subtitle={number || 'Call summary and transcript'} onRefresh={resource.refresh}><Action secondary label="Back to calls" onPress={close} /><ErrorNotice message={error || resource.error} retry={resource.refresh} />{resource.loading ? <Loading /> : call && <><Card><Badge label={call.status} /><Text style={ui.body}>{call.durationSec ?? 0} seconds · {new Date(call.createdAt).toLocaleString()}</Text><Text style={ui.heading}>Summary</Text><Text style={ui.body}>{call.summary || 'No summary is available for this call.'}</Text></Card><Card><Text style={ui.heading}>Transcript</Text>{call.transcript?.length ? call.transcript.map((message, i) => <View key={i}><Text style={ui.label}>{message.role === 'user' ? 'Caller' : 'Assistant'}</Text><Text style={ui.body}>{message.content}</Text></View>) : <Text style={ui.body}>No transcript is available.</Text>}</Card>{number && <Action label="Call back using phone app" onPress={() => Linking.openURL(`tel:${number.replace(/[^\d+]/g, '')}`).catch(() => setError('Could not open the phone app.'))} />}</>}</Screen>;
}
