import React, { useState } from 'react';
import { Image, Linking, Share, Switch, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Screen, Card, Action, ErrorNotice, Loading, ui, colors, Avatar, MenuRow } from '../../src/components/ui';
import { useResource } from '../../src/hooks/use-resource';
import { apiRequest } from '../../src/lib/api';
import { WEB_URL } from '../../src/lib/constants';
import { useAuthStore } from '../../src/stores/auth-store';
import { enablePush } from '../../src/lib/push';
import type { BgosWorkspace } from '../../../shared/bgos-contracts';
export default function ToolsScreen() {
  const workspace = useResource<BgosWorkspace>('/api/bgos/workspace'); const router = useRouter(); const { logout, user } = useAuthStore();
  const [busy,setBusy] = useState(false); const [error,setError] = useState<string | null>(null); const [qr,setQr] = useState<string | null>(null); const [notice,setNotice] = useState('');
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(null); try { await action(); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function update(body: object) { await apiRequest('/api/bgos/workspace', { method: 'PATCH', body }); await workspace.refresh(); }
  function absolute(path: string) { return path.startsWith('https://') ? path : `${WEB_URL}${path}`; }
  const data = workspace.data;
  return <Screen title="More" subtitle="Your business, connected." onRefresh={workspace.refresh}><ErrorNotice message={error || workspace.error} retry={workspace.refresh} />{notice ? <Card><Text style={ui.body}>{notice}</Text></Card> : null}<Card><View style={ui.row}><Avatar name={user?.name || 'Your account'} /><View><Text style={ui.heading}>{user?.name || 'Your account'}</Text><Text style={ui.caption}>{user?.email}</Text></View></View></Card>
    <Card><Text style={ui.heading}>Growth & communication</Text><MenuRow title="Marketing Studio" icon="auto-awesome" onPress={() => router.push('/(tabs)/marketing')} /><MenuRow title="Reviews & reputation" icon="star-outline" onPress={() => router.push('/(tabs)/growth')} /><MenuRow title="AI assistant" icon="smart-toy" onPress={() => router.push('/(tabs)/agents')} /><MenuRow title="Business phone" icon="call" onPress={() => router.push('/(tabs)/phone')} /><MenuRow title="Forms & responses" icon="description" onPress={() => router.push('/(tabs)/submissions')} /><MenuRow title="Outreach approvals" icon="send" onPress={() => router.push('/(tabs)/outreach')} /><MenuRow title="Integrations" icon="link" onPress={() => router.push('/(tabs)/integrations')} /><MenuRow title="Team & permissions · Web" icon="people-outline" onPress={() => run(() => Linking.openURL(`${WEB_URL}/app?view=settings`))} /><MenuRow title="Analytics · Web" icon="bar-chart" onPress={() => run(() => Linking.openURL(`${WEB_URL}/app?view=formsAnalytics`))} /><MenuRow title="Help & support · Web" icon="help-outline" onPress={() => run(() => Linking.openURL(`${WEB_URL}/app?view=helpCenter`))} /></Card>
    {workspace.loading ? <Loading /> : data && <>
    <Card><Text style={ui.heading}>Digital identity</Text>{([['profile','Business card'],['booking','Booking page'],['form','Intake form']] as const).map(([key,label]) => <View key={key} style={{ gap: 10 }}><Text style={ui.label}>{label}</Text><Text style={ui.body}>{data.links[key] ? absolute(data.links[key]!) : 'Not published yet. Set this up in BGOS web.'}</Text>{data.links[key] && <Action secondary disabled={busy} label={`Share ${label.toLowerCase()}`} onPress={() => run(() => Share.share({ message: absolute(data.links[key]!), url: absolute(data.links[key]!) }))} />}</View>)}<Action disabled={busy || !data.links.profile} label="Show scannable QR" onPress={() => run(async () => { const result = await apiRequest<{ image: string }>('/api/bgos/qr'); setQr(result.image); })} />{qr && <Image accessibilityLabel="QR code for your published business profile" source={{ uri: qr }} style={{ width: '100%', aspectRatio: 1 }} />}</Card>
    <Card><Text style={ui.heading}>Automations</Text>{([['profileAssistant','Digital profile AI assistant'],['offlineReply','Offline customer auto-reply']] as const).map(([key,label]) => <View key={key} style={[ui.row,{ justifyContent: 'space-between' }]}><Text style={[ui.body,{ flex: 1 }]}>{label}</Text><Switch accessibilityLabel={label} disabled={busy} value={data.automations[key]} onValueChange={value => run(() => update({ [key]: value }))} trackColor={{ true: colors.brand }} /></View>)}<Text style={ui.body}>Auto-reply availability follows your connected channels and subscription.</Text><Action label="Manage workflows" secondary onPress={() => router.push('/(tabs)/automations')} /></Card>
    <Card><Text style={ui.heading}>Workspace mode</Text><Action disabled={busy} secondary label={data.mode === 'local' ? 'Local business · Switch to agency' : 'B2B agency · Switch to local'} onPress={() => run(() => update({ mode: data.mode === 'local' ? 'agency' : 'local' }))} /></Card>
    <Card><Text style={ui.heading}>Plan & account</Text><Text style={ui.body}>{data.plan.code} · {data.plan.status}</Text><Action secondary label="Plan details & usage" onPress={() => run(() => Linking.openURL(`${WEB_URL}/app?view=billing`))} /><Action secondary disabled={busy} label="Enable customer notifications" onPress={() => run(async () => { await enablePush(); setNotice('Notifications are enabled for this device.'); })} /></Card>
  </>}<Action disabled={busy} secondary label="Sign out" onPress={() => run(async () => { await logout(); router.replace('/login'); })} /></Screen>;
}
