import { getSitemapIds, serializeSitemapIndex } from "@/lib/sitemap-builder";

/**
 * GET /sitemap.xml — sitemap index.
 *
 * Returns a `<sitemapindex>` XML document that lists all individual sitemap
 * files (`/sitemap/0.xml`, `/sitemap/1.xml`, ...). This is the entry point
 * that Google and other search engines use to discover the site's URLs.
 *
 * WHY THIS EXISTS AS AN EXPLICIT ROUTE HANDLER:
 * Previously this was auto-generated by `src/app/sitemap.ts` using Next.js's
 * `generateSitemaps()` feature. In production, the auto-generated index at
 * `/sitemap.xml` was returning 404 even though the individual sitemaps
 * (`/sitemap/{id}.xml`) worked fine. Replacing the special file with an
 * explicit route handler guarantees the index is always served.
 *
 * `robots.ts` references this URL in its `sitemap:` directive.
 */
export async function GET() {
  try {
    const ids = await getSitemapIds();
    const xml = serializeSitemapIndex(ids);

    return new Response(xml, {
      headers: {
        "Content-Type": "application/xml; charset=UTF-8",
        // Cache at the CDN for 24 HOURS + 24h stale-while-revalidate.
        // The sitemap index changes only when business count crosses a
        // BUSINESS_PER_FILE boundary — rarely. 24h TTL is safe and prevents
        // Googlebot from hitting cold-cache regeneration (which can take 30s+
        // on Supabase and cause "Sitemap could not be read" errors).
        "Cache-Control": "public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400",
      },
    });
  } catch (error) {
    console.error("[sitemap.xml] Failed to generate sitemap index:", error);
    // Return 503 so Googlebot retries. See sitemap/[id]/route.ts for rationale.
    return new Response(
      '<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</sitemapindex>',
      {
        status: 503,
        headers: {
          "Content-Type": "application/xml; charset=UTF-8",
          "Retry-After": "300",
        },
      },
    );
  }
}
