import { getSitemapIds, serializeSitemapIndex } from "@/lib/sitemap-builder";

/**
 * GET /sitemap.xml — sitemap index.
 *
 * Returns a `<sitemapindex>` XML document that lists all individual sitemap
 * files (`/sitemap/0.xml`, `/sitemap/1.xml`, ...). This is the entry point
 * that Google and other search engines use to discover the site's URLs.
 *
 * WHY THIS EXISTS AS AN EXPLICIT ROUTE HANDLER:
 * Previously this was auto-generated by `src/app/sitemap.ts` using Next.js's
 * `generateSitemaps()` feature. In production, the auto-generated index at
 * `/sitemap.xml` was returning 404 even though the individual sitemaps
 * (`/sitemap/{id}.xml`) worked fine. Replacing the special file with an
 * explicit route handler guarantees the index is always served.
 *
 * `robots.ts` references this URL in its `sitemap:` directive.
 */
export async function GET() {
  try {
    const ids = await getSitemapIds();
    const xml = serializeSitemapIndex(ids);

    return new Response(xml, {
      headers: {
        "Content-Type": "application/xml; charset=UTF-8",
        // Cache at the CDN/browser for 1 hour. After that, the CDN may serve
        // a STALE response for up to 24h while regenerating in the background.
        // This is critical: sitemap regeneration can take 30s+ on a cold cache
        // (100+ sequential Supabase REST calls). Without stale-while-revalidate,
        // Googlebot hits a cold cache after the 1h TTL expires, waits 30s, and
        // gives up — reporting "Sitemap could not be read" in Search Console.
        // With SWR, Googlebot always gets an instant response (the stale one)
        // while Vercel regenerates fresh data in the background.
        "Cache-Control": "public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400",
      },
    });
  } catch (error) {
    console.error("[sitemap.xml] Failed to generate sitemap index:", error);
    return new Response(
      '<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</sitemapindex>',
      {
        status: 200,
        headers: {
          "Content-Type": "application/xml; charset=UTF-8",
        },
      },
    );
  }
}
