'use client';

/**
 * JobDetailPage — Phase 2D extraction from jobs-view.tsx.
 *
 * Replaces the inline `renderJobDetailPage()` closure that used to live inside
 * the parent JobsView component. The detail page is the Jobber-style full-page
 * view that opens when a job card/row is clicked. It renders:
 *
 *   1. Recurring-schedule back-link banner (when this job was generated by a
 *      RecurringJobSchedule)
 *   2. Sticky page header (Back + title + lifecycle / management actions +
 *      More menu)
 *   3. Two-column layout:
 *      Left column:
 *        - Client + Job details (side-by-side cards)
 *        - Lifecycle timeline + stage-appropriate action buttons
 *        - Product / Service (line items table with totals)
 *        - Expenses (JobExpensesSection)
 *        - Scheduled visits (ScheduledVisitsSection)
 *        - Time tracking (live timer + LaborSection)
 *        - GPS & route summary
 *        - Customer Verification card (PIN pipeline)
 *        - #job custom fields (when any)
 *        - Billing (invoice lifecycle)
 *        - Attached files & photos (when any)
 *        - On-site checklists (when any)
 *        - Linked equipment (when any)
 *        - Photos (PhotoCapture)
 *        - Signatures (SignaturePad + collected signatures)
 *        - Notes (notes + activity log)
 *        - Danger actions (Close Job + Delete)
 *      Right column (sidebar):
 *        - Profit margin card (revenue / costs / profit)
 *        - Quick actions (Edit / Print / Email)
 *
 * The component is a pure presentational extraction: ALL state lives in the
 * parent JobsView and is threaded through as props. Same JSX, same handler
 * wiring, same prop dependencies — moved to its own file so jobs-view.tsx
 * shrinks by ~885 lines.
 *
 * Extracted from src/components/views/jobs-view.tsx (Phase 2D refactor).
 */

import type { ReactNode } from 'react';
import {
  Briefcase, Pencil, Phone, Mail, MapPin, User, Info, Activity, Timer,
  MapPinned, ShieldCheck, Tag, FileText, Paperclip, ClipboardList,
  ChevronRight, Camera, PenLine, StickyNote, TrendingUp, Printer, Send,
  Play, Pause, Navigation, Wrench, Check, CheckCircle2, Loader2, Plus,
  Repeat, ExternalLink, DollarSign, CalendarDays, Zap, Trash2, X,
  MoreHorizontal, File as FileIcon,
} from 'lucide-react';
import { Separator } from '@/components/ui/separator';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  DropdownMenu,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import {
  formatDate,
  formatDateTime,
  formatFileSize,
} from '@/lib/format-utils';
import {
  parseCustomFields,
  parseAttachments,
  parseStringArray,
  parseNotificationLog,
  parseAssetIdFromMetadata,
} from '@/lib/json-parsers';
import { FormSectionCard } from '@/components/shared/form-section-card';
import { LifecycleTimelineSection } from '@/features/jobs/components/lifecycle-timeline-section';
import { TimeTrackingSection } from '@/features/jobs/components/time-tracking-section';
import { GpsRouteSection } from '@/features/jobs/components/gps-route-section';
import { CustomerVerificationCard } from '@/features/jobs/components/customer-verification-card';
import { ScheduledVisitsSection } from '@/components/job/scheduled-visits-section';
import { LaborSection } from '@/components/job/labor-section';
import { JobExpensesSection } from '@/components/job/job-expenses-section';
import { PhotoCapture } from '@/components/job/photo-capture';
import { SignaturePad, type SavedSignature } from '@/components/job/signature-pad';
import { ChecklistExecution } from '@/components/job/checklist-execution';
import { lineItemsSubtotal, parseLineItems } from '@/features/line-items';
import type {
  Job,
  Employee,
  CustomerAssetOption,
  LifecycleDataShape,
} from '@/features/jobs/types/jobs-view-types';
import type { CurrentUser } from '@/hooks/use-current-user';
import type { PendingOpenEntity, ActiveView } from '@/store/app-store';

// ── Helper types ────────────────────────────────────────────────────────────

/** Shape of the parent's `composerInitial` state slot. */
interface ComposerInitial {
  body?: string;
  subject?: string;
  templateKey?: string;
}

/** Lifecycle transition actions accepted by handleLifecycleTransition. */
type LifecycleTransitionAction =
  | 'accept'
  | 'start_travel'
  | 'arrive'
  | 'start_work'
  | 'pause'
  | 'resume'
  | 'complete'
  | 'generate_invoice';

// ── Props contract ──────────────────────────────────────────────────────────
// Mirrors the closure variables the original `renderJobDetailPage()` reached
// into from the parent JobsView. Each prop below corresponds 1:1 to a parent
// state slot or handler; the wiring at the call site just spreads them in.

export interface JobDetailPageProps {
  // ── Selected job + linked asset ──
  selectedJob: Job | null;
  detailLinkedAsset: CustomerAssetOption | null;

  // ── V1.5 Lifecycle / Time Tracking / GPS state ──
  lifecycleData: LifecycleDataShape | null;
  lifecycleLoadingAction: string | null;
  liveTimerSeconds: number;
  jobLaborMinutes: number;
  jobExpensesTotal: number;

  // ── Signatures state ──
  jobSignatures: SavedSignature[];
  signaturePadType: 'customer' | 'employee' | null;
  setSignaturePadType: (v: 'customer' | 'employee' | null) => void;

  // ── Checklist execution panel state ──
  showChecklistExecution: boolean;
  setShowChecklistExecution: React.Dispatch<React.SetStateAction<boolean>>;

  // ── Catalog data ──
  employees: Employee[];
  checklists: { id: string; title: string }[];

  // ── Recurring schedule cache (title for the back-link banner) ──
  scheduleMetaCache: Record<string, { title?: string }>;

  // ── Auth + RBAC ──
  currentUser: CurrentUser | null;
  canManageJob: boolean;

  // ── Legacy lifecycle action loading flags (for the page-header buttons) ──
  lifecycleLoading: boolean;
  loadingAction: string | null;

  // ── Currency symbol (from useCompanyCurrency) ──
  symbol: string;

  // ── State setters (threaded through from parent) ──
  setPendingOpenEntity: (e: PendingOpenEntity | null) => void;
  setActiveView: (view: ActiveView) => void;
  setSelectedJob: (job: Job | null) => void;
  setShowRouteModal: (v: boolean) => void;
  setShowComposer: (v: boolean) => void;
  setComposerInitial: React.Dispatch<React.SetStateAction<ComposerInitial>>;
  setDeletingJob: (job: Job) => void;

  // ── Handlers ──
  closeJobDetail: () => void;
  openEditJob: (job: Job) => void;
  openAssignDialog: (job: Job) => void;
  openCompletionDialog: (job: Job) => void;
  handleCloseJobClick: (job: Job) => void;
  handlePrintJob: () => void;
  handleEmailClient: (job: Job) => void;
  handleCreateInvoice: (job: Job) => void;
  handleLifecycleAction: (action: string, jobId: string) => void;
  handleLifecycleTransition: (
    action: LifecycleTransitionAction,
    jobId: string,
    extra?: { latitude?: number; longitude?: number; notes?: string },
  ) => void;
  fetchRouteData: (employeeId: string, jobId?: string) => void;
  fetchJobSignatures: (jobId: string) => void;
  fetchJobs: () => void;
  ensureScheduleState: (scheduleId: string) => void;
  /**
   * Shared More-menu builder (returns the `<DropdownMenuContent>` JSX).
   * Called with `{ includeViewEdit: false }` from the detail page so the
   * menu skips "View Details" + "Edit Job" (already on the page).
   */
  renderMoreMenuItems: (
    job: Job,
    ctx: { includeViewEdit?: boolean },
  ) => ReactNode;
}

export function JobDetailPage({
  selectedJob,
  detailLinkedAsset,
  lifecycleData,
  lifecycleLoadingAction,
  liveTimerSeconds,
  jobLaborMinutes,
  jobExpensesTotal,
  jobSignatures,
  signaturePadType,
  setSignaturePadType,
  showChecklistExecution,
  setShowChecklistExecution,
  employees,
  checklists,
  scheduleMetaCache,
  currentUser,
  canManageJob,
  lifecycleLoading,
  loadingAction,
  symbol,
  setPendingOpenEntity,
  setActiveView,
  setSelectedJob,
  setShowRouteModal,
  setShowComposer,
  setComposerInitial,
  setDeletingJob,
  closeJobDetail,
  openEditJob,
  openAssignDialog,
  openCompletionDialog,
  handleCloseJobClick,
  handlePrintJob,
  handleEmailClient,
  handleCreateInvoice,
  handleLifecycleAction,
  handleLifecycleTransition,
  fetchRouteData,
  fetchJobSignatures,
  fetchJobs,
  ensureScheduleState,
  renderMoreMenuItems,
}: JobDetailPageProps) {
  if (!selectedJob) return null;

  const job = selectedJob;
  const lineItems = parseLineItems(job.lineItemsJson);
  const customFields = parseCustomFields(job.customFieldsJson);
  const attachments = parseAttachments(job.attachmentsJson);
  const linkedChecklists = parseStringArray(job.linkedChecklistsJson);
  const linkedAssetId = parseAssetIdFromMetadata(job.metadataJson);
  const linkedAsset = linkedAssetId ? detailLinkedAsset : null;
  const totalPrice = lineItemsSubtotal(lineItems) || (job.quotedAmount || 0);
  const totalCost = lineItems.reduce((sum, it) => sum + (Number(it.unitCost) || 0) * (Number(it.quantity) || 0), 0);
  // Labor cost: convert tracked working minutes to a monetary value.
  // Uses a conservative $50/hr default rate; employees without an explicit
  // hourly rate fall back to this. (Future: read from Employee.hourlyRate.)
  const LABOR_HOURLY_RATE = 50;
  const laborCost = (jobLaborMinutes / 60) * LABOR_HOURLY_RATE;
  const expensesCost = jobExpensesTotal;
  const profit = totalPrice - totalCost - laborCost - expensesCost;
  const profitPct = totalPrice > 0 ? (profit / totalPrice) * 100 : 0;
  const isClosed = job.status === 'completed' || job.status === 'cancelled';
  const logs = parseNotificationLog(job.notificationLogJson);

  const detailRows: { label: string; value: React.ReactNode }[] = [
    { label: 'Job #', value: <span className="font-mono">{job.jobNumber || '--'}</span> },
    { label: 'Job type', value: <span className="capitalize">{job.type === 'one-off' ? 'One-off job' : job.type === 'recurring' ? 'Recurring job' : (job.type || 'One-off job')}</span> },
    { label: 'Status', value: (
      <span className="inline-flex items-center gap-1.5">
        <span className={cn('size-2 rounded-full', {
          'bg-amber-400': job.status === 'pending',
          'bg-blue-400': job.status === 'assigned',
          'bg-emerald-500': job.status === 'in_progress',
          'bg-green-600': job.status === 'completed',
          'bg-red-500': job.status === 'cancelled',
        })} />
        <span className="capitalize">{job.status.replace('_', ' ')}</span>
      </span>
    ) },
    { label: 'Priority', value: <span className="capitalize">{job.priority}</span> },
    ...(job.scheduledAt ? [{ label: 'Start date', value: <span>{formatDate(job.scheduledAt)}{job.scheduledTime ? ` · ${job.scheduledTime}` : ''}</span> }] : []),
    ...(job.actualEndTime ? [{ label: 'End date', value: <span>{formatDate(job.actualEndTime)}</span> }] : []),
    ...(job.estimatedDuration ? [{ label: 'Est. duration', value: <span>{job.estimatedDuration} min</span> }] : []),
    { label: 'Created', value: <span>{formatDate(job.createdAt)}</span> },
  ];

  return (
    <div className="w-full space-y-6">
      {/* ─── Recurring-schedule back-link banner ─────────────────────────
          Shows above the sticky page header when this Job was generated by
          a recurring schedule. Lets the user navigate from an individual
          generated Job back to its parent schedule — the inverse of the
          "Generated Jobs" tab on the schedule detail page.

          Title comes from `scheduleMetaCache`, populated lazily by
          `ensureScheduleState` when this detail page mounts (see the
          useEffect in the parent component). If the title hasn't loaded
          yet (or the schedule was deleted), we still render the banner
          with a generic label so the navigation affordance is always
          visible. */}
      {job.recurringScheduleId && (
        <button
          type="button"
          onClick={() => {
            setPendingOpenEntity({ kind: 'recurringSchedule', id: job.recurringScheduleId! });
            setActiveView('recurringJobs');
          }}
          className="group w-full flex items-center justify-between gap-3 rounded-lg border border-emerald-600/30 bg-emerald-500/5 hover:bg-emerald-500/10 hover:border-emerald-600/50 px-4 py-2.5 transition-colors text-left"
        >
          <div className="flex items-center gap-2.5 min-w-0">
            <Repeat className="size-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
            <div className="min-w-0">
              <p className="text-xs text-muted-foreground leading-none mb-0.5">
                Recurring schedule
              </p>
              <p className="text-sm font-medium text-foreground truncate">
                {scheduleMetaCache[job.recurringScheduleId]?.title || 'View recurring schedule'}
              </p>
            </div>
          </div>
          <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 dark:text-emerald-300 shrink-0 group-hover:gap-1.5 transition-all">
            View schedule
            <ExternalLink className="size-3.5" />
          </span>
        </button>
      )}

      {/* ─── Sticky page header (Back + title + actions) ────────── */}
      <div className="form-page-header -mx-3 px-3 sm:-mx-4 sm:px-4 lg:-mx-6 lg:px-6 py-3 mb-2">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3 min-w-0">
            <button
              type="button"
              onClick={closeJobDetail}
              className="inline-flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors shrink-0"
            >
              <svg className="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7" /></svg>
              <span className="hidden sm:inline">Back</span>
            </button>
            <Separator orientation="vertical" className="h-8 bg-border/60 hidden sm:block" />
            <div className="flex items-center justify-center size-9 rounded-lg shrink-0 shadow-sm bg-amber-600">
              <Briefcase className="size-5 text-white" strokeWidth={2.2} />
            </div>
            <div className="min-w-0">
              <div className="flex items-center gap-2">
                <h2 className="text-lg sm:text-xl font-bold tracking-tight text-foreground leading-tight truncate">{job.title}</h2>
                <button title="Edit job" onClick={() => openEditJob(job)} className="inline-flex items-center justify-center size-9 -m-1 text-muted-foreground hover:text-emerald-600 transition-colors shrink-0">
                  <Pencil className="size-4" />
                </button>
              </div>
              <p className="text-xs text-muted-foreground line-clamp-1">
                {job.jobNumber && <span className="font-mono">#{job.jobNumber}</span>}
                {job.jobNumber && job.customerName && ' · '}
                {job.customerName && <span>{job.customerName}</span>}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            {/* Status-aware lifecycle action (primary) + owner/admin secondary action */}
            {job.status === 'pending' && (
              <>
                <button onClick={() => openAssignDialog(job)} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 transition-colors shadow-sm">
                  <User className="size-4 mr-1.5" /> Assign
                </button>
                {canManageJob && (
                  <button onClick={() => handleLifecycleAction('start', job.id)} disabled={lifecycleLoading} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted disabled:opacity-60 transition-colors">
                    {lifecycleLoading && loadingAction === 'start' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Play className="size-4 mr-1.5" />} Start Job
                  </button>
                )}
              </>
            )}
            {job.status === 'assigned' && (
              <>
                <button onClick={() => handleLifecycleAction('start', job.id)} disabled={lifecycleLoading} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 transition-colors shadow-sm">
                  {lifecycleLoading && loadingAction === 'start' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Play className="size-4 mr-1.5" />} Start Job
                </button>
                {canManageJob && (
                  <button onClick={() => openAssignDialog(job)} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted transition-colors">
                    <User className="size-4 mr-1.5" /> Re-assign
                  </button>
                )}
              </>
            )}
            {job.status === 'in_progress' && (
              <button onClick={() => openCompletionDialog(job)} disabled={lifecycleLoading} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-green-600 hover:bg-green-700 disabled:opacity-60 transition-colors shadow-sm">
                {lifecycleLoading && loadingAction === 'complete' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <CheckCircle2 className="size-4 mr-1.5" />} Complete
              </button>
            )}
            {isClosed && canManageJob && (
              <button onClick={async () => {
                await fetch(`/api/jobs/${job.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: job.id, status: 'pending' }) });
                toast.success('Job reopened'); fetchJobs();
                const r = await fetch(`/api/jobs/lifecycle?jobId=${job.id}`); if (r.ok) setSelectedJob(await r.json());
              }} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 transition-colors shadow-sm">
                Reopen Job
              </button>
            )}
            <button
              type="button"
              onClick={() => {
                setComposerInitial({ templateKey: 'custom' });
                setShowComposer(true);
              }}
              title="Message customer"
              disabled={!job.customerId}
              className="inline-flex items-center justify-center min-h-[44px] px-3 rounded-lg text-sm font-medium text-emerald-700 border border-emerald-600/40 bg-emerald-500/5 hover:bg-emerald-500/15 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <Mail className="size-4 mr-1.5" /> Message
            </button>
            <button onClick={() => openEditJob(job)} className="inline-flex items-center justify-center min-h-[44px] px-3 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted transition-colors">
              <Pencil className="size-4 mr-1.5" /> Edit
            </button>
            {/* ── Issue 1: Detail page More menu ────────────────────────
                Mirrors the list view's MoreVertical menu structure via the
                shared renderMoreMenuItems builder. Detail page hides the
                "View Details" + "Edit Job" items (already on the page) —
                passes includeViewEdit:false so the menu opens straight to
                "Close Job". */}
            <DropdownMenu
              onOpenChange={(open) => {
                if (open && job.recurringScheduleId) {
                  ensureScheduleState(job.recurringScheduleId);
                }
              }}
            >
              <DropdownMenuTrigger asChild>
                <button
                  title="More actions"
                  aria-label="More actions"
                  className="inline-flex items-center justify-center size-9 min-h-[44px] rounded-lg text-foreground border border-border bg-background hover:bg-muted transition-colors"
                >
                  <MoreHorizontal className="size-4" />
                </button>
              </DropdownMenuTrigger>
              {renderMoreMenuItems(job, { includeViewEdit: false })}
            </DropdownMenu>
          </div>
        </div>
      </div>

      {/* ─── Two-column layout ─────────────────────────────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-6 items-start">
        {/* ── Left column: main job details ── */}
        <div className="space-y-6 min-w-0">
          {/* ── Client + Job details (same row on desktop) ─────────────── */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
            {/* Client card */}
            <FormSectionCard icon={User} title="Client">
              <div className="space-y-2">
                <p className="text-base font-semibold text-foreground">{job.customerName || 'No client linked'}</p>
                {job.customerPhone && (
                  <a href={`tel:${job.customerPhone}`} className="flex items-center gap-2 text-sm text-emerald-700 hover:underline">
                    <Phone className="size-4" /> {job.customerPhone}
                  </a>
                )}
                {job.customerEmail && (
                  <a href={`mailto:${job.customerEmail}`} className="flex items-center gap-2 text-sm text-emerald-700 hover:underline">
                    <Mail className="size-4" /> {job.customerEmail}
                  </a>
                )}
                {job.address && (
                  <div className="flex items-start gap-2 text-sm text-muted-foreground">
                    <MapPin className="size-4 mt-0.5 shrink-0" /> <span>{job.address}</span>
                  </div>
                )}
                {!job.customerPhone && !job.customerEmail && !job.address && (
                  <p className="text-sm text-muted-foreground italic">No contact details on file.</p>
                )}
              </div>
            </FormSectionCard>

            {/* Job details card */}
            <FormSectionCard icon={Info} title="Job details">
              <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3">
                {detailRows.map((row, i) => (
                  <div key={i} className="flex items-start justify-between gap-3 border-b border-border/40 pb-2 last:border-0">
                    <dt className="text-sm text-muted-foreground shrink-0">{row.label}</dt>
                    <dd className="text-sm font-medium text-foreground text-right min-w-0 break-words">{row.value}</dd>
                  </div>
                ))}
              </dl>
            </FormSectionCard>
          </div>

          {/* ── V1.5: Lifecycle Timeline ─────────────────────────────────── */}
          <FormSectionCard icon={Activity} title="Lifecycle timeline" description="Track the job through its 8 stages — from assignment to invoice.">
            <LifecycleTimelineSection
              job={job}
              lifecycleData={lifecycleData}
            />
            {/* Quick action buttons for the current stage */}
            <div className="mt-4 flex flex-wrap gap-2 pt-3 border-t border-border/40">
              {job.status === 'assigned' && (
                <button
                  onClick={() => handleLifecycleTransition('accept', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 transition-colors shadow-sm"
                >
                  {lifecycleLoadingAction === 'accept' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Check className="size-4 mr-1.5" />} Accept
                </button>
              )}
              {job.status === 'accepted' && (
                <button
                  onClick={() => handleLifecycleTransition('start_travel', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-amber-500 hover:bg-amber-600 disabled:opacity-60 transition-colors shadow-sm"
                >
                  {lifecycleLoadingAction === 'start_travel' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Navigation className="size-4 mr-1.5" />} Start Travel
                </button>
              )}
              {job.status === 'travelling' && (
                <button
                  onClick={() => handleLifecycleTransition('arrive', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-amber-600 hover:bg-amber-700 disabled:opacity-60 transition-colors shadow-sm"
                >
                  {lifecycleLoadingAction === 'arrive' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <MapPin className="size-4 mr-1.5" />} Mark Arrived
                </button>
              )}
              {job.status === 'arrived' && (
                <button
                  onClick={() => handleLifecycleTransition('start_work', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 transition-colors shadow-sm"
                >
                  {lifecycleLoadingAction === 'start_work' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Wrench className="size-4 mr-1.5" />} Start Work
                </button>
              )}
              {job.status === 'working' && (
                <button
                  onClick={() => handleLifecycleTransition('pause', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted disabled:opacity-60 transition-colors"
                >
                  {lifecycleLoadingAction === 'pause' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Pause className="size-4 mr-1.5" />} Pause
                </button>
              )}
              {job.status === 'paused' && (
                <button
                  onClick={() => handleLifecycleTransition('resume', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 transition-colors shadow-sm"
                >
                  {lifecycleLoadingAction === 'resume' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <Play className="size-4 mr-1.5" />} Resume
                </button>
              )}
              {(job.status === 'working' || job.status === 'paused') && (
                <button
                  onClick={() => openCompletionDialog(job)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-green-600 hover:bg-green-700 disabled:opacity-60 transition-colors shadow-sm"
                >
                  <CheckCircle2 className="size-4 mr-1.5" /> Complete
                </button>
              )}
              {job.status === 'completed' && (
                <button
                  onClick={() => handleLifecycleTransition('generate_invoice', job.id)}
                  disabled={!!lifecycleLoadingAction}
                  className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-semibold text-white bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 transition-colors shadow-sm"
                >
                  {lifecycleLoadingAction === 'generate_invoice' ? <Loader2 className="size-4 mr-1.5 animate-spin" /> : <FileText className="size-4 mr-1.5" />} Generate Invoice
                </button>
              )}
            </div>
          </FormSectionCard>

          {/* ── Product / Service (line items) — immediately after timeline ── */}
          <FormSectionCard
            icon={Briefcase}
            title="Product / Service"
            action={<button onClick={() => openEditJob(job)} className="text-muted-foreground hover:text-emerald-600 transition-colors"><Pencil className="size-4" /></button>}
          >
            {lineItems.length === 0 ? (
              <p className="text-sm text-muted-foreground italic">No line items added to this job.</p>
            ) : (
              <div className="overflow-x-auto -mx-2">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-xs text-muted-foreground border-b border-border/60">
                      <th className="px-2 py-2 font-medium">Line Item</th>
                      <th className="px-2 py-2 font-medium text-center">Qty</th>
                      <th className="px-2 py-2 font-medium text-right">Unit Cost</th>
                      <th className="px-2 py-2 font-medium text-right">Unit Price</th>
                      <th className="px-2 py-2 font-medium text-right">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {lineItems.map((it, i) => (
                      <tr key={i} className="border-b border-border/40 last:border-0">
                        <td className="px-2 py-2.5 font-medium text-foreground">{it.name || 'Custom item'}{it.description && <span className="block text-xs text-muted-foreground font-normal">{it.description}</span>}</td>
                        <td className="px-2 py-2.5 text-center text-muted-foreground">{Number(it.quantity) || 0}</td>
                        <td className="px-2 py-2.5 text-right text-muted-foreground">{symbol}{(Number(it.unitCost) || 0).toFixed(2)}</td>
                        <td className="px-2 py-2.5 text-right text-muted-foreground">{symbol}{(Number(it.unitPrice) || 0).toFixed(2)}</td>
                        <td className="px-2 py-2.5 text-right font-semibold text-foreground">
                          {symbol}{((Number(it.unitPrice) || 0) * (Number(it.quantity) || 0)).toFixed(2)}
                          <span className="block text-[10px] font-normal text-muted-foreground/70">{Number(it.quantity) || 0} × {symbol}{(Number(it.unitPrice) || 0).toFixed(2)}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="border-t border-border/60">
                      <td colSpan={3} />
                      <td className="px-2 py-2 text-right text-sm text-muted-foreground">Total cost</td>
                      <td className="px-2 py-2 text-right text-sm text-muted-foreground">{symbol}{totalCost.toFixed(2)}</td>
                    </tr>
                    <tr>
                      <td colSpan={3} />
                      <td className="px-2 py-1 text-right text-sm font-semibold text-foreground">Total price</td>
                      <td className="px-2 py-1 text-right text-base font-bold text-foreground">{symbol}{totalPrice.toFixed(2)}</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            )}
          </FormSectionCard>

          {/* ── Expenses — immediately after Product / Service ───────────── */}
          <FormSectionCard icon={DollarSign} title="Expenses" description="Track all expenses for this job in one place.">
            <JobExpensesSection job={{ id: job.id, title: job.title, customerName: job.customerName }} />
          </FormSectionCard>

          {/* ── Scheduled visits — immediately after Expenses ───────────── */}
          <FormSectionCard icon={CalendarDays} title="Scheduled visits">
            <ScheduledVisitsSection
              job={{ id: job.id, title: job.title, customerName: job.customerName, jobNumber: job.jobNumber }}
              employees={employees.map((e) => ({ id: e.id, name: e.name }))}
              checklists={checklists.map((c) => ({ id: c.id, name: c.title }))}
            />
          </FormSectionCard>

          {/* ── V1.5: Time Tracking (live timer + entries log, merged) ──────── */}
          <FormSectionCard
            icon={Timer}
            title="Time tracking"
            description="Live timer for the active session, plus the full time log for this job."
          >
            <TimeTrackingSection
              job={job}
              lifecycleData={lifecycleData}
              liveTimerSeconds={liveTimerSeconds}
              lifecycleLoadingAction={lifecycleLoadingAction}
              onAction={handleLifecycleTransition}
              onOpenCompletion={() => openCompletionDialog(job)}
            />

            {/* Divider between the live-timer zone and the entries-log zone. */}
            <div className="border-t border-border/40 my-4" />

            <LaborSection
              jobId={job.id}
              employees={employees.map((e) => ({ id: e.id, name: e.name }))}
              canAdd={true}
              /* Hide the in-flight session from the list when the live timer
                 above is already showing it (job is working or paused). */
              hideActiveEntry={job.status === 'working' || job.status === 'paused'}
            />
          </FormSectionCard>

          {/* ── V1.5: GPS / Route summary ──────────────────────────────────── */}
          <FormSectionCard
            icon={MapPinned}
            title="GPS & route"
            description="Travel route, distance, and on-time arrival for this job."
          >
            <GpsRouteSection
              job={job}
              lifecycleData={lifecycleData}
              onOpenRoute={() => {
                if (job.assigneeId) {
                  fetchRouteData(job.assigneeId, job.id);
                  setShowRouteModal(true);
                }
              }}
            />
          </FormSectionCard>

          {/* ── PIN pipeline (Phase 6): Customer Verification card ─────────── */}
          {/* Shows the 4-digit verification PIN (when authorized), plus Resend */}
          {/* / Regenerate buttons and the notification dispatch history.       */}
          <FormSectionCard
            icon={ShieldCheck}
            title="Customer Verification"
            description="4-digit PIN sent to the customer for visit verification. Resend or regenerate as needed."
          >
            <CustomerVerificationCard job={job} />
          </FormSectionCard>

          {/* #job custom fields (only if any) */}
          {customFields.length > 0 && (
            <FormSectionCard icon={Tag} title="#job">
              <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-3">
                {customFields.map((f) => (
                  <div key={f.id} className="flex items-start justify-between gap-3 border-b border-border/40 pb-2 last:border-0">
                    <dt className="text-sm text-muted-foreground shrink-0">{f.label || '—'}</dt>
                    <dd className="text-sm font-medium text-foreground text-right min-w-0 break-words">{f.value || '—'}</dd>
                  </div>
                ))}
              </dl>
            </FormSectionCard>
          )}

          {/* Billing — Billing lifecycle split: read ACTUAL Invoice.status
              from the joined `job.invoices` array (latest first) instead of
              the previous hardcoded `job.status === 'completed' ? 'Paid' : 'Pending'`
              check which lied for any job past 'completed' (e.g. a job moved
              to 'invoice_generated' showed 'Pending' even though the invoice
              was sent or paid). The amount shown is now the real
              Invoice.total, not the UI-computed `totalPrice` sum of
              lineItemsJson. */}
          <FormSectionCard icon={FileText} title="Billing">
            <div className="space-y-2">
              <p className="text-xs text-muted-foreground">Invoice status & total</p>
              {(() => {
                // invoices are joined from GET /api/jobs/[id] ordered by
                // createdAt DESC, so [0] is the most recent. Most jobs have
                // 0 or 1 invoice; milestone-split jobs may have several.
                const invoice = job.invoices?.[0];
                if (!invoice) {
                  // No invoice yet — empty state with inline CTA.
                  return (
                    <div className="rounded-md border border-dashed border-border/60 px-3 py-3 flex items-center justify-between gap-3">
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-foreground">No invoice yet</p>
                        <p className="text-xs text-muted-foreground">
                          {symbol}{totalPrice.toFixed(2)} · ready to generate
                        </p>
                      </div>
                      <button
                        onClick={() => handleCreateInvoice(job)}
                        className="text-sm font-medium text-emerald-700 hover:text-emerald-800 inline-flex items-center gap-1 shrink-0"
                      >
                        <Plus className="size-3.5" /> Create
                      </button>
                    </div>
                  );
                }
                // Invoice exists — map status → label + Tailwind classes.
                // NOTE: avoids indigo/blue per design rules.
                const statusMap: Record<string, { label: string; className: string }> = {
                  paid: { label: 'Paid', className: 'bg-green-50 text-green-700 border-green-200' },
                  sent: { label: 'Sent', className: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
                  draft: { label: 'Draft', className: 'bg-muted text-muted-foreground border-border' },
                  overdue: { label: 'Overdue', className: 'bg-red-50 text-red-700 border-red-200' },
                  pending_approval: { label: 'Pending Approval', className: 'bg-amber-50 text-amber-700 border-amber-200' },
                  cancelled: { label: 'Cancelled', className: 'bg-muted text-muted-foreground border-border line-through' },
                };
                const info = statusMap[invoice.status] || {
                  label: invoice.status || 'Unknown',
                  className: 'bg-muted text-muted-foreground border-border',
                };
                const invoiceAmount = `${invoice.currency || 'USD'} ${Number(invoice.total).toFixed(2)}`;
                return (
                  <>
                    <div className="rounded-md border border-border/60 px-3 py-2.5 flex items-center justify-between gap-3">
                      <div className="min-w-0">
                        <p className="text-sm font-medium text-foreground truncate">
                          Invoice #{invoice.number}
                        </p>
                        <p className="text-xs text-muted-foreground truncate">
                          {info.label} · {invoiceAmount}
                        </p>
                      </div>
                      <Badge variant="outline" className={cn('shrink-0', info.className)}>
                        {info.label}
                      </Badge>
                    </div>
                    <div className="flex items-center justify-between gap-2">
                      <button
                        onClick={() => setActiveView('invoices')}
                        className="text-sm font-medium text-emerald-700 hover:text-emerald-800 inline-flex items-center gap-1"
                      >
                        <FileText className="size-3.5" /> View Invoice
                      </button>
                      {/* Only show "Regenerate" for draft invoices — sent /
                          paid invoices shouldn't be regenerated (would
                          create duplicates; the idempotency check returns
                          the existing one anyway, but better to hide the
                          button to avoid confusing the user). */}
                      {invoice.status === 'draft' && (
                        <button
                          onClick={() => handleCreateInvoice(job)}
                          className="text-sm font-medium text-emerald-700 hover:text-emerald-800 inline-flex items-center gap-1"
                        >
                          <Plus className="size-3.5" /> Regenerate
                        </button>
                      )}
                    </div>
                  </>
                );
              })()}
            </div>
          </FormSectionCard>

          {/* Attachments (only if any) */}
          {attachments.length > 0 && (
            <FormSectionCard icon={Paperclip} title="Attached files & photos">
              <div className="space-y-1.5">
                {attachments.map((att, idx) => {
                  const isImage = att.type?.startsWith('image/');
                  return (
                    <div key={idx} className="flex items-center gap-3 rounded-md border border-border/60 bg-background px-3 py-2">
                      {isImage ? (
                        <img src={att.url} alt={att.name} className="size-8 rounded object-cover shrink-0" />
                      ) : (
                        <div className="size-8 rounded bg-muted flex items-center justify-center shrink-0"><FileIcon className="size-4 text-muted-foreground" /></div>
                      )}
                      <div className="min-w-0 flex-1">
                        <p className="text-sm font-medium truncate">{att.name}</p>
                        {att.size ? <p className="text-xs text-muted-foreground">{formatFileSize(att.size)}</p> : null}
                      </div>
                      <a href={att.url} target="_blank" rel="noopener noreferrer" className="text-xs text-emerald-700 hover:underline shrink-0">View</a>
                    </div>
                  );
                })}
              </div>
            </FormSectionCard>
          )}

          {/* Linked checklists (only if any) */}
          {(linkedChecklists.length > 0 || linkedAssetId) && (
            <FormSectionCard
              icon={ClipboardList}
              title="On-site checklists"
              action={
                <Button
                  size="sm"
                  variant="outline"
                  className="gap-1.5"
                  onClick={() => setShowChecklistExecution((s) => !s)}
                >
                  {showChecklistExecution ? 'Hide' : 'Open checklist'}
                  <ChevronRight className={cn('size-3.5 transition-transform', showChecklistExecution && 'rotate-90')} />
                </Button>
              }
            >
              {showChecklistExecution ? (
                <ChecklistExecution jobId={job.id} />
              ) : (
                <div className="space-y-2">
                  {linkedChecklists.length === 0 ? (
                    <p className="text-sm text-muted-foreground italic">
                      No checklist template linked. Opening the runner will attempt to auto-create
                      one from this job&apos;s service template (if any).
                    </p>
                  ) : (
                    <div className="flex flex-wrap gap-1.5">
                      {linkedChecklists.map((cid) => (
                        <Badge key={cid} variant="secondary" className="bg-emerald-50 text-emerald-800 border-emerald-200 gap-1">
                          <ClipboardList className="size-3" /> {checklists.find((c) => c.id === cid)?.title || 'Checklist'}
                        </Badge>
                      ))}
                    </div>
                  )}
                  <p className="text-[11px] text-muted-foreground">
                    Tap “Open checklist” to fill it in on-site.
                  </p>
                </div>
              )}
            </FormSectionCard>
          )}

          {/* V1.5: Linked equipment (asset) */}
          {linkedAssetId && (
            <FormSectionCard icon={Wrench} title="Equipment serviced">
              {linkedAsset ? (
                <div className="flex items-start gap-3">
                  <div className="size-9 rounded-lg bg-emerald-50 flex items-center justify-center shrink-0">
                    <Wrench className="size-4 text-emerald-600" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-foreground">{linkedAsset.name}</p>
                    <div className="flex items-center gap-1.5 flex-wrap mt-0.5">
                      <Badge variant="outline" className="text-[10px] py-0 px-1.5 capitalize">
                        {linkedAsset.assetType}
                      </Badge>
                      {linkedAsset.brand && (
                        <span className="text-xs text-muted-foreground">
                          {linkedAsset.brand}{linkedAsset.model ? ` · ${linkedAsset.model}` : ''}
                        </span>
                      )}
                      {linkedAsset.serialNumber && (
                        <span className="text-xs text-muted-foreground font-mono">
                          S/N: {linkedAsset.serialNumber}
                        </span>
                      )}
                    </div>
                    <p className="text-[11px] text-muted-foreground mt-1">
                      Service history is tracked on this asset in the customer&apos;s Equipment tab.
                    </p>
                  </div>
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">
                  Linked asset <span className="font-mono text-xs">{linkedAssetId.slice(-8)}</span> (details unavailable)
                </p>
              )}
            </FormSectionCard>
          )}

          {/* V1.5: Before / After Photos */}
          <FormSectionCard
            icon={Camera}
            title="Photos"
            description="Before / after / progress / issue photos with GPS metadata"
            action={
              job.status === 'in_progress' && (
                <button
                  type="button"
                  onClick={() => openCompletionDialog(job)}
                  className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 hover:text-emerald-800"
                >
                  <CheckCircle2 className="size-3.5" /> Complete
                </button>
              )
            }
          >
            <PhotoCapture jobId={job.id} showTabs refreshKey={`${job.status}-${job.updatedAt || ''}`} />
          </FormSectionCard>

          {/* V1.5: Signatures */}
          <FormSectionCard
            icon={PenLine}
            title="Signatures"
            description="Customer + employee signatures collected at job completion"
          >
            <div className="space-y-4">
              {jobSignatures.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {jobSignatures.map((sig) => (
                    <div
                      key={sig.id}
                      className="rounded-lg border border-border/60 bg-background p-3 space-y-2"
                    >
                      <div className="flex items-center justify-between gap-2">
                        <Badge
                          variant="outline"
                          className={cn(
                            'text-[10px] capitalize',
                            sig.signatoryType === 'customer'
                              ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                              : 'bg-blue-50 text-blue-700 border-blue-200'
                          )}
                        >
                          {sig.signatoryType}
                        </Badge>
                        <span className="text-[10px] text-muted-foreground">
                          {new Date(sig.signedAt).toLocaleString()}
                        </span>
                      </div>
                      <img
                        src={sig.signatureUrl}
                        alt={`Signature by ${sig.signatoryName}`}
                        className="w-full h-16 object-contain bg-white rounded border border-border/40"
                      />
                      <div className="text-xs">
                        <p className="font-medium text-foreground">{sig.signatoryName}</p>
                        {sig.signatoryRole && (
                          <p className="text-muted-foreground">{sig.signatoryRole}</p>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground italic">No signatures collected yet.</p>
              )}

              {signaturePadType ? (
                <div className="rounded-lg border border-border/60 bg-muted/20 p-3 space-y-3">
                  <div className="flex items-center justify-between gap-2">
                    <h4 className="text-sm font-semibold capitalize">
                      Add {signaturePadType} signature
                    </h4>
                    <button
                      type="button"
                      onClick={() => setSignaturePadType(null)}
                      className="text-xs text-muted-foreground hover:text-foreground"
                    >
                      <X className="size-3.5" />
                    </button>
                  </div>
                  <SignaturePad
                    key={`${job.id}-${signaturePadType}`}
                    jobId={job.id}
                    signatoryType={signaturePadType}
                    defaultSignatoryName={
                      signaturePadType === 'employee'
                        ? (currentUser?.name || job.assigneeName || '')
                        : (job.customerName || '')
                    }
                    defaultSignatoryRole={
                      signaturePadType === 'employee' ? 'Technician' : 'Customer'
                    }
                    onSaved={() => {
                      fetchJobSignatures(job.id);
                      setSignaturePadType(null);
                    }}
                  />
                </div>
              ) : (
                <div className="flex flex-wrap gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setSignaturePadType('customer')}
                    className="bg-background"
                  >
                    <User className="size-4 mr-1.5" /> Add Customer Signature
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => setSignaturePadType('employee')}
                    className="bg-background"
                  >
                    <Wrench className="size-4 mr-1.5" /> Add Employee Signature
                  </Button>
                </div>
              )}
            </div>
          </FormSectionCard>

          {/* Notes */}
          <FormSectionCard icon={StickyNote} title="Notes">
            <div className="space-y-2">
              {(job.notes || job.description) && (
                <div className="rounded-md bg-muted/30 px-3 py-2.5">
                  <p className="text-xs text-muted-foreground mb-0.5">{formatDateTime(job.createdAt)}</p>
                  <p className="text-sm text-foreground whitespace-pre-wrap">{job.notes || job.description}</p>
                </div>
              )}
              {logs.length > 0 && (
                <div className="space-y-1.5">
                  <p className="text-xs font-medium text-muted-foreground pt-2">Activity log</p>
                  {logs.map((logRaw, i) => {
                    const log = logRaw as Record<string, unknown>;
                    return (
                    <div key={i} className="flex items-center gap-2 text-xs p-2 rounded bg-muted/40">
                      <Zap className="size-3 text-yellow-500 shrink-0" />
                      <span className="font-medium">{String(log.action)}</span>
                      {Boolean(log.resourceName) && <span className="text-muted-foreground">to {String(log.resourceName)}</span>}
                      {Boolean(log.timestamp) && <span className="text-muted-foreground ml-auto">{new Date(String(log.timestamp)).toLocaleString()}</span>}
                    </div>
                    );
                  })}
                </div>
              )}
              {!job.notes && !job.description && logs.length === 0 && (
                <p className="text-sm text-muted-foreground italic">No notes yet.</p>
              )}
            </div>
          </FormSectionCard>

          {/* Danger actions
              ── Issue 1: the legacy "Cancel Job" button was replaced by the
              "Close Job" item in the More menu. The More menu's Close Job
              action opens CloseJobDialog, which branches on recurring vs
              non-recurring and surfaces a confirmation. We keep the inline
              "Delete" shortcut on the detail page since destructive actions
              benefit from being visible + persistent (not buried in a menu). */}
          {!['completed', 'cancelled'].includes(job.status) && (
            <div className="flex flex-wrap gap-2 pt-2">
              <button
                onClick={() => handleCloseJobClick(job)}
                className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-medium text-emerald-700 border border-emerald-300 bg-background hover:bg-emerald-50 transition-colors"
              >
                <CheckCircle2 className="size-4 mr-1.5" /> Close Job
              </button>
              <button onClick={() => setDeletingJob(job)} className="inline-flex items-center justify-center min-h-[44px] px-4 rounded-lg text-sm font-medium text-red-600 border border-red-200 bg-background hover:bg-red-50 transition-colors">
                <Trash2 className="size-4 mr-1.5" /> Delete
              </button>
            </div>
          )}
        </div>

        {/* ── Right column: sidebar ── */}
        <div className="space-y-6 lg:sticky lg:top-4">
          {/* Profit margin */}
          <FormSectionCard icon={TrendingUp} title="Profit margin">
            <div className="space-y-2">
              <p className="text-3xl font-bold text-foreground">{profitPct.toFixed(1)}%</p>
              <div className="space-y-1 text-sm pt-1">
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Revenue</span>
                  <span className="font-medium text-foreground">{symbol}{totalPrice.toFixed(2)}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Line Item Cost</span>
                  <span className="text-muted-foreground">({symbol}{totalCost.toFixed(2)})</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Labor <span className="text-[10px]">({Math.round(jobLaborMinutes)}m)</span></span>
                  <span className="text-muted-foreground">({symbol}{laborCost.toFixed(2)})</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-muted-foreground">Expenses</span>
                  <span className="text-muted-foreground">({symbol}{expensesCost.toFixed(2)})</span>
                </div>
                <Separator className="my-2 bg-border/60" />
                <div className="flex items-center justify-between">
                  <span className="font-semibold text-foreground">Profit</span>
                  <span className="font-semibold text-foreground">{profitPct.toFixed(1)}% · {symbol}{profit.toFixed(2)}</span>
                </div>
              </div>
            </div>
          </FormSectionCard>

          {/* Quick actions */}
          <FormSectionCard icon={Briefcase} title="Actions">
            <div className="grid grid-cols-1 gap-2">
              <button onClick={() => openEditJob(job)} className="inline-flex items-center justify-start gap-2 min-h-[44px] px-3 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted transition-colors">
                <Pencil className="size-4" /> Edit job
              </button>
              <button onClick={handlePrintJob} className="inline-flex items-center justify-start gap-2 min-h-[44px] px-3 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted transition-colors">
                <Printer className="size-4" /> Print / PDF
              </button>
              <button onClick={() => handleEmailClient(job)} className="inline-flex items-center justify-start gap-2 min-h-[44px] px-3 rounded-lg text-sm font-medium text-foreground border border-border bg-background hover:bg-muted transition-colors">
                <Send className="size-4" /> Email client
              </button>
            </div>
          </FormSectionCard>
        </div>
      </div>
    </div>
  );
}
