import type { Metadata, Viewport } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/providers/query-provider";
import { PwaProvider } from "@/components/pwa/pwa-provider";
import { CookieConsentBanner } from "@/components/legal/cookie-consent-banner";
import { StructuredData } from "@/components/seo/structured-data";
import { WebVitalsReporter } from "@/components/seo/web-vitals-reporter";
import { Analytics } from "@/components/analytics/analytics";
import { getOrganizationSchema, getWebsiteSchema } from "@/lib/seo/schemas";
import { BRAND } from "@/lib/brand";

// P5 (Font CLS fix): Poppins with `display: "swap"` causes a FOUT (flash of
// unstyled text) where the fallback (Arial) is shown first, then swapped for
// Poppins when it loads — the metrics differ, causing a ~0.31 CLS score.
//
// Fix: `adjustFontFallback: true` tells Next.js to emit a `size-adjust` +
// metric override on the Arial fallback @font-face so it has the SAME advance
// width as Poppins. The swap becomes metric-invisible. This is the
// recommended Next.js pattern for CLS reduction with Google Fonts.
//
// All 6 weights are kept because the codebase uses font-light (300) through
// font-extrabold (800); removing any would cause faux-rendering (browser
// synthetically stretches the nearest available weight, which looks worse
// than the original CLS). With size-adjust the swap is CLS-free so keeping
// all weights has no CLS cost.
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
  preload: true,
  adjustFontFallback: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#10b981" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
};

export const metadata: Metadata = {
  // P0-3 (SEO): metadataBase makes all relative metadata URLs (canonical,
  // openGraph.url, openGraph.images, alternates) resolve to absolute
  // https://fieseros.com/... URLs. Without this, social scrapers and Google
  // see relative paths like "/og/og-default.png" which they can't resolve —
  // resulting in broken OG cards and canonical warnings in Search Console.
  metadataBase: new URL(BRAND.url),
  title: `${BRAND.name} - ${BRAND.tagline}`,
  description: BRAND.description,
  applicationName: BRAND.name,
  keywords: [BRAND.name, "field service", "SaaS", "job management", "email notifications", "SMS notifications", "push notifications", "invoicing", "workflow automation", "service business"],
  authors: [{ name: `${BRAND.name} Team` }],
  creator: BRAND.name,
  publisher: BRAND.name,
  manifest: '/manifest.json',
  formatDetection: { telephone: false },
  alternates: {
    canonical: '/',
  },
  icons: {
    icon: [
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
      { url: "/logo.svg", sizes: "any", type: "image/svg+xml" },
      { url: "/icon.svg", sizes: "any", type: "image/svg+xml" },
    ],
    // iOS requires a PNG apple-touch-icon (it does NOT render SVG). Ship a
    // real 180×180 PNG so "Add to Home Screen" shows our logo on iPhone.
    apple: [
      { url: "/icon-180.png", sizes: "180x180", type: "image/png" },
      { url: "/icon-167.png", sizes: "167x167", type: "image/png" },
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: BRAND.name,
  },
  openGraph: {
    title: `${BRAND.name} - ${BRAND.tagline}`,
    description: 'Replace scattered texts, emails, and spreadsheets with one powerful platform',
    type: 'website',
    siteName: BRAND.name,
    url: '/',
    locale: 'en_US',
    // OG image is auto-generated by src/app/opengraph-image.tsx (next/og).
    // No static /og/og-default.png file needed — Next.js injects the
    // <meta property="og:image"> tag automatically from the file convention.
  },
  twitter: {
    card: 'summary_large_image',
    title: `${BRAND.name} - ${BRAND.tagline}`,
    description: 'Replace scattered texts, emails, and spreadsheets with one powerful platform',
    // Twitter image also auto-injected from opengraph-image.tsx.
  },
};

// Whether to register the SW with ?dev=1 (dev mode bypasses caching so
// Next.js HMR works; production uses the plain /sw.js URL with full caching).
const IS_DEV = process.env.NODE_ENV !== 'production';
const SW_URL = IS_DEV ? '/sw.js?dev=1' : '/sw.js';

// ─── Approach B1: Intercepting Routes for /recurring-jobs/* ──────────────
// The root layout now accepts a `recurring` parallel-route slot. When a
// client-side navigation to /recurring-jobs/* is intercepted (via the
// @recurring/(.)recurring-jobs/* directory), the intercepted page renders
// in this slot INSTEAD of navigating to the real (app)/recurring-jobs/*
// route. The main `children` (the SPA shell at /) stays mounted — preserving
// ViewCache + all SPA view state (scroll, filters, form drafts).
//
// The slot content is passed to <RouteContentProvider> which makes it
// available via React Context to the deeply-nested <AppLayout> → <ViewCache>,
// which renders it as a special '__route__' view when usePathname() indicates
// we're on /recurring-jobs/*.
//
// Direct visits (hard refresh, external link) to /recurring-jobs/* bypass
// the intercepting route and hit the real (app)/recurring-jobs/* page +
// (app)/layout.tsx auth gate (renders <AppShell>). This is the correct
// behaviour for SEO + deep-linking.
//
// DEV NOTE: On low-memory dev sandboxes (4GB RAM), Turbopack may OOM during
// the first compilation of `/` because the parallel slot forces the entire
// intercepting graph to be evaluated. Production builds (Vercel/Netlify)
// compile at build time with ample RAM and are unaffected.
import { RouteContentProvider } from '@/components/layout/route-content-context';

export default function RootLayout({
  children,
  recurring,
}: Readonly<{
  children: React.ReactNode;
  // The `recurring` prop is the parallel-route slot populated by Next.js
  // when an intercepting route matches. When no interception is active,
  // Next.js renders `@recurring/default.tsx` (which returns null).
  recurring?: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="msapplication-TileColor" content="#10b981" />
        {/*
          PERF-2: Removed unused Google Fonts preconnect/dns-prefetch hints.
          next/font/google SELF-HOSTS Poppins + Geist Mono — the font files
          are served from /_next/static/media/*, never from fonts.googleapis.com
          or fonts.gstatic.com. Lighthouse flagged all 4 hints as "unused
          preconnect" because the browser set up DNS+TLS connections to Google
          that were never used, wasting ~100ms of connection setup.
        */}
        <link rel="icon" href="/favicon.png" type="image/png" sizes="32x32" />
        <link rel="icon" href="/favicon-16.png" type="image/png" sizes="16x16" />
        <link rel="apple-touch-icon" href="/icon-180.png" />
        <link rel="apple-touch-icon" sizes="167x167" href="/icon-167.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icon-180.png" />
        <link rel="apple-touch-startup-image" href="/icon-512.png" />
        {/*
          Synchronous service worker registration.
          ------------------------------------------
          PWABuilder / Lighthouse / Android APK generators check whether a
          service worker is registered within ~3 seconds of the first page
          load. Registering inside a React useEffect (in PwaProvider) is
          too late — by the time React hydrates and the effect runs, the
          audit has already finished and reports "no service worker".

          By putting the registration in an inline <script> in <head>, the
          browser runs it synchronously during HTML parsing, BEFORE any
          JS bundle is fetched. PWABuilder immediately detects the SW and
          unblocks APK packaging.

          The register() call itself is async (returns a Promise) but the
          network request for /sw.js is fired synchronously, which is what
          the audit looks for. The SW then installs + activates
          (clients.claim() takes control of the page) on its own schedule.

          Calling register() multiple times is safe — browsers dedupe by
          URL. The PwaProvider component keeps its own register() call
          (harmless duplicate) plus renders the install/update prompts.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `if('serviceWorker' in navigator){navigator.serviceWorker.register('${SW_URL}',{scope:'/'}).catch(function(){})}`,
          }}
        />
        {/* Google Analytics 4 (gtag.js) with Consent Mode v2.
            Loaded on every page. Default consent is "denied" until the
            cookie banner receives an explicit accept. See
            src/components/analytics/analytics.tsx for the full flow. */}
        <Analytics />
      </head>
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased bg-background text-foreground font-sans`}
      >
        {/* Skip link (P0 a11y fix) — first focusable element on every page.
            Visually hidden by default (`sr-only`), becomes visible when
            focused via keyboard navigation (`focus:not-sr-only ...`). Lets
            keyboard users jump straight to main content instead of tabbing
            through the entire header + nav on every page. The
            `href="#main-content"` matches the `id="main-content"` we add to
            the <main> element on the marketplace browse page (and any other
            page that opts in). Pages without an element bearing that id
            simply don't scroll — the link is still focusable + announced by
            screen readers as "Skip to main content". */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:absolute focus:top-2 focus:left-2 focus:z-50 focus:px-4 focus:py-2 focus:bg-background focus:text-foreground focus:border focus:border-border focus:rounded-md focus:shadow-lg focus:outline-2 focus:outline-emerald-600"
        >
          Skip to main content
        </a>
        {/* Site-wide structured data: Organization + WebSite schema.
            Injected on every page so Google can understand the entity. */}
        <StructuredData
          data={[getOrganizationSchema(), getWebsiteSchema()]}
        />
        <QueryProvider>
          {children}
          <Toaster position="top-center" />
          <PwaProvider />
          <CookieConsentBanner />
          {/* P3-1 (SEO): Core Web Vitals RUM — reports field CLS/INP/LCP/FCP/TTFB
              to /api/vitals for production performance monitoring. */}
          <WebVitalsReporter />
        </QueryProvider>
      </body>
    </html>
  );
}
