import type { MetadataRoute } from "next";
import {
  listIndexableBusinessUrls,
  countIndexableBusinessTenants,
} from "@/lib/public-business";
import { getAllPosts } from "@/lib/blog";
import { db } from "@/lib/db";
import {
  mapIndustryToPluralSlug,
  PLURAL_SLUG_TO_INDUSTRY,
} from "@/lib/seo/plural-industry-slugs";

/**
 * Dynamic sitemap-index for Fieseros public pages.
 *
 * FIX (Q2-Fix 2): Previously this was a single `MetadataRoute.Sitemap`
 * generator. With ~100K marketplace tenants, a single sitemap would exceed
 * Google's 50,000-URL-per-file cap. We now use Next.js's `generateSitemaps()`
 * pattern to split into multiple files:
 *
 *   /sitemap.xml          → sitemap index (auto-generated by Next.js)
 *   /sitemap/0.xml        → static + blog + industry hubs + browse (~266 URLs)
 *   /sitemap/1.xml        → business hub pages, page 1 (≤40K URLs)
 *   /sitemap/2.xml        → business hub pages, page 2 (≤40K URLs)
 *   ...
 *
 * Each business file is capped at BUSINESS_PER_FILE = 40,000 URLs (safe
 * margin under Google's 50K limit). The total file count is computed from
 * `countIndexableBusinessTenants()` so it scales with the marketplace.
 *
 * Authenticated app routes and API routes are intentionally omitted —
 * they should not be indexed.
 */

const BUSINESS_PER_FILE = 40_000;

/**
 * Returns the list of sitemap IDs. Next.js generates a sitemap index at
 * `/sitemap.xml` linking to `/sitemap/{id}.xml` for each ID.
 *
 *   ID 0           = static + blog + industry hubs + browse (always 1 file)
 *   IDs 1..N       = business hub pages, paginated at BUSINESS_PER_FILE each
 *
 * If the business count is 0 (e.g. DB unavailable), we still emit ID 0 so
 * the static routes are always discoverable.
 */
export async function generateSitemaps(): Promise<number[]> {
  let businessCount = 0;
  try {
    businessCount = await countIndexableBusinessTenants();
  } catch (err) {
    console.error("[sitemap] countIndexableBusinessTenants failed:", err);
    businessCount = 0;
  }
  const businessFileCount = Math.max(1, Math.ceil(businessCount / BUSINESS_PER_FILE));
  // ID 0 = static/etc, IDs 1..businessFileCount = business pages
  return Array.from({ length: 1 + businessFileCount }, (_, i) => i);
}

/**
 * The static + blog + industry-hub + browse sitemap (ID 0).
 *
 * Extracted so the main `sitemap({ id })` switch stays readable.
 */
async function buildStaticSitemap(base: string): Promise<MetadataRoute.Sitemap> {
  const now = new Date().toISOString();

  const staticRoutes: {
    path: string;
    priority: number;
    changeFreq: MetadataRoute.Sitemap[number]["changeFrequency"];
  }[] = [
    // ─── Core ────────────────────────────────────────────────────────────
    { path: "", priority: 1.0, changeFreq: "weekly" },

    // ─── Marketplace (Phase 13 — dual-audience landing + marketplace routes)
    { path: "/marketplace", priority: 0.9, changeFreq: "weekly" },

    // ─── Cornerstone: Industry pages (high commercial intent) ────────────
    { path: "/field-service-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/plumbing-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/hvac-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/cleaning-business-software", priority: 0.9, changeFreq: "monthly" },
    {
      path: "/electrical-contractor-software",
      priority: 0.9,
      changeFreq: "monthly",
    },
    { path: "/landscaping-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/lawn-care-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/painting-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/handyman-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/tree-care-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/snow-removal-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/pest-control-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/roofing-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/pool-service-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/window-cleaning-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/concrete-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/garage-door-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/solar-software", priority: 0.9, changeFreq: "monthly" },
    { path: "/pet-services-software", priority: 0.9, changeFreq: "monthly" },

    // ─── Cornerstone: Comparison pages (high conversion intent) ──────────
    { path: "/jobber-alternatives", priority: 0.9, changeFreq: "monthly" },
    {
      path: "/housecall-pro-alternatives",
      priority: 0.8,
      changeFreq: "monthly",
    },
    {
      path: "/servicetitan-alternatives",
      priority: 0.8,
      changeFreq: "monthly",
    },
    {
      path: "/best-field-service-software",
      priority: 0.9,
      changeFreq: "monthly",
    },

    // ─── Cornerstone: Feature pages ──────────────────────────────────────
    { path: "/scheduling-and-dispatch", priority: 0.8, changeFreq: "monthly" },
    { path: "/invoicing-and-payments", priority: 0.8, changeFreq: "monthly" },
    { path: "/customer-crm", priority: 0.8, changeFreq: "monthly" },
    { path: "/technician-app", priority: 0.8, changeFreq: "monthly" },
    { path: "/automations", priority: 0.8, changeFreq: "monthly" },

    // ─── Free tools (link magnets) ───────────────────────────────────────
    { path: "/invoice-generator", priority: 0.9, changeFreq: "monthly" },

    // ─── Blog (informational content hub — drives top-of-funnel traffic) ─
    { path: "/blog", priority: 0.8, changeFreq: "weekly" },

    // ─── Contact & legal (low priority, rarely change) ───────────────────
    { path: "/contact-us", priority: 0.6, changeFreq: "monthly" },
    { path: "/privacy-policy", priority: 0.3, changeFreq: "yearly" },
    { path: "/terms-of-service", priority: 0.3, changeFreq: "yearly" },
    { path: "/cookie-policy", priority: 0.3, changeFreq: "yearly" },
    { path: "/data-deletion", priority: 0.3, changeFreq: "yearly" },
  ];

  const staticEntries: MetadataRoute.Sitemap = staticRoutes.map((r) => ({
    url: `${base}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFreq,
    priority: r.priority,
  }));

  // Dynamic: blog articles (from MDX files in content/blog/).
  const blogEntries: MetadataRoute.Sitemap = getAllPosts().map((post) => ({
    url: `${base}/blog/${post.slug}`,
    lastModified: post.date,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  // ── Industry-only hub pages (/{pluralIndustry}) ──────────────────────────
  const industryHubEntries: MetadataRoute.Sitemap = Object.keys(
    PLURAL_SLUG_TO_INDUSTRY
  ).map((slug) => ({
    url: `${base}/${slug}`,
    lastModified: now,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  // ── Dynamic: plural browse pages (/{pluralIndustry}/{city}) ───────────────
  // Top 50 cities × 4 most popular industries = up to 200 high-intent
  // "category + location" landing pages. Demand-gated: only emit entries
  // for (city, industry) combos that have ≥1 provider.
  let browseEntries: MetadataRoute.Sitemap = [];
  try {
    const cities = await db.directoryLocation.findMany({
      where: { isActive: true },
      orderBy: { population: "desc" },
      take: 50,
      select: { citySlug: true },
    });
    const topIndustries = ["plumbing", "electrical", "cleaning", "hvac"];

    // FIX (Q2-Fix 1, secondary): The demand query also used `findMany`
    // without `take`, so under Supabase it would silently cap at 1000 rows.
    // With 100K marketplace tenants, the top-industries subset can easily
    // exceed 1000. Paginate the demand fetch the same way as
    // listIndexableBusinessUrls.
    const demandKeys = new Set<string>();
    const PAGE_SIZE = 1000;
    let skip = 0;
    while (true) {
      const page = await db.tenant.findMany({
        where: {
          publicProfileEnabled: true,
          marketplaceOptIn: true,
          suspendedAt: null,
          OR: topIndustries.flatMap((industry) => [
            { industry: { equals: industry } },
            { businessCategoriesJson: { contains: `"${industry}"` } },
          ]),
        },
        select: {
          industry: true,
          city: true,
          businessCategoriesJson: true,
        },
        skip,
        take: PAGE_SIZE,
        orderBy: { id: "asc" },
      });
      if (!page || page.length === 0) break;
      for (const t of page) {
        if (!t.city) continue;
        const citySlug = t.city
          .toLowerCase()
          .replace(/[^a-z0-9\s-]/g, "")
          .replace(/\s+/g, "-")
          .replace(/-+/g, "-")
          .trim();
        if (!citySlug) continue;
        for (const industry of topIndustries) {
          const matches =
            t.industry === industry ||
            t.businessCategoriesJson?.includes(`"${industry}"`);
          if (matches) {
            demandKeys.add(`${citySlug}|${industry}`);
          }
        }
      }
      if (page.length < PAGE_SIZE) break;
      skip += page.length;
    }

    for (const city of cities) {
      for (const industry of topIndustries) {
        if (!demandKeys.has(`${city.citySlug}|${industry}`)) continue;
        const plural = mapIndustryToPluralSlug(industry);
        browseEntries.push({
          url: `${base}/${plural}/${city.citySlug}`,
          lastModified: now,
          changeFrequency: "weekly" as const,
          priority: 0.8,
        });
      }
    }
  } catch (err) {
    console.error("[sitemap] failed to list plural browse URLs:", err);
  }

  return [...staticEntries, ...blogEntries, ...industryHubEntries, ...browseEntries];
}

/**
 * Build a single business-page sitemap chunk (IDs 1..N).
 *
 * Calls `listIndexableBusinessUrls({ offset, limit })` which paginates the
 * underlying DB query with `skip`/`take` — bypassing the Supabase
 * PostgREST 1000-row default cap (Q2-Fix 1).
 */
async function buildBusinessSitemap(
  base: string,
  pageZeroIndexed: number,
): Promise<MetadataRoute.Sitemap> {
  const now = new Date().toISOString();
  const offset = pageZeroIndexed * BUSINESS_PER_FILE;
  try {
    const businessUrls = await listIndexableBusinessUrls({
      offset,
      limit: BUSINESS_PER_FILE,
    });
    return businessUrls.map((entry) => {
      const tier = (entry as { tier?: "A" | "B" }).tier;
      const priority = tier === "A" ? 0.8 : tier === "B" ? 0.5 : 0.7;
      return {
        url: entry.url,
        lastModified: entry.lastModified || now,
        changeFrequency: "weekly" as const,
        priority,
      };
    });
  } catch (err) {
    console.error(
      `[sitemap] failed to list business URLs for page ${pageZeroIndexed}:`,
      err,
    );
    return [];
  }
}

export default async function sitemap({
  id,
}: {
  id: number;
}): Promise<MetadataRoute.Sitemap> {
  const base = "https://fieseros.com";
  if (id === 0) {
    return buildStaticSitemap(base);
  }
  return buildBusinessSitemap(base, id - 1);
}
