/**
 * Shared sitemap route helpers — used by sitemap.xml, sitemap1.xml, sitemap2.xml, sitemap3.xml.
 *
 * Each route serves a static XML file (NO DB queries at runtime).
 * Files are generated by the daily cron + stored in /tmp + Supabase Storage.
 */

import { NextResponse } from 'next/server';
import { fetchSitemapFile } from '@/lib/sitemap/storage';
import { getSitemapFileName } from '@/lib/sitemap/hash';

/**
 * Serve a sitemap file by bucket number (0-3).
 *
 * Reads the static XML file from:
 *   1. /tmp/sitemaps/ (cron-generated, fresh) — instant
 *   2. public/sitemap/ (build-time fallback) — instant
 *   3. Supabase Storage (persistent backup) — ~50ms
 *
 * NO DB queries — this is a pure file read. Response time: <10ms.
 *
 * @param fileNumber - 0 (sitemap.xml), 1 (sitemap1.xml), 2 (sitemap2.xml), 3 (sitemap3.xml)
 */
export async function serveSitemapFile(fileNumber: number): Promise<NextResponse> {
  const fileName = getSitemapFileName(fileNumber);

  // Fetch the static file (no DB query)
  const xml = await fetchSitemapFile(fileName);

  if (xml && xml.length > 0) {
    const buf = Buffer.from(xml, 'utf-8');
    const res = new NextResponse(buf, {
      status: 200,
      headers: {
        'Content-Type': 'application/xml; charset=UTF-8',
        'Content-Length': String(buf.length),
        'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=3600',
      },
    });
    // Override vary to remove Next.js RSC headers that confuse Google
    res.headers.set('vary', 'Accept-Encoding');
    return res;
  }

  // File not found — return 404 (Google will retry on next crawl)
  return new NextResponse(`${fileName} not yet generated`, { status: 404 });
}
