import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getAuthUser } from '@/lib/auth';
import { requirePlanFeature } from '@/lib/plan-gate';

// ─── GET /api/recurring-jobs/[id]/invoices ──────────────────────────────────
//
// Returns the invoices generated by a recurring schedule.
//
// The Invoice table has a direct FK `recurringScheduleId` (Phase C — see
// prisma/schema.prisma lines 809+), populated when invoiceTiming='on_generation'
// (the engine creates the invoice at job-creation time, linked directly to the
// schedule, NOT via the Job). Invoices generated via invoiceTiming='on_completion'
// are linked via `jobId` to the generated Job — they will NOT appear in this
// endpoint's response unless they were also stamped with recurringScheduleId
// (which the on_completion path doesn't do — it relies on the Job → Invoice
// relation instead).
//
// For the Billing tab's purposes, the on_generation invoices are the ones that
// are unambiguously owned by THIS schedule. Invoices generated via on_completion
// are surfaced indirectly through the Generated Jobs tab (each job's invoices).
//
// Response shape:
//   { invoices: Array<Invoice>, total: number }
//
// Auth: must be the schedule's owning tenant. Plan-gated to `recurring_jobs`.
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await getAuthUser();
    if (!user || !user.tenantId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const gate = await requirePlanFeature('recurring_jobs');
    if (!gate.ok) {
      return NextResponse.json({ error: gate.reason }, { status: gate.status });
    }

    const { id } = await params;

    const schedule = await db.recurringJobSchedule.findUnique({
      where: { id },
      select: { id: true, tenantId: true, title: true },
    });
    if (!schedule) {
      return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
    }
    if (schedule.tenantId !== user.tenantId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    // Pull every invoice whose `recurringScheduleId` points to this schedule.
    // Scoped to the user's tenant for defense in depth — the FK alone is
    // authoritative but tenant filtering is cheap and prevents any accidental
    // cross-tenant leak if a future bug were to mis-set recurringScheduleId.
    const invoices = await db.invoice.findMany({
      where: {
        recurringScheduleId: id,
        tenantId: user.tenantId,
      },
      orderBy: { createdAt: 'desc' },
      select: {
        id: true,
        number: true,
        status: true,
        amount: true,
        tax: true,
        discount: true,
        total: true,
        currency: true,
        dueDate: true,
        sentAt: true,
        paidAt: true,
        createdAt: true,
      },
    });

    return NextResponse.json({ invoices, total: invoices.length });
  } catch (error) {
    console.error('Get recurring-jobs/[id]/invoices error:', error);
    return NextResponse.json({ error: 'Failed to fetch generated invoices' }, { status: 500 });
  }
}
