'use client';
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Check, CreditCard, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { authFetch } from '@/lib/client-auth';
type Billing = { subscription: { plan: string; status: string; legacy: boolean; currentPeriodEnd: string | null }; usage: { contacts: number; forms: number; usedLeadCredits: number; leadCreditLimit: number }; portalEnabled: boolean; plans: { code: string; name: string; priceInr: number; features: string[]; checkoutEnabled: boolean }[] };
export function BgosBilling() {
  const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  const query = useQuery({ queryKey: ['bgos','billing'], queryFn: async (): Promise<Billing> => { const res = await authFetch('/api/bgos/billing'); const data = await res.json(); if (!res.ok) throw new Error(data.error); return data; } });
  async function checkout(body: object) { setBusy(true); setError(''); try { const res = await authFetch('/api/bgos/billing', { method: 'POST', headers: { 'Content-Type':'application/json' }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); const url = new URL(data.url); if (!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname) || url.protocol !== 'https:') throw new Error('Invalid billing destination'); window.location.assign(url.toString()); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Workspace / Plan & usage</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Room for your next stage.</h1><p className="mt-2 text-sm text-muted-foreground">Monthly plans in INR. Your subscription changes after payment is confirmed.</p></header>{query.isPending && <p role="status">Loading subscription…</p>}{(error || query.error) && <div role="alert" className="rounded-xl border border-destructive/30 p-4 text-sm text-destructive">{error || query.error?.message}<Button variant="outline" className="ml-3" onClick={() => query.refetch()}>Retry</Button></div>}{query.data && <><section className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-card p-6"><div><h2 className="font-semibold">Current plan: {query.data.subscription.plan}</h2><p className="mt-2 text-sm text-muted-foreground">{query.data.subscription.status} · {query.data.usage.contacts} contacts · {query.data.usage.forms} active forms · {query.data.usage.usedLeadCredits}/{query.data.usage.leadCreditLimit} lead credits used</p>{query.data.subscription.currentPeriodEnd && <p className="mt-1 text-xs text-muted-foreground">Current period ends {new Date(query.data.subscription.currentPeriodEnd).toLocaleDateString()}</p>}</div>{query.data.portalEnabled && <Button variant="outline" disabled={busy} onClick={() => checkout({ action:'portal' })}><CreditCard className="mr-2 size-4" />Manage subscription</Button>}</section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{query.data.plans.map(plan => <div key={plan.code} className="flex flex-col rounded-2xl border bg-card p-6"><h2 className="font-semibold">{plan.name}</h2><p className="mt-5 text-3xl font-semibold tracking-tight">₹{plan.priceInr.toLocaleString('en-IN')}<span className="text-xs font-normal text-muted-foreground"> / month</span></p><ul className="my-6 flex-1 space-y-3">{plan.features.map(feature => <li key={feature} className="flex gap-2 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-primary" />{feature}</li>)}</ul><Button disabled={busy || !plan.checkoutEnabled || query.data.subscription.plan === plan.code || query.data.portalEnabled} variant={plan.code === 'growth' ? 'default' : 'outline'} onClick={() => checkout({ plan: plan.code })}>{busy ? <Loader2 className="size-4 animate-spin" /> : query.data.subscription.plan === plan.code ? 'Current plan' : plan.code === 'free' ? 'Included at signup' : !plan.checkoutEnabled ? 'Checkout not configured' : query.data.portalEnabled ? 'Use subscription settings' : `Choose ${plan.name}`}</Button></div>)}</section></>}</div>;
}
