import {
  buildStaticSitemap,
  buildBusinessSitemap,
  serializeUrlSet,
  getSitemapIds,
} from "@/lib/sitemap-builder";

/**
 * GET /sitemap/[id] — individual sitemap file.
 *
 * Serves a `<urlset>` XML document for a single sitemap page:
 *   - id 0           → static + blog + industry hubs + browse URLs
 *   - id 1..N        → business hub pages (paginated at 40K URLs each)
 *
 * URL FORMAT:
 * The dynamic `[id]` segment matches the full path tail, so BOTH of these
 * work:
 *   /sitemap/0        → id = "0"
 *   /sitemap/0.xml    → id = "0.xml"  (we strip the .xml suffix)
 *
 * This preserves backward compatibility with the URLs that were previously
 * auto-generated by `src/app/sitemap.ts` (which used the `/sitemap/{id}.xml`
 * format). The sitemap index at `/sitemap.xml` links to the `.xml` variants.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id: rawId } = await params;

    // Strip optional .xml suffix (supports both /sitemap/0 and /sitemap/0.xml)
    const idStr = rawId.replace(/\.xml$/i, "");
    const id = parseInt(idStr, 10);

    if (isNaN(id) || id < 0) {
      return new Response("Invalid sitemap id", { status: 404 });
    }

    // Validate the requested id is within the valid range. This prevents
    // crawlers from hammering non-existent sitemap pages.
    const validIds = await getSitemapIds();
    const maxId = validIds.length > 0 ? validIds[validIds.length - 1].id : 0;
    if (id > maxId) {
      return new Response("Sitemap not found", { status: 404 });
    }

    const entries =
      id === 0
        ? await buildStaticSitemap()
        : await buildBusinessSitemap(id - 1);

    const xml = serializeUrlSet(entries);

    return new Response(xml, {
      headers: {
        "Content-Type": "application/xml; charset=UTF-8",
        // Cache at the CDN for 24 HOURS. After that, the CDN may serve a
        // STALE response for another 24h while regenerating in the background.
        //
        // WHY 24h (was 1h):
        //   Sitemaps don't change often — Google re-crawls on its own schedule
        //   (hours to days). A 1h TTL meant the CDN cache expired frequently,
        //   and the next Googlebot fetch hit a cold cache (30s+ generation on
        //   Supabase) → "Sitemap could not be read" in Search Console.
        //   With 24h max-age + 24h SWR, Googlebot ALWAYS gets an instant
        //   response, and the sitemap-warm cron (every 30 min) keeps the
        //   in-memory cache fresh so regeneration is fast when the CDN does
        //   revalidate.
        "Cache-Control": "public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400",
      },
    });
  } catch (error) {
    console.error("[sitemap/[id]] Failed to generate sitemap:", error);
    return new Response(
      '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>',
      {
        status: 200,
        headers: {
          "Content-Type": "application/xml; charset=UTF-8",
        },
      },
    );
  }
}
