import {
  buildStaticSitemap,
  buildBusinessSitemap,
  serializeUrlSet,
  getSitemapIds,
  getCachedSitemapXml,
} from "@/lib/sitemap-builder";
import { sharedCacheSet } from "@/lib/shared-cache";

/**
 * GET /sitemap/[id] — individual sitemap file.
 *
 * Serves a `<urlset>` XML document for a single sitemap page:
 *   - id 0           → static + blog + industry hubs + browse URLs
 *   - id 1..N        → business hub pages (paginated at 2,500 URLs each)
 *
 * URL FORMAT:
 * The dynamic `[id]` segment matches the full path tail, so BOTH of these
 * work:
 *   /sitemap/0        → id = "0"
 *   /sitemap/0.xml    → id = "0.xml"  (we strip the .xml suffix)
 *
 * This preserves backward compatibility with the URLs that were previously
 * auto-generated by `src/app/sitemap.ts` (which used the `/sitemap/{id}.xml`
 * format). The sitemap index at `/sitemap.xml` links to the `.xml` variants.
 *
 * CACHE STRATEGY (3 layers, fastest first):
 *   1. Pre-serialized XML in Redis (`fieseros:sitemap:xml:{id}`)
 *      → Instant (~50ms). Populated by the sitemap-warm cron every 30 min.
 *        Each page stored as its own key (~250KB, well under Upstash's
 *        10MB limit). This is the primary path.
 *   2. Fallback: build + serialize on-the-fly, then cache the result
 *      → Slow on first hit (~3-15s on Supabase), but caches the XML for
 *        subsequent requests. Used when the warm cron hasn't run yet or
 *        the Redis key expired.
 *   3. CDN edge cache (24h max-age + 24h SWR via Cache-Control header)
 *      → Vercel's edge network serves the response without hitting the
 *        function at all. This is the outermost layer.
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id: rawId } = await params;

    // Strip optional .xml suffix (supports both /sitemap/0 and /sitemap/0.xml)
    const idStr = rawId.replace(/\.xml$/i, "");
    const id = parseInt(idStr, 10);

    if (isNaN(id) || id < 0) {
      return new Response("Invalid sitemap id", { status: 404 });
    }

    // ── Layer 1: Try pre-serialized XML from Redis ────────────────────────
    // This is the fast path — zero DB queries, zero JSON parsing, zero
    // serialization. Just a single Redis GET returning a ~250KB string.
    const cachedXml = await getCachedSitemapXml(id);
    if (cachedXml) {
      return new Response(cachedXml, {
        headers: {
          "Content-Type": "application/xml; charset=UTF-8",
          "Cache-Control":
            "public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400",
        },
      });
    }

    // ── Layer 2: Fallback — build on-the-fly + cache for next time ────────
    // Validate the requested id is within the valid range before building.
    const validIds = await getSitemapIds();
    const maxId = validIds.length > 0 ? validIds[validIds.length - 1].id : 0;
    if (id > maxId) {
      return new Response("Sitemap not found", { status: 404 });
    }

    const entries =
      id === 0
        ? await buildStaticSitemap()
        : await buildBusinessSitemap(id - 1);

    const xml = serializeUrlSet(entries);

    // Cache the serialized XML so the next request hits Layer 1 (instant).
    // Fire-and-forget — don't block the response on the Redis SET.
    // Skip caching empty business pages (transient failure protection).
    if (entries.length > 0 || id === 0) {
      void sharedCacheSet(
        `fieseros:sitemap:xml:${id}`,
        xml,
        60 * 60 * 1000, // 1h fresh
        24 * 60 * 60 * 1000, // 24h stale
      ).catch(() => {
        // Redis SET failure is non-fatal — the response is already built.
      });
    }

    return new Response(xml, {
      headers: {
        "Content-Type": "application/xml; charset=UTF-8",
        // Cache at the CDN for 24 HOURS. After that, the CDN may serve a
        // STALE response for another 24h while regenerating in the background.
        //
        // WHY 24h (was 1h):
        //   Sitemaps don't change often — Google re-crawls on its own schedule
        //   (hours to days). A 1h TTL meant the CDN cache expired frequently,
        //   and the next Googlebot fetch hit a cold cache (30s+ generation on
        //   Supabase) → "Sitemap could not be read" in Search Console.
        //   With 24h max-age + 24h SWR, Googlebot ALWAYS gets an instant
        //   response, and the sitemap-warm cron (every 30 min) keeps the
        //   in-memory cache fresh so regeneration is fast when the CDN does
        //   revalidate.
        "Cache-Control": "public, max-age=86400, s-maxage=86400, stale-while-revalidate=86400",
      },
    });
  } catch (error) {
    console.error("[sitemap/[id]] Failed to generate sitemap:", error);
    // Return 503 (not 200) so Googlebot retries instead of recording
    // "Sitemap could not be read" as a permanent failure. A 200 with empty
    // <urlset> was being interpreted as "sitemap exists but has no URLs" —
    // Google dropped all discovered URLs. With 503 + Retry-After, Google
    // will retry within hours.
    return new Response(
      '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>',
      {
        status: 503,
        headers: {
          "Content-Type": "application/xml; charset=UTF-8",
          "Retry-After": "300",
        },
      },
    );
  }
}
