import type { BusinessType, BusinessCapabilities } from './types';

export const BUSINESS_TYPE_LABELS: Record<BusinessType, { label: string; icon: string; subtitle: string }> = {
  retail: {
    label: 'Retail / Shop',
    icon: '🛍️',
    subtitle: 'Clothing, electronics, general retail, gifts, cosmetics',
  },
  restaurant: {
    label: 'Restaurant / Café',
    icon: '🍽️',
    subtitle: 'Dine-in, takeaway, food truck, cloud kitchen, café, bakery',
  },
  grocery: {
    label: 'Grocery / Supermarket',
    icon: '🏪',
    subtitle: 'Daily essentials, produce, marts, supermarkets, kirana',
  },
  services: {
    label: 'Service Business / Trades',
    icon: '🔧',
    subtitle: 'Plumbing, HVAC, electrical, cleaning, maintenance, roofing',
  },
  salon: {
    label: 'Salon / Beauty / Spa',
    icon: '💇',
    subtitle: 'Hair salons, barbershops, nail studios, aesthetics, massage',
  },
  wholesale: {
    label: 'Wholesale / Distribution',
    icon: '📦',
    subtitle: 'B2B supply, bulk inventory, distributors, traders',
  },
  freelancer: {
    label: 'Freelancer / Professional',
    icon: '🧑‍💻',
    subtitle: 'Consulting, design, legal, marketing, software, photography',
  },
  online_store: {
    label: 'Online Store / Brand',
    icon: '📱',
    subtitle: 'Direct-to-consumer brand, social commerce, catalog sales',
  },
  manufacturing: {
    label: 'Manufacturing / Workshop',
    icon: '🏭',
    subtitle: 'Fabrication, assembly, production workshops, packaging',
  },
  other: {
    label: 'Other Business',
    icon: '🏢',
    subtitle: 'Custom business setup tailored to your exact workflows',
  },
};

export const BASE_CAPABILITIES: BusinessCapabilities = {
  onlineStore: false,
  orders: false,
  posRegister: false,
  catalog: false,
  inventory: false,
  purchases: false,
  suppliers: false,
  dining: false,
  tables: false,
  kitchenKot: false,
  reservations: false,
  leads: false,
  jobs: false,
  dispatch: false,
  calendarBooking: false,
  invoicing: true,
  quotes: false,
  expenses: true,
  customerCredit: true,
  customers: true,
  loyalty: false,
  marketingBlasts: false,
  aiReceptionist: false,
  customDomain: false,
};

export const BUSINESS_TYPE_PRESETS: Record<BusinessType, BusinessCapabilities> = {
  restaurant: {
    ...BASE_CAPABILITIES,
    dining: true,
    tables: true,
    kitchenKot: true,
    reservations: true,
    onlineStore: true,
    orders: true,
    posRegister: true,
    catalog: true,
    inventory: true,
    purchases: true,
    suppliers: true,
    invoicing: true,
    quotes: false,
    expenses: true,
    customerCredit: false,
    customers: true,
    loyalty: true,
    marketingBlasts: true,
  },

  retail: {
    ...BASE_CAPABILITIES,
    onlineStore: true,
    orders: true,
    posRegister: true,
    catalog: true,
    inventory: true,
    purchases: true,
    suppliers: true,
    invoicing: true,
    quotes: true,
    expenses: true,
    customerCredit: true,
    customers: true,
    loyalty: true,
    marketingBlasts: true,
    customDomain: true,
  },

  grocery: {
    ...BASE_CAPABILITIES,
    onlineStore: true,
    orders: true,
    posRegister: true,
    catalog: true,
    inventory: true,
    purchases: true,
    suppliers: true,
    invoicing: true,
    expenses: true,
    customerCredit: true,
    customers: true,
    loyalty: true,
  },

  services: {
    ...BASE_CAPABILITIES,
    leads: true,
    jobs: true,
    dispatch: true,
    calendarBooking: true,
    invoicing: true,
    quotes: true,
    expenses: true,
    customerCredit: true,
    customers: true,
    aiReceptionist: true,
  },

  salon: {
    ...BASE_CAPABILITIES,
    calendarBooking: true,
    posRegister: true,
    catalog: true,
    inventory: true,
    invoicing: true,
    expenses: true,
    customers: true,
    loyalty: true,
    marketingBlasts: true,
    aiReceptionist: true,
  },

  wholesale: {
    ...BASE_CAPABILITIES,
    orders: true,
    catalog: true,
    inventory: true,
    purchases: true,
    suppliers: true,
    invoicing: true,
    quotes: true,
    expenses: true,
    customerCredit: true,
    customers: true,
  },

  freelancer: {
    ...BASE_CAPABILITIES,
    leads: true,
    invoicing: true,
    quotes: true,
    expenses: true,
    customers: true,
    calendarBooking: true,
  },

  online_store: {
    ...BASE_CAPABILITIES,
    onlineStore: true,
    orders: true,
    catalog: true,
    inventory: true,
    invoicing: true,
    customers: true,
    marketingBlasts: true,
    customDomain: true,
  },

  manufacturing: {
    ...BASE_CAPABILITIES,
    orders: true,
    catalog: true,
    inventory: true,
    purchases: true,
    suppliers: true,
    invoicing: true,
    quotes: true,
    expenses: true,
    customers: true,
  },

  other: {
    ...BASE_CAPABILITIES,
    onlineStore: true,
    orders: true,
    posRegister: true,
    catalog: true,
    inventory: true,
    invoicing: true,
    quotes: true,
    expenses: true,
    customers: true,
  },
};

export function getCapabilitiesForBusinessType(type: BusinessType): BusinessCapabilities {
  return { ...BUSINESS_TYPE_PRESETS[type] || BUSINESS_TYPE_PRESETS.other };
}
