import { NextRequest, NextResponse } from 'next/server';
import { getAuthUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { getBrandContextRaw } from '@/lib/brand-context';

/**
 * Brand Brain — Engine 4
 * ----------------------
 * GET  /api/brand-profile      — fetch the tenant's BrandProfile (or null)
 * PUT  /api/brand-profile      — upsert the BrandProfile, auto-generating
 *                                an AI synthesis summary on save.
 *
 * Auth: any authenticated tenant user (owner/admin/agent). The BrandProfile
 * is tenant-scoped (one per tenant, enforced by `tenantId @unique`).
 *
 * The `aiGeneratedSummary` field is a 2-3 sentence synthesis of the form
 * fields, generated by the z-ai-web-dev-sdk LLM. It is cached on the row so
 * the UI can show a "Brand snapshot" card without re-calling the LLM, and so
 * downstream AI routes can use a tighter summary instead of the full
 * structured context when token budget matters.
 */

// ─── Types ─────────────────────────────────────────────────────────────────

/** Shape of a JSON-array column (services, products, forbiddenPhrases, competitors). */
type StringList = string[];

/** Body the UI sends on PUT. All fields are optional except businessName + industry. */
interface BrandProfileInput {
  businessName: string;
  industry: string;
  website?: string | null;
  location?: string | null;
  serviceArea?: string | null;
  targetCustomer?: string | null;
  customerPainPoints?: string | null;
  tone?: string | null;
  voiceDescription?: string | null;
  forbiddenPhrases?: StringList | null;
  defaultCta?: string | null;
  services?: StringList | null;
  products?: StringList | null;
  usps?: string | null;
  currentOffers?: string | null;
  competitors?: StringList | null;
  // Allow caller to skip the (slow) AI summary regeneration.
  skipAiSummary?: boolean;
}

// ─── Helpers ───────────────────────────────────────────────────────────────

/**
 * Normalise a list input: drop non-strings, trim, dedupe. Always returns a
 * string array (never null) so the caller can `JSON.stringify` it safely.
 */
function normaliseList(input: StringList | null | undefined): string[] {
  if (!Array.isArray(input)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of input) {
    if (typeof item !== 'string') continue;
    const trimmed = item.trim();
    if (!trimmed || seen.has(trimmed.toLowerCase())) continue;
    seen.add(trimmed.toLowerCase());
    out.push(trimmed);
  }
  return out;
}

/**
 * Synthesise a 2-3 sentence "brand snapshot" from the form fields using the
 * z-ai-web-dev-sdk. Failures are non-fatal — we return `null` and the row
 * saves without a summary so the user never sees a 500 from a flaky LLM.
 *
 * The summary is intended to be the "elevator pitch" an AI can use as a
 * one-liner system prompt when token budget is tight.
 */
async function generateAiSummary(input: BrandProfileInput): Promise<string | null> {
  try {
    const ZAI = (await import('z-ai-web-dev-sdk')).default;
    const zai = await ZAI.create();

    const services = normaliseList(input.services);
    const usps = (input.usps || '').trim();

    const facts: string[] = [];
    facts.push(`Business name: ${input.businessName}`);
    facts.push(`Industry: ${input.industry}`);
    if (input.location) facts.push(`Location: ${input.location}`);
    if (input.website) facts.push(`Website: ${input.website}`);
    if (input.targetCustomer) facts.push(`Target customer: ${input.targetCustomer}`);
    if (input.customerPainPoints) facts.push(`Customer pain points: ${input.customerPainPoints}`);
    if (input.tone) facts.push(`Tone: ${input.tone}`);
    if (input.voiceDescription) facts.push(`Voice: ${input.voiceDescription}`);
    if (services.length > 0) facts.push(`Services: ${services.join(', ')}`);
    if (usps) facts.push(`USPs: ${usps}`);
    if (input.currentOffers) facts.push(`Current offers: ${input.currentOffers}`);
    if (input.defaultCta) facts.push(`Default CTA: ${input.defaultCta}`);

    const systemPrompt =
      'You are a brand strategist. Synthesise the business facts below into a single 2-3 sentence ' +
      '"brand snapshot" — an elevator pitch an AI content generator can use as a one-line system prompt. ' +
      'The snapshot must capture: who the business is, who they serve, and what makes them different. ' +
      'Plain prose only. No headings, no markdown, no quotes, no preamble. Maximum 80 words.';

    const userPrompt = `Business facts:\n${facts.join('\n')}\n\nWrite the brand snapshot now.`;

    const completion = await zai.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      thinking: { type: 'disabled' },
    });

    const text = completion?.choices?.[0]?.message?.content?.trim();
    if (!text) return null;
    // Hard cap to keep the field predictable.
    return text.slice(0, 600);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[brand-profile] AI summary generation failed:', msg);
    return null;
  }
}

// ─── GET ───────────────────────────────────────────────────────────────────

export async function GET() {
  try {
    const user = await getAuthUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const tenantId = user.tenantId;
    if (!tenantId) {
      return NextResponse.json(
        { error: 'No active tenant for this user.' },
        { status: 400 },
      );
    }

    const profile = await getBrandContextRaw(tenantId);
    return NextResponse.json({ profile });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('[/api/brand-profile GET] error:', error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

// ─── PUT ───────────────────────────────────────────────────────────────────

export async function PUT(request: NextRequest) {
  try {
    const user = await getAuthUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const tenantId = user.tenantId;
    if (!tenantId) {
      return NextResponse.json(
        { error: 'No active tenant for this user.' },
        { status: 400 },
      );
    }

    const body = (await request.json().catch(() => null)) as BrandProfileInput | null;
    if (!body || typeof body !== 'object') {
      return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    // Validate required fields.
    const businessName = (body.businessName || '').trim();
    const industry = (body.industry || '').trim();
    if (!businessName) {
      return NextResponse.json({ error: 'businessName is required.' }, { status: 400 });
    }
    if (!industry) {
      return NextResponse.json({ error: 'industry is required.' }, { status: 400 });
    }

    // Normalise list-shaped fields to JSON strings.
    const forbiddenPhrasesJson = JSON.stringify(normaliseList(body.forbiddenPhrases));
    const servicesJson = JSON.stringify(normaliseList(body.services));
    const productsJson = JSON.stringify(normaliseList(body.products));
    const competitorsJson = JSON.stringify(normaliseList(body.competitors));

    // Build the data payload once (used for both create + update paths).
    const data = {
      businessName,
      industry,
      website: body.website?.trim() || null,
      location: body.location?.trim() || null,
      serviceArea: body.serviceArea?.trim() || null,
      targetCustomer: body.targetCustomer?.trim() || null,
      customerPainPoints: body.customerPainPoints?.trim() || null,
      tone: body.tone?.trim() || null,
      voiceDescription: body.voiceDescription?.trim() || null,
      forbiddenPhrases: forbiddenPhrasesJson,
      defaultCta: body.defaultCta?.trim() || null,
      services: servicesJson,
      products: productsJson,
      usps: body.usps?.trim() || null,
      currentOffers: body.currentOffers?.trim() || null,
      competitors: competitorsJson,
    };

    // Generate the AI summary (unless the caller asked us to skip it).
    // We do this BEFORE the upsert so we can write both fields in one query.
    let aiGeneratedSummary: string | null = null;
    if (!body.skipAiSummary) {
      aiGeneratedSummary = await generateAiSummary(body);
    }

    // Upsert — there's a unique constraint on tenantId, so this is safe
    // against concurrent saves from the same tenant.
    const profile = await db.brandProfile.upsert({
      where: { tenantId },
      create: {
        tenantId,
        ...data,
        aiGeneratedSummary,
      },
      update: {
        ...data,
        // Only overwrite the summary when we generated a new one. If the
        // LLM call failed (null), keep the previous summary so the UI
        // doesn't lose its snapshot.
        ...(aiGeneratedSummary ? { aiGeneratedSummary } : {}),
      },
    });

    return NextResponse.json({ profile });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    console.error('[/api/brand-profile PUT] error:', error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
