/**
 * generate-supabase-migration.ts
 *
 * Reads prisma/schema.prisma and generates a FULLY IDEMPOTENT supabase-migration.sql
 * that is bulletproof against:
 *   1. Pre-existing tables missing new columns (CREATE TABLE IF NOT EXISTS is a no-op,
 *      so we ALSO run ALTER TABLE ADD COLUMN IF NOT EXISTS for every field)
 *   2. Orphaned indexes blocking ADD CONSTRAINT (we DROP INDEX IF EXISTS first)
 *   3. Duplicate constraint creation (DO blocks with _constraint_exists guard)
 *   4. FK failures from missing columns (columns are backported before FKs run)
 *
 * Output: supabase-migration.sql
 *
 * Usage: bun scripts/generate-supabase-migration.ts
 */

import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

interface PrismaField {
  name: string
  type: string
  isRelation: boolean
  isList: boolean
  isOptional: boolean
  isId: boolean
  isUnique: boolean
  defaultRaw?: string
  mapName?: string
}

interface PrismaModel {
  name: string
  fields: PrismaField[]
  indexes: { fields: string[]; name?: string }[]
  uniques: { fields: string[]; name?: string }[]
}

// ── Parse Prisma schema ────────────────────────────────────────────────
const schemaPath = join(process.cwd(), 'prisma/schema.prisma')
const schemaContent = readFileSync(schemaPath, 'utf8')

const models: PrismaModel[] = []

// Split into model blocks
const modelRegex = /^model\s+(\w+)\s+\{([^}]*)\}/gm
let match: RegExpExecArray | null
while ((match = modelRegex.exec(schemaContent)) !== null) {
  const modelName = match[1]
  const body = match[2]
  const fields: PrismaField[] = []
  const indexes: { fields: string[]; name?: string }[] = []
  const uniques: { fields: string[]; name?: string }[] = []

  for (const rawLine of body.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('//') || line.startsWith('@@')) {
      // Parse @@index and @@unique
      const idxMatch = line.match(/@@index\(\[([^\]]+)\](?:,\s*name:\s*"([^"]+)")?\)/)
      if (idxMatch) {
        indexes.push({
          fields: idxMatch[1].split(',').map(f => f.trim()),
          name: idxMatch[2],
        })
      }
      const uniqMatch = line.match(/@@unique\(\[([^\]]+)\](?:,\s*name:\s*"([^"]+)")?\)/)
      if (uniqMatch) {
        uniques.push({
          fields: uniqMatch[1].split(',').map(f => f.trim()),
          name: uniqMatch[2],
        })
      }
      continue
    }

    // Skip relation fields (Type starts with uppercase and is a model, or is a list)
    // Field format: name Type? @... or name Type @...
    const fieldMatch = line.match(/^(\w+)\s+(\w+)(\?)?(\[\])?\s*(.*)$/)
    if (!fieldMatch) continue

    const [, fname, ftype, optQ, listBr, attrs] = fieldMatch
    const isOptional = !!optQ
    const isList = !!listBr

    // Determine if relation: type is capitalized (not a Prisma scalar)
    const scalars = new Set([
      'String', 'Int', 'BigInt', 'Float', 'Decimal', 'Boolean', 'DateTime',
      'Json', 'Bytes', 'Date', 'Time',
    ])
    const isRelation = !scalars.has(ftype) && /^[A-Z]/.test(ftype)

    if (isRelation) {
      // Skip relation fields — they become FKs, not columns
      continue
    }

    const isId = attrs.includes('@id')
    const isUnique = attrs.includes('@unique')

    // Extract default
    let defaultRaw: string | undefined
    const defMatch = attrs.match(/@default\(([^)]*)\)/)
    if (defMatch) defaultRaw = defMatch[1].trim()

    // Extract map name
    let mapName: string | undefined
    const mapMatch = attrs.match(/@map\("([^"]+)"\)/)
    if (mapMatch) mapName = mapMatch[1]

    fields.push({
      name: fname,
      type: ftype,
      isRelation: false,
      isList,
      isOptional,
      isId,
      isUnique,
      defaultRaw,
      mapName,
    })
  }

  models.push({ name: modelName, fields, indexes, uniques })
}

console.log(`Parsed ${models.length} models from Prisma schema`)

// ── Map Prisma types to Postgres types ─────────────────────────────────
function prismaTypeToPg(field: PrismaField): string {
  const t = field.type
  switch (t) {
    case 'String': return 'TEXT'
    case 'Int': return 'INTEGER'
    case 'BigInt': return 'BIGINT'
    case 'Float': return 'DOUBLE PRECISION'
    case 'Decimal': return 'DECIMAL(65,30)'
    case 'Boolean': return 'BOOLEAN'
    case 'DateTime': return 'TIMESTAMP(3)'
    case 'Json': return 'JSONB'
    case 'Bytes': return 'BYTEA'
    default: return 'TEXT'
  }
}

// ── Build default clause ───────────────────────────────────────────────
function buildDefault(field: PrismaField): string {
  if (!field.defaultRaw) return ''
  const d = field.defaultRaw

  // autoincrement()
  if (d === 'autoincrement()') return ' GENERATED BY DEFAULT AS IDENTITY'

  // now() / uuid() / gen_random_uuid()
  if (d === 'now()') return ` DEFAULT now()`
  if (d === 'uuid()' || d === 'gen_random_uuid()') return ` DEFAULT gen_random_uuid()`

  // cuid(), nanoid() → use gen_random_uuid for Supabase
  if (d === 'cuid()' || d === 'nanoid()') return ` DEFAULT gen_random_uuid()`

  // Boolean defaults
  if (d === 'true' || d === 'false') return ` DEFAULT ${d}`

  // Numeric defaults
  if (/^-?\d+(\.\d+)?$/.test(d)) return ` DEFAULT ${d}`

  // String literal default — Prisma uses double quotes, Postgres needs single quotes
  if (d.startsWith('"') && d.endsWith('"')) {
    const strVal = d.slice(1, -1).replace(/'/g, "''")
    return ` DEFAULT '${strVal}'`
  }

  // dbgenerated() or other — skip
  return ''
}

// ── Generate SQL ───────────────────────────────────────────────────────
const sqlParts: string[] = []

sqlParts.push(`-- ====================================================================
-- SERVICEOS — SUPABASE MIGRATION (AUTO-GENERATED)
-- Generated from prisma/schema.prisma
--
-- This migration is FULLY IDEMPOTENT and SELF-HEALING:
--   • Every table uses CREATE TABLE IF NOT EXISTS
--   • Every column is ALSO backported via ALTER TABLE ADD COLUMN IF NOT EXISTS
--     (so pre-existing tables missing new columns get fixed automatically)
--   • Every unique constraint drops orphaned indexes first (avoids
--     "relation already exists" errors from partial prior runs)
--   • Every foreign key uses a DO block guard
--   • Every index uses CREATE INDEX IF NOT EXISTS
--
-- Safe to re-run any number of times. Safe to run on fresh DBs AND on
-- DBs that have partial prior migrations.
-- ====================================================================

-- ##########################################
-- PHASE 0: HELPER FUNCTIONS
-- ##########################################

-- Check if a foreign key constraint exists
CREATE OR REPLACE FUNCTION _fk_exists(text) RETURNS boolean AS $$
  SELECT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = $1 AND contype = 'f')
$$ LANGUAGE sql;

-- Check if any constraint exists by name (and optional type)
-- type: 'p' (primary key), 'u' (unique), 'f' (foreign key), 'c' (check)
CREATE OR REPLACE FUNCTION _constraint_exists(text, text DEFAULT NULL) RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = $1
    AND ($2 IS NULL OR contype = $2)
  )
$$ LANGUAGE sql;

-- Check if an index exists by name
CREATE OR REPLACE FUNCTION _index_exists(text) RETURNS boolean AS $$
  SELECT EXISTS (SELECT 1 FROM pg_class WHERE relname = $1 AND relkind = 'i')
$$ LANGUAGE sql;

-- Check if a column exists on a table
CREATE OR REPLACE FUNCTION _column_exists(text, text) RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = $1 AND column_name = $2
  )
$$ LANGUAGE sql;

`)

// ── PHASE 1: CREATE TABLE for all models ───────────────────────────────
sqlParts.push(`-- ##########################################
-- PHASE 1: CREATE TABLES
-- ##########################################

`)

for (const model of models) {
  sqlParts.push(`CREATE TABLE IF NOT EXISTS "${model.name}" (`)

  const columnDefs: string[] = []
  for (const field of model.fields) {
    const pgType = prismaTypeToPg(field)
    const nullClause = field.isId || (!field.isOptional && field.defaultRaw === undefined) ? ' NOT NULL' : (field.isOptional ? '' : ' NOT NULL')
    const defaultClause = buildDefault(field)

    if (field.isId) {
      columnDefs.push(`  "${field.name}" ${pgType} PRIMARY KEY${defaultClause}`)
    } else if (field.isUnique) {
      columnDefs.push(`  "${field.name}" ${pgType}${nullClause}${defaultClause} UNIQUE`)
    } else {
      columnDefs.push(`  "${field.name}" ${pgType}${nullClause}${defaultClause}`)
    }
  }

  sqlParts.push(columnDefs.join(',\n'))
  sqlParts.push(`);\n\n`)
}

// ── PHASE 2: ALTER TABLE ADD COLUMN (backport all columns) ─────────────
sqlParts.push(`-- ##########################################
-- PHASE 2: BACKPORT COLUMNS
-- (ensures pre-existing tables get any missing columns)
-- ##########################################

`)

for (const model of models) {
  for (const field of model.fields) {
    const pgType = prismaTypeToPg(field)
    const defaultClause = buildDefault(field)
    const nullClause = field.isId || (!field.isOptional && field.defaultRaw === undefined) ? ' NOT NULL' : ''

    // For NOT NULL columns with no default on existing tables, we need a default to backfill
    // Use a safe default based on type
    let backportDefault = defaultClause
    if (!field.isOptional && field.defaultRaw === undefined && !field.isId) {
      // Add a temporary default so existing rows don't fail NOT NULL
      switch (field.type) {
        case 'String': backportDefault = ` DEFAULT ''`; break
        case 'Int': case 'BigInt': case 'Float': case 'Decimal': backportDefault = ` DEFAULT 0`; break
        case 'Boolean': backportDefault = ` DEFAULT false`; break
        case 'DateTime': backportDefault = ` DEFAULT now()`; break
        case 'Json': backportDefault = ` DEFAULT '{}'::jsonb`; break
        default: backportDefault = ` DEFAULT ''`
      }
    }

    sqlParts.push(`ALTER TABLE "${model.name}" ADD COLUMN IF NOT EXISTS "${field.name}" ${pgType}${nullClause}${backportDefault};`)
  }
  sqlParts.push('')
}

// ── PHASE 3: UNIQUE CONSTRAINTS (drop orphaned indexes first) ──────────
sqlParts.push(`-- ##########################################
-- PHASE 3: UNIQUE CONSTRAINTS
-- (drops orphaned indexes first to avoid name collisions)
-- ##########################################

`)

for (const model of models) {
  // Single-field @unique
  for (const field of model.fields) {
    if (field.isUnique && !field.isId) {
      const constraintName = `${model.name}_${field.name}_key`
      sqlParts.push(`-- ${model.name}.${field.name} unique`)
      sqlParts.push(`ALTER TABLE "${model.name}" DROP CONSTRAINT IF EXISTS "${constraintName}";`)
      sqlParts.push(`DROP INDEX IF EXISTS "${constraintName}";`)
      sqlParts.push(`DO $$ BEGIN`)
      sqlParts.push(`  IF NOT _constraint_exists('${constraintName}', 'u') THEN`)
      sqlParts.push(`    ALTER TABLE "${model.name}" ADD CONSTRAINT "${constraintName}" UNIQUE ("${field.name}");`)
      sqlParts.push(`  END IF;`)
      sqlParts.push(`END $$;`)
      sqlParts.push('')
    }
  }

  // Multi-field @@unique
  for (const uniq of model.uniques) {
    const constraintName = uniq.name || `${model.name}_${uniq.fields.join('_')}_key`
    const cols = uniq.fields.map(f => `"${f}"`).join(', ')
    sqlParts.push(`-- ${model.name} @@unique [${uniq.fields.join(', ')}]`)
    sqlParts.push(`ALTER TABLE "${model.name}" DROP CONSTRAINT IF EXISTS "${constraintName}";`)
    sqlParts.push(`DROP INDEX IF EXISTS "${constraintName}";`)
    sqlParts.push(`DO $$ BEGIN`)
    sqlParts.push(`  IF NOT _constraint_exists('${constraintName}', 'u') THEN`)
    sqlParts.push(`    ALTER TABLE "${model.name}" ADD CONSTRAINT "${constraintName}" UNIQUE (${cols});`)
    sqlParts.push(`  END IF;`)
    sqlParts.push(`END $$;`)
    sqlParts.push('')
  }
}

// ── PHASE 4: FOREIGN KEYS ──────────────────────────────────────────────
sqlParts.push(`-- ##########################################
-- PHASE 4: FOREIGN KEY CONSTRAINTS
-- ##########################################

`)

// Re-parse to get relations (we need them for FKs)
const modelNames = new Set(models.map(m => m.name))

interface FKDef {
  model: string
  field: string
  refModel: string
  refField: string
  onDelete?: string
  name: string
}

const fks: FKDef[] = []

const modelBodyMap = new Map<string, string>()
const modelRegex2 = /^model\s+(\w+)\s+\{([^}]*)\}/gm
let m2: RegExpExecArray | null
while ((m2 = modelRegex2.exec(schemaContent)) !== null) {
  modelBodyMap.set(m2[1], m2[2])
}

for (const model of models) {
  const body = modelBodyMap.get(model.name)!
  for (const rawLine of body.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith('//') || line.startsWith('@@')) continue

    const fieldMatch = line.match(/^(\w+)\s+(\w+)(\?)?(\[\])?\s*(.*)$/)
    if (!fieldMatch) continue
    const [, fname, ftype, optQ, listBr, attrs] = fieldMatch

    const scalars = new Set([
      'String', 'Int', 'BigInt', 'Float', 'Decimal', 'Boolean', 'DateTime',
      'Json', 'Bytes', 'Date', 'Time',
    ])
    if (scalars.has(ftype) || !/^[A-Z]/.test(ftype)) continue
    if (listBr) continue // list relations don't create FK columns

    // This is a relation field — find the @relation attribute
    const relMatch = attrs.match(/@relation\(([^)]*)\)/)
    if (!relMatch) continue

    const relArgs = relMatch[1]
    // Parse fields and references
    const fieldsMatch = relArgs.match(/fields:\s*\[([^\]]+)\]/)
    const refsMatch = relArgs.match(/references:\s*\[([^\]]+)\]/)
    const onDeleteMatch = relArgs.match(/onDelete:\s*(\w+)/)
    const mapMatch = relArgs.match(/name:\s*"([^"]+)"/)

    if (!fieldsMatch || !refsMatch) continue

    const fkField = fieldsMatch[1].trim()
    const refField = refsMatch[1].trim()
    const onDelete = onDeleteMatch ? onDeleteMatch[1] : undefined

    // FK name convention: Model_field_key (Prisma default)
    const fkName = mapMatch
      ? `${mapMatch[1]}_fkey`
      : `${model.name}_${fkField}_fkey`

    // Translate Prisma onDelete enum to SQL clause
    // Prisma: Cascade | Restrict | SetNull | SetDefault | NoAction
    // SQL:    CASCADE | RESTRICT | SET NULL | SET DEFAULT | NO ACTION
    let sqlOnDelete: string | undefined
    if (onDelete) {
      switch (onDelete) {
        case 'Cascade': sqlOnDelete = 'CASCADE'; break
        case 'Restrict': sqlOnDelete = 'RESTRICT'; break
        case 'SetNull': sqlOnDelete = 'SET NULL'; break
        case 'SetDefault': sqlOnDelete = 'SET DEFAULT'; break
        case 'NoAction': sqlOnDelete = 'NO ACTION'; break
        default: sqlOnDelete = onDelete // already SQL form
      }
    }

    fks.push({
      model: model.name,
      field: fkField,
      refModel: ftype,
      refField: refField,
      onDelete: sqlOnDelete,
      name: fkName,
    })
  }
}

for (const fk of fks) {
  if (!modelNames.has(fk.refModel)) continue

  const onDeleteClause = fk.onDelete ? ` ON DELETE ${fk.onDelete}` : ''
  sqlParts.push(`DO $$ BEGIN`)
  sqlParts.push(`  IF NOT _fk_exists('${fk.name}') THEN`)
  sqlParts.push(`    ALTER TABLE "${fk.model}" ADD CONSTRAINT "${fk.name}" FOREIGN KEY ("${fk.field}") REFERENCES "${fk.refModel}"("${fk.refField}")${onDeleteClause};`)
  sqlParts.push(`  END IF;`)
  sqlParts.push(`END $$;`)
  sqlParts.push('')
}

// ── PHASE 5: INDEXES ───────────────────────────────────────────────────
sqlParts.push(`-- ##########################################
-- PHASE 5: INDEXES
-- ##########################################

`)

for (const model of models) {
  for (const idx of model.indexes) {
    const idxName = idx.name || `${model.name}_${idx.fields.join('_')}_idx`
    const cols = idx.fields.map(f => `"${f}"`).join(', ')
    sqlParts.push(`CREATE INDEX IF NOT EXISTS "${idxName}" ON "${model.name}"(${cols});`)
  }
  if (model.indexes.length > 0) sqlParts.push('')
}

// ── PHASE 6: CLEANUP ───────────────────────────────────────────────────
sqlParts.push(`
-- ##########################################
-- PHASE 6: CLEANUP HELPER FUNCTIONS
-- ##########################################
-- Drop helper functions (optional — keeping them speeds up future runs)
-- DROP FUNCTION IF EXISTS _fk_exists(text);
-- DROP FUNCTION IF EXISTS _constraint_exists(text, text);
-- DROP FUNCTION IF EXISTS _index_exists(text);
-- DROP FUNCTION IF EXISTS _column_exists(text, text);

-- Migration complete.
`)

// ── Write output ────────────────────────────────────────────────────────
const outputPath = join(process.cwd(), 'supabase-migration.sql')
writeFileSync(outputPath, sqlParts.join('\n'))

console.log(`✅ Generated ${outputPath}`)
console.log(`   ${models.length} models, ${fks.length} foreign keys`)
console.log(`   ${sqlParts.join('\n').split('\n').length} lines total`)
