/**
 * Fieseros Universal Studio - Widget Manifests & Registry Definitions
 */

import { StudioWidgetType, StudioWidgetCategory, StudioNode } from './node';

export interface WidgetManifest {
  type: StudioWidgetType;
  name: string;
  description: string;
  category: StudioWidgetCategory;
  icon: string;
  isContainer?: boolean;
  defaultProps: Record<string, any>;
  defaultStyle?: Record<string, any>;
}

export const WIDGET_MANIFESTS: Record<StudioWidgetType, WidgetManifest> = {
  // ── 1. LAYOUT ──
  container: {
    type: 'container',
    name: 'Container',
    description: 'Flex or grid container for structuring sections and nested elements',
    category: 'layout',
    icon: 'SquareDashed',
    isContainer: true,
    defaultProps: {},
    defaultStyle: {
      display: 'flex',
      flexDirection: 'column',
      padding: '24px',
      gap: '16px',
      width: '100%',
    },
  },
  grid: {
    type: 'grid',
    name: 'Grid 12-Col',
    description: '12-column responsive layout grid for multi-card sections',
    category: 'layout',
    icon: 'LayoutGrid',
    isContainer: true,
    defaultProps: {},
    defaultStyle: {
      display: 'grid',
      colSpan: 12,
      gap: '16px',
      padding: '16px',
    },
  },
  columns: {
    type: 'columns',
    name: '2-Columns Split',
    description: 'Two equal 50/50 split columns with responsive stacking',
    category: 'layout',
    icon: 'Columns',
    isContainer: true,
    defaultProps: {},
    defaultStyle: {
      display: 'flex',
      flexDirection: 'row',
      gap: '24px',
      padding: '20px',
    },
  },
  spacer: {
    type: 'spacer',
    name: 'Spacer',
    description: 'Adjustable blank vertical spacing between blocks',
    category: 'layout',
    icon: 'MoveVertical',
    defaultProps: { height: '32px' },
    defaultStyle: { height: '32px', width: '100%' },
  },
  divider: {
    type: 'divider',
    name: 'Divider Line',
    description: 'Decorative horizontal rule or separator line',
    category: 'layout',
    icon: 'Minus',
    defaultProps: { thickness: '1px', style: 'solid', color: '#e2e8f0' },
    defaultStyle: { margin: '16px 0', width: '100%' },
  },
  tabs: {
    type: 'tabs',
    name: 'Tabs Component',
    description: 'Multi-tab content switcher with customizable tab headers',
    category: 'layout',
    icon: 'Folders',
    isContainer: true,
    defaultProps: { tabs: ['Overview', 'Details', 'Reviews'] },
    defaultStyle: { padding: '16px' },
  },
  accordion: {
    type: 'accordion',
    name: 'Accordion FAQ',
    description: 'Expandable/collapsible FAQ accordion panels',
    category: 'layout',
    icon: 'ListCollapse',
    defaultProps: {
      items: [
        { title: 'What is your response time?', content: 'We arrive within 45 minutes for emergency dispatches.' },
        { title: 'Are your technicians licensed & insured?', content: 'Yes, 100% background checked and fully licensed.' },
      ],
    },
    defaultStyle: { padding: '12px' },
  },

  // ── 2. BASIC ──
  heading: {
    type: 'heading',
    name: 'Heading',
    description: 'Headline and sub-headline typography with H1-H6 tags',
    category: 'basic',
    icon: 'Heading',
    defaultProps: {
      title: 'Book Your Professional Service',
      htmlTag: 'h2',
      align: 'left',
    },
    defaultStyle: {
      typography: {
        fontSize: '28px',
        fontWeight: 'bold',
        color: '#0f172a',
      },
    },
  },
  text: {
    type: 'text',
    name: 'Text Paragraph',
    description: 'Standard descriptive paragraph with rich text styling',
    category: 'basic',
    icon: 'Pilcrow',
    defaultProps: {
      text: 'Fill out the form below to receive upfront guaranteed pricing and schedule verified pros.',
    },
    defaultStyle: {
      typography: {
        fontSize: '14px',
        color: '#64748b',
        lineHeight: '1.6',
      },
    },
  },
  rich_text: {
    type: 'rich_text',
    name: 'Rich Text Block',
    description: 'Formatted HTML content with bullet points and bold highlights',
    category: 'basic',
    icon: 'FileText',
    defaultProps: {
      html: '<p>⭐ <strong>5-Star Rated Service</strong><br/>• Upfront pricing<br/>• Guaranteed satisfaction</p>',
    },
    defaultStyle: { padding: '8px' },
  },
  image: {
    type: 'image',
    name: 'Image',
    description: 'Responsive photo with rounded borders and lightbox zoom',
    category: 'basic',
    icon: 'Image',
    defaultProps: {
      url: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80',
      alt: 'Service technician at work',
      aspectRatio: '16:9',
    },
    defaultStyle: {
      border: { radius: '16px' },
      shadow: 'md',
    },
  },
  image_gallery: {
    type: 'image_gallery',
    name: 'Image Gallery',
    description: 'Grid or carousel gallery of project and portfolio photos',
    category: 'basic',
    icon: 'Images',
    defaultProps: {
      images: [
        'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
      ],
    },
    defaultStyle: { padding: '8px' },
  },
  video: {
    type: 'video',
    name: 'Video Player',
    description: 'Embedded YouTube, Vimeo or MP4 direct video stream',
    category: 'basic',
    icon: 'Video',
    defaultProps: {
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      autoplay: false,
    },
    defaultStyle: { border: { radius: '16px' } },
  },
  icon: {
    type: 'icon',
    name: 'Lucide Icon',
    description: 'Customizable vector icon badge',
    category: 'basic',
    icon: 'Sparkles',
    defaultProps: { iconName: 'ShieldCheck', size: 24, color: '#059669' },
    defaultStyle: { padding: '8px' },
  },
  button: {
    type: 'button',
    name: 'Action Button',
    description: 'Call-to-action button with link, modal or workflow trigger',
    category: 'basic',
    icon: 'MousePointerClick',
    defaultProps: {
      label: 'Get Free Estimate ⚡',
      variant: 'primary',
    },
    defaultStyle: {
      backgroundColor: '#059669',
      typography: { color: '#ffffff', fontWeight: 'bold' },
      border: { radius: '12px' },
      padding: '12px 24px',
    },
  },
  badge: {
    type: 'badge',
    name: 'Status Badge',
    description: 'Pill badge highlighting trust tags or urgency',
    category: 'basic',
    icon: 'Tag',
    defaultProps: { text: '⚡ Instant 15-Min Dispatch', color: 'emerald' },
    defaultStyle: { padding: '4px 12px' },
  },
  list: {
    type: 'list',
    name: 'Feature List',
    description: 'Icon checklist displaying benefits and guarantee items',
    category: 'basic',
    icon: 'ListChecks',
    defaultProps: {
      items: [
        'Guaranteed arrival window',
        'Licensed & background-checked techs',
        '100% Money-back escrow guarantee',
      ],
    },
    defaultStyle: { padding: '8px' },
  },

  // ── 3. FORM ──
  form_container: {
    type: 'form_container',
    name: 'Form Container',
    description: 'Interactive form wrapper with multi-step support and validation',
    category: 'form',
    icon: 'FileSpreadsheet',
    isContainer: true,
    defaultProps: { submitLabel: 'Submit Request' },
    defaultStyle: { padding: '24px', backgroundColor: '#ffffff', border: { radius: '20px' }, shadow: 'sm' },
  },
  text_input: {
    type: 'text_input',
    name: 'Text Input',
    description: 'Single-line text field for names, titles, or short entries',
    category: 'form',
    icon: 'Type',
    defaultProps: { label: 'Full Name', placeholder: 'e.g. John Doe', required: true },
    defaultStyle: { colSpan: 12 },
  },
  email_input: {
    type: 'email_input',
    name: 'Email Field',
    description: 'Validated email input with auto-complete',
    category: 'form',
    icon: 'Mail',
    defaultProps: { label: 'Email Address', placeholder: 'name@example.com', required: true },
    defaultStyle: { colSpan: 6 },
  },
  phone_input: {
    type: 'phone_input',
    name: 'Phone Field',
    description: 'International phone input with SMS dispatch support',
    category: 'form',
    icon: 'Phone',
    defaultProps: { label: 'Phone Number', placeholder: '(555) 000-0000', required: true },
    defaultStyle: { colSpan: 6 },
  },
  number_input: {
    type: 'number_input',
    name: 'Number / Scope',
    description: 'Numeric input for quantities, dimensions, or rooms',
    category: 'form',
    icon: 'Binary',
    defaultProps: { label: 'Square Footage', placeholder: '1500', defaultValue: 1500 },
    defaultStyle: { colSpan: 6 },
  },
  textarea_input: {
    type: 'textarea_input',
    name: 'Multi-Line Textarea',
    description: 'Long text input for project descriptions and notes',
    category: 'form',
    icon: 'AlignLeft',
    defaultProps: { label: 'Describe the Issue / Scope', placeholder: 'Provide details...', rows: 3 },
    defaultStyle: { colSpan: 12 },
  },
  dropdown: {
    type: 'dropdown',
    name: 'Select Dropdown',
    description: 'Single-choice dropdown selector with search',
    category: 'form',
    icon: 'ChevronDownSquare',
    defaultProps: {
      label: 'Service Needed',
      options: ['Emergency AC Repair', 'Full System Replacement', 'Seasonal Maintenance', 'Duct Inspection'],
    },
    defaultStyle: { colSpan: 12 },
  },
  radio_group: {
    type: 'radio_group',
    name: 'Radio Card Group',
    description: 'Visual single-select card options with icons and prices',
    category: 'form',
    icon: 'CircleDot',
    defaultProps: {
      label: 'Urgency Level',
      options: [
        { label: 'Emergency (Immediate)', value: 'emergency', badge: 'Fastest' },
        { label: 'Standard (Within 24h)', value: 'standard' },
        { label: 'Flexible / Next Week', value: 'flexible' },
      ],
    },
    defaultStyle: { colSpan: 12 },
  },
  checkbox_group: {
    type: 'checkbox_group',
    name: 'Checkbox Multi-Select',
    description: 'Multiple selection checkboxes for service add-ons',
    category: 'form',
    icon: 'CheckSquare',
    defaultProps: {
      label: 'Additional Services',
      options: ['Air Filter Upgrade', 'Thermostat Diagnostic', 'Safety CO Check'],
    },
    defaultStyle: { colSpan: 12 },
  },
  date_picker: {
    type: 'date_picker',
    name: 'Date Picker',
    description: 'Interactive calendar date selector',
    category: 'form',
    icon: 'CalendarDays',
    defaultProps: { label: 'Preferred Service Date', required: true },
    defaultStyle: { colSpan: 6 },
  },
  time_picker: {
    type: 'time_picker',
    name: 'Time Slot Picker',
    description: 'Morning / Afternoon / Evening arrival window selector',
    category: 'form',
    icon: 'Clock',
    defaultProps: {
      label: 'Preferred Time Window',
      options: ['Morning (8 AM - 12 PM)', 'Afternoon (12 PM - 4 PM)', 'Evening (4 PM - 8 PM)'],
    },
    defaultStyle: { colSpan: 6 },
  },
  file_upload: {
    type: 'file_upload',
    name: 'File / Photo Upload',
    description: 'Drag-and-drop photo and document uploader with camera capture',
    category: 'form',
    icon: 'UploadCloud',
    defaultProps: { label: 'Upload Photos of Equipment / Area', maxFiles: 5 },
    defaultStyle: { colSpan: 12 },
  },
  digital_signature: {
    type: 'digital_signature',
    name: 'Digital Signature Pad',
    description: 'Touch-friendly e-signature canvas for contracts and authorizations',
    category: 'form',
    icon: 'PenTool',
    defaultProps: { label: 'Customer Authorization Signature', required: true },
    defaultStyle: { colSpan: 12 },
  },
  star_rating: {
    type: 'star_rating',
    name: '5-Star Rating',
    description: 'Interactive star rating for customer feedback and surveys',
    category: 'form',
    icon: 'Star',
    defaultProps: { label: 'Rate Your Experience', count: 5 },
    defaultStyle: { colSpan: 12 },
  },
  scale_rating: {
    type: 'scale_rating',
    name: 'NPS Scale (1-10)',
    description: 'Net Promoter Score rating buttons 1 through 10',
    category: 'form',
    icon: 'SlidersHorizontal',
    defaultProps: { label: 'How likely are you to recommend our service?' },
    defaultStyle: { colSpan: 12 },
  },
  calculation_field: {
    type: 'calculation_field',
    name: 'Cognito Math Calculator',
    description: 'Real-time mathematical formula calculation with live currency display',
    category: 'form',
    icon: 'Calculator',
    defaultProps: {
      label: 'Estimated Instant Quote',
      formula: '= (sqft * 4.50) + 120',
      currencySymbol: '$',
      decimalPlaces: 2,
    },
    defaultStyle: { colSpan: 12 },
  },
  address_input: {
    type: 'address_input',
    name: 'Google Places Address',
    description: 'Address search input with auto-complete and geocoding',
    category: 'form',
    icon: 'MapPin',
    defaultProps: { label: 'Service Property Address', placeholder: 'Start typing address...' },
    defaultStyle: { colSpan: 12 },
  },

  // ── 4. AI ──
  ai_chat_concierge: {
    type: 'ai_chat_concierge',
    name: '24/7 AI Service Concierge',
    description: 'Embedded interactive AI assistant that answers questions and fills forms',
    category: 'ai',
    icon: 'Bot',
    defaultProps: {
      title: '24/7 AI Service Concierge',
      persona: 'friendly',
      greeting: 'Hi! I am your AI assistant. How can I help you with your project today?',
      connectedFormId: 'default',
    },
    defaultStyle: { colSpan: 12, backgroundColor: '#0f172a', border: { radius: '20px' } },
  },
  ai_smart_fastfill: {
    type: 'ai_smart_fastfill',
    name: 'AI Voice / Text FastFill',
    description: 'One-click natural language voice/text input that auto-fills the entire form',
    category: 'ai',
    icon: 'Sparkles',
    defaultProps: { promptPlaceholder: 'Describe your job in your own words, e.g. "My AC stopped blowing cold air yesterday"...' },
    defaultStyle: { colSpan: 12 },
  },
  ai_lead_qualifier: {
    type: 'ai_lead_qualifier',
    name: 'AI Lead Scorer & Router',
    description: 'Instant AI lead scoring with automated high-priority dispatcher routing',
    category: 'ai',
    icon: 'Zap',
    defaultProps: { thresholdScore: 80 },
    defaultStyle: { colSpan: 12 },
  },
  ai_voice_caller: {
    type: 'ai_voice_caller',
    name: 'AI Instant Callback',
    description: 'Initiates a live two-way AI voice call to the client in under 30 seconds',
    category: 'ai',
    icon: 'PhoneCall',
    defaultProps: { ctaText: 'Receive Instant AI Callback in 30 Seconds' },
    defaultStyle: { colSpan: 12 },
  },
  ai_recommendation_card: {
    type: 'ai_recommendation_card',
    name: 'AI Service Recommender',
    description: 'Dynamic AI service packages recommended based on user inputs',
    category: 'ai',
    icon: 'BrainCircuit',
    defaultProps: { title: 'AI Recommended Solution' },
    defaultStyle: { colSpan: 12 },
  },

  // ── 5. BUSINESS ──
  booking_calendar: {
    type: 'booking_calendar',
    name: 'Live Booking Calendar',
    description: 'Real-time technician calendar availability and instant reservation',
    category: 'business',
    icon: 'CalendarCheck2',
    defaultProps: { title: 'Select Appointment Slot', durationMinutes: 60 },
    defaultStyle: { colSpan: 12 },
  },
  stripe_checkout: {
    type: 'stripe_checkout',
    name: 'Stripe Pay / Deposit',
    description: 'Integrated credit card and Apple Pay / Google Pay checkout',
    category: 'business',
    icon: 'CreditCard',
    defaultProps: { amount: 99, currency: 'USD', itemDescription: 'Emergency Service Deposit' },
    defaultStyle: { colSpan: 12 },
  },
  service_catalog: {
    type: 'service_catalog',
    name: 'Service Catalog Grid',
    description: 'Visual cards showing service packages, pricing, and book buttons',
    category: 'business',
    icon: 'Layers',
    defaultProps: {
      services: [
        { title: 'Standard Diagnostic', price: '$89', description: 'Complete 24-point inspection' },
        { title: 'Comprehensive Tune-up', price: '$189', description: 'Refrigerant check, coil cleaning & tune' },
      ],
    },
    defaultStyle: { colSpan: 12 },
  },
  product_card: {
    type: 'product_card',
    name: 'Product / Part Card',
    description: 'E-commerce style card for air filters, thermostats, and parts',
    category: 'business',
    icon: 'ShoppingBag',
    defaultProps: { title: 'Smart WiFi Thermostat', price: '$249', imageUrl: 'https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?auto=format&fit=crop&w=600&q=80' },
    defaultStyle: { colSpan: 6 },
  },
  quote_calculator: {
    type: 'quote_calculator',
    name: 'Instant Quote Summary',
    description: 'Real-time breakdown of labor, materials, tax, and total price',
    category: 'business',
    icon: 'Receipt',
    defaultProps: { title: 'Quote Breakdown' },
    defaultStyle: { colSpan: 12 },
  },
  service_passport: {
    type: 'service_passport',
    name: 'Service Passport Badge',
    description: 'Equipment health history, serial numbers, and active warranties',
    category: 'business',
    icon: 'ShieldCheck',
    defaultProps: { title: 'Service Passport™ Equipment History' },
    defaultStyle: { colSpan: 12 },
  },
  map_location: {
    type: 'map_location',
    name: 'Service Area Map',
    description: 'Interactive map displaying service coverage radius and active trucks',
    category: 'business',
    icon: 'Map',
    defaultProps: { centerAddress: 'Austin, TX', radiusMiles: 25 },
    defaultStyle: { colSpan: 12, height: '240px' },
  },
  reviews_wall: {
    type: 'reviews_wall',
    name: 'Verified Reviews Wall',
    description: 'Google & Yelp verified customer reviews and star badges',
    category: 'business',
    icon: 'Award',
    defaultProps: { rating: '4.9', count: 342 },
    defaultStyle: { colSpan: 12 },
  },
  whatsapp_button: {
    type: 'whatsapp_button',
    name: 'WhatsApp Direct Chat',
    description: '1-click button to chat with dispatcher on WhatsApp',
    category: 'business',
    icon: 'MessageCircle',
    defaultProps: { phoneNumber: '+15550192834', message: 'Hello, I need service quote.' },
    defaultStyle: { colSpan: 6 },
  },
  phone_call_button: {
    type: 'phone_call_button',
    name: 'Click-to-Call Button',
    description: 'Direct tap-to-call phone button for urgent customer emergencies',
    category: 'business',
    icon: 'PhoneCall',
    defaultProps: { phoneNumber: '1-800-555-0199', label: 'Call 24/7 Dispatch Now' },
    defaultStyle: { colSpan: 6 },
  },

  // ── 6. DATA ──
  data_table: {
    type: 'data_table',
    name: 'Data Table',
    description: 'Tabular view of CRM customers, previous jobs, or inquiries',
    category: 'data',
    icon: 'Table',
    defaultProps: { dataSource: 'jobs', columns: ['Job #', 'Customer', 'Date', 'Status', 'Total'] },
    defaultStyle: { colSpan: 12 },
  },
  record_view: {
    type: 'record_view',
    name: 'Single Record Card',
    description: 'Detailed card view of a single invoice, customer, or equipment item',
    category: 'data',
    icon: 'Contact',
    defaultProps: { recordType: 'invoice' },
    defaultStyle: { colSpan: 12 },
  },
  card_grid: {
    type: 'card_grid',
    name: 'Dynamic Card Grid',
    description: 'Repeater card grid bound to database records or API endpoints',
    category: 'data',
    icon: 'Grid',
    defaultProps: { layout: '3-col' },
    defaultStyle: { colSpan: 12 },
  },
  stat_metric: {
    type: 'stat_metric',
    name: 'KPI Metric Stat',
    description: 'Key metric display (e.g. Total Jobs Completed, Average Rating)',
    category: 'data',
    icon: 'TrendingUp',
    defaultProps: { label: 'Jobs Completed This Month', value: '1,429', trend: '+14% vs last month' },
    defaultStyle: { colSpan: 4 },
  },

  // ── 7. ADVANCED ──
  custom_html: {
    type: 'custom_html',
    name: 'Custom HTML / Embed',
    description: 'Raw HTML, iframe or custom JavaScript embed block',
    category: 'advanced',
    icon: 'Code2',
    defaultProps: { code: '<div class="p-4 text-center">Custom Widget Embed</div>' },
    defaultStyle: { colSpan: 12 },
  },
  webhook_button: {
    type: 'webhook_button',
    name: 'Webhook Trigger Button',
    description: 'Executes a background Zapier/Make webhook payload upon click',
    category: 'advanced',
    icon: 'Webhook',
    defaultProps: { webhookUrl: 'https://hooks.zapier.com/...', label: 'Send Payload' },
    defaultStyle: { colSpan: 12 },
  },
  global_symbol: {
    type: 'global_symbol',
    name: 'Global Component Instance',
    description: 'Reusable global component synchronized across all pages',
    category: 'global',
    icon: 'Globe',
    defaultProps: { symbolId: '' },
    defaultStyle: { colSpan: 12 },
  },
};
