'use client';

import { useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, CalendarDays, Check, ChevronRight, LayoutGrid, List, Mail, MessageSquare, Plus, Search, Users } from 'lucide-react';
import { Avatar, Badge, Empty, Modal, Stat, Tabs } from './primitives';
import { money, STAGES, type Lead, type Stage } from './fixtures';

type Props = { leads: Lead[]; setLeads: (leads: Lead[]) => void; notify: (message: string) => void; openInbox: () => void };
export function CrmPreview({ leads, setLeads, notify, openInbox }: Props) {
  const [tab, setTab] = useState('Pipeline');
  const [query, setQuery] = useState('');
  const [source, setSource] = useState('All sources');
  const [selected, setSelected] = useState<string | null>(null);
  const [adding, setAdding] = useState(false);
  const [importing, setImporting] = useState(false);
  const [note, setNote] = useState('');
  const [view, setView] = useState('board');
  const file = useRef<HTMLInputElement>(null);
  const filtered = leads.filter(lead => `${lead.name} ${lead.company} ${lead.email}`.toLowerCase().includes(query.toLowerCase()) && (source === 'All sources' || lead.source === source));
  const active = leads.find(lead => lead.id === selected);
  function update(patch: Partial<Lead>) { setLeads(leads.map(lead => lead.id === selected ? { ...lead, ...patch } : lead)); }
  function exportLeads() {
    const quote = (s: string | number) => { const value = String(s); const safe = /^[=+@\-\t\r]/.test(value) ? `'${value}` : value; return `"${safe.replaceAll('"', '""')}"`; };
    const csv = [['Name', 'Company', 'Email', 'Stage', 'Source', 'Value'], ...filtered.map(l => [l.name, l.company, l.email, l.stage, l.source, l.value])].map(row => row.map(quote).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' }));
    const a = document.createElement('a'); a.href = url; a.download = 'bgos-sample-leads.csv'; a.click(); URL.revokeObjectURL(url);
    notify('Sample leads exported. No live records were accessed.');
  }
  return <>
    <div className="dp-page-heading"><div><div className="dp-eyebrow">RELATIONSHIPS THAT GROW</div><h1>Leads & CRM</h1><p>Every conversation. Every follow-up. One clear next step.</p></div><div className="dp-actions"><button className="dp-button" onClick={() => setImporting(true)}><ArrowUpFromLine size={16} />Import</button><button className="dp-button primary" onClick={() => setAdding(true)}><Plus size={17} />Add lead</button></div></div>
    <div className="dp-stats four"><Stat label="Total leads" value={leads.length} change="Across your sample workspace" icon={Users} /><Stat label="Open pipeline" value={money(leads.filter(l => l.stage !== 'Won').reduce((n, l) => n + l.value, 0))} change="Estimated opportunity value" icon={LayoutGrid} /><Stat label="Follow-ups today" value={leads.filter(l => l.next.startsWith('Today')).length} change="Keep the conversation going" icon={CalendarDays} /><Stat label="Won opportunities" value={leads.filter(l => l.stage === 'Won').length} change="From the sample pipeline" icon={Check} /></div>
    <div className="dp-card dp-crm-workspace"><div className="dp-toolbar"><Tabs values={['Pipeline', 'Contacts', 'Follow-ups', 'Segments']} value={tab} onChange={setTab} label="CRM section" /><button className="dp-button quiet" onClick={exportLeads}><ArrowDownToLine size={15} />Export</button></div>
      <div className="dp-filterbar"><label className="dp-search"><Search size={16} /><input aria-label="Search leads" placeholder="Search name, company or email…" value={query} onChange={e => setQuery(e.target.value)} /></label><div className="dp-actions"><select aria-label="Lead source" value={source} onChange={e => setSource(e.target.value)}>{['All sources', 'WhatsApp', 'Google', 'Website', 'Form', 'Referral'].map(s => <option key={s}>{s}</option>)}</select>{tab === 'Pipeline' && <div className="dp-view-toggle"><button aria-label="Board view" aria-pressed={view === 'board'} onClick={() => setView('board')}><LayoutGrid size={16} /></button><button aria-label="List view" aria-pressed={view === 'list'} onClick={() => setView('list')}><List size={17} /></button></div>}</div></div>
      {tab === 'Pipeline' && view === 'board' ? <div className="dp-pipeline">{STAGES.map(stage => { const entries = filtered.filter(l => l.stage === stage); return <section className={`dp-lane ${stage.toLowerCase()}`} key={stage}><header><span className="dp-stage-dot" /><h3>{stage}</h3><span className="dp-count">{entries.length}</span></header><p className="dp-lane-value">{money(entries.reduce((n, l) => n + l.value, 0))}</p><div className="dp-lane-cards">{entries.map(lead => <button className="dp-lead-card" key={lead.id} onClick={() => setSelected(lead.id)}><div className="dp-person"><Avatar initials={lead.initials} /><div><strong>{lead.name}</strong><small>{lead.company}</small></div></div><div className="dp-between"><Badge tone={lead.source === 'WhatsApp' ? 'green' : 'violet'}>{lead.source}</Badge><strong>{money(lead.value)}</strong></div><div className="dp-lead-bottom"><span><CalendarDays size={12} />{lead.next}</span><Avatar small initials={lead.owner.slice(0, 1)} /></div></button>)}{!entries.length && <div className="dp-lane-empty">No leads in this stage</div>}</div></section>; })}</div> : tab === 'Segments' ? <div className="dp-segment-grid">{['All sources', 'Google', 'WhatsApp', 'Referral'].map(s => <button className="dp-card dp-segment" key={s} onClick={() => { setSource(s); setTab('Contacts'); }}><Users size={21} /><h3>{s === 'All sources' ? 'All contacts' : `${s} leads`}</h3><p>{leads.filter(l => s === 'All sources' || l.source === s).length} sample contacts</p><span>View contacts <ChevronRight size={14} /></span></button>)}</div> : <div className="dp-table-wrap"><table className="dp-table"><thead><tr><th>Contact</th><th>{tab === 'Follow-ups' ? 'Next follow-up' : 'Company'}</th><th>Stage</th><th>Source</th><th>Owner</th><th>Value</th></tr></thead><tbody>{filtered.map(lead => <tr key={lead.id}><td><button className="dp-person dp-text-button" onClick={() => setSelected(lead.id)}><Avatar initials={lead.initials} /><span><strong>{lead.name}</strong><small>{lead.email}</small></span></button></td><td>{tab === 'Follow-ups' ? lead.next : lead.company}</td><td><Badge tone={lead.stage === 'Won' ? 'green' : 'violet'}>{lead.stage}</Badge></td><td>{lead.source}</td><td>{lead.owner}</td><td>{money(lead.value)}</td></tr>)}</tbody></table>{!filtered.length && <Empty title="No matching leads" detail="Try a different name or source." />}</div>}
      <div className="dp-table-footer"><span>{filtered.length} of {leads.length} sample leads</span><span>Click a lead to view details and change its stage</span></div>
    </div>
    {active && <Modal title="Lead details" drawer onClose={() => { setSelected(null); setNote(''); }}><div className="dp-contact-hero"><Avatar initials={active.initials} /><h2>{active.name}</h2><p>{active.company}</p><Badge tone="violet">{active.source}</Badge></div><div className="dp-actions"><button className="dp-button primary" onClick={openInbox}><MessageSquare size={16} />Open inbox</button><button className="dp-button" onClick={() => notify('Email composer preview. No email will be sent.')}><Mail size={16} />Email</button></div><div className="dp-form-grid"><label>Pipeline stage<select value={active.stage} onChange={e => update({ stage: e.target.value as Stage })}>{STAGES.map(stage => <option key={stage}>{stage}</option>)}</select></label><label>Assigned to<select value={active.owner} onChange={e => update({ owner: e.target.value })}><option>Rohit</option><option>Meera</option></select></label><label>Email<input readOnly value={active.email} /></label><label>Opportunity value<input type="number" min="0" value={active.value} onChange={e => update({ value: Math.max(0, Number(e.target.value)) })} /></label><label className="full">Next follow-up<input value={active.next} onChange={e => update({ next: e.target.value })} /></label></div><h3 className="dp-subheading">Activity & notes</h3><div className="dp-timeline">{active.notes.map((n, i) => <div key={`${i}-${n}`}><span /><p>{n}<small>{i === 0 ? 'Sample activity' : 'Added in this preview'}</small></p></div>)}</div><form onSubmit={e => { e.preventDefault(); if (!note.trim()) return; update({ notes: [...active.notes, note.trim()] }); setNote(''); }}><label className="dp-field">Add a note<textarea value={note} onChange={e => setNote(e.target.value)} placeholder="Capture context for your team…" rows={3} /></label><button className="dp-button" disabled={!note.trim()}>Save note</button></form><p className="dp-helper">Preview changes stay in this tab and reset on reload.</p></Modal>}
    {adding && <Modal title="Add a lead" onClose={() => setAdding(false)}><p className="dp-muted">Create a sample lead to explore the pipeline.</p><form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get('name')).trim(); if (!name) return; setLeads([...leads, { id: crypto.randomUUID(), name, company: String(data.get('company')), email: String(data.get('email')), phone: '', initials: name.split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase(), source: 'Website', stage: 'New', value: Number(data.get('value')) || 0, owner: 'Rohit', next: 'Today, 4:00 PM', notes: ['Added in the design preview.'] }]); setAdding(false); notify('Sample lead added to the New stage.'); }}><div className="dp-form-grid"><label>Full name<input name="name" required maxLength={100} autoFocus /></label><label>Company<input name="company" maxLength={100} /></label><label>Email<input name="email" type="email" required /></label><label>Estimated value (₹)<input name="value" type="number" min="0" defaultValue="0" /></label></div><div className="dp-dialog-footer"><button type="button" className="dp-button" onClick={() => setAdding(false)}>Cancel</button><button className="dp-button primary">Add sample lead</button></div></form></Modal>}
    {importing && <Modal title="Import contacts" onClose={() => setImporting(false)}><p className="dp-muted">CSV import will include field mapping, duplicate detection and a review step before saving.</p><div className="dp-upload"><ArrowUpFromLine size={30} /><h3>Choose a CSV to preview the import</h3><p>The file is not uploaded or added to your contacts.</p><input ref={file} type="file" accept=".csv,text/csv" onChange={e => notify(e.target.files?.[0] ? `Selected ${e.target.files[0].name}. Import mapping is planned for the data-integration phase.` : 'No file selected.')} /></div><ol className="dp-steps"><li>Upload CSV</li><li>Map fields</li><li>Review duplicates</li><li>Import contacts</li></ol></Modal>}
  </>;
}
