'use client';

import { useState } from 'react';
import { ArrowRight, Bot, CalendarDays, Check, FileText, Globe, Link2, MessageSquare, Plus, Search, Settings2, ShieldCheck, Sparkles, Star, Upload, Users, Workflow } from 'lucide-react';
import { Avatar, Badge, Modal, SectionTitle, Stat, Tabs } from './primitives';
import { GrowthChart } from './workspaces';

export function SupportingPreview({ page, notify }: { page: string; notify: (message: string) => void }) {
  const [tab, setTab] = useState('');
  const [modal, setModal] = useState<string | null>(null);
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ 'Welcome new leads': true, 'Follow up after a meeting': true });
  const [reply, setReply] = useState('');
  const [profile, setProfile] = useState({ name: 'Laddu Kirana', description: 'Your neighbourhood favourites, made with care. Discover thoughtful gifts and everyday treats in the heart of Delhi.', category: 'Local business', address: 'Chawri Bazar, Delhi' });
  const titles: Record<string, [string, string]> = {
    'Business profile': ['YOUR BUSINESS, BEAUTIFULLY PRESENTED', 'Make a memorable first impression, wherever customers find you.'],
    'Appointments': ['MAKE TIME FOR WHAT MATTERS', 'A clear calendar. Easier bookings. Better conversations.'],
    'Reviews & Google growth': ['BUILD TRUST. BE DISCOVERED.', 'Listen to your customers and grow your local presence.'],
    'AI studio': ['YOUR EXPERTISE, ALWAYS AVAILABLE', 'Give your assistant the knowledge and guidance it needs.'],
    'Forms & funnels': ['TURN INTEREST INTO OPPORTUNITY', 'Create thoughtful forms and bring every response into your CRM.'],
    'Automations': ['A LITTLE LESS REPETITION', 'Keep your customer relationships moving, one thoughtful step at a time.'],
    'Business phone': ['EVERY CALL IS AN OPPORTUNITY', 'Bring your conversations, missed calls and next steps together.'],
    'Reports': ['SEE WHAT’S WORKING', 'Understand the journey from first impression to lasting relationship.'],
    'Settings': ['YOUR WORKSPACE, YOUR WAY', 'Manage your team, channels, preferences and plan.'],
    'Lead intelligence': ['DISCOVER YOUR NEXT CONNECTION', 'Find relevant businesses and bring qualified prospects into your CRM.'],
  };
  const [eyebrow, description] = titles[page] || ['', ''];
  const save = (message = 'Preview settings saved for this visit.') => notify(`${message} No live data was changed.`);
  let content;
  if (page === 'Business profile') content = <div className="dp-two-thirds"><section className="dp-card dp-pad"><Tabs values={['Business details', 'Appearance', 'Digital card']} value={tab || 'Business details'} onChange={setTab} />{(!tab || tab === 'Business details') ? <form onSubmit={e => { e.preventDefault(); save(); }}><div className="dp-form-grid"><label>Business name<input value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })} required /></label><label>Category<select value={profile.category} onChange={e => setProfile({ ...profile, category: e.target.value })}><option>Local business</option><option>Agency</option><option>Professional services</option></select></label><label className="full">About your business<textarea rows={4} value={profile.description} onChange={e => setProfile({ ...profile, description: e.target.value })} /></label><label className="full">Address<input value={profile.address} onChange={e => setProfile({ ...profile, address: e.target.value })} /></label></div><button className="dp-button primary">Save preview</button></form> : tab === 'Appearance' ? <div className="dp-pad"><h3>Brand colour</h3><div className="dp-swatches">{['Violet', 'Ocean', 'Forest', 'Terracotta'].map((c, i) => <button key={c} className={`swatch swatch-${i}`} aria-label={c} onClick={() => save(`${c} selected for the design preview.`)} />)}</div><div className="dp-upload"><Upload size={26} /><h3>Logo & cover image</h3><p>Media upload and crop will be connected during data integration.</p></div></div> : <div className="dp-pad"><h3>One link for your business</h3><p className="dp-muted">The final card will use your published mini-site URL and a scannable QR code.</p><Badge tone="amber">QR generation connects in the data phase</Badge><div className="dp-upload"><Link2 size={32} /><p>bgos.example.test/p/laddu-kirana</p></div></div>}</section><section className="dp-phone-preview"><div className="dp-phone-camera" /><div className="dp-phone-cover"><Sparkles size={30} /></div><Avatar initials="LK" /><h2>{profile.name}</h2><p>{profile.category} · Delhi</p><div className="dp-stars">★★★★★</div><p>{profile.description}</p><button className="dp-button primary" onClick={() => setModal('Booking preview')}>Book an appointment</button><button className="dp-button" onClick={() => setModal('Contact preview')}>Get in touch</button><small>LIVE DESIGN PREVIEW</small></section></div>;
  else if (page === 'Appointments') content = <><div className="dp-stats four"><Stat label="This week" value="12" change="Sample scheduled meetings" icon={CalendarDays} /><Stat label="Awaiting confirmation" value="3" change="Ready for your review" icon={Users} /><Stat label="Available hours" value="18" change="Across connected calendars" icon={Globe} /><Stat label="Booking conversion" value="24%" change="Illustrative metric" icon={Check} /></div><section className="dp-card dp-pad"><SectionTitle title="Your appointments" action={<button className="dp-button primary" onClick={() => setModal('New appointment')}><Plus size={16} />New appointment</button>} /><Tabs values={['Upcoming', 'Availability', 'Meeting types', 'Calendar connections']} value={tab || 'Upcoming'} onChange={setTab} />{(!tab || tab === 'Upcoming') ? ['Priya Singh', 'Amit Kumar', 'Rahul Mehta'].map((name, i) => <div className="dp-activity-row" key={name}><span className="dp-date-tile"><strong>{10 + i}</strong>OCT</span><span className="dp-grow"><h3>{name}</h3><p>Discovery call · 30 minutes · {11 + i}:00 AM</p></span><Badge tone={i === 0 ? 'amber' : 'green'}>{i === 0 ? 'Pending' : 'Confirmed'}</Badge><button className="dp-button" onClick={() => setModal(`Reschedule ${name}`)}>Manage</button></div>) : tab === 'Calendar connections' ? ['Google Calendar', 'Microsoft Outlook'].map(name => <div className="dp-activity-row" key={name}><CalendarDays size={24} /><div className="dp-grow"><h3>{name}</h3><p>Check availability and synchronize bookings.</p></div><button className="dp-button" onClick={() => notify('Connection screen preview. OAuth starts only after data integration.')}>Connect</button></div>) : <div className="dp-form-grid"><label>{tab === 'Availability' ? 'Working days' : 'Meeting name'}<input defaultValue={tab === 'Availability' ? 'Monday – Friday' : 'Discovery call'} /></label><label>{tab === 'Availability' ? 'Working hours' : 'Duration'}<input defaultValue={tab === 'Availability' ? '9:00 AM – 6:00 PM' : '30 minutes'} /></label><button className="dp-button primary" onClick={() => save()}>Save preview</button></div>}</section></>;
  else if (page === 'Reviews & Google growth') content = <><div className="dp-stats four"><Stat label="Average rating" value="4.8" change="Based on sample reviews" icon={Star} /><Stat label="Total reviews" value="128" change="12 new this sample period" icon={MessageSquare} /><Stat label="Awaiting reply" value="3" change="A chance to connect" icon={Users} /><Stat label="Profile views" value="1,248" change="Illustrative Google metric" icon={Globe} /></div><section className="dp-card dp-pad"><div className="dp-toolbar"><Tabs values={['Reviews', 'Request reviews', 'Google performance', 'Keywords']} value={tab || 'Reviews'} onChange={setTab} /></div>{(!tab || tab === 'Reviews') ? ['Rakesh Agarwal', 'Priya Sharma', 'Amit Verma'].map((n, i) => <div className="dp-review" key={n}><div className="dp-between"><span className="dp-person"><Avatar initials={n.split(' ').map(s => s[0]).join('')} /><span><strong>{n}</strong><small>Google · {i + 1} days ago</small></span></span><Badge tone="amber">Awaiting reply</Badge></div><div className="dp-stars">★★★★★</div><p>{['A wonderful experience. The team was thoughtful and everything felt personal.', 'Fresh, beautifully presented and perfect for our team celebration.', 'A neighbourhood favourite. Thank you for the warm service!'][i]}</p><button className="dp-button" onClick={() => { setModal(`Reply to ${n}`); setReply(`Thank you, ${n.split(' ')[0]}! We’re glad you enjoyed your experience and look forward to welcoming you again.`); }}><Sparkles size={15} />Draft reply</button></div>) : tab === 'Google performance' ? <><SectionTitle title="Profile performance" detail="Illustrative data · Google connection required in production" /><GrowthChart /></> : tab === 'Keywords' ? <div className="dp-table-wrap"><table className="dp-table"><thead><tr><th>Keyword</th><th>Monthly searches</th><th>Difficulty</th><th>Action</th></tr></thead><tbody>{['gift boxes near me', 'local sweets delhi', 'corporate festive gifts'].map((k, i) => <tr key={k}><td>{k}</td><td>{[1200, 900, 2400][i]} · sample</td><td><Badge tone="green">Low · sample</Badge></td><td><button className="dp-button quiet" onClick={() => notify(`“${k}” saved to the preview keyword list.`)}>Save</button></td></tr>)}</tbody></table></div> : <div className="dp-form-grid"><label>Contact<select><option>Priya Singh</option><option>Amit Kumar</option></select></label><label>Channel<select><option>WhatsApp</option><option>Email</option></select></label><label className="full">Personal message<textarea rows={4} defaultValue="Thank you for choosing us! If you enjoyed your experience, we’d love to hear your feedback." /></label><button className="dp-button primary" onClick={() => notify('Review request preview saved. No request was sent.')}>Preview request</button></div>}</section></>;
  else if (page === 'AI studio') content = <div className="dp-two-thirds"><section className="dp-card dp-pad"><Tabs values={['Instructions', 'Knowledge', 'Test assistant']} value={tab || 'Instructions'} onChange={setTab} />{(!tab || tab === 'Instructions') ? <div className="dp-form-grid"><label className="full">Assistant name<input defaultValue="Laddu business assistant" /></label><label className="full">System instructions<textarea rows={8} defaultValue="You are a warm, helpful assistant for Laddu Kirana. Answer questions using approved business information. Help visitors book a conversation. When you do not know an answer, offer to connect them with our team." /></label><button className="dp-button primary" onClick={() => save()}>Save instructions</button></div> : tab === 'Knowledge' ? <div className="dp-upload"><FileText size={32} /><h3>Give your assistant the right context</h3><p>Add business documents, FAQs and website content.</p><button className="dp-button" onClick={() => setModal('Add knowledge source')}><Plus size={16} />Add source</button></div> : <div className="dp-upload"><Bot size={32} /><h3>Assistant test space</h3><p>Live RAG answers will be connected after the design review.</p><input aria-label="Test question" placeholder="Ask about the business…" /><button className="dp-button" onClick={() => notify('AI testing is not connected in this design preview.')}>Preview test flow</button></div>}</section><section className="dp-card dp-pad"><span className="dp-icon-tile"><Bot size={25} /></span><h2 className="dp-subheading">A helpful member of your team</h2><p className="dp-muted">Consistent answers, clear limits and a smooth handoff when a customer needs a person.</p><div className="dp-check-list"><p><Check size={16} />Approved knowledge sources</p><p><Check size={16} />Human takeover in inbox</p><p><Check size={16} />Clear fallback behavior</p></div></section></div>;
  else if (page === 'Forms & funnels') content = <section className="dp-card dp-pad"><SectionTitle title="Your forms" detail="One response, one shared customer record" action={<button className="dp-button primary" onClick={() => setModal('Form studio preview')}><Plus size={16} />Create form</button>} /><Tabs values={['Forms', 'Responses', 'Conversion']} value={tab || 'Forms'} onChange={setTab} />{tab === 'Conversion' ? <GrowthChart /> : ['Get in touch', 'Book a discovery call', 'Festive gifting enquiry'].map((name, i) => <div className="dp-activity-row" key={name}><span className="dp-icon-tile"><FileText size={20} /></span><div className="dp-grow"><h3>{name}</h3><p>{[42, 28, 16][i]} sample responses · {tab === 'Responses' ? 'Latest: today at 10:24 AM' : 'Connects to Leads & CRM'}</p></div><Badge tone="green">Published</Badge><button className="dp-button" onClick={() => setModal(tab === 'Responses' ? `${name} · Responses` : `${name} · Form studio`)}>{tab === 'Responses' ? 'View responses' : 'Open builder'}</button></div>)}</section>;
  else if (page === 'Automations') content = <><section className="dp-card dp-pad"><SectionTitle title="Your workflows" detail="A clear trigger. A thoughtful next step." action={<button className="dp-button primary" onClick={() => setModal('Workflow designer')}><Plus size={16} />Create workflow</button>} />{['Welcome new leads', 'Follow up after a meeting', 'Request a customer review'].map((name, i) => <div className="dp-activity-row" key={name}><span className="dp-icon-tile"><Workflow size={21} /></span><div className="dp-grow"><h3>{name}</h3><p>{['Form submitted → Add CRM lead → Notify owner', 'Appointment completed → Wait 1 day → Draft follow-up', 'Lead marked Won → Wait 3 days → Prepare review request'][i]}</p></div><button role="switch" aria-checked={!!enabled[name]} aria-label={name} className={`dp-switch ${enabled[name] ? 'on' : ''}`} onClick={() => setEnabled({ ...enabled, [name]: !enabled[name] })}><span /></button></div>)}</section><section className="dp-card dp-pad"><SectionTitle title="Workflow preview" /><div className="dp-workflow"><span><FileText size={23} />Form submitted<small>Trigger</small></span><ArrowRight /><span><Users size={23} />Create CRM lead<small>Shared contact record</small></span><ArrowRight /><span><MessageSquare size={23} />Notify the team<small>Assigned owner</small></span></div></section></>;
  else if (page === 'Reports') content = <><div className="dp-stats four"><Stat label="Profile views" value="1,248" change="12% sample growth" icon={Globe} /><Stat label="Enquiries" value="84" change="18% sample growth" icon={MessageSquare} /><Stat label="Appointments" value="48" change="14% sample growth" icon={CalendarDays} /><Stat label="Cost per lead" value="—" change="Ad spend source required" icon={Users} /></div><section className="dp-card dp-pad"><Tabs values={['Overview', 'Acquisition', 'Conversion', 'Attribution']} value={tab || 'Overview'} onChange={setTab} /><SectionTitle title={tab === 'Attribution' ? 'Attribution needs connected sources' : 'Your customer journey'} detail={tab === 'Attribution' ? 'ROAS will only appear when both ad spend and attributable revenue are available.' : 'Illustrative trends · Provider metrics will retain source and date labels'} />{tab !== 'Attribution' && <GrowthChart />}</section></>;
  else if (page === 'Business phone') content = <><div className="dp-notice-inline"><ShieldCheck size={20} /><div><strong>Connect a business phone to get started</strong><p>Phone provisioning and calling will be verified before this module goes live.</p></div><button className="dp-button" onClick={() => setModal('Connect business phone')}>Explore setup</button></div><div className="dp-stats four"><Stat label="Incoming calls" value="12" change="Sample calls today" icon={MessageSquare} /><Stat label="Outgoing calls" value="8" change="Sample calls today" icon={Users} /><Stat label="Missed calls" value="2" change="Follow-up opportunities" icon={CalendarDays} /><Stat label="Talk time" value="1h 32m" change="Illustrative duration" icon={Globe} /></div><section className="dp-card dp-pad"><SectionTitle title="Recent calls" />{['Priya Singh', 'Amit Kumar', 'Rahul Mehta'].map((n, i) => <div className="dp-activity-row" key={n}><Avatar initials={n.split(' ').map(v => v[0]).join('')} /><div className="dp-grow"><h3>{n}</h3><p>Sample contact · Today, {10 + i}:24 AM</p></div><Badge tone={i === 1 ? 'red' : 'green'}>{i === 1 ? 'Missed' : 'Incoming'}</Badge><button className="dp-button" onClick={() => setModal(`Call details · ${n}`)}>Details</button></div>)}</section></>;
  else if (page === 'Lead intelligence') content = <div className="dp-intelligence"><section className="dp-card dp-pad"><SectionTitle title="1. Find businesses" /><label className="dp-field">Source<select><option>Apollo</option><option>Hunter</option></select></label><label className="dp-field">Business or keyword<input placeholder="e.g. Creative agencies in Delhi" /></label><button className="dp-button primary" onClick={() => notify('Showing illustrative results. No provider search or credits used.')}><Search size={15} />Preview search</button><p className="dp-helper">Provider search and credits connect after design approval.</p></section><section className="dp-card dp-pad"><SectionTitle title="2. Review prospects" />{['Orbit Design', 'Maple Works', 'Bloom Events'].map((n, i) => <button className="dp-prospect" key={n} onClick={() => setTab(n)}><Avatar initials={n.split(' ').map(v => v[0]).join('')} /><span><strong>{n}</strong><small>Delhi · Sample business</small></span><ChevronRightFallback /></button>)}</section><section className="dp-card dp-pad"><SectionTitle title="3. Prepare outreach" detail={tab || 'Select a business to begin'} /><label className="dp-field">Your offer<textarea rows={5} placeholder="Why is your business relevant to this prospect?" /></label><button className="dp-button primary" onClick={() => notify('Sample prospect selected. Live saving will reuse the Leads & CRM contact record.')}>Save to Leads & CRM</button><p className="dp-helper">Prospects feed the same CRM. Outreach approval remains a separate step.</p></section></div>;
  else content = <section className="dp-card dp-pad"><Tabs values={['Workspace', 'Team', 'Integrations', 'Plan & usage']} value={tab || 'Workspace'} onChange={setTab} />{tab === 'Team' ? ['Rohit Sharma', 'Meera Patel'].map((n, i) => <div className="dp-activity-row" key={n}><Avatar initials={n.split(' ').map(v => v[0]).join('')} /><span className="dp-grow"><h3>{n}</h3><p>{i ? 'Team member' : 'Workspace owner'}</p></span><Badge tone="green">Active</Badge></div>) : tab === 'Integrations' ? ['Google Business Profile', 'WhatsApp', 'Instagram', 'Email provider'].map(n => <div className="dp-activity-row" key={n}><Globe size={21} /><h3 className="dp-grow">{n}</h3><Badge>Not connected</Badge><button className="dp-button" onClick={() => notify(`${n} connection is not started in the design preview.`)}>Connect</button></div>) : tab === 'Plan & usage' ? <div className="dp-upload"><Sparkles size={30} /><h2>Your plan, built around your business</h2><p>The production pricing catalog and enforced usage limits will be mapped here.</p><Badge tone="amber">No checkout in design preview</Badge></div> : <div className="dp-form-grid"><label>Workspace name<input defaultValue="Laddu Kirana" /></label><label>Time zone<select><option>Asia/Kolkata</option></select></label><label>Email notifications<select><option>Important updates</option><option>All activity</option><option>Off</option></select></label><label>Workspace mode<select><option>Local business</option><option>Agency</option></select></label><button className="dp-button primary" onClick={() => save()}>Save preview</button></div>}</section>;
  return <><div className="dp-page-heading"><div><div className="dp-eyebrow">{eyebrow}</div><h1>{page}</h1><p>{description}</p></div></div>{content}{modal && <Modal title={modal} onClose={() => setModal(null)}>{modal.startsWith('Reply') ? <><label className="dp-field">Suggested reply<textarea value={reply} rows={5} onChange={e => setReply(e.target.value)} /></label><button className="dp-button primary" onClick={() => { setModal(null); notify('Sample reply saved. Nothing was posted to Google.'); }}>Save sample reply</button></> : <><p className="dp-muted">This screen establishes the design and navigation. The existing {page.toLowerCase()} workflow will be mapped to this interface during data integration.</p><div className="dp-upload"><Settings2 size={30} /><h3>Detailed interaction planned</h3><p>No external service is called from this preview.</p></div><button className="dp-button primary" onClick={() => setModal(null)}>Back to preview</button></>}</Modal>}</>;
}
function ChevronRightFallback() { return <ArrowRight size={15} />; }
