import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getAuthUser } from '@/lib/auth';
import { requirePlanFeature } from '@/lib/plan-gate';
import { computeNextOccurrence } from '@/lib/recurring-jobs';
import { logActivity } from '@/lib/activity-log';

// GET /api/recurring-jobs/[id] — Get a single schedule with customer +
// last 10 generated jobs.
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await getAuthUser();
    if (!user || !user.tenantId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const { id } = await params;

    // Fast-path: Postgres RPC (1 DB round trip for schedule + customer + recent 10 jobs + consolidated metrics)
    try {
      const rpcRes = await db.$queryRawUnsafe<Array<{ get_recurring_job_details: any }>>(
        `SELECT get_recurring_job_details($1, $2);`,
        user.tenantId,
        id
      );
      const data = rpcRes?.[0]?.get_recurring_job_details;
      if (data && !data.error) {
        return NextResponse.json(data);
      }
      if (data?.error && data?.status === 404) {
        return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
      }
    } catch {
      // Fallback to optimized Prisma query below
    }

    const schedule = await db.recurringJobSchedule.findUnique({
      where: { id },
      include: {
        customer: { select: { id: true, name: true, phone: true, email: true } },
      },
    });

    if (!schedule) {
      return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
    }
    if (schedule.tenantId !== user.tenantId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    // Look up the last 10 jobs generated by this schedule via the clean FK
    // (Job.recurringScheduleId). Previously this was best-effort matching by
    // title+customer+date — fragile and prone to false positives on rename.
    const recentJobs = await db.job.findMany({
      where: {
        recurringScheduleId: schedule.id,
      },
      orderBy: { createdAt: 'desc' },
      take: 10,
      select: {
        id: true,
        jobNumber: true,
        title: true,
        status: true,
        scheduledAt: true,
        createdAt: true,
        customerId: true,
      },
    });

    // ── Schedule-level metrics for the Overview tab. ───────────────────────
    //
    // The Overview tab now shows compact counts (total / completed / upcoming
    // / cancelled) + the most-recently-generated job's scheduled date. We
    // compute these server-side so the UI doesn't have to issue a second
    // call to /jobs and so the "Last generated" label can be derived from
    // the actual generated Job's scheduledAt (NOT schedule.lastRunAt, which
    // is the schedule's processing timestamp and misleading as a "last
    // visit" indicator).
    //
    // Definitions match the Generated Jobs tab filter:
    //   upcoming = status IN (pending, assigned, accepted, in_progress)
    //   completed = status = 'completed'
    //   cancelled = status = 'cancelled'
    //
    // "Last generated" = the most-recently-CREATED job's scheduledAt
    // (ordered by createdAt desc, NOT scheduledAt desc — the latter would
    // surface the furthest-future visit, which doesn't match the user's
    // mental model of "the last visit we generated just now").
    const statusCounts = await db.job.groupBy({
      by: ['status'],
      where: { recurringScheduleId: schedule.id },
      _count: { _all: true },
    });

    let total = 0;
    let completed = 0;
    let cancelled = 0;
    let upcoming = 0;
    const upcomingStatuses = new Set(['pending', 'assigned', 'accepted', 'in_progress']);

    for (const sc of statusCounts) {
      const c = sc._count._all;
      total += c;
      if (sc.status === 'completed') completed += c;
      else if (sc.status === 'cancelled') cancelled += c;
      else if (upcomingStatuses.has(sc.status)) upcoming += c;
    }

    const lastGenerated = recentJobs[0] ?? null;

    const metrics = {
      total,
      completed,
      cancelled,
      upcoming,
      lastJobScheduledAt: lastGenerated?.scheduledAt ?? null,
      lastJobCreatedAt: lastGenerated?.createdAt ?? null,
    };

    return NextResponse.json({ schedule, recentJobs, metrics });
  } catch (error) {
    console.error('Get recurring job error:', error);
    return NextResponse.json({ error: 'Failed to fetch recurring job schedule' }, { status: 500 });
  }
}

// PUT /api/recurring-jobs/[id] — Update a schedule.
// Recomputes nextRunAt if frequency / day / time fields change AND the
// schedule is currently active. Plan-gated.
export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await getAuthUser();
    if (!user || !user.tenantId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const gate = await requirePlanFeature('recurring_jobs');
    if (!gate.ok) {
      return NextResponse.json({ error: gate.reason }, { status: gate.status });
    }

    const { id } = await params;
    const existing = await db.recurringJobSchedule.findUnique({ where: { id } });
    if (!existing) {
      return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
    }
    if (existing.tenantId !== user.tenantId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    const body = await request.json();
    const updateData: Record<string, unknown> = {};

    if (body.title !== undefined) updateData.title = String(body.title).trim();
    if (body.description !== undefined) updateData.description = body.description?.trim() || null;
    if (body.customerId !== undefined) updateData.customerId = body.customerId || null;
    if (body.templateJobId !== undefined) updateData.templateJobId = body.templateJobId || null;
    if (body.frequency !== undefined) updateData.frequency = body.frequency;
    if (body.dayOfWeek !== undefined) updateData.dayOfWeek = body.dayOfWeek == null ? null : Number(body.dayOfWeek);
    if (body.dayOfMonth !== undefined) updateData.dayOfMonth = body.dayOfMonth == null ? null : Number(body.dayOfMonth);
    if (body.weekOfMonth !== undefined) updateData.weekOfMonth = body.weekOfMonth == null ? null : Number(body.weekOfMonth);
    if (body.timeOfDay !== undefined) updateData.timeOfDay = body.timeOfDay || null;
    if (body.durationMins !== undefined) updateData.durationMins = Number(body.durationMins) || 60;
    if (body.endDate !== undefined) updateData.endDate = body.endDate ? new Date(body.endDate) : null;
    if (body.assigneeIds !== undefined) updateData.assigneeIdsJson = JSON.stringify(body.assigneeIds);
    if (body.checklistIds !== undefined) updateData.checklistIdsJson = JSON.stringify(body.checklistIds);
    if (body.serviceId !== undefined) updateData.serviceId = body.serviceId || null;
    if (body.branchId !== undefined) updateData.branchId = body.branchId || null;
    if (body.visitInstructions !== undefined) updateData.visitInstructions = body.visitInstructions?.trim() || null;
    if (body.lineItemsJson !== undefined) {
      updateData.lineItemsJson =
        typeof body.lineItemsJson === 'string'
          ? body.lineItemsJson
          : JSON.stringify(body.lineItemsJson ?? []);
    }
    if (body.active !== undefined) updateData.active = Boolean(body.active);
    // ── Phase C: Optional billing fields ──
    if (body.generateInvoice !== undefined) updateData.generateInvoice = Boolean(body.generateInvoice);
    if (body.invoiceTiming !== undefined) {
      updateData.invoiceTiming = body.invoiceTiming === 'on_generation' ? 'on_generation' : 'on_completion';
    }
    // ── Phase F: Timezone ──
    if (body.timezone !== undefined) updateData.timezone = body.timezone || null;

    // Recompute nextRunAt if any scheduling field changed AND the schedule
    // is currently active (or being reactivated). Paused schedules get their
    // nextRunAt recomputed on resume, not on edit.
    const schedulingFieldsChanged =
      body.frequency !== undefined ||
      body.dayOfWeek !== undefined ||
      body.dayOfMonth !== undefined ||
      body.weekOfMonth !== undefined ||
      body.timeOfDay !== undefined ||
      body.endDate !== undefined ||
      body.timezone !== undefined;

    const effectiveActive = body.active !== undefined ? Boolean(body.active) : existing.active;
    if (schedulingFieldsChanged && effectiveActive) {
      const freq = (updateData.frequency as string) || existing.frequency;
      const dow = updateData.dayOfWeek !== undefined ? (updateData.dayOfWeek as number | null) : existing.dayOfWeek;
      const dom = updateData.dayOfMonth !== undefined ? (updateData.dayOfMonth as number | null) : existing.dayOfMonth;
      const wom = updateData.weekOfMonth !== undefined ? (updateData.weekOfMonth as number | null) : existing.weekOfMonth;
      const tod = updateData.timeOfDay !== undefined ? (updateData.timeOfDay as string | null) : existing.timeOfDay;
      const endDate = updateData.endDate !== undefined ? (updateData.endDate as Date | null) : existing.endDate;
      const tz = updateData.timezone !== undefined ? (updateData.timezone as string | null) : existing.timezone;

      const next = computeNextOccurrence(
        { frequency: freq, dayOfWeek: dow, dayOfMonth: dom, weekOfMonth: wom, timeOfDay: tod, endDate, timezone: tz },
        new Date(),
      );
      if (next) {
        updateData.nextRunAt = next;
        updateData.active = true;
      } else {
        // Past end date — deactivate.
        updateData.active = false;
        updateData.pausedAt = new Date();
      }
    }

    const schedule = await db.recurringJobSchedule.update({
      where: { id },
      data: updateData,
      include: {
        customer: { select: { id: true, name: true, phone: true, email: true } },
      },
    });

    try {
      await logActivity({
        tenantId: user.tenantId,
        actorId: user.id,
        actorName: user.name || user.email,
        actorType: 'user',
        action: 'update',
        entityType: 'recurringJobSchedule',
        entityId: schedule.id,
        entityName: schedule.title,
        description: `Updated recurring job schedule "${schedule.title}"`,
        metadataJson: JSON.stringify({ changedFields: Object.keys(updateData) }),
        severity: 'info',
      });
    } catch (logErr) {
      console.error('[RecurringJobs PUT] activity log failed:', logErr);
    }

    return NextResponse.json({ schedule });
  } catch (error) {
    console.error('Update recurring job error:', error);
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { error: 'Failed to update recurring job schedule', message },
      { status: 500 },
    );
  }
}

// DELETE /api/recurring-jobs/[id] — Hard-delete a schedule.
// (Generated jobs remain — they have no FK back to the schedule.)
export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const user = await getAuthUser();
    if (!user || !user.tenantId) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const gate = await requirePlanFeature('recurring_jobs');
    if (!gate.ok) {
      return NextResponse.json({ error: gate.reason }, { status: gate.status });
    }

    const { id } = await params;
    const existing = await db.recurringJobSchedule.findUnique({ where: { id } });
    if (!existing) {
      return NextResponse.json({ error: 'Schedule not found' }, { status: 404 });
    }
    if (existing.tenantId !== user.tenantId) {
      return NextResponse.json({ error: 'Access denied' }, { status: 403 });
    }

    await db.recurringJobSchedule.delete({ where: { id } });

    try {
      await logActivity({
        tenantId: user.tenantId,
        actorId: user.id,
        actorName: user.name || user.email,
        actorType: 'user',
        action: 'delete',
        entityType: 'recurringJobSchedule',
        entityId: id,
        entityName: existing.title,
        description: `Deleted recurring job schedule "${existing.title}"`,
        metadataJson: JSON.stringify({ scheduleId: id, executionCount: existing.executionCount }),
        severity: 'warning',
      });
    } catch (logErr) {
      console.error('[RecurringJobs DELETE] activity log failed:', logErr);
    }

    return NextResponse.json({ success: true, message: 'Recurring job schedule deleted' });
  } catch (error) {
    console.error('Delete recurring job error:', error);
    return NextResponse.json({ error: 'Failed to delete recurring job schedule' }, { status: 500 });
  }
}
